### ISSUE TITLE
error: (-215:Assertion failed) !ssize.empty() in function 'resize' on extraction

### ISSUE THREAD

**Issue by ringoribon** [deepfakes/faceswap#1027]
**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
In extracting, faceswap stops on 25915/27198 png file.
it said:
```
Traceback (most recent call last):
  File "/home/<username>/faceswap/lib/cli/launcher.py", line 155, in execute_script
    process.process()
  File "/home/<username>/faceswap/scripts/extract.py", line 116, in process
    self._run_extraction()
  File "/home/<username>/faceswap/scripts/extract.py", line 212, in _run_extraction
    for idx, extract_media in enumerate(status_bar):
  File "/home/<username>/miniconda3/lib/python3.7/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/<username>/faceswap/plugins/extract/pipeline.py", line 229, in detected_faces
    if self._check_and_raise_error():
  File "/home/<username>/faceswap/plugins/extract/pipeline.py", line 648, in _check_and_raise_error
    if plugin.check_and_raise_error():
  File "/home/<username>/faceswap/plugins/extract/_base.py", line 300, in check_and_raise_error
    err = thread.check_and_raise_error()
  File "/home/<username>/faceswap/lib/multithreading.py", line 84, in check_and_raise_error
    raise error[1].with_traceback(error[2])
  File "/home/<username>/faceswap/lib/multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "/home/<username>/faceswap/plugins/extract/_base.py", line 418, in _thread_process
    batch = function(batch)
  File "/home/<username>/faceswap/plugins/extract/align/cv2_dnn.py", line 54, in process_input
    faces, batch["roi"], batch["offsets"] = self.align_image(batch)
  File "/home/<username>/faceswap/plugins/extract/align/cv2_dnn.py", line 82, in align_image
    face = cv2.resize(face, dsize=sizes, interpolation=interpolation)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

**To Reproduce**
Sorry, I cannot reproduce this crush generally. But it is reproduced on my data.
The data is not permitted to distribute again, so I cannot give data.
Here is my directory composition:
- to
  -  scene000001.png
  -  scene000002.png
  -  ...
  -  scene027198.png
- to_face

Execute: `python faceswap.py extract -i ./to -o ./to_face`

**Expected behavior**
No crush.

**Screenshots**
I don't use gui, so crush report is all.

**Desktop (please complete the following information):**
 - OS: ubuntu20.04 (Windows subsystem for Linux)
 - Python Version 3.7.6
 - Conda Version 4.8.3
 - Commit ID ac40b0f52f5a745aa058f92339302065177dd28b
 - 
**Additional context**
I know this bug seem to be fixed on #993. I would just like to tell you that this bug is not still fixed, even on latest commit.

**Crash Report**
[crash_report.2020.05.30.192613736796.log](https://github.com/deepfakes/faceswap/files/4705528/crash_report.2020.05.30.192613736796.log)

**Comment by torzdf** [comment]
We have seen this error reported a few times, but have never been able to reproduce it, and suspect it is a GPU memory issue.

Try a different Detector, and see if the problem persists.
