### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'trace'

### ISSUE THREAD

**Issue by consciousgaze** [deepfakes/faceswap#1052]
**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
When I am trying to extract faces from a video in notebook, it fails for exception AttributeError: 'Logger' object has no attribute 'trace'

**To Reproduce**
1. Build a docker image with command `docker build -t faceswap:latest -f Dockerfile.gpu .`
2. Start a docker instance with `docker run -d --runtime=nvidia --name faceswap --rm -it -v `pwd`:/notebooks -p 8000:8888 faceswap:latest`
3. create a notebook
2. Write the following code to execute ```
from scripts import convert
from scripts import train
from scripts import extract
from lib.cli import args
from lib.config import generate_configs

video_path = f"./{project}/{person}/video/faces.mp4"
output_path = f"./{project}/{person}/faces"
parser = args.FullHelpArgumentParser()
subparser = parser.add_subparsers()
args.ExtractArgs(subparser, "extract", "Extract the faces fronm pictures")
parser.parse_args(f"extract -X 0 -LF {project}/logs -i {video_path} -o {output_path}".split())
```
4. Run the cell and the bug will be reproduced.

**Expected behavior**
The cell should finish run with extracted face images

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version 3.7
 - Conda Version: as specified in the dockerfile
 - Commit ID 6b2aac65b14b9683f72ad09bbeae47977308d368
 - 
**Additional context**
Add any other context about the problem here.

**Crash Report**
The crash report generated in the root of your Faceswap folder

08/22/2020 08:35:44 MainProcess     MainThread      utils           safe_shutdown             DEBUG    Safely shutting down
08/22/2020 08:35:44 MainProcess     MainThread      queue_manager   terminate_queues          DEBUG    QueueManager terminating all queues
08/22/2020 08:35:44 MainProcess     MainThread      queue_manager   flush_queues              DEBUG    QueueManager flushed all queues
08/22/2020 08:35:44 MainProcess     MainThread      queue_manager   terminate_queues          DEBUG    QueueManager terminated all queues
08/22/2020 08:35:44 MainProcess     MainThread      utils           safe_shutdown             DEBUG    Cleanup complete. Shutting down queue manager and exiting
08/22/2020 08:35:58 MainProcess     MainThread      utils           set_system_verbosity      DEBUG    System Verbosity level: 2
08/22/2020 08:35:58 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO
08/22/2020 08:35:58 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       set_exclude_devices       DEBUG    Excluding GPU indicies: [0]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       set_exclude_devices       DEBUG    Excluding GPU indicies: [0]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Initializing GPUStats
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Initializing GPUStats
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    OS is not macOS. Trying pynvml
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    OS is not macOS. Trying pynvml
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Device count: 2
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Device count: 2
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Active GPU Devices: [1]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Active GPU Devices: [1]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Handles found: 2
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Handles found: 2
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Driver: 440.100
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Driver: 440.100
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Devices: ['GeForce GTX 1080', 'GeForce RTX 2060']
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Devices: ['GeForce GTX 1080', 'GeForce RTX 2060']
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU VRAM: [8116.4375, 5934.5625]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU VRAM: [8116.4375, 5934.5625]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Initialized GPUStats
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Initialized GPUStats
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Initializing GPUStats
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Initializing GPUStats
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    OS is not macOS. Trying pynvml
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    OS is not macOS. Trying pynvml
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Device count: 2
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Device count: 2
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Active GPU Devices: [1]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Active GPU Devices: [1]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Handles found: 2
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Handles found: 2
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Driver: 440.100
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Driver: 440.100
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Devices: ['GeForce GTX 1080', 'GeForce RTX 2060']
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU Devices: ['GeForce GTX 1080', 'GeForce RTX 2060']
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU VRAM: [8116.4375, 5934.5625]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    GPU VRAM: [8116.4375, 5934.5625]
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Initialized GPUStats
08/22/2020 08:35:58 MainProcess     MainThread      gpu_stats       _log                      DEBUG    Initialized GPUStats
08/22/2020 08:35:58 MainProcess     MainThread      launcher        _configure_backend        DEBUG    Executing: extract. PID: 12
08/22/2020 08:35:58 MainProcess     MainThread      launcher        _configure_backend        DEBUG    Executing: extract. PID: 12
08/22/2020 08:35:58 MainProcess     MainThread      launcher        _test_for_tf_version      DEBUG    Installed Tensorflow Version: 2.2
08/22/2020 08:35:58 MainProcess     MainThread      launcher        _test_for_tf_version      DEBUG    Installed Tensorflow Version: 2.2
08/22/2020 08:35:58 MainProcess     MainThread      extract         __init__                  DEBUG    Initializing Extract: (args: Namespace(aligner='fan', alignments_path=None, colab=False, configfile=None, debug_landmarks=False, detector='s3fd', exclude_gpus=[0], extract_every_n=1, filter=None, func=<bound method ScriptExecutor.execute_script of <lib.cli.launcher.ScriptExecutor object at 0x7f742c204610>>, input_dir='/notebooks/workspace/chenshu/mitaotun/video/faces.mp4', logfile='/notebooks/workspace/chenshu/logs', loglevel='INFO', masker=None, min_size=0, nfilter=None, normalization='none', output_dir='/notebooks/workspace/chenshu/mitaotun/faces', redirect_gui=False, ref_threshold=0.4, rotate_images=None, save_interval=0, singleprocess=False, size=256, skip_existing=False, skip_faces=False, skip_saving_faces=False)
08/22/2020 08:35:58 MainProcess     MainThread      extract         __init__                  DEBUG    Initializing Extract: (args: Namespace(aligner='fan', alignments_path=None, colab=False, configfile=None, debug_landmarks=False, detector='s3fd', exclude_gpus=[0], extract_every_n=1, filter=None, func=<bound method ScriptExecutor.execute_script of <lib.cli.launcher.ScriptExecutor object at 0x7f742c204610>>, input_dir='/notebooks/workspace/chenshu/mitaotun/video/faces.mp4', logfile='/notebooks/workspace/chenshu/logs', loglevel='INFO', masker=None, min_size=0, nfilter=None, normalization='none', output_dir='/notebooks/workspace/chenshu/mitaotun/faces', redirect_gui=False, ref_threshold=0.4, rotate_images=None, save_interval=0, singleprocess=False, size=256, skip_existing=False, skip_faces=False, skip_saving_faces=False)
08/22/2020 08:35:58 MainProcess     MainThread      utils           get_folder                DEBUG    Requested path: '/notebooks/workspace/chenshu/mitaotun/faces'
08/22/2020 08:35:58 MainProcess     MainThread      utils           get_folder                DEBUG    Requested path: '/notebooks/workspace/chenshu/mitaotun/faces'
08/22/2020 08:35:58 MainProcess     MainThread      utils           get_folder                DEBUG    Returning: '/notebooks/workspace/chenshu/mitaotun/faces'
08/22/2020 08:35:58 MainProcess     MainThread      utils           get_folder                DEBUG    Returning: '/notebooks/workspace/chenshu/mitaotun/faces'
08/22/2020 08:35:58 MainProcess     MainThread      extract         __init__                  INFO     Output Directory: /notebooks/workspace/chenshu/mitaotun/faces
08/22/2020 08:35:58 MainProcess     MainThread      extract         __init__                  INFO     Output Directory: /notebooks/workspace/chenshu/mitaotun/faces
08/22/2020 08:35:58 MainProcess     MainThread      image           __init__                  DEBUG    Initializing ImagesLoader: (path: /notebooks/workspace/chenshu/mitaotun/video/faces.mp4, queue_size: 8, fast_count: True, skip_list: None, count: None)
08/22/2020 08:35:58 MainProcess     MainThread      image           __init__                  DEBUG    Initializing ImagesLoader: (path: /notebooks/workspace/chenshu/mitaotun/video/faces.mp4, queue_size: 8, fast_count: True, skip_list: None, count: None)
08/22/2020 08:35:58 MainProcess     MainThread      image           __init__                  DEBUG    Initializing ImagesLoader: (path: /notebooks/workspace/chenshu/mitaotun/video/faces.mp4, queue_size: 8, args: None)
08/22/2020 08:35:58 MainProcess     MainThread      image           __init__                  DEBUG    Initializing ImagesLoader: (path: /notebooks/workspace/chenshu/mitaotun/video/faces.mp4, queue_size: 8, args: None)
08/22/2020 08:35:58 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'ImagesLoader'
08/22/2020 08:35:58 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'ImagesLoader'
08/22/2020 08:35:58 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'ImagesLoader', maxsize: 8)
08/22/2020 08:35:58 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'ImagesLoader', maxsize: 8)
08/22/2020 08:35:58 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'ImagesLoader')
08/22/2020 08:35:58 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'ImagesLoader')
08/22/2020 08:35:58 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'ImagesLoader'
08/22/2020 08:35:58 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'ImagesLoader'
08/22/2020 08:35:58 MainProcess     MainThread      image           _check_for_video          DEBUG    Input '/notebooks/workspace/chenshu/mitaotun/video/faces.mp4' is_video: True
08/22/2020 08:35:58 MainProcess     MainThread      image           _check_for_video          DEBUG    Input '/notebooks/workspace/chenshu/mitaotun/video/faces.mp4' is_video: True
08/22/2020 08:35:59 MainProcess     MainThread      image           _get_fps                  DEBUG    25.0
08/22/2020 08:35:59 MainProcess     MainThread      image           _get_fps                  DEBUG    25.0
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    filename: /notebooks/workspace/chenshu/mitaotun/video/faces.mp4, fast: True
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    filename: /notebooks/workspace/chenshu/mitaotun/video/faces.mp4, fast: True
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    FFMPEG Command: '/usr/local/lib/python3.7/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2 -i /notebooks/workspace/chenshu/mitaotun/video/faces.mp4 -map 0:v:0 -c copy -f null -'
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    FFMPEG Command: '/usr/local/lib/python3.7/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2 -i /notebooks/workspace/chenshu/mitaotun/video/faces.mp4 -map 0:v:0 -c copy -f null -'
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    Duration line: Duration: 00:40:45.16, start: 0.000000, bitrate: 697 kb/s
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    Duration line: Duration: 00:40:45.16, start: 0.000000, bitrate: 697 kb/s
08/22/2020 08:35:59 MainProcess     MainThread      utils           convert_to_secs           DEBUG    from time: ('00', '40', '45.16')
08/22/2020 08:35:59 MainProcess     MainThread      utils           convert_to_secs           DEBUG    from time: ('00', '40', '45.16')
08/22/2020 08:35:59 MainProcess     MainThread      utils           convert_to_secs           DEBUG    to secs: 2445.16
08/22/2020 08:35:59 MainProcess     MainThread      utils           convert_to_secs           DEBUG    to secs: 2445.16
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    duration: 2445
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    duration: 2445
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    frame line: frame=61128 fps=0.0 q=-1.0 Lsize=N/A time=00:40:45.00 bitrate=N/A speed=1.03e+04x
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    frame line: frame=61128 fps=0.0 q=-1.0 Lsize=N/A time=00:40:45.00 bitrate=N/A speed=1.03e+04x
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    Initializing tqdm
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    Initializing tqdm
08/22/2020 08:35:59 MainProcess     MainThread      utils           convert_to_secs           DEBUG    from time: ('00', '40', '45.00')
08/22/2020 08:35:59 MainProcess     MainThread      utils           convert_to_secs           DEBUG    from time: ('00', '40', '45.00')
08/22/2020 08:35:59 MainProcess     MainThread      utils           convert_to_secs           DEBUG    to secs: 2445.0
08/22/2020 08:35:59 MainProcess     MainThread      utils           convert_to_secs           DEBUG    to secs: 2445.0
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    frames: 61128, vid_time: 2445
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    frames: 61128, vid_time: 2445
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    Return code: 0, frames: 61128
08/22/2020 08:35:59 MainProcess     MainThread      image           count_frames              DEBUG    Return code: 0, frames: 61128
08/22/2020 08:35:59 MainProcess     MainThread      image           _get_count_and_filelist   DEBUG    count: 61128
08/22/2020 08:35:59 MainProcess     MainThread      image           _get_count_and_filelist   DEBUG    count: 61128
Traceback (most recent call last):
  File "/notebooks/lib/cli/launcher.py", line 155, in execute_script
    process = script(arguments)
  File "/notebooks/scripts/extract.py", line 44, in __init__
    self._images = ImagesLoader(self._args.input_dir, fast_count=True)
  File "/notebooks/lib/image.py", line 754, in __init__
    self._get_count_and_filelist(fast_count, count)
  File "/notebooks/lib/image.py", line 869, in _get_count_and_filelist
    logger.trace("filelist: %s", self.file_list)
AttributeError: 'Logger' object has no attribute 'trace'

============ System Information ============
encoding:            UTF-8
git_branch:          local
git_commits:         15d401c Improve data cleansing ui. 42acd68 Add ui feature to move selected images to selected folder. 61a23da typo fix. efc61ae Add code to support iteractive data cleansing. d143aa1 include work notebooks
gpu_cuda:            10.1
gpu_cudnn:           No global version found
gpu_devices:         GPU_0: GeForce GTX 1080, GPU_1: GeForce RTX 2060
gpu_devices_active:  GPU_1
gpu_driver:          440.100
gpu_vram:            GPU_0: 8116MB, GPU_1: 5934MB
os_machine:          x86_64
os_platform:         Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
os_release:          5.4.0-42-generic
py_command:          /usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py -f /root/.local/share/jupyter/runtime/kernel-91d04234-b5a8-4c62-a4f2-beef453e3768.json
py_conda_version:    N/A
py_implementation:   CPython
py_version:          3.7.8
py_virtual_env:      False
sys_cores:           12
sys_processor:       x86_64
sys_ram:             Total: 64287MB, Available: 52798MB, Used: 9941MB, Free: 13970MB

=============== Pip Packages ===============
absl-py==0.9.0
argon2-cffi==20.1.0
asn1crypto==0.24.0
astunparse==1.6.3
attrs==19.3.0
backcall==0.2.0
bleach==3.1.5
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
cryptography==2.1.4
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
fastcluster==1.1.26
ffmpy==0.2.3
gast==0.3.3
google-auth==1.20.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.31.0
h5py==2.10.0
idna==2.6
imageio==2.9.0
imageio-ffmpeg==0.4.2
importlib-metadata==1.7.0
ipykernel==5.3.4
ipython==7.17.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.2
Jinja2==2.11.2
joblib==0.16.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.6
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyter-http-over-ws==0.0.8
Keras-Preprocessing==1.1.2
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.2.0
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.3.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.7
notebook==6.1.3
numpy==1.19.1
nvidia-ml-py3 @ git+https://github.com/deepfakes/nvidia-ml-py3.git@6fc29ac84b32bad877f078cb4a777c1548a00bf6
oauthlib==3.1.0
opencv-python==4.4.0.42
opt-einsum==3.3.0
packaging==20.4
pandocfilters==1.4.2
parso==0.7.1
pathlib==1.0.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
prometheus-client==0.8.0
prompt-toolkit==3.0.6
protobuf==3.13.0
psutil==5.7.2
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycrypto==2.6.1
Pygments==2.6.1
pygobject==3.26.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-apt==1.6.5+ubuntu0.2
python-dateutil==2.8.1
pyxdg==0.25
pyzmq==19.0.2
qtconsole==4.7.6
QtPy==1.9.0
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-learn==0.23.2
scipy==1.5.2
SecretStorage==2.3.1
Send2Trash==1.5.0
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow-estimator==2.2.0
tensorflow-gpu==2.2.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
threadpoolctl==2.1.0
tornado==6.0.4
tqdm==4.48.2
traitlets==4.3.3
urllib3==1.25.10
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.1.0

================= Configs ==================
--------- extract.ini ---------

[global]
allow_growth:             True

[mask.vgg_obstructed]
batch-size:               2

[mask.vgg_clear]
batch-size:               6

[mask.unet_dfl]
batch-size:               8

[align.fan]
batch-size:               12

[detect.cv2_dnn]
confidence:               50

[detect.mtcnn]
minsize:                  20
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7
scalefactor:              0.709
batch-size:               8

[detect.s3fd]
confidence:               70
batch-size:               4

--------- .faceswap ---------
backend:                  nvidia

--------- convert.ini ---------

[writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

[writer.pillow]
format:                   png
draw_transparent:         False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

[writer.opencv]
format:                   png
draw_transparent:         False
jpg_quality:              75
png_compress_level:       3

[writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     none
profile:                  auto
level:                    auto
skip_mux:                 False

[color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

[color.match_hist]
threshold:                99.0

[color.color_transfer]
clip:                     True
preserve_paper:           True

[mask.box_blend]
type:                     gaussian
distance:                 11.0
radius:                   5.0
passes:                   1

[mask.mask_blend]
type:                     normalized
kernel_size:              3
passes:                   4
threshold:                4
erosion:                  0.0

[scaling.sharpen]
method:                   unsharp_mask
amount:                   150
radius:                   0.3
threshold:                5.0

--------- train.ini ---------

[global]
coverage:                 68.75
mask_type:                extended
mask_blur_kernel:         3
mask_threshold:           4
learn_mask:               False
icnr_init:                False
conv_aware_init:          False
reflect_padding:          False
allow_growth:             False
penalized_mask_loss:      True
loss_function:            mae
learning_rate:            5e-05

[model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.dlight]
features:                 best
details:                  good
output_size:              256

[model.dfl_h128]
lowmem:                   False

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.villain]
lowmem:                   False

[model.original]
lowmem:                   False

[model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4

**Comment by torzdf** [comment]
Unfortunately, whilst we have a Docker container, which (I think) still works, none of the current devs use it, so it is unsupported.

We welcome PRs to keep it working, but that is as far as our support goes on it.
