### ISSUE TITLE
can't train after update

### ISSUE THREAD

**Issue by mnmn44** [deepfakes/faceswap#1062]
09/12/2020 12:02:53 CRITICAL Error caught! Exiting...
09/12/2020 12:02:53 ERROR    Caught exception in thread: '_training_0'
09/12/2020 12:02:56 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "K:\faceswap_v2\lib\cli\launcher.py", line 156, in execute_script
process.process()
File "K:\faceswap_v2\scripts\train.py", line 165, in process
self._end_thread(thread, err)
File "K:\faceswap_v2\scripts\train.py", line 205, in _end_thread
thread.join()
File "K:\faceswap_v2\lib\multithreading.py", line 121, in join
raise thread.err[1].with_traceback(thread.err[2])
File "K:\faceswap_v2\lib\multithreading.py", line 37, in run
self._target(*self._args, **self._kwargs)
File "K:\faceswap_v2\scripts\train.py", line 227, in _training
raise err
File "K:\faceswap_v2\scripts\train.py", line 217, in _training
self._run_training_cycle(model, trainer)
File "K:\faceswap_v2\scripts\train.py", line 298, in _run_training_cycle
trainer.train_one_step(viewer, timelapse)
File "K:\faceswap_v2\plugins\train\trainer\_base.py", line 211, in train_one_step
loss = self._model.model.train_on_batch(model_inputs, y=model_targets)
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1348, in train_on_batch
logs = train_function(iterator)
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
result = self._call(*args, **kwds)
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\eager\def_function.py", line 627, in _call
self._initialize(args, kwds, add_initializers_to=initializers)
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\eager\def_function.py", line 505, in _initialize
self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\eager\function.py", line 2446, in _get_concrete_function_internal_garbage_collected
graph_function, _, _ = self._maybe_define_function(args, kwargs)
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\eager\function.py", line 2777, in _maybe_define_function
graph_function = self._create_graph_function(args, kwargs)
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\eager\function.py", line 2657, in _create_graph_function
func_graph_module.func_graph_from_py_func(
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
func_outputs = python_func(*func_args, **func_kwargs)
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\eager\def_function.py", line 441, in wrapped_fn
return weak_wrapped_fn().__wrapped__(*args, **kwds)
File "C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\framework\func_graph.py", line 968, in wrapper
raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\keras\engine\training.py:571 train_function  *
outputs = self.distribute_strategy.run(
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:951 run  **
return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2290 call_for_each_replica
return self._call_for_each_replica(fn, args, kwargs)
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2649 _call_for_each_replica
return fn(*args, **kwargs)
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\keras\engine\training.py:532 train_step  **
loss = self.compiled_loss(
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:205 __call__
loss_value = loss_obj(y_t, y_p, sample_weight=sw)
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\keras\losses.py:143 __call__
losses = self.call(y_true, y_pred)
K:\faceswap_v2\lib\model\losses_tf.py:559 call
n_true, n_pred = self._apply_mask(y_true, y_pred, mask_channel)
K:\faceswap_v2\lib\model\losses_tf.py:589 _apply_mask
mask = K.expand_dims(y_true[..., mask_channel], axis=-1)
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\ops\array_ops.py:973 _slice_helper
return strided_slice(
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\ops\array_ops.py:1140 strided_slice
op = gen_array_ops.strided_slice(
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\ops\gen_array_ops.py:10174 strided_slice
_, _, _op, _outputs = _op_def_library._apply_op_helper(
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\framework\op_def_library.py:742 _apply_op_helper
op = g._create_op_internal(op_type_name, inputs, dtypes=None,
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\framework\func_graph.py:593 _create_op_internal
return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\framework\ops.py:3319 _create_op_internal
ret = Operation(
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\framework\ops.py:1816 __init__
self._c_op = _create_c_op(self._graph, node_def, inputs,
C:\Users\Betes\MiniConda3\envs\faceswapv2\lib\site-packages\tensorflow\python\framework\ops.py:1657 _create_c_op
raise ValueError(str(e))

ValueError: slice index 4 of dimension 3 out of bounds. for '{{node LossWrapper/strided_slice_11}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=1, end_mask=0, new_axis_mask=0, shrink_axis_mask=2](IteratorGetNext:2, LossWrapper/strided_slice_11/stack, LossWrapper/strided_slice_11/stack_1, LossWrapper/strided_slice_11/stack_2)' with input shapes: [15,128,128,4], [2], [2], [2] and with computed input tensors: input[1] = <0 4>, input[2] = <0 5>, input[3] = <1 1>.

09/12/2020 12:02:56 CRITICAL An unexpected crash has occurred. Crash report written to 'K:\faceswap_v2\crash_report.2020.09.12.120253943868.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting

Process exited.

**Comment by mnmn44** [comment]
[crash_report.2020.09.12.115827271955.log](https://github.com/deepfakes/faceswap/files/5212220/crash_report.2020.09.12.115827271955.log)

**Comment by torzdf** [comment]
I believe this bug has been fixed. If not, please reopen with a new crash report
