### ISSUE TITLE
Can't start it at all, settings for AMD 

### ISSUE THREAD

**Issue by paja93** [deepfakes/faceswap#1076]
Trying python faceswap.py -h

Setting Faceswap backend to AMD
Traceback (most recent call last):
  File "faceswap.py", line 5, in <module>
    from lib.cli import args
  File "/home/xxxxx/faceswap/lib/cli/args.py", line 21, in <module>
    _GPUS = GPUStats().cli_devices
  File "/home/xxxxx/faceswap/lib/gpu_stats.py", line 76, in __init__
    self._initialize(log)
  File "/home/xxxxx/faceswap/lib/gpu_stats.py", line 164, in _initialize
    self._plaid = plaidlib(log_level=loglevel, log=log)
TypeError: 'NoneType' object is not callable

**Comment by torzdf** [comment]
Your GPU isn't detected. Make sure you have the latest AMDGPU PRO drivers installed.

If you still have issues, enter your faceswap environment and run `plaidml-setup`
