### ISSUE TITLE
ModuleNotFoundError: No module named 'Users'

### ISSUE THREAD

**Issue by itfvck** [deepfakes/faceswap#1093]
1. Go to the menu 'Settings'
2. Click on 'Configure Settings'
3. See error

Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\faceswap\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "d:\Users\Administrator\faceswap\lib\gui\popup_configure.py", line 41, in open_popup
    self._scan_for_configs()
  File "d:\Users\Administrator\faceswap\lib\gui\popup_configure.py", line 68, in _scan_for_configs
    config = self._load_config(plugin_type)
  File "d:\Users\Administrator\faceswap\lib\gui\popup_configure.py", line 90, in _load_config
    config = module.Config(None)
  File "d:\Users\Administrator\faceswap\lib\config.py", line 27, in __init__
    self.set_defaults()
  File "d:\Users\Administrator\faceswap\plugins\convert\_config.py", line 31, in set_defaults
    self.load_module(filename, import_path, plugin_type)
  File "d:\Users\Administrator\faceswap\plugins\convert\_config.py", line 40, in load_module
    mod = import_module("{}.{}".format(module_path, module))
  File "D:\ProgramData\Miniconda3\envs\faceswap\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Users'

**Comment by torzdf** [comment]
This looks like a system issue rather than a bug in the software.

You should look for support either at our Forum (https://forum.faceswap.dev/index.php) or Discord (https://discord.gg/FC54sYg)
