### ISSUE TITLE
Recent commit causing list index out of range error?

### ISSUE THREAD

**Issue by jediMindTricker** [deepfakes/faceswap#110]
Ubuntu 16.04, CPU only, commit 2198ec6, Python 3.5, tensorflow 1.5/1.4

<>@<>:~/faceswap/faceswap-master$ python3 faceswap.py train -A ~/faceswap/<>/data -B ~/faceswap/<>/data -m ~/faceswap/models/
Model A Directory: /<>/data
Model B Directory: /home/<>data
Training data directory: /home/<>/models
Loading data, this may take a while...
Loading Model from Model_Original plugin...
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Failed loading existing training data.
Unable to open file (unable to open file: name = '/home/justinkterry/faceswap/models/encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Loading Trainer from Model_Original plugin...
Starting. Press "Enter" to stop training and save model
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/justinkterry/faceswap/faceswap-master/lib/utils.py", line 42, in run
    for item in self.generator:
  File "/home/justinkterry/faceswap/faceswap-master/lib/training_data.py", line 43, in minibatch
    rtn = numpy.float32([read_image(data[j]) for j in range(i,i+size)])
  File "/home/justinkterry/faceswap/faceswap-master/lib/training_data.py", line 43, in <listcomp>
    rtn = numpy.float32([read_image(data[j]) for j in range(i,i+size)])
IndexError: list index out of range

**Comment by jediMindTricker** [comment]
My paths are fine, they're just weird. the <> is to anonymize it if that's what you're asking about.

The 64 items explains it; a more specific error and documentation would be very helpful. I'm doing something specific where there's only 40 images available for the face being transferred. Is there a flag to change the batch size to get around this?

Also, because I can't find this anywhere else, how many images are recommended? (I'm aware it's more than 40, but ball park).

**Comment by facepainter** [comment]
> My paths are fine, they're just weird. the <> is to anonymize it if that's what you're asking about.

Ah ok, makes sense.

> Is there a flag to change the batch size to get around this?

Sure - just set the batch size via the -bs flag (Batch size, as a power of 2 (64, 128, 256, etc))

`train -A ~/faceswap/A -B ~/faceswap/B -m ~/faceswap/models/.... -bs 32
`
Looking at 

https://github.com/deepfakes/faceswap/blob/2198ec677961aad77dfab25988b62b0ea654e8a0/lib/training_data.py#L43

There is actually a check on line 39 - but 43 is not in that scope...can be fixes easily. 

I guess it hasn't come up because most people are training with 100s/1000s of images.

**Comment by jediMindTricker** [comment]
Could you add the -bs flag to the usage md file as well?

**Comment by facepainter** [comment]
You can get the full list of arguments for each script by running it with the help flag. e.g.

> python faceswap.py -h
> python faceswap.py train -h
> python faceswap.py extract -h
> python faceswap.py convert -h

**Comment by jediMindTricker** [comment]
Fair enough, just mentioning people would be worth including in the usage.md if you want to go that way. 

Also, if you don't mind, could you please walk me through what the window shown by -p is displaying? That flag and the usage don't specify, and (at least without a trained model) it's not clear what exactly it's representing/

**Comment by facepainter** [comment]
Not really the place for an extended discussion about that here....but 

col 1 shows A 
col 2 shows A redrawn using model
col 3 shows predicted transform A->B
cols 4-6 do the same as 1-3.
cols 7-9 do the same as 1-3 but swap A for B
cols 10-12 do the same 7-9.

**Comment by Gastel71** [comment]
Just change line 43 on training_data.py to
`rtn = numpy.float32([read_image(data[j]) for j in range(i,min(length,i+size))])`
if you want to fix the index out of range error

**Comment by gdunstone** [comment]
@Gastel71 it is better to throw an error in this case.

I would put a test just before processing begins:

https://github.com/deepfakes/faceswap/blob/1f1cbdf0e7c69a1cdf162e182470c51d3e6623d2/lib/training_data.py#L33

```python
assert length >= batchsize, "Number of images less than batch size. # images: {}".format(length)
```

Correct me if Im wrong but there seems like almost no reason why the batch size should be larger than the number of images.

**Comment by gdunstone** [comment]
@facepainter Could you add that information about the preview window to our USAGE.md?

**Comment by Gastel71** [comment]
Hi @gdunstone,
honestly, but it's just my opinion, I prefer my solution since it fixes the problem and it lets someone with a small group of images (say for example 63, since the default batch size is 64) to use the script without having to manually adjust the -bs argument.

**Comment by jediMindTricker** [comment]
@gdunstone Of course there's no reason for the batch size to be bigger, but say somethings doing something where only 40 images exist of one person (reasonable thing for someone to attempt) and didn't know how to change the batch size. Hence it being an error.

@facepainter when you add the column descriptors, consider adding what they should look like for a good model.
