### ISSUE TITLE
Tkinter error

### ISSUE THREAD

**Issue by torvall11** [deepfakes/faceswap#1114]
Bug Description:
Running training in the GUI results in the following error message after all images and alignments are loaded and then the "Graph" tab is selected:
`Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/torvall11/anaconda3/envs/fs/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/torvall11/anaconda3/envs/fs/lib/python3.8/tkinter/__init__.py", line 804, in callit
    func(*args)
  File "/home/torvall11/faceswap/lib/gui/display_page.py", line 268, in _update_page
    self.load_display()
  File "/home/torvall11/faceswap/lib/gui/display_page.py", line 280, in load_display
    self.display_item_process()
  File "/home/torvall11/faceswap/lib/gui/display_command.py", line 380, in display_item_process
    data = Calculations(session_id=Session.session_ids[-1],
  File "/home/torvall11/faceswap/lib/gui/stats.py", line 837, in __init__
    self.refresh()
  File "/home/torvall11/faceswap/lib/gui/stats.py", line 862, in refresh
    self._get_raw()
  File "/home/torvall11/faceswap/lib/gui/stats.py", line 925, in _get_raw
    loss_dict = Session.get_loss(self._session_id)
  File "/home/torvall11/faceswap/lib/gui/stats.py", line 176, in get_loss
    retval = loss_dict[session_id]
KeyError: 5
`
The "Graph" and "Analysis" tabs are both blank. However, the train.py seems to be running because the "Stop" button causes training to end gracefully. 

1. Create new conda environment and activate it
2. Run setup.py
3. Run python faceswap.py gui 
4. Extract all images
5. Start training 
6. Click on "Graph" tab

Expected behavior
The Graph and Analysis tabs should be functional.

Desktop
 - OS: Ubuntu 20.04.1
 - Python Version 3.8
 - Conda Version 4.9.2
 
 `pip list`
Package                Version
---------------------- -------------------
absl-py                0.11.0
aiohttp                3.6.3
astunparse             1.6.3
async-timeout          3.0.1
attrs                  20.3.0
blinker                1.4
brotlipy               0.7.0
cachetools             4.2.0
certifi                2020.12.5
cffi                   1.14.4
chardet                3.0.4
click                  7.1.2
cryptography           3.3.1
cycler                 0.10.0
fastcluster            1.1.26
ffmpy                  0.2.3
gast                   0.3.3
google-auth            1.24.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
grpcio                 1.31.0
h5py                   2.10.0
idna                   2.10
imageio                2.9.0
imageio-ffmpeg         0.4.3
importlib-metadata     2.0.0
joblib                 1.0.0
Keras-Preprocessing    1.1.0
kiwisolver             1.3.0
Markdown               3.3.3
matplotlib             3.0.3
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
multidict              4.7.6
numpy                  1.19.2
nvidia-ml-py3          7.352.1
oauthlib               3.1.0
olefile                0.46
opencv-python          4.5.1.48
opt-einsum             3.1.0
pathlib                1.0.1
Pillow                 8.1.0
pip                    20.3.3
protobuf               3.13.0
psutil                 5.7.2
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
PyJWT                  1.7.1
pyOpenSSL              20.0.1
pyparsing              2.4.7
PySocks                1.7.1
python-dateutil        2.8.1
requests               2.25.1
requests-oauthlib      1.3.0
rsa                    4.6
scikit-learn           0.23.2
scipy                  1.5.2
setuptools             51.0.0.post20201207
sip                    4.19.13
six                    1.15.0
tensorboard            2.3.0
tensorboard-plugin-wit 1.6.0
tensorflow             2.3.0
tensorflow-estimator   2.3.0
termcolor              1.1.0
threadpoolctl          2.1.0
tornado                6.1
tqdm                   4.55.1
urllib3                1.26.2
Werkzeug               1.0.1
wheel                  0.36.2
wrapt                  1.12.1
yarl                   1.6.3
zipp                   3.4.0

**Crash Report**
No crash report was found in root directory.

**Comment by torvall11** [comment]
Never mind, the solution is to run the python inside the conda environment. bash was defaulting to the system-wide python. Use `~/anaconda3/envs/<name>/bin/python3.8 faceswap.py gui` for the correct functionality.
