### ISSUE TITLE
Crash after trained for 2 days and can not run Train process and Tools/Preview process

### ISSUE THREAD

**Issue by cocia** [deepfakes/faceswap#1130]
Crash after trained for 2 days and can not run Train process and Tools/Preview process again.

**Describe the bug log in GUI**

Loading...
Setting Faceswap backend to NVIDIA
Please backup your data and/or test the tool you want to use with a smaller data set to make sure you understand how it works.
03/08/2021 09:47:41 INFO     Log level set to: INFO
03/08/2021 09:47:43 INFO     Input Video: C:\Users\LPC02\Videos\ForrestGumpC1.mp4

03/08/2021 09:47:44 INFO     Reading alignments from: 'C:\Users\LPC02\Videos\ForrestGumpC1_alignments.fsa'
03/08/2021 09:47:44 INFO     Loading Model from Original plugin...
03/08/2021 09:47:44 INFO     Using configuration saved in state file
03/08/2021 09:47:48 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "D:\app\faceswap\lib\cli\launcher.py", line 181, in execute_script
process = script(arguments)
File "D:\app\faceswap\tools\preview\preview.py", line 62, in __init__
self._samples = Samples(arguments, 5, self._display, self._lock, trigger_patch)
File "D:\app\faceswap\tools\preview\preview.py", line 202, in __init__
self._predictor = Predict(queue_manager.get_queue("preview_predict_in"),
File "D:\app\faceswap\scripts\convert.py", line 661, in __init__
self._model = self._load_model()
File "D:\app\faceswap\scripts\convert.py", line 746, in _load_model
model.build()
File "D:\app\faceswap\plugins\train\model\_base.py", line 258, in build
model = self._io._load()  # pylint:disable=protected-access
File "D:\app\faceswap\plugins\train\model\_base.py", line 520, in _load
model = load_model(self._filename, compile=False)
File "C:\Users\LPC02\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\keras\saving\save.py", line 182, in load_model
return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
File "C:\Users\LPC02\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 181, in load_model_from_hdf5
load_weights_from_hdf5_group(f['model_weights'], model.layers)
File "C:\Users\LPC02\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 677, in load_weights_from_hdf5_group
g = f[name]
File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "C:\Users\LPC02\MiniConda3\envs\faceswap\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'face_in_a' doesn't exist)"
03/08/2021 09:47:48 CRITICAL An unexpected crash has occurred. Crash report written to 'D:\app\faceswap\crash_report.2021.03.08.094746579604.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting

Process exited.

**Crash Report**
[crash_report.2021.03.08.094746579604.log](https://github.com/deepfakes/faceswap/files/6098449/crash_report.2021.03.08.094746579604.log)

**Comment by torzdf** [comment]
This is model corruption. Use the restore tool to restore a good backup.
