### ISSUE TITLE
DLL load failed while importing qhull

### ISSUE THREAD

**Issue by ydanila** [deepfakes/faceswap#1141]
After one of the latest updates (and may be GPU driver update too) Train fails to start.

I tried to remove everything including miniconda, cleanup and reinstall. Tried to changed default conda enironment name and reinstall again, but this not helps.

Here is error from CLI

```
C:\Users\user>C:\Users\user\MiniConda3\envs\faceswap_new\python.exe E:\0\faceswap\faceswap.py train -A E:/0/workspace/facce2_faces -B E:/0/workspace/facce1_faces -m E:/0/workspace/facce1_facce2_dlight -t dlight -bs 24 -it 1000000 -s 250 -ss 5000 -ps 100 -w -L INFO
Setting Faceswap backend to AMD
04/02/2021 10:06:11 INFO     Log level set to: INFO
04/02/2021 10:06:11 INFO     Setting up for PlaidML
04/02/2021 10:06:11 INFO     Using GPU(s): ['Advanced Micro Devices, Inc. - gfx902 (experimental)']
04/02/2021 10:06:11 INFO     Successfully set up for PlaidML
04/02/2021 10:06:13 INFO     Model A Directory: 'E:\0\workspace\facce2_faces' (4556 images)
04/02/2021 10:06:13 INFO     Model B Directory: 'E:\0\workspace\facce1_faces' (2006 images)
04/02/2021 10:06:13 INFO     Training data directory: E:\0\workspace\facce1_facce2_dlight
04/02/2021 10:06:13 INFO     ===================================================
04/02/2021 10:06:13 INFO       Starting
04/02/2021 10:06:13 INFO       Press 'ENTER' to save and quit
04/02/2021 10:06:13 INFO       Press 'S' to save model weights immediately
04/02/2021 10:06:13 INFO     ===================================================
04/02/2021 10:06:13 INFO     Exit requested! The trainer will complete its current cycle, save the models and quit (This can take a couple of minutes depending on your training speed). If you want to kill it now, press Ctrl + c
04/02/2021 10:06:14 INFO     Loading data, this may take a while...
04/02/2021 10:06:14 INFO     Loading Model from Dlight plugin...
04/02/2021 10:06:14 ERROR    Caught exception in thread: '_training_0'
04/02/2021 10:06:15 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\site-packages\keras\backend\__init__.py", line 93, in <module>
    backend_module = importlib.import_module(_BACKEND)
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\site-packages\plaidml\keras\backend.py", line 33, in <module>
    import scipy.stats
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\site-packages\scipy\stats\__init__.py", line 391, in <module>
    from .stats import *
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\site-packages\scipy\stats\stats.py", line 174, in <module>
    from scipy.spatial.distance import cdist
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\site-packages\scipy\spatial\__init__.py", line 98, in <module>
    from .qhull import *
ImportError: DLL load failed while importing qhull: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\0\faceswap\lib\cli\launcher.py", line 182, in execute_script
    process.process()
  File "E:\0\faceswap\scripts\train.py", line 187, in process
    self._end_thread(thread, err)
  File "E:\0\faceswap\scripts\train.py", line 227, in _end_thread
    thread.join()
  File "E:\0\faceswap\lib\multithreading.py", line 121, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "E:\0\faceswap\lib\multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "E:\0\faceswap\scripts\train.py", line 249, in _training
    raise err
  File "E:\0\faceswap\scripts\train.py", line 237, in _training
    model = self._load_model()
  File "E:\0\faceswap\scripts\train.py", line 261, in _load_model
    model = PluginLoader.get_model(self._args.trainer)(
  File "E:\0\faceswap\plugins\plugin_loader.py", line 97, in get_model
    return PluginLoader._import("train.model", name, disable_logging)
  File "E:\0\faceswap\plugins\plugin_loader.py", line 163, in _import
    module = import_module(mod)
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\0\faceswap\plugins\train\model\dlight.py", line 11, in <module>
    from keras.layers import (AveragePooling2D, BatchNormalization, Concatenate, Dense, Dropout,
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\user\MiniConda3\envs\faceswap_new\lib\site-packages\keras\backend\__init__.py", line 108, in <module>
    raise ValueError('Unable to import backend : ' + str(_BACKEND))
ValueError: Unable to import backend : plaidml.keras.backend
04/02/2021 10:06:15 CRITICAL An unexpected crash has occurred. Crash report written to 'E:\0\faceswap\crash_report.2021.04.02.100614675689.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting
```
**Desktop (please complete the following information):**
 - Win10x64
 - Python 3.8.8
 - conda 4.9.0
 - SHA-1: f60eaee9557b9f54bd3ec3446563aa820ce421ed
 - 
**Additional context**
```
04/02/2021 10:23:47 INFO     Checking for updates...
04/02/2021 10:23:48 INFO     Faceswap is up to date.
04/02/2021 10:23:48 INFO     Updating dependencies...
04/02/2021 10:23:48 INFO     Setup in Windows 10
04/02/2021 10:23:48 INFO     Installed Python: 3.8.8 64bit
04/02/2021 10:23:48 INFO     Running in Conda
04/02/2021 10:23:48 INFO     Running in a Virtual Environment
04/02/2021 10:23:48 INFO     Encoding: cp1251
04/02/2021 10:23:48 INFO     Installed pip: 21.0.1
04/02/2021 10:23:51 INFO     All Dependencies are up to date
04/02/2021 10:23:51 INFO     Dependencies updated
```

**Crash Report**
The crash report generated in the root of your Faceswap folder
[crash_report.2021.04.02.100614675689.log](https://github.com/deepfakes/faceswap/files/6248251/crash_report.2021.04.02.100614675689.log)

**Comment by torzdf** [comment]
This, unfortunately, is a system issue, not a Faceswap issue.

You can try this solution by a user posted on our forums:
https://forum.faceswap.dev/viewtopic.php?t=572

Otherwise, you're going to need to do some googling, I'm afraid:
https://www.google.com/search?q=%22DLL+load+failed+while+importing+qhull%22&client=firefox-b-d&sxsrf=ALeKk02XrVsRJ-pnaKqLJXuc1jL3VWze0Q%3A1617359912453&ei=KPRmYIaEG8aK9u8Pv_eJsAE&oq=%22DLL+load+failed+while+importing+qhull%22&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBggAEAcQHjICCAAyBAgAEB4yBggAEAcQHjoHCCMQsAMQJzoHCAAQRxCwAzoGCAAQFhAeUPI1WI87YMo8aAFwAngAgAF_iAH0AZIBAzIuMZgBAKABAaoBB2d3cy13aXrIAQnAAQE&sclient=gws-wiz&ved=0ahUKEwiGuLiYr9_vAhVGhf0HHb97AhYQ4dUDCAw&uact=5
