### ISSUE TITLE
Disabling AMD and CUDA sets backed to "cpu" in config, but running faceswap -h still tries to load CUDA

### ISSUE THREAD

**Issue by dneuer** [deepfakes/faceswap#1143]
Turning off all GPU related config items during setup does create config/.faceswap, which contains {"backend": "cpu"}.

However, running faceswap.py -h throws an exception and terminates the program:

Setting Faceswap backend to CPU
Traceback (most recent call last):
  File "faceswap.py", line 6, in <module>
    from lib.cli import args as cli_args
  File "/Users/mrfredsmoothie/software/faceswap/lib/cli/args.py", line 13, in <module>
    from lib.gpu_stats import GPUStats
  File "/Users/mrfredsmoothie/software/faceswap/lib/gpu_stats.py", line 17, in <module>
    import pynvx  # pylint: disable=import-error
ModuleNotFoundError: No module named 'pynvx'

Why set the backend to CPU and then choke trying to display options?

**To Reproduce**
1. configure a lack of GPU support
2. try to use the -h option to list available options and commands

**Expected behavior**
Don't try to load GPU info if no GPU support is configured

**Desktop (please complete the following information):**
 - OS: MacOS X 11.2.3 (M1 arm64)
 - Python Version Python 3.8.8
 - Conda Version 4.10.0
 - Commit ID f60eaee

**Comment by sonson1023** [comment]
I have same issue. ...

**Comment by torzdf** [comment]
This is because you are running on an M1 Mac.

I will update documentation at some point, but M1 Mac's are not supported by default, and would require some work on your part to get working.

When pynvx was added as a lib for Mac users, M1 did not exist. Clearly this package cannot be used for M1 Macs, so some work would need to be done to handle this.

I do not own a Mac, much less an M1 Mac, so it's unlikely I'm going to be able to do much with this,

**Comment by saifookhan** [comment]
+1 for M1. ;_;

**Comment by torzdf** [comment]
Closing issue as M1 support has been added
