### ISSUE TITLE
BUG: Exception in Tkinter callback & TypeError: 'NoneType' object is not an iterator

### ISSUE THREAD

**Issue by HoloByteus** [deepfakes/faceswap#1148]
1.  Start a new training and wait for 250 iterations in the default preview tab view. 
2. The first click on the Analysis tab will generate the following error in the console.  Training is still running and no data is displayed in the Analysis window.  
3. Clicking on the Graphs tab at this point will cause Faceswap to hang which I did to generate a crash report.
4. Reloading Faceswap and continuing training will then allow the Analysis tab to display data and resolve the issue.

Console Error:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mmcgu\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\mmcgu\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "F:\program files\faceswap\lib\gui\display_analysis.py", line 190, in <lambda>
    self.after(1000, lambda msg=message: self._set_session_summary(msg))
  File "F:\program files\faceswap\lib\gui\display_analysis.py", line 196, in _set_session_summary
    result = self._thread.get_result()
  File "F:\program files\faceswap\lib\gui\utils.py", line 1183, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "F:\program files\faceswap\lib\gui\utils.py", line 1154, in run
    retval = self._target(*self._args, **self._kwargs)
  File "F:\program files\faceswap\lib\gui\display_analysis.py", line 215, in _summarise_data
    return session.full_summary
  File "F:\program files\faceswap\lib\gui\analysis\stats.py", line 70, in full_summary
    return self._summary.get_summary_stats()
  File "F:\program files\faceswap\lib\gui\analysis\stats.py", line 280, in get_summary_stats
    self._get_time_stats()
  File "F:\program files\faceswap\lib\gui\analysis\stats.py", line 306, in _get_time_stats
    for sess_id, timestamps in self._session.get_timestamps(None).items()}
  File "F:\program files\faceswap\lib\gui\analysis\stats.py", line 204, in get_timestamps
    retval = self._tb_logs.get_timestamps(session_id=session_id)
  File "F:\program files\faceswap\lib\gui\analysis\event_reader.py", line 498, in get_timestamps
    self._check_cache(idx)
  File "F:\program files\faceswap\lib\gui\analysis\event_reader.py", line 440, in _check_cache
    self._cache_data(session_id)
  File "F:\program files\faceswap\lib\gui\analysis\event_reader.py", line 428, in _cache_data
    parser.cache_events(session_id)
  File "F:\program files\faceswap\lib\gui\analysis\event_reader.py", line 570, in cache_events
    for record in self._iterator:
  File "F:\program files\faceswap\lib\gui\analysis\event_reader.py", line 548, in _get_latest_live
    yield next(iterator)
TypeError: 'NoneType' object is not an iterator

**Expected behavior**
Clicking on the Analysis tab should bring up Analysis data and not generate a console error.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2 build 19042.928 (latest updates)
 - Python Version: 3.8
 - Conda Version: default faceswap miniconda install
 - Commit ID: None
 - 
**Additional context**

**Crash Report**
See attached Zip for log, gui log and crash dump.
[faceswap.zip](https://github.com/deepfakes/faceswap/files/6335970/faceswap.zip)

**Comment by torzdf** [comment]
Thanks. This should be fixed in latest update.
