### ISSUE TITLE
Debug landmarks feature resulting in OpenCV error

### ISSUE THREAD

**Issue by alphanoob1337** [deepfakes/faceswap#1153]
## Problem description

When running Extraction with "Debug landmarks" checked under "Output", the task fails with an OpenCV error:

```
Traceback (most recent call last):
  File "lib/cli/launcher.py", line 182, in execute_script
    process.process()
  File "scripts/extract.py", line 119, in process
    self._run_extraction()
  File "scripts/extract.py", line 219, in _run_extraction
    self._output_processing(extract_media, size)
  File "scripts/extract.py", line 258, in _output_processing
    self._post_process.do_actions(extract_media)
  File "scripts/fsmedia.py", line 443, in do_actions
    action.process(extract_media)
  File "scripts/fsmedia.py", line 506, in process
    cv2.circle(face.aligned.face, (pos_x, pos_y), 1, (0, 255, 255), -1)
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'circle'
> Overload resolution failed:
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
```

## The actual bug

`cv.circle` expects a tuple of integers as second argument but `pos_x` and `pos_y` are floats.

## Proposed fix

Changing line 506 of `scripts/fsmedia.py` from

```
cv2.circle(face.aligned.face, (pos_x, pos_y), 1, (0, 255, 255), -1)
```

to

```
cv2.circle(face.aligned.face, (int(pos_x), int(pos_y)), 1, (0, 255, 255), -1)
```

**Comment by torzdf** [comment]
Thanks for the heads up. Should be fixed in latest commit
