### ISSUE TITLE
error during installation windows 10

### ISSUE THREAD

**Issue by mikelty** [deepfakes/faceswap#1160]
using newest release on 64 bit windows 10, this error happens for both nvidia gpu (which i have, and can run tensorflow) and cpu.
message:

```
(check) MiniConda installed: conda 4.9.2
(check) CPU Supports AVX Instructions
(check) CPU Supports SSE4 Instructions
(check) Completed check for installed applications
(check) Setting up for: cpu

Miniconda3 installed.
Initializing Conda...
Collecting package metadata (current_repodata.json): ...working... failed
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\subdir_data.py", line 259, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\subdir_data.py", line 613, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\cli\main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\cli\install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\index.py", line 276, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\subdir_data.py", line 120, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "C:\Users\mik\MiniConda3\lib\concurrent\futures\_base.py", line 611, in result_iterator
        yield fs.pop().result()
      File "C:\Users\mik\MiniConda3\lib\concurrent\futures\_base.py", line 432, in result
        return self.__get_result()
      File "C:\Users\mik\MiniConda3\lib\concurrent\futures\_base.py", line 388, in __get_result
        raise self._exception
      File "C:\Users\mik\MiniConda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\subdir_data.py", line 112, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\subdir_data.py", line 125, in query
        self.load()
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\subdir_data.py", line 189, in load
        _internal_state = self._load()
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\subdir_data.py", line 277, in _load
        _internal_state = self._read_local_repdata(mod_etag_headers.get('_etag'),
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\subdir_data.py", line 326, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "C:\Users\mik\MiniConda3\lib\site-packages\conda\core\subdir_data.py", line 364, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "C:\Users\mik\MiniConda3\lib\json\__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "C:\Users\mik\MiniConda3\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\mik\MiniConda3\lib\json\decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting ',' delimiter: line 10048 column 32 (char 294738)
`$ C:\Users\mik\MiniConda3\Scripts\conda-script.py update -y -n base -c defaults conda`
  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\mik\MiniConda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\mik\MiniConda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\mik\MiniConda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\mik\MiniConda3\python.exe
               CONDA_ROOT=C:\Users\mik\MiniConda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
           CURL_CA_BUNDLE=<not set>
                   GOPATH=C:\Users\mik\go
                 HOMEPATH=\Users\mik
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\mik\MiniConda3;C:\Users\mik\MiniConda3\Library\mingw-w64\bin;
                          C:\Users\mik\MiniConda3\Library\usr\bin;C:\Users\mik\MiniConda3\Librar
                          y\bin;C:\Users\mik\MiniConda3\Scripts;C:\Users\mik\MiniConda3\bin;C:\U
                          sers\mik\MiniConda3;C:\Users\mik\MiniConda3\Library\mingw-w64\bin;C:\U
                          sers\mik\MiniConda3\Library\usr\bin;C:\Users\mik\MiniConda3\Library\bi
                          n;C:\Users\mik\MiniConda3\Scripts;C:\Users\mik\MiniConda3\bin;C:\Users
                          \mik\MiniConda3\condabin;C:\Program
                          Files\AdoptOpenJDK\jdk-8.0.282.8-hotspot\bin;C:\Program Files\Common
                          Files\Oracle\Java\javapath;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.1\libnvvp;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v11.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\C
                          UDA\v11.1\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\W
                          bem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\Ope
                          nSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program
                          Files\nodejs;D:\Program Files (x86)\chromedriver_win32;D:\Program
                          Files (x86)\hacky;D:\Program Files (x86)\platform-
                          tools;C:\Users\mik\AppData\Local\Android\Sdk\platform-
                          tools;C:\Python27;C:\Program Files\MongoDB\Server\4.4\bin;C:\Users\mik
                          \AppData\Local\Programs\Python\Python36;C:\sqlite3;C:\Users\mik\AppDat
                          a\Local\Programs\Python\Python39;C:\Users\mik\AppData\Roaming\Python\P
                          ython37\Scripts;C:\Program Files\NVIDIA Corporation\Nsight Compute
                          2019.1;C:\Program Files\NVIDIA GPU Computing Toolkit\cudnn-10.1-window
                          s10-x64-v8.0.4.30\cuda\bin;C:\Go\bin;D:\Program Files (x86);C:\Program
                          Files (x86)\swigwin-4.0.2;C:\Program Files (x86)\Vim\vim81;C:\Program 
                          Files\Git\cmd;D:\downloads\ffmpeg-4.3.2-2021-02-02-full_build\ffmpeg-4
                          .3.2-2021-02-02-full_build\bin;C:\Program Files (x86)\Microsoft VS
                          Code\bin;C:\Program Files\dotnet;C:\Users\mik\.cargo\bin;C:\Program
                          Files\MySQL\MySQL Shell 8.0\bin;C:\Users\mik\AppData\Local\Programs\Py
                          thon\Python39\Scripts;C:\Users\mik\AppData\Local\Programs\Python\Pytho
                          n39;C:\Ruby26\bin;C:\Users\mik\AppData\Local\Programs\Python\Python36\
                          Scripts;C:\Users\mik\AppData\Local\Programs\Python\Python36;C:\Users\m
                          ik\AppData\Local\Programs\Python\Python37\Scripts;C:\Users\mik\AppData
                          \Local\Programs\Python\Python37;C:\Users\mik\AppData\Local\Microsoft\W
                          indowsApps;C:\Users\mik\AppData\Roaming\npm;C:\Users\mik\go\bin;D:\dow
                          nloads\phantomjs-2.1.1-windows\phantomjs-2.1.1-windows\bin;C:\Program 
                          Files\subfinder_2.4.5_windows_amd64;C:\Users\mik\AppData\Local\Program
                          s\Microsoft VS Code\bin;C:\Program Files\JetBrains\IntelliJ IDEA
                          Community Edition 2021.1\bin;C:\Users\mik\.dotnet\tools;C:\Users\mik\A
                          ppData\Roaming\equant_pkg\Miniconda;C:\Users\mik\AppData\Roaming\equan
                          t_pkg\Miniconda\Scripts;C:\Users\mik\AppData\Roaming\equant_pkg\Minico
                          nda\Library\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                ZWCADPATH=C:\Program Files (x86)\ZWSOFT\ZWCAD 2021\ZWCAD.EXE
     active environment : base
    active env location : C:\Users\mik\MiniConda3
            shell level : 1
       user config file : C:\Users\mik\.condarc
 populated config files : C:\Users\mik\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\mik\MiniConda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/win-64
                          https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/noarch
                          https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/win-64
                          https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/win-64
                          https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/noarch
                          https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
          package cache : C:\Users\mik\MiniConda3\pkgs
                          C:\Users\mik\.conda\pkgs
                          C:\Users\mik\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\mik\MiniConda3\envs
                          C:\Users\mik\.conda\envs
                          C:\Users\mik\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : True
             netrc file : None
           offline mode : False
An unexpected error has occurred. Conda has prepared the above report.
Upload successful.
Creating Conda Virtual Environment...
Collecting package metadata (current_repodata.json): ...working... failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/noarch/current_repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/noarch'
Error Creating Conda Virtual Environment
Install Aborted

```

**Comment by torzdf** [comment]
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/noarch/current_repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```
Connection error for MiniConda3. Probably intermittent, just try again
