### ISSUE TITLE
Tkinter Exception when trying to open the graph tab after restarting an training.

### ISSUE THREAD

**Issue by AhmedAhmedEG** [deepfakes/faceswap#1164]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\PC\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\faceswap\lib\gui\display.py", line 186, in _on_tab_change
    selected_object.on_tab_select()
  File "D:\faceswap\lib\gui\display_command.py", line 254, in on_tab_select
    self._update_page()
  File "D:\faceswap\lib\gui\display_page.py", line 273, in _update_page
    self.load_display()
  File "D:\faceswap\lib\gui\display_page.py", line 285, in load_display
    self.display_item_process()
  File "D:\faceswap\lib\gui\display_command.py", line 388, in display_item_process
    for key in self.display_item.get_loss_keys(Session.session_ids[-1])
  File "D:\faceswap\lib\gui\analysis\stats.py", line 245, in get_loss_keys
    retval = loss_keys[session_id]
KeyError: 5`

This exception happens when I open the graph tab but in a specific case, when I start training, then stop it and start it again later without restarting the app, this makes it happen, I have to restart the app to get rid of this exception.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.8
 - Conda Version Latest

**Comment by NXTler** [comment]
I have the same issue on my system.
