### ISSUE TITLE
Exception when hitting the save button in manual tool while being on the "All Frames" menu

### ISSUE THREAD

**Issue by AhmedAhmedEG** [deepfakes/faceswap#1165]
`Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 1892, in __call__
return self.func(*args)
File "D:\faceswap\tools\manual\detected_faces.py", line 144, in save
self._children["io"].save()
File "D:\faceswap\tools\manual\detected_faces.py", line 284, in save
frame = self._sorted_frame_names[idx]
IndexError: list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 1892, in __call__
return self.func(*args)
File "D:\faceswap\tools\manual\detected_faces.py", line 144, in save
self._children["io"].save()
File "D:\faceswap\tools\manual\detected_faces.py", line 284, in save
frame = self._sorted_frame_names[idx]
IndexError: list index out of range`

this exception accours and the edits to the alignment file will not be saved.

**Comment by torzdf** [comment]
I cannot recreate this bug. I would need reproducible steps to be able to fix it.

I am closing this issue, but if you can add reproducible steps, I will re-open it.

**Comment by AhmedAhmedEG** [comment]
I have just seen your replay, I see the issue marked as a bug, do i still
need to add more steps or you could reproduce it?
