### ISSUE TITLE
Caught exception in thread: '_training_0'

### ISSUE THREAD

**Issue by crazyzcc619** [deepfakes/faceswap#1179]
Loading...
Setting Faceswap backend to NVIDIA
08/22/2021 20:54:07 INFO     Log level set to: INFO
08/22/2021 20:54:09 INFO     Model A Directory: 'E:\1' (1260 images)
08/22/2021 20:54:09 INFO     Model B Directory: 'E:\4' (4812 images)
08/22/2021 20:54:09 INFO     Training data directory: E:\model
08/22/2021 20:54:09 INFO     ===================================================
08/22/2021 20:54:09 INFO       Starting
08/22/2021 20:54:09 INFO       Press 'Stop' to save and quit
08/22/2021 20:54:09 INFO     ===================================================
08/22/2021 20:54:10 INFO     Loading data, this may take a while...
08/22/2021 20:54:10 INFO     Loading Model from Original plugin...
08/22/2021 20:54:10 INFO     No existing state file found. Generating.
08/22/2021 20:54:12 INFO     Loading Trainer from Original plugin...
08/22/2021 20:54:23 CRITICAL Error caught! Exiting...
08/22/2021 20:54:23 ERROR    Caught exception in thread: '_training_0'
08/22/2021 20:54:26 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "C:\faceswap\lib\cli\launcher.py", line 182, in execute_script
    process.process()
  File "C:\faceswap\scripts\train.py", line 190, in process
    self._end_thread(thread, err)
  File "C:\faceswap\scripts\train.py", line 230, in _end_thread
    thread.join()
  File "C:\faceswap\lib\multithreading.py", line 121, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "C:\faceswap\lib\multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "C:\faceswap\scripts\train.py", line 252, in _training
    raise err
  File "C:\faceswap\scripts\train.py", line 242, in _training
    self._run_training_cycle(model, trainer)
  File "C:\faceswap\scripts\train.py", line 327, in _run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "C:\faceswap\plugins\train\trainer\_base.py", line 193, in train_one_step
    loss = self._model.model.train_on_batch(model_inputs, y=model_targets)
  File "D:\Z_Q_Z_B_R_J\ANACONDA3\envs\faceswap\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1727, in train_on_batch
    logs = self.train_function(iterator)
  File "D:\Z_Q_Z_B_R_J\ANACONDA3\envs\faceswap\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "D:\Z_Q_Z_B_R_J\ANACONDA3\envs\faceswap\lib\site-packages\tensorflow\python\eager\def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "D:\Z_Q_Z_B_R_J\ANACONDA3\envs\faceswap\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "D:\Z_Q_Z_B_R_J\ANACONDA3\envs\faceswap\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "D:\Z_Q_Z_B_R_J\ANACONDA3\envs\faceswap\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "D:\Z_Q_Z_B_R_J\ANACONDA3\envs\faceswap\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found:  No algorithm worked!
	 [[node original/encoder/conv_128_0_conv2d/Conv2D (defined at C:\faceswap\plugins\train\trainer\_base.py:193) ]]
	 [[Func/cond_2/then/_20/input/_56/_68]]
  (1) Not found:  No algorithm worked!
	 [[node original/encoder/conv_128_0_conv2d/Conv2D (defined at C:\faceswap\plugins\train\trainer\_base.py:193) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_8935]

Function call stack:
train_function -> train_function

08/22/2021 20:54:26 CRITICAL An unexpected crash has occurred. Crash report written to 'C:\faceswap\crash_report.2021.08.22.205423781802.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting
Process exited.

**Comment by crazyzcc619** [comment]
Please help me

**Comment by crazyzcc619** [comment]
NVIDIA 3070 and cudn11.3 are used

**Comment by crazyzcc619** [comment]
[crash_report.2021.08.22.204852508894.log](https://github.com/deepfakes/faceswap/files/7027386/crash_report.2021.08.22.204852508894.log)

**Comment by torzdf** [comment]
This is an OOM. Try enabling "allow growth" in the training settings.
