### ISSUE TITLE
Crash on starting. Potential fix provided

### ISSUE THREAD

**Issue by theFSO** [deepfakes/faceswap#1204]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
Maybe the language setting for OS is prevent GUI from starting.

**To Reproduce**
Steps to reproduce the behaviour:
1. Simplified Chinese as OS language(windows 10)
2. run python3.8 faceswap.py gui

**Expected behaviour**
crashed

**Desktop (please complete the following information):**
 - OS: win10
 - Python Version 3.8
 - Conda Version not using conda
 
**Additional context**
Fixed by changing `stdout.decode()` to `stdout.decode("utf-8","ignore")` on line 271 of faceswap/lib/gui/menu.py

**Crash Report**

> Traceback (most recent call last):
  File "D:\deepswap\faceswap\lib\cli\launcher.py", line 181, in execute_script
    process = script(arguments)
  File "D:\deepswap\faceswap\scripts\gui.py", line 179, in __init__
    self.root = FaceswapGui(arguments.debug)
  File "D:\deepswap\faceswap\scripts\gui.py", line 34, in __init__
    self.build_gui()
  File "D:\deepswap\faceswap\scripts\gui.py", line 58, in build_gui
    self.configure(menu=MainMenuBar(self))
  File "D:\deepswap\faceswap\lib\gui\menu.py", line 47, in __init__
    self.help_menu = HelpMenu(self)
  File "D:\deepswap\faceswap\lib\gui\menu.py", line 207, in __init__
    self.build()
  File "D:\deepswap\faceswap\lib\gui\menu.py", line 220, in build
    if self._build_branches_menu():
  File "D:\deepswap\faceswap\lib\gui\menu.py", line 241, in _build_branches_menu
    stdout = self._get_branches()
  File "D:\deepswap\faceswap\lib\gui\menu.py", line 271, in _get_branches
    retcode, stdout.decode().strip().replace("\n", " - "))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte

**Comment by PAACY** [comment]
I also encountered this problem,thank you very much.

**Comment by torzdf** [comment]
This was a bug in upstream pynvml. This issue should no longer occur.
