### ISSUE TITLE
i can not run the script 

### ISSUE THREAD

**Issue by MATRIX-hc2** [deepfakes/faceswap#1209]
when i run script this error aper
(faceswap) matrix@matrix-hpelitebook8570p:~/faceswap$ python faceswap.py gui
Setting Faceswap backend to NVIDIA
There was an error reading from the Nvidia Machine Learning Library. Either you do not have an Nvidia GPU (in which case this warning can be ignored) or the most likely cause is incorrectly installed drivers. If this is the case, Please remove and reinstall your Nvidia drivers before reporting.Original Error: NVML Shared Library Not Found
No GPU detected. Switching to CPU mode
Traceback (most recent call last):
  File "faceswap.py", line 55, in <module>
    _main()
  File "faceswap.py", line 51, in _main
    arguments.func(arguments)
  File "/home/matrix/faceswap/lib/cli/launcher.py", line 174, in execute_script
    log_setup(arguments.loglevel, arguments.logfile, self._command, is_gui)
  File "/home/matrix/faceswap/lib/logger.py", line 204, in log_setup
    f_handler = _file_handler(numeric_loglevel, log_file, log_format, command)
  File "/home/matrix/faceswap/lib/logger.py", line 241, in _file_handler
    log_file = RotatingFileHandler(filename, backupCount=1, encoding="utf-8")
  File "/home/matrix/anaconda3/envs/faceswap/lib/python3.8/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/home/matrix/anaconda3/envs/faceswap/lib/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/home/matrix/anaconda3/envs/faceswap/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/matrix/anaconda3/envs/faceswap/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)

PermissionError: [Errno 13] Permission denied: '/home/matrix/faceswap/faceswap_gui.log'

**Comment by bryanlyon** [comment]
You need to either allow permissions in the folder faceswap is installed in or specify the logfile locations with ` -LF LOGFILE, --logfile LOGFILE`
