### ISSUE TITLE
click the icon on desktop and start application failed

### ISSUE THREAD

**Issue by KabourWu** [deepfakes/faceswap#1219]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
I run faceswap_setup_x64.exe and succeed, i click the icon on desktop start the application, but crashed, the logger paste in Crash Report section.
**To Reproduce**

**Expected behavior**
show GUI

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Python Version [3.8]
 - Commit ID [Faceswap2.0-release]
**Additional context**

**Crash Report**
C:\Users\wudon\faceswap>faceswap_win_launcher.bat

C:\Users\wudon\faceswap>"C:\Users\wudon\Miniconda3\scripts\activate.bat"   && conda activate "faceswap"   && python "C:\Users\wudon\faceswap/faceswap.py" gui
Setting Faceswap backend to NVIDIA
Traceback (most recent call last):
  File "C:\Users\wudon\MiniConda3\envs\faceswap\lib\site-packages\pynvml.py", line 808, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "C:\Users\wudon\MiniConda3\envs\faceswap\lib\ctypes\__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\wudon\MiniConda3\envs\faceswap\lib\ctypes\__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'nvmlInitWithFlags' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wudon\faceswap\lib\gpu_stats\nvidia.py", line 48, in _initialize
    pynvml.nvmlInit()
  File "C:\Users\wudon\MiniConda3\envs\faceswap\lib\site-packages\pynvml.py", line 1537, in nvmlInit
    nvmlInitWithFlags(0)
  File "C:\Users\wudon\MiniConda3\envs\faceswap\lib\site-packages\pynvml.py", line 1525, in nvmlInitWithFlags
    fn = _nvmlGetFunctionPointer("nvmlInitWithFlags")
  File "C:\Users\wudon\MiniConda3\envs\faceswap\lib\site-packages\pynvml.py", line 811, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.NVMLError_FunctionNotFound: Function Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wudon\faceswap/faceswap.py", line 6, in <module>
    from lib.cli import args as cli_args
  File "C:\Users\wudon\faceswap\lib\cli\args.py", line 22, in <module>
    _GPUS = GPUStats().cli_devices
  File "C:\Users\wudon\faceswap\lib\gpu_stats\_base.py", line 65, in __init__
    self._initialize()
  File "C:\Users\wudon\faceswap\lib\gpu_stats\nvidia.py", line 60, in _initialize
    raise FaceswapError(msg) from err
lib.utils.FaceswapError: An unhandled exception occured reading from the Nvidia Machine Learning Library. Original error: Function Not Found

**Comment by torzdf** [comment]
Make sure your Nvidia drivers are up to date. If needs be, use DDU to remove the current drivers and reinstall them
