### ISSUE TITLE
Training mode error with Dlight faxeswap gui ubuntu 22.04

### ISSUE THREAD

**Issue by gravitydeep** [deepfakes/faceswap#1227]
**Describe the bug**

Error when start training with  Dlight

Setting Faceswap backend to NVIDIA
05/29/2022 21:10:09 INFO     Log level set to: INFO
05/29/2022 21:10:10 INFO     Model A Directory: '/home/cedric/LAB/faceswap/workspace/faceAdst' (1305 images)
05/29/2022 21:10:10 INFO     Model B Directory: '/home/cedric/LAB/faceswap/workspace/faceBsrc' (596 images)
05/29/2022 21:10:10 INFO     Training data directory: /home/cedric/LAB/faceswap/workspace/modelAB
05/29/2022 21:10:10 INFO     ===================================================
05/29/2022 21:10:10 INFO       Starting
05/29/2022 21:10:10 INFO     ===================================================
05/29/2022 21:10:11 INFO     Loading data, this may take a while...
05/29/2022 21:10:11 INFO     Loading Model from Dlight plugin...
05/29/2022 21:10:11 INFO     No existing state file found. Generating.
05/29/2022 21:10:11 INFO     Enabling Mixed Precision Training.
05/29/2022 21:10:11 INFO     Mixed precision compatibility check (mixed_float16): OK\nYour GPU will likely run quickly with dtype policy mixed_float16 as it has compute capability of at least 7.0. Your GPU: NVIDIA GeForce RTX 3060 Laptop GPU, compute capability 8.6
05/29/2022 21:10:12 INFO     Loading Trainer from Original plugin...

05/29/2022 21:10:36 INFO     [Saved models] - Average loss since last save: face_a: 0.16586, face_b: 0.20392
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/cedric/LAB/faceswap/lib/gui/display_graph.py", line 364, in refresh
    self._calcs = self._thread.get_result()  # Terminate the LongRunningTask object
  File "/home/cedric/LAB/faceswap/lib/gui/utils.py", line 1263, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "/home/cedric/LAB/faceswap/lib/gui/utils.py", line 1234, in run
    retval = self._target(*self._args, **self._kwargs)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 565, in refresh
    self._get_raw()
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 628, in _get_raw
    loss_dict = _SESSION.get_loss(self._session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 174, in get_loss
    loss_dict = self._tb_logs.get_loss(session_id=session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 489, in get_loss
    self._check_cache(idx)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 463, in _check_cache
    self._cache_data(session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 448, in _cache_data
    iterator = self._training_iterator if live_data else tf.compat.v1.io.tf_record_iterator(
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py", line 344, in new_func
    return func(*args, **kwargs)
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/lib/io/tf_record.py", line 167, in tf_record_iterator
    return _pywrap_record_io.RecordIterator(path, compression_type)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python.lib.io._pywrap_record_io.RecordIterator(arg0: str, arg1: str)

Invoked with: None, ''
05/29/2022 21:10:57 CRITICAL Error caught! Exiting...
05/29/2022 21:10:57 ERROR    Caught exception in thread: '_training_0'
05/29/2022 21:10:57 ERROR    You do not have enough GPU memory available to train the selected model at the selected settings. You can try a number of things:
05/29/2022 21:10:57 ERROR    1) Close any other application that is using your GPU (web browsers are particularly bad for this).
05/29/2022 21:10:57 ERROR    2) Lower the batchsize (the amount of images fed into the model each iteration).
05/29/2022 21:10:57 ERROR    3) Try enabling 'Mixed Precision' training.
05/29/2022 21:10:57 ERROR    4) Use a more lightweight model, or select the model's 'LowMem' option (in config) if it has one.
Process exited.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/cedric/LAB/faceswap/lib/gui/display_graph.py", line 364, in refresh
    self._calcs = self._thread.get_result()  # Terminate the LongRunningTask object
  File "/home/cedric/LAB/faceswap/lib/gui/utils.py", line 1263, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "/home/cedric/LAB/faceswap/lib/gui/utils.py", line 1234, in run
    retval = self._target(*self._args, **self._kwargs)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 565, in refresh
    self._get_raw()
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 628, in _get_raw
    loss_dict = _SESSION.get_loss(self._session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 174, in get_loss
    loss_dict = self._tb_logs.get_loss(session_id=session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 489, in get_loss
    self._check_cache(idx)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 463, in _check_cache
    self._cache_data(session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 448, in _cache_data
    iterator = self._training_iterator if live_data else tf.compat.v1.io.tf_record_iterator(
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py", line 344, in new_func
    return func(*args, **kwargs)
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/lib/io/tf_record.py", line 167, in tf_record_iterator
    return _pywrap_record_io.RecordIterator(path, compression_type)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python.lib.io._pywrap_record_io.RecordIterator(arg0: str, arg1: str)

Invoked with: None, ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/cedric/LAB/faceswap/lib/gui/display_graph.py", line 364, in refresh
    self._calcs = self._thread.get_result()  # Terminate the LongRunningTask object
  File "/home/cedric/LAB/faceswap/lib/gui/utils.py", line 1263, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "/home/cedric/LAB/faceswap/lib/gui/utils.py", line 1234, in run
    retval = self._target(*self._args, **self._kwargs)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 565, in refresh
    self._get_raw()
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 628, in _get_raw
    loss_dict = _SESSION.get_loss(self._session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 174, in get_loss
    loss_dict = self._tb_logs.get_loss(session_id=session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 489, in get_loss
    self._check_cache(idx)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 463, in _check_cache
    self._cache_data(session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 448, in _cache_data
    iterator = self._training_iterator if live_data else tf.compat.v1.io.tf_record_iterator(
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py", line 344, in new_func
    return func(*args, **kwargs)
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/lib/io/tf_record.py", line 167, in tf_record_iterator
    return _pywrap_record_io.RecordIterator(path, compression_type)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python.lib.io._pywrap_record_io.RecordIterator(arg0: str, arg1: str)

Invoked with: None, ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/cedric/LAB/faceswap/lib/gui/display_graph.py", line 364, in refresh
    self._calcs = self._thread.get_result()  # Terminate the LongRunningTask object
  File "/home/cedric/LAB/faceswap/lib/gui/utils.py", line 1263, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "/home/cedric/LAB/faceswap/lib/gui/utils.py", line 1234, in run
    retval = self._target(*self._args, **self._kwargs)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 565, in refresh
    self._get_raw()
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 628, in _get_raw
    loss_dict = _SESSION.get_loss(self._session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/stats.py", line 174, in get_loss
    loss_dict = self._tb_logs.get_loss(session_id=session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 489, in get_loss
    self._check_cache(idx)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 463, in _check_cache
    self._cache_data(session_id)
  File "/home/cedric/LAB/faceswap/lib/gui/analysis/event_reader.py", line 448, in _cache_data
    iterator = self._training_iterator if live_data else tf.compat.v1.io.tf_record_iterator(
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py", line 344, in new_func
    return func(*args, **kwargs)
  File "/home/cedric/anaconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/lib/io/tf_record.py", line 167, in tf_record_iterator
    return _pywrap_record_io.RecordIterator(path, compression_type)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python.lib.io._pywrap_record_io.RecordIterator(arg0: str, arg1: str)

Invoked with: None, ''

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Python Version 3.9
 - Conda Version Latest
 

**Crash Report**
05/29/2022 21:10:09 MainProcess     MainThread                     logger          log_setup                      INFO     Log level set to: INFO
05/29/2022 21:10:10 MainProcess     MainThread                     train           _get_images                    INFO     Model A Directory: '/home/cedric/LAB/faceswap/workspace/faceAdst' (1305 images)
05/29/2022 21:10:10 MainProcess     MainThread                     train           _get_images                    INFO     Model B Directory: '/home/cedric/LAB/faceswap/workspace/faceBsrc' (596 images)
05/29/2022 21:10:10 MainProcess     MainThread                     train           process                        INFO     Training data directory: /home/cedric/LAB/faceswap/workspace/modelAB
05/29/2022 21:10:10 MainProcess     MainThread                     train           _monitor                       INFO     ===================================================
05/29/2022 21:10:10 MainProcess     MainThread                     train           _monitor                       INFO       Starting
05/29/2022 21:10:10 MainProcess     MainThread                     train           _monitor                       INFO     ===================================================
05/29/2022 21:10:11 MainProcess     _training_0                    train           _training                      INFO     Loading data, this may take a while...
05/29/2022 21:10:11 MainProcess     _training_0                    plugin_loader   _import                        INFO     Loading Model from Dlight plugin...
05/29/2022 21:10:11 MainProcess     _training_0                    _base           _load                          INFO     No existing state file found. Generating.
05/29/2022 21:10:11 MainProcess     _training_0                    _base           _set_keras_mixed_precision     INFO     Enabling Mixed Precision Training.
05/29/2022 21:10:11 MainProcess     _training_0                    device_compatibility_check _log_device_compatibility_check INFO     Mixed precision compatibility check (mixed_float16): OK\nYour GPU will likely run quickly with dtype policy mixed_float16 as it has compute capability of at least 7.0. Your GPU: NVIDIA GeForce RTX 3060 Laptop GPU, compute capability 8.6
05/29/2022 21:10:12 MainProcess     _training_0                    plugin_loader   _import                        INFO     Loading Trainer from Original plugin...
05/29/2022 21:10:36 MainProcess     _training_0                    _base           _save                          INFO     [Saved models] - Average loss since last save: face_a: 0.16586, face_b: 0.20392
05/29/2022 21:10:57 MainProcess     MainThread                     train           _end_thread                    CRITICAL Error caught! Exiting...
05/29/2022 21:10:57 MainProcess     MainThread                     multithreading  join                           ERROR    Caught exception in thread: '_training_0'
05/29/2022 21:10:57 MainProcess     MainThread                     launcher        execute_script                 ERROR    You do not have enough GPU memory available to train the selected model at the selected settings. You can try a number of things:
05/29/2022 21:10:57 MainProcess     MainThread                     launcher        execute_script                 ERROR    1) Close any other application that is using your GPU (web browsers are particularly bad for this).
05/29/2022 21:10:57 MainProcess     MainThread                     launcher        execute_script                 ERROR    2) Lower the batchsize (the amount of images fed into the model each iteration).
05/29/2022 21:10:57 MainProcess     MainThread                     launcher        execute_script                 ERROR    3) Try enabling 'Mixed Precision' training.
05/29/2022 21:10:57 MainProcess     MainThread                     launcher        execute_script                 ERROR    4) Use a more lightweight model, or select the model's 'LowMem' option (in config) if it has one.

**Comment by torzdf** [comment]
1) Not an error. Issue and resolution clearly stated in output
2) Github issues is not a support channel.
