### ISSUE TITLE
run‘python faceswap.py extract -i ./face-swap/src/trump -o ./face-swap/faces/trump’ with an error

### ISSUE THREAD

**Issue by chaohuichen1024** [deepfakes/faceswap#1234]
Traceback (most recent call last):
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\cli\launcher.py", line 189, in execute_script
    process.process()
  File "E:\VisualStudioIDE\AIProject\faceswap\scripts\extract.py", line 126, in process
    self._run_extraction()
  File "E:\VisualStudioIDE\AIProject\faceswap\scripts\extract.py", line 220, in _run_extraction
    desc=desc)):
  File "E:\Anaconda\envs\faceswap\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "E:\VisualStudioIDE\AIProject\faceswap\plugins\extract\pipeline.py", line 239, in detected_faces
    if self._check_and_raise_error():
  File "E:\VisualStudioIDE\AIProject\faceswap\plugins\extract\pipeline.py", line 662, in _check_and_raise_error
    if plugin.check_and_raise_error():
  File "E:\VisualStudioIDE\AIProject\faceswap\plugins\extract\_base.py", line 347, in check_and_raise_error
    err = thread.check_and_raise_error()
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\multithreading.py", line 84, in check_and_raise_error
    raise error[1].with_traceback(error[2])
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "E:\VisualStudioIDE\AIProject\faceswap\plugins\extract\_base.py", line 465, in _thread_process
    batch = function(batch)
  File "E:\VisualStudioIDE\AIProject\faceswap\plugins\extract\detect\_base.py", line 212, in _predict
    batch = self.predict(batch)
  File "E:\VisualStudioIDE\AIProject\faceswap\plugins\extract\detect\s3fd.py", line 58, in predict
    predictions = self.model.predict(batch["feed"])
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\model\session.py", line 82, in predict
    return self._model.predict(feed, batch_size=batch_size)
  File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "E:\Anaconda\envs\faceswap\lib\site-packages\tensorflow\python\eager\execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'model/conv1_1/Conv2D' defined at (most recent call last):
    File "E:\Anaconda\envs\faceswap\lib\threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "E:\Anaconda\envs\faceswap\lib\threading.py", line 926, in _bootstrap_inner
      self.run()
    File "E:\VisualStudioIDE\AIProject\faceswap\lib\multithreading.py", line 37, in run
      self._target(*self._args, **self._kwargs)
    File "E:\VisualStudioIDE\AIProject\faceswap\plugins\extract\_base.py", line 465, in _thread_process
      batch = function(batch)
    File "E:\VisualStudioIDE\AIProject\faceswap\plugins\extract\detect\_base.py", line 212, in _predict
      batch = self.predict(batch)
    File "E:\VisualStudioIDE\AIProject\faceswap\plugins\extract\detect\s3fd.py", line 58, in predict
      predictions = self.model.predict(batch["feed"])
    File "E:\VisualStudioIDE\AIProject\faceswap\lib\model\session.py", line 82, in predict
      return self._model.predict(feed, batch_size=batch_size)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1982, in predict
      tmp_batch_outputs = self.predict_function(iterator)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1801, in predict_function
      return step_function(self, iterator)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1790, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1783, in run_step
      outputs = model.predict_step(data)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1751, in predict_step
      return self(x, training=False)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\functional.py", line 452, in call
      inputs, training=training, mask=mask)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\layers\convolutional.py", line 248, in call
      outputs = self.convolution_op(inputs, self.kernel)
    File "E:\Anaconda\envs\faceswap\lib\site-packages\keras\layers\convolutional.py", line 240, in convolution_op
      name=self.__class__.__name__)
Node: 'model/conv1_1/Conv2D'
DNN library is not found.
	 [[{{node model/conv1_1/Conv2D}}]] [Op:__inference_predict_function_1372]

============ System Information ============
encoding:            cp936
git_branch:          Not Found
git_commits:         Not Found
gpu_cuda:            11.1
gpu_cudnn:           8.0.5
gpu_devices:         GPU_0: GeForce GTX 1650 Ti
gpu_devices_active:  GPU_0
gpu_driver:          457.07
gpu_vram:            GPU_0: 4096MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.19041-SP0
os_release:          10
py_command:          faceswap.py extract -i ./face-swap/src/trump -o ./face-swap/faces/trump
py_conda_version:    conda 4.13.0
py_implementation:   CPython
py_version:          3.7.13
py_virtual_env:      True
sys_cores:           8
sys_processor:       Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
sys_ram:             Total: 16251MB, Available: 6305MB, Used: 9946MB, Free: 6305MB

=============== Pip Packages ===============
absl-py==1.1.0
astunparse==1.6.3
cachetools==5.2.0
certifi==2022.5.18.1
charset-normalizer==2.0.12
colorama==0.4.4
cycler==0.11.0
fastcluster==1.2.6
ffmpy==0.2.3
flatbuffers==2.0
fonttools==4.33.3
gast==0.5.3
google-auth==2.7.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.46.3
h5py==3.7.0
idna==3.3
imageio==2.19.3
imageio-ffmpeg==0.4.7
importlib-metadata==4.11.4
joblib==1.1.0
keras==2.8.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.2
libclang==14.0.1
Markdown==3.3.7
matplotlib==3.5.2
numpy==1.21.6
nvidia-ml-py==11.510.69
oauthlib==3.2.0
opencv-python==4.6.0.66
opt-einsum==3.3.0
packaging==21.3
Pillow==9.1.1
protobuf==3.19.4
psutil==5.9.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pynvml==11.4.1
pyparsing==3.0.9
python-dateutil==2.8.2
pywin32==304
requests==2.28.0
requests-oauthlib==1.3.1
rsa==4.8
scikit-learn==1.0.2
scipy==1.7.3
six==1.16.0
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.8.0
tensorflow-gpu==2.8.2
tensorflow-io-gcs-filesystem==0.26.0
termcolor==1.1.0
threadpoolctl==3.1.0
tqdm==4.64.0
typing_extensions==4.2.0
urllib3==1.26.9
Werkzeug==2.1.2
wincertstore==0.2
wrapt==1.14.1
zipp==3.8.0

**Comment by torzdf** [comment]
I *think* this is a VRAM out of memory issue. Try either:
- Going into settings and reducing the batch size to each of the plugins to 1
- Running in "single process" model
