### ISSUE TITLE
cannot reshape array of size 23994 into shape

### ISSUE THREAD

**Issue by gravitydeep** [deepfakes/faceswap#1236]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
During the training with dlight when I switch from graph to preview I have an alert but it does not stop the training so I wanted to point it out to you maybe it is a bug?

**Warning**

xception in Tkinter callback
Traceback (most recent call last):
  File "/home/cedric/miniconda3/envs/faceswap/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/cedric/Lab/faceswap/lib/gui/display.py", line 186, in _on_tab_change
    selected_object.on_tab_select()
  File "/home/cedric/Lab/faceswap/lib/gui/display_command.py", line 248, in on_tab_select
    self._update_page()
  File "/home/cedric/Lab/faceswap/lib/gui/display_page.py", line 273, in _update_page
    self.load_display()
  File "/home/cedric/Lab/faceswap/lib/gui/display_page.py", line 285, in load_display
    self.display_item_process()
  File "/home/cedric/Lab/faceswap/lib/gui/display_command.py", line 384, in display_item_process
    loss_keys = self.display_item.get_loss_keys(Session.session_ids[-1])
  File "/home/cedric/Lab/faceswap/lib/gui/analysis/stats.py", line 254, in get_loss_keys
    in self._tb_logs.get_loss(session_id=session_id).items()}
  File "/home/cedric/Lab/faceswap/lib/gui/analysis/event_reader.py", line 490, in get_loss
    data = self._cache.get_data(idx, "loss")
  File "/home/cedric/Lab/faceswap/lib/gui/analysis/event_reader.py", line 362, in get_data
    val = {metric: np.frombuffer(zlib.decompress(data[metric]),
ValueError: cannot reshape array of size 23994 into shape (12023,2)

**Desktop (please complete the following information):**

 - ubuntu 22.04
 - Python Version 3.9
 - Conda Version 4.12

**Crash Report**
No crash report

**Comment by torzdf** [comment]
This is a bug I'm aware of. It only affects display of graph/analysis during a training session though. It doesn't break training.

**Comment by torzdf** [comment]
Closing as FS2 no longer supported
