### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by FacundoMartinezCampos** [deepfakes/faceswap#1270]
When i try to execute the training via CLI commands in a cloud server i get the following log error: 

09/12/2022 18:10:25 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/notebooks/faceswap/lib/cli/launcher.py", line 201, in execute_script
    process.process()
  File "/notebooks/faceswap/scripts/train.py", line 219, in process
    err = self._monitor(thread)
  File "/notebooks/faceswap/scripts/train.py", line 471, in _monitor
    if self._preview.should_quit:
  File "/notebooks/faceswap/scripts/train.py", line 600, in should_quit
    self._thread.check_and_raise_error()
  File "/notebooks/faceswap/lib/multithreading.py", line 90, in check_and_raise_error
    raise self.err[1].with_traceback(self.err[2])
  File "/notebooks/faceswap/lib/multithreading.py", line 96, in run
    self._target(*self._args, **self._kwargs)
  File "/notebooks/faceswap/lib/training/preview_tk.py", line 613, in __init__
    self._root = parent if parent is not None else tk.Tk()
  File "/root/anaconda3/envs/faceswap/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
09/12/2022 18:10:25 CRITICAL An unexpected crash has occurred. Crash report written to '/notebooks/faceswap/crash_report.2022.09.12.181022422680.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting

The command was: python faceswap.py train -A ./datasets/Avatar/ -B ./datasets/Real/ -m ./modelo/ -p -t dfl-h128 -bs 24 -it 100000

[crash_report.2022.09.12.175259608094.log](https://github.com/deepfakes/faceswap/files/9550770/crash_report.2022.09.12.175259608094.log)

**Comment by FacundoMartinezCampos** [comment]
My mistake, it was because using the parameter -p with the training command and not having a display. removing the -p solves the error!,
