### ISSUE TITLE
The preview window don't update

### ISSUE THREAD

**Issue by vlccdl** [deepfakes/faceswap#1277]
I have updated to the latest version.
When training starts,The preview window  no longer update after a few interval.
At this time, the following red words appear in the log window。
I didn't find any other way to resume preview updates except by restart the program。

============================================================

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jiang\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\jiang\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\jiang\faceswap\lib\gui\display_page.py", line 266, in _update_page
    self.display_item_set()
  File "C:\Users\jiang\faceswap\lib\gui\display_command.py", line 146, in display_item_set
    if not self._preview.load():
  File "C:\Users\jiang\faceswap\lib\gui\utils\image.py", line 119, in load
    self._buffer.add_image(os.path.basename(filename), img)
  File "C:\Users\jiang\faceswap\lib\training\preview_cv.py", line 48, in add_image
    logger.debug("Adding image: (name: '%s', shape: %s)", name, image.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jiang\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\jiang\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\jiang\faceswap\lib\gui\display_page.py", line 266, in _update_page
    self.display_item_set()
  File "C:\Users\jiang\faceswap\lib\gui\display_command.py", line 146, in display_item_set
    if not self._preview.load():
  File "C:\Users\jiang\faceswap\lib\gui\utils\image.py", line 119, in load
    self._buffer.add_image(os.path.basename(filename), img)
  File "C:\Users\jiang\faceswap\lib\training\preview_cv.py", line 48, in add_image
    logger.debug("Adding image: (name: '%s', shape: %s)", name, image.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jiang\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\jiang\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\jiang\faceswap\lib\gui\display_page.py", line 266, in _update_page
    self.display_item_set()
  File "C:\Users\jiang\faceswap\lib\gui\display_command.py", line 146, in display_item_set
    if not self._preview.load():
  File "C:\Users\jiang\faceswap\lib\gui\utils\image.py", line 119, in load
    self._buffer.add_image(os.path.basename(filename), img)
  File "C:\Users\jiang\faceswap\lib\training\preview_cv.py", line 48, in add_image
    logger.debug("Adding image: (name: '%s', shape: %s)", name, image.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
```

==================================================================

**Comment by torzdf** [comment]
This looks like a temporary error reading the preview image from disk. I have pushed an update to hopefully fix this. Please update.
