### ISSUE TITLE
Error during Installation at windows by building project for dev

### ISSUE THREAD

**Issue by DonOhhhh** [deepfakes/faceswap#1279]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
Hi, I want to contribute to this repo as an assignment of my college class.
So I folked this repo and clone it on my local and i ran setup.py with python 3.9 interpreter installed at anaconda env folder.
and this error is occured...
```bash
INFO     Running without root/admin privileges
INFO     The tool provides tips for installation and installs required python packages
INFO     Setup in Windows 10
INFO     Installed Python: 3.9.0 64bit
INFO     Running in Conda
INFO     Running in a Virtual Environment
INFO     Encoding: cp949
INFO     Installed pip: 22.2.2
Traceback (most recent call last):
  File "D:\faceswap\setup.py", line 1400, in <module>
    ENV = Environment()
  File "D:\faceswap\setup.py", line 76, in __init__
    self.installed_packages.update(self.get_installed_conda_packages())
  File "D:\faceswap\setup.py", line 277, in get_installed_conda_packages
    retval[item[0]] = item[1]
IndexError: list index out of range

Process finished with exit code 1
```
So I go down to the error occuring code and see what's the problem by debugging. And I found that
![debug](https://user-images.githubusercontent.com/96936113/200165222-576725fe-24c0-4559-83fe-a46c62bf516e.png)
the pkg variable should have package name and version but some crazy key(\x1b[0m) was input without any value. That's why the IndexError was occured so I covered that code with try-except that do nothing when except occured. Then, It' works perfectly without any error. So the question I want you to ask is "Is is okay to make an pr about the issues similar to this one(related to setup)? and will you merge it?"

**To Reproduce**
1. Go to root of your Faceswap folder
2. Click on setup.py and run it

**Expected behavior**
Merge the pr

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H2
 - Python Version: 3.9
 - Conda Version: 22.9.0
 - Commit ID: X

**Additional context**

**Crash Report**
There is no crash report about this issue

**Comment by acdop100** [comment]
If it helps, you can just run the installer exe and then navigate to /Users/<your user>/faceswap and the code is all there after install.

**Comment by torzdf** [comment]
Short answer to your question is. no, I wouldn't except this as a PR I'm afraid. The reason being that a try/except just ignores the error, it does not fix the underlying issue.

Which leads me on to, what is the underlying issue? I have never seen this before, so worry that it is an edge case local to your machine. The first thing I would be looking at is where does `\x1b[0m` come from and why is it being inserted into the list, then work back from there.

**Comment by DonOhhhh** [comment]
@torzdf I found that `\x1b[0m` is actually meant for `ESC[0m` explain in [here](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#colors--graphics-mode). Basically it's the escape sequence to show that the graphical settings have been reset to parse the text only. So, it's has no relation to setting up the project. That means it doesn't matter to delele that text from the installed list or just ignore it. How do you think?

**Comment by torzdf** [comment]
Closing as FS2 no longer supported
