### ISSUE TITLE
Error occured during extraction

### ISSUE THREAD

**Issue by DonOhhhh** [deepfakes/faceswap#1281]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
I placed Trump.mp4 in faceswap/src and set output dir to faceswap/faces. And I pressed extract button and this error is occured
```bash
Loading...
Setting Faceswap backend to NVIDIA
11/07/2022 09:03:33 INFO     Log level set to: INFO
11/07/2022 09:03:35 INFO     Loading Detect from S3Fd plugin...
11/07/2022 09:03:35 INFO     Loading Align from Fan plugin...
11/07/2022 09:03:35 INFO     Downloading model: 'face-alignment-network_2d4_keras' from: https://github.com/deepfakes-models/faceswap-models/releases/download/v13.2/face-alignment-network_2d4_keras_v2.zip

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\Don Oh\anaconda3\envs\faceswap\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Don Oh\anaconda3\envs\faceswap\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "D:\faceswap\lib\gui\wrapper.py", line 269, in read_stderr
    output = self.process.stderr.readline()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 19: illegal multibyte sequence
11/07/2022 09:03:46 INFO     Extracting: 'face-alignment-network_2d4_keras'
```
This shows me that error occured in faceswap\lib\gui\wrapper.py, line 269 that has a problem with encoding. And I can't find the line to set the encoding. If I can find it, then I can replace to utf-8 or something that doesn't occur the error. Can you let me know where the encoding setting is placed in? It's good to know as specific as.

**To Reproduce**
2. Click on extract

**Expected behavior**
Let me know where I can find encoding setting in the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/96936113/200203599-ae531d9e-06a1-4070-b1c8-80ddd11c3175.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Home 21H2
- Python Version: 3.9
- Conda Version: 22.9.0
- Commit ID: X

**Additional context**

**Crash Report**
And there is an error log in the root of faceswap folder. I'm not sure it's crash report, cause there's no file named as "crash report".
```bash
11/06/2022 21:04:37 MainProcess     MainThread                     logger          log_setup                      INFO     Log level set to: INFO
11/06/2022 21:04:40 MainProcess     MainThread                     plugin_loader   _import                        INFO     Loading Detect from S3Fd plugin...
11/06/2022 21:04:40 MainProcess     MainThread                     utils           _download_model                INFO     Downloading model: 's3fd_keras' from: https://github.com/deepfakes-models/faceswap-models/releases/download/v11.2/s3fd_keras_v2.zip
11/06/2022 21:04:43 MainProcess     MainThread                     utils           _unzip_model                   INFO     Extracting: 's3fd_keras'
11/06/2022 21:04:43 MainProcess     MainThread                     plugin_loader   _import                        INFO     Loading Align from Fan plugin...
11/06/2022 21:04:43 MainProcess     MainThread                     utils           _download_model                INFO     Downloading model: 'face-alignment-network_2d4_keras' from: https://github.com/deepfakes-models/faceswap-models/releases/download/v13.2/face-alignment-network_2d4_keras_v2.zip
11/06/2022 21:05:17 MainProcess     MainThread                     utils           _download_model                WARNING  Error downloading model ([Errno 22] Invalid argument). Retrying 2 of 6...
11/06/2022 21:05:17 MainProcess     MainThread                     utils           _download_model                WARNING  Error downloading model ([Errno 22] Invalid argument). Retrying 3 of 6...
11/06/2022 21:05:17 MainProcess     MainThread                     utils           _download_model                WARNING  Error downloading model ([Errno 22] Invalid argument). Retrying 4 of 6...
11/06/2022 21:05:18 MainProcess     MainThread                     utils           _download_model                WARNING  Error downloading model ([Errno 22] Invalid argument). Retrying 5 of 6...
11/06/2022 21:05:18 MainProcess     MainThread                     utils           _download_model                WARNING  Error downloading model ([Errno 22] Invalid argument). Retrying 6 of 6...
11/06/2022 21:05:18 MainProcess     MainThread                     utils           _download_model                ERROR    Failed to download model. Exiting. (Error: '[Errno 22] Invalid argument', URL: 'https://github.com/deepfakes-models/faceswap-models/releases/download/v13.2/face-alignment-network_2d4_keras_v2.zip')
11/06/2022 21:05:18 MainProcess     MainThread                     utils           _download_model                INFO     You can try running again to resume the download.
11/06/2022 21:05:18 MainProcess     MainThread                     utils           _download_model                INFO     Alternatively, you can manually download the model from: https://github.com/deepfakes-models/faceswap-models/releases/download/v13.2/face-alignment-network_2d4_keras_v2.zip and unzip the contents to: D:\faceswap\.fs_cache
```

**Comment by DonOhhhh** [comment]
Thanks to @torzdf 
```bash
conda activate faceswap
cd faceswap
chcp 65001
python faceswap.py gui
```
These commands solved the problem
