### ISSUE TITLE
TypeError: Unable to convert function return value to a Python type! The signature was () -> handle

### ISSUE THREAD

**Issue by tikitong** [deepfakes/faceswap#1292]
**Describe the bug**
Hello, after following exactly the steps in the INSTALL file: https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#macos-apple-silicon-install-guide, this error raised when I try to run the project. Has this ever happened to anyone? Thanks a lot. 

```
(faceswap) user@MacBook-Pro-de-user faceswap % python setup.py 
INFO     Running without root/admin privileges
INFO     The tool provides tips for installation and installs required python packages
INFO     Setup in Darwin 21.6.0
INFO     Installed Python: 3.9.15 64bit
INFO     Running in Conda
INFO     Running in a Virtual Environment
INFO     Encoding: UTF-8
INFO     Installed pip: 22.3.1
INFO     Faceswap config written to: /Users/user/Desktop/faceswap/config/.faceswap
Please ensure your System Dependencies are met. Continue? [y/N] y
INFO     Installing Required Python Packages. This may take some time...
INFO     All python3 dependencies are met.
         You are good to go.
         
         Enter:  'python faceswap.py -h' to see the options
                 'python faceswap.py gui' to launch the GUI
(faceswap) user@MacBook-Pro-de-user faceswap % 
```

```
(faceswap) user@MacBook-Pro-de-user faceswap % python faceswap.py gui
Setting Faceswap backend to APPLE_SILICON
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/Users/user/Desktop/faceswap/faceswap.py", line 6, in <module>
    from lib.cli import args as cli_args
  File "/Users/user/Desktop/faceswap/lib/cli/args.py", line 15, in <module>
    from lib.gpu_stats import GPUStats
  File "/Users/user/Desktop/faceswap/lib/gpu_stats/__init__.py", line 20, in <module>
    from .apple_silicon import AppleSiliconStats as GPUStats  # type:ignore
  File "/Users/user/Desktop/faceswap/lib/gpu_stats/apple_silicon.py", line 7, in <module>
    import tensorflow as tf
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/data/experimental/__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 24, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 23, in <module>
    from tensorflow.python.data.util import nest
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/data/util/nest.py", line 36, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/framework/sparse_tensor.py", line 24, in <module>
    from tensorflow.python.framework import constant_op
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 23, in <module>
    from tensorflow.python.framework import dtypes
  File "/Users/user/miniconda3/envs/faceswap/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py", line 34, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle
(faceswap) user@MacBook-Pro-de-user faceswap % 
```

**Desktop (please complete the following information):**
 - OS: `macOS arm64` 12.5 Monterey M2
 - Python Version: Python 3.9.15
 - Conda Version: conda 22.11.1
 
**Additional context**
```
(faceswap) user@MacBook-Pro-de-user faceswap % conda list
# packages in environment at /Users/user/miniconda3/envs/faceswap:
#
# Name                    Version                   Build  Channel
absl-py                   1.3.0            py39hca03da5_0  
astunparse                1.6.3                    pypi_0    pypi
blas                      1.0                    openblas  
brotli                    1.0.9                h1a28f6b_7  
brotli-bin                1.0.9                h1a28f6b_7  
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h1a28f6b_0  
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
cachetools                5.2.1                    pypi_0    pypi
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
charset-normalizer        2.1.1                    pypi_0    pypi
cloudpickle               2.0.0              pyhd3eb1b0_0  
cycler                    0.11.0             pyhd3eb1b0_0  
decorator                 5.1.1              pyhd3eb1b0_0  
dm-tree                   0.1.7            py39h313beb8_1  
fastcluster               1.2.6                    pypi_0    pypi
ffmpeg                    4.2.2                h04105a8_0  
ffmpy                     0.3.0                    pypi_0    pypi
fftw                      3.3.10          nompi_h3046061_106    conda-forge
flatbuffers               23.1.4                   pypi_0    pypi
flit-core                 3.6.0              pyhd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h1192e45_0  
gast                      0.4.0                    pypi_0    pypi
gettext                   0.21.1               h0186832_0    conda-forge
giflib                    5.2.1                h1a28f6b_0  
gmp                       6.2.1                h9f76cd9_0    conda-forge
gnutls                    3.6.15               h887c41c_0  
google-auth               2.15.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.51.1                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
hdf5                      1.12.1               h160e8cb_2  
idna                      3.4                      pypi_0    pypi
imageio                   2.19.3           py39hca03da5_0  
imageio-ffmpeg            0.4.7              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0                    pypi_0    pypi
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h1a28f6b_0  
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4            py39h313beb8_0  
krb5                      1.19.2               h3b8d789_0  
lame                      3.100             h1a8c8d9_1003    conda-forge
lcms2                     2.12                 hba8e193_0  
lerc                      3.0                  hc377ac9_0  
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a28f6b_7  
libbrotlidec              1.0.9                h1a28f6b_7  
libbrotlienc              1.0.9                h1a28f6b_7  
libclang                  15.0.6.1                 pypi_0    pypi
libcurl                   7.86.0               h0f1d93c_0  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.8                  h1a28f6b_5  
libedit                   3.1.20221030         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libffi                    3.4.2                hca03da5_6  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libiconv                  1.17                 he4db4b2_0    conda-forge
libidn2                   2.3.4                h1a8c8d9_0    conda-forge
libnghttp2                1.46.0               h95c9599_0  
libopenblas               0.3.21               h269037a_0  
libopus                   1.3.1                h27ca646_1    conda-forge
libpng                    1.6.37               hb8d0fd4_0  
libprotobuf               3.19.1               h98b2900_0  
libssh2                   1.10.0               hf27765b_0  
libtasn1                  4.19.0               h1a8c8d9_0    conda-forge
libtiff                   4.4.0                h2fd578a_2  
libunistring              0.9.10               h3422bc3_0    conda-forge
libvpx                    1.10.0               hc377ac9_0  
libwebp                   1.2.4                h68602c7_0  
libwebp-base              1.2.4                h1a28f6b_0  
llvm-openmp               14.0.6               hc6e5704_0  
lz4-c                     1.9.4                h313beb8_0  
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.2            py39hca03da5_0  
matplotlib-base           3.5.2            py39hc377ac9_0  
munkres                   1.1.4                      py_0  
ncurses                   6.3                  h1a28f6b_3  
nettle                    3.7.3                h84b5d62_1  
numexpr                   2.8.4            py39h79ee842_0  
numpy                     1.22.3           py39h25ab29e_0  
numpy-base                1.22.3           py39h974a1f5_0  
nvidia-ml-py              11.515.75                pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.7.0.68                 pypi_0    pypi
openh264                  1.8.0                h98b2900_0  
openssl                   1.1.1s               h03a7124_1    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 22.0             py39hca03da5_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pillow                    9.3.0            py39hf4a492f_1  
pip                       22.3.1           py39hca03da5_0  
protobuf                  3.19.1           py39hc377ac9_0  
psutil                    5.9.0            py39h1a28f6b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyparsing                 3.0.9            py39hca03da5_0  
python                    3.9.15               hc0d8a6c_2  
python-dateutil           2.8.2              pyhd3eb1b0_0  
readline                  8.2                  h1a28f6b_0  
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.1.3            py39hc377ac9_0  
scipy                     1.9.3            py39h9d039d2_0  
setuptools                65.5.0           py39hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.40.0               h7a7dc30_0  
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow-deps           2.9.0                         0    apple
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-macos          2.10.0                   pypi_0    pypi
tensorflow-metal          0.5.1                    pypi_0    pypi
tensorflow-probability    0.14.0             pyhd3eb1b0_0  
termcolor                 2.2.0                    pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               hb8d0fd4_0  
tornado                   6.2              py39h1a28f6b_0  
tqdm                      4.64.1           py39hca03da5_0  
typing-extensions         4.4.0            py39hca03da5_0  
typing_extensions         4.4.0            py39hca03da5_0  
tzdata                    2022g                h04d1e81_0  
urllib3                   1.26.13                  pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.14.1                   pypi_0    pypi
x264                      1!152.20180806       h1a28f6b_0  
xz                        5.2.8                h80987f9_0  
zipp                      3.11.0                   pypi_0    pypi
zlib                      1.2.13               h5a0b063_0  
zstd                      1.5.2                h8574219_0  
(faceswap) user@MacBook-Pro-de-user faceswap % 
```

**Comment by torzdf** [comment]
This is an installed numpy version issue.

Try opening a terminal and entering
```
conda activate faceswap
conda install "numpy>=1.23.0,<1.24.0"
```
