### ISSUE TITLE
Faceswap Gui Crashes On Launch

### ISSUE THREAD

**Issue by DrDreGFunk** [deepfakes/faceswap#1296]
Hello, I've been following the faceswap install guide as I had to start a new virtual environment again, but every-time I load up the gui it crashes. I've also tried to update everything, but nothing seems to be working and it takes me around in loops. I'm using a Mac on CPU, so it's probably a dinosaur here, but I'm hoping it can still be resolved. Here's my crash report:

```
01/17/2023 11:39:46 MainProcess     MainThread                     logger          log_setup                      INFO     Log level set to: INFO
01/17/2023 11:39:50 MainProcess     MainThread                     __init__        <module>                       DEBUG    Creating converter from 7 to 5
01/17/2023 11:39:50 MainProcess     MainThread                     __init__        <module>                       DEBUG    Creating converter from 5 to 7
01/17/2023 11:39:50 MainProcess     MainThread                     __init__        <module>                       DEBUG    Creating converter from 7 to 5
01/17/2023 11:39:50 MainProcess     MainThread                     __init__        <module>                       DEBUG    Creating converter from 5 to 7
Traceback (most recent call last):
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USERS/faceswap/lib/cli/launcher.py", line 224, in execute_script
    script = self._import_script()
  File "/Users/USERS/faceswap/lib/cli/launcher.py", line 46, in _import_script
    self._test_for_tf_version()
  File "/Users/USERS/faceswap/lib/cli/launcher.py", line 95, in _test_for_tf_version
    import tensorflow as tf  # noqa pylint:disable=import-outside-toplevel,unused-import
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 37, in <module>
    from tensorflow._api.v2.compat.v2 import distribute
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/distribute/__init__.py", line 182, in <module>
    from . import experimental
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/__init__.py", line 10, in <module>
    from . import rpc
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/rpc/__init__.py", line 8, in <module>
    from tensorflow.python.distribute.experimental.rpc.rpc_ops import Client
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/python/distribute/experimental/__init__.py", line 22, in <module>
    from tensorflow.python.distribute.failure_handling import failure_handling
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/python/distribute/failure_handling/failure_handling.py", line 33, in <module>
    from tensorflow.python.distribute.failure_handling import gce_util
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/python/distribute/failure_handling/gce_util.py", line 20, in <module>
    import requests
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/Users/USERS/opt/anaconda3/envs/faceswap/lib/python3.8/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

============ System Information ============
backend:             amd
encoding:            UTF-8
git_branch:          master
git_commits:         80f6328 Bugfixes   - plugin.train.unbalanced - decoder b   - gui.stats - crash when log folder deleted   - setup.py - install gcc=12.1.0 on linux (scipy dep)   - setup.py - don't test ROCm unless valid   - typofix - cli_args extract singleprocess help typing   - lib.gui.analysis.event_reader   - lib.gpu_stats.directml - make platform specific unit tests   - lib.gui.analysis.event_reader. 28cb2fc Unhide options for ROCm. c455601 Linux - ROCm (AMD) support. edd7e52 docs: typofix. 0dbeafb bugfix: sysinfo   - Fix getting free Vram on Nvidia   - Don't halt sysinfo on GPU stats error   - lib.sysinfo unit test
gpu_cuda:            No global version found. Check Conda packages for Conda Cuda
gpu_cudnn:           No global version found. Check Conda packages for Conda cuDNN
gpu_devices:         GPU_0: llvm_cpu.0 - CPU (via LLVM) (experimental)
gpu_devices_active:  GPU_0
gpu_driver:          No Driver Found
gpu_vram:            GPU_0: 4096MB (4096MB free)
os_machine:          x86_64
os_platform:         macOS-10.15.6-x86_64-i386-64bit
os_release:          19.6.0
py_command:          faceswap.py gui
py_conda_version:    conda 22.11.1
py_implementation:   CPython
py_version:          3.8.15
py_virtual_env:      True
sys_cores:           8
sys_processor:       i386
sys_ram:             Total: 16384MB, Available: 8017MB, Used: 8203MB, Free: 60MB

=============== Pip Packages ===============
absl-py @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_09tbpzfe9v/croot/absl-py_1666362946999/work
aiohttp @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_690hlorvpy/croot/aiohttp_1670009554132/work
aiosignal @ file:///tmp/build/80754af9/aiosignal_1637843061372/work
astunparse==1.6.3
async-timeout @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_732x52axrd/croots/recipe/async-timeout_1664876366763/work
attrs @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_33k1uces4n/croot/attrs_1668696162258/work
blinker==1.4
brotlipy==0.7.0
cachetools==4.2.4
certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_477u68wvzm/croot/certifi_1671487773341/work/certifi
cffi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_1b0qzba5nr/croot/cffi_1670423213150/work
charset-normalizer==3.0.1
click @ file:///opt/concourse/worker/volumes/live/709f530a-8ffd-4e02-4f5f-9b3cfddd0e0b/volume/click_1646056616410/work
cloud-tpu-client==0.10
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1632508026186/work
cryptography @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_0ayq9hu973/croot/cryptography_1673298756837/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
dm-tree @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_1fp7e2h87y/croot/dm-tree_1671027438289/work
enum34==1.1.10
fastcluster @ file:///Users/runner/miniforge3/conda-bld/fastcluster_1646148981469/work
ffmpy==0.3.0
flatbuffers==23.1.4
flit_core @ file:///opt/conda/conda-bld/flit-core_1644941570762/work/source/flit_core
fonttools==4.25.0
frozenlist @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_5eiq5594pj/croot/frozenlist_1670004516635/work
gast @ file:///Users/ktietz/demo/mc3/conda-bld/gast_1628588903283/work
google-api-core==1.34.0
google-api-python-client==1.8.0
google-auth @ file:///opt/conda/conda-bld/google-auth_1646735974934/work
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.6
google-pasta @ file:///Users/ktietz/demo/mc3/conda-bld/google-pasta_1630577991354/work
googleapis-common-protos==1.58.0
grpcio==1.51.1
h5py @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_7fnj4n39p5/croots/recipe/h5py_1659091379933/work
httplib2==0.21.0
idna @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_00jf0h4zbt/croot/idna_1666125573348/work
imageio @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_5460df32-49d6-4565-9afb-ddc7de276101dvh8sph9/croots/recipe/imageio_1658785049436/work
imageio-ffmpeg @ file:///home/conda/feedstock_root/build_artifacts/imageio-ffmpeg_1673483481485/work
importlib-metadata==6.0.0
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1663332044897/work
keras @ file:///Users/ec2-user/miniconda3/conda-bld/keras_1669750590284/work/keras-2.10.0-py2.py3-none-any.whl
Keras-Applications==1.0.8
Keras-Preprocessing @ file:///tmp/build/80754af9/keras-preprocessing_1612283640596/work
kiwisolver @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_e26jwrjf6j/croot/kiwisolver_1672387151391/work
libclang==15.0.6.1
Markdown @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_90m_zl2p10/croot/markdown_1671541913695/work
MarkupSafe @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d4a9444f-bd4c-4043-b47d-cede33979b0fve7bm42r/croots/recipe/markupsafe_1654597878200/work
matplotlib @ file:///opt/concourse/worker/volumes/live/f670ab63-e220-495e-450b-14c9591f195b/volume/matplotlib-suite_1634667037960/work
mkl-fft==1.3.1
mkl-random @ file:///opt/concourse/worker/volumes/live/f196a661-8e33-4aac-63bc-efb2ff50e035/volume/mkl_random_1626186080069/work
mkl-service==2.4.0
multidict @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_81upqwhecp/croot/multidict_1665674236996/work
munkres==1.1.4
numexpr @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cef3ah6r8w/croot/numexpr_1668713880672/work
numpy @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_e3f85f54-0572-4c0e-b190-4bc4766fc3fenewxarhq/croots/recipe/numpy_and_numpy_base_1652801682879/work
nvidia-ml-py==11.525.84
oauth2client==4.1.3
oauthlib==3.2.2
opencv-python==4.7.0.68
opt-einsum @ file:///tmp/build/80754af9/opt_einsum_1621500238896/work
packaging==23.0
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
Pillow==9.3.0
plaidml==0.7.0
plaidml-keras==0.7.0
protobuf==3.20.1
psutil @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_c9b604bf-685f-47f6-8304-238e4e70557e1o7mmsot/croots/recipe/psutil_1656431274701/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pyasn1 @ file:///Users/ktietz/demo/mc3/conda-bld/pyasn1_1629708007385/work
pyasn1-modules==0.2.8
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
PyJWT @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_eec47dd9-fcc8-4e06-bbca-6138d11dbbcch6zasfc4/croots/recipe/pyjwt_1657544589510/work
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_3a17y2delq/croots/recipe/pyparsing_1661452538853/work
PySocks @ file:///opt/concourse/worker/volumes/live/85a5b906-0e08-41d9-6f59-084cee4e9492/volume/pysocks_1594394636991/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
PyYAML==6.0
requests==2.28.2
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn @ file:///opt/concourse/worker/volumes/live/09b793c0-41c8-469b-7e31-b4a39bc68d95/volume/scikit-learn_1642617120730/work
scipy @ file:///opt/concourse/worker/volumes/live/7554f9b4-1616-4d3d-50f8-914545975614/volume/scipy_1641555024289/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
tensorboard==2.10.1
tensorboard-data-server @ file:///var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b8sq3zgkhr/croot/tensorboard-data-server_1670853593214/work/tensorboard_data_server-0.6.1-py3-none-macosx_10_9_x86_64.whl
tensorboard-plugin-wit==1.8.1
tensorflow @ file:///Users/ec2-user/miniconda3/conda-bld/tensorflow-base_1669830675347/work/tensorflow_pkg/tensorflow-2.10.0-cp38-cp38-macosx_10_14_x86_64.whl
tensorflow-cpu==2.10.1
tensorflow-estimator @ file:///Users/ec2-user/miniconda3/conda-bld/tensorflow-estimator_1669751680663/work/tensorflow_estimator-2.10.0-py2.py3-none-any.whl
tensorflow-io-gcs-filesystem==0.29.0
tensorflow-probability @ file:///tmp/build/80754af9/tensorflow-probability_1633017132682/work
termcolor==2.2.0
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
tornado @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_1fimz6o0gc/croots/recipe/tornado_1662061695695/work
tqdm @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_2adqcbsqqd/croots/recipe/tqdm_1664392689227/work
typing_extensions @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_4b7xacf029/croot/typing_extensions_1669923792404/work
uritemplate==3.0.1
urllib3==1.26.14
Werkzeug @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_322nlonnpf/croot/werkzeug_1671215993374/work
wrapt @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_1ade1f68-8354-4db8-830b-ff3072015779vd_2hm7k/croots/recipe/wrapt_1657814407132/work
yarl @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d8a27nidjc/croots/recipe/yarl_1661437080982/work
zipp @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b71z79bye2/croot/zipp_1672387125902/work

============== Conda Packages ==============
# packages in environment at /Users/USERS/opt/anaconda3/envs/faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.2.0                     eigen  
abseil-cpp                20211102.0           he9d5cce_0  
absl-py                   1.3.0            py38hecd8cb5_0  
aiohttp                   3.8.3            py38h6c40b1e_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
astunparse                1.6.3                      py_0  
async-timeout             4.0.2            py38hecd8cb5_0  
attrs                     22.1.0           py38hecd8cb5_0  
blas                      1.0                         mkl  
blinker                   1.4              py38hecd8cb5_0  
brotli                    1.0.9                hca72f7f_7  
brotli-bin                1.0.9                hca72f7f_7  
brotlipy                  0.7.0           py38h9ed2024_1003  
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               hca72f7f_0  
ca-certificates           2022.10.11           hecd8cb5_0  
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.12.7        py38hecd8cb5_0  
cffi                      1.15.1           py38h6c40b1e_3  
charset-normalizer        3.0.1                    pypi_0    pypi
click                     8.0.4            py38hecd8cb5_0  
cloud-tpu-client          0.10                     pypi_0    pypi
cloudpickle               2.0.0              pyhd3eb1b0_0  
cryptography              38.0.4           py38hf6deb26_0  
cycler                    0.11.0             pyhd3eb1b0_0  
decorator                 5.1.1              pyhd3eb1b0_0  
dm-tree                   0.1.7            py38hcec6c5f_1  
enum34                    1.1.10                   pypi_0    pypi
fastcluster               1.2.6            py38h52e9a12_0    conda-forge
ffmpeg                    4.2.2                h97e5cf8_0  
flatbuffers               23.1.4                   pypi_0    pypi
flit-core                 3.6.0              pyhd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               hd8bbffd_0  
frozenlist                1.3.3            py38h6c40b1e_0  
gast                      0.3.3                    pypi_0    pypi
gettext                   0.21.1               h8a4c099_0    conda-forge
giflib                    5.2.1                haf1e3a3_0  
gmp                       6.2.1                h2e338ed_0    conda-forge
gnutls                    3.6.13               h756fd2b_1    conda-forge
google-api-core           1.34.0                   pypi_0    pypi
google-api-python-client  1.8.0                    pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0              pyhd3eb1b0_0  
googleapis-common-protos  1.58.0                   pypi_0    pypi
grpc-cpp                  1.46.1               h067a048_0  
grpcio                    1.51.1                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf5                      1.10.6               hdbbcd12_0  
httplib2                  0.21.0                   pypi_0    pypi
icu                       58.2                 h0a44026_3  
idna                      3.4              py38hecd8cb5_0  
imageio                   2.19.3           py38hecd8cb5_0  
imageio-ffmpeg            0.4.8              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          hecd8cb5_3538  
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hca72f7f_0  
keras                     2.10.0           py38hecd8cb5_0  
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
kiwisolver                1.4.4            py38hcec6c5f_0  
krb5                      1.19.2               hcd88c3b_0  
lame                      3.100             hb7f2c08_1003    conda-forge
lcms2                     2.12                 hf1fd2bf_0  
lerc                      3.0                  he9d5cce_0  
libbrotlicommon           1.0.9                hca72f7f_7  
libbrotlidec              1.0.9                hca72f7f_7  
libbrotlienc              1.0.9                hca72f7f_7  
libclang                  15.0.6.1                 pypi_0    pypi
libcurl                   7.86.0               ha585b31_0  
libcxx                    14.0.6               h9765a3e_0  
libdeflate                1.8                  h9ed2024_5  
libedit                   3.1.20221030         h6c40b1e_0  
libev                     4.33                 h9ed2024_1  
libffi                    3.4.2                hecd8cb5_6  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.17                 hac89ed1_0    conda-forge
libnghttp2                1.46.0               ha29bfda_0  
libopus                   1.3.1                hc929b4f_1    conda-forge
libpng                    1.6.37               ha441bb4_0  
libprotobuf               3.20.1               h8346a28_0  
libssh2                   1.10.0               h0a4fc7d_0  
libtiff                   4.5.0                h2cd0358_0  
libvpx                    1.7.0                h378b8a2_0  
libwebp                   1.2.4                h56c3ce4_0  
libwebp-base              1.2.4                hca72f7f_0  
llvm-openmp               15.0.7               h61d9ccf_0    conda-forge
lz4-c                     1.9.4                hcec6c5f_0  
markdown                  3.4.1            py38hecd8cb5_0  
markupsafe                2.1.1            py38hca72f7f_0  
matplotlib                3.4.3            py38hecd8cb5_0  
matplotlib-base           3.4.3            py38h0a11d32_0  
mkl                       2021.4.0           hecd8cb5_637  
mkl-service               2.4.0            py38h9ed2024_0  
mkl_fft                   1.3.1            py38h4ab4a9b_0  
mkl_random                1.2.2            py38hb2f4e1b_0  
multidict                 6.0.2            py38hca72f7f_0  
munkres                   1.1.4                      py_0  
ncurses                   6.3                  hca72f7f_3  
nettle                    3.6                  hedd7734_0    conda-forge
numexpr                   2.8.4            py38he696674_0  
numpy                     1.16.0                   pypi_0    pypi
numpy-base                1.22.3           py38h3b1a694_0  
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openh264                  2.1.1                h8346a28_0  
openssl                   1.1.1s               hca72f7f_0  
opt_einsum                3.3.0              pyhd3eb1b0_1  
packaging                 23.0                     pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pillow                    9.3.0            py38h81888ad_1  
pip                       22.3.1           py38hecd8cb5_0  
plaidml                   0.7.0                    pypi_0    pypi
plaidml-keras             0.7.0                    pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.0            py38hca72f7f_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyjwt                     2.4.0            py38hecd8cb5_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9            py38hecd8cb5_0  
pysocks                   1.7.1                    py38_1  
python                    3.8.15               h218abb5_2  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-flatbuffers        2.0                pyhd3eb1b0_0  
python_abi                3.8                      2_cp38    conda-forge
pyyaml                    6.0                      pypi_0    pypi
re2                       2022.04.01           he9d5cce_0  
readline                  8.2                  hca72f7f_0  
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.0.2            py38hae1ba45_1  
scipy                     1.7.3            py38h8c7af03_0  
setuptools                65.6.3           py38hecd8cb5_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.1.9                he9d5cce_0  
sqlite                    3.40.1               h880c91c_0  
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1            py38h7242b5c_0  
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.2.3                    pypi_0    pypi
tensorflow-base           2.10.0          eigen_py38h61e1807_0  
tensorflow-cpu            2.10.1                   pypi_0    pypi
tensorflow-estimator      2.10.0           py38hecd8cb5_0  
tensorflow-io-gcs-filesystem 0.29.0                   pypi_0    pypi
tensorflow-probability    0.14.0             pyhd3eb1b0_0  
termcolor                 2.2.0                    pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h5d9f67b_0  
tornado                   6.2              py38hca72f7f_0  
tqdm                      4.64.1           py38hecd8cb5_0  
typing-extensions         4.4.0            py38hecd8cb5_0  
typing_extensions         4.4.0            py38hecd8cb5_0  
uritemplate               3.0.1                    pypi_0    pypi
urllib3                   1.26.14                  pypi_0    pypi
werkzeug                  2.2.2            py38hecd8cb5_0  
wheel                     0.35.1             pyhd3eb1b0_0  
wrapt                     1.14.1           py38hca72f7f_0  
x264                      1!157.20191217       h1de35cc_0  
xz                        5.2.8                h6c40b1e_0  
yarl                      1.8.1            py38hca72f7f_0  
zipp                      3.11.0           py38hecd8cb5_0  
zlib                      1.2.13               h4dc903c_0  
zstd                      1.5.2                hcb37349_0  

================= Configs ==================
--------- convert.ini ---------

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.match_hist]
threshold:                99.0

[color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

[writer.pillow]
format:                   png
draw_transparent:         False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

[writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     None
profile:                  auto
level:                    auto
skip_mux:                 False

[writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

[writer.opencv]
format:                   png
draw_transparent:         False
jpg_quality:              75
png_compress_level:       3

[mask.mask_blend]
type:                     normalized
kernel_size:              3
passes:                   4
threshold:                6
erosion:                  1.2

[mask.box_blend]
type:                     gaussian
distance:                 11.0
radius:                   5.0
passes:                   1

[scaling.sharpen]
method:                   unsharp_mask
amount:                   150
radius:                   0.3
threshold:                5.0

--------- gui.ini ---------

[global]
fullscreen:               False
tab:                      extract
options_panel_width:      30
console_panel_height:     20
icon_size:                14
font:                     default
font_size:                9
autosave_last_session:    prompt
timeout:                  120
auto_load_model_stats:    True

--------- .faceswap ---------
backend:                  amd

--------- extract.ini ---------

[global]
allow_growth:             False

[detect.mtcnn]
minsize:                  20
scalefactor:              0.709
batch-size:               8
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7

[detect.cv2_dnn]
confidence:               50

[detect.s3fd]
confidence:               70
batch-size:               4

[align.fan]
batch-size:               12

[mask.unet_dfl]
batch-size:               8

[mask.vgg_obstructed]
batch-size:               2

[mask.vgg_clear]
batch-size:               6

[mask.bisenet_fp]
batch-size:               8
weights:                  faceswap
include_ears:             False
include_hair:             False
include_glasses:          True

--------- train.ini ---------

[global]
centering:                face
coverage:                 68.75
icnr_init:                False
conv_aware_init:          False
optimizer:                adam
learning_rate:            5e-05
epsilon_exponent:         -7
reflect_padding:          False
allow_growth:             False
mixed_precision:          False
nan_protection:           True
convert_batchsize:        16

[global.loss]
loss_function:            ssim
mask_loss_function:       mse
l2_reg_term:              100
eye_multiplier:           3
mouth_multiplier:         2
penalized_mask_loss:      True
mask_type:                extended
mask_blur_kernel:         3
mask_threshold:           4
learn_mask:               False

[model.phaze_a]
output_size:              128
shared_fc:                None
enable_gblock:            True
split_fc:                 True
split_gblock:             False
split_decoders:           False
enc_architecture:         fs_original
enc_scaling:              40
enc_load_weights:         True
bottleneck_type:          dense
bottleneck_norm:          None
bottleneck_size:          1024
bottleneck_in_encoder:    True
fc_depth:                 1
fc_min_filters:           1024
fc_max_filters:           1024
fc_dimensions:            4
fc_filter_slope:          -0.5
fc_dropout:               0.0
fc_upsampler:             upsample2d
fc_upsamples:             1
fc_upsample_filters:      512
fc_gblock_depth:          3
fc_gblock_min_nodes:      512
fc_gblock_max_nodes:      512
fc_gblock_filter_slope:   -0.5
fc_gblock_dropout:        0.0
dec_upscale_method:       subpixel
dec_norm:                 None
dec_min_filters:          64
dec_max_filters:          512
dec_filter_slope:         -0.45
dec_res_blocks:           1
dec_output_kernel:        5
dec_gaussian:             True
dec_skip_last_residual:   True
freeze_layers:            keras_encoder
load_layers:              encoder
fs_original_depth:        4
fs_original_min_filters:  128
fs_original_max_filters:  1024
mobilenet_width:          1.0
mobilenet_depth:          1
mobilenet_dropout:        0.001

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.dlight]
features:                 best
details:                  good
output_size:              256

[model.villain]
lowmem:                   False

[model.dfaker]
output_size:              128

[model.original]
lowmem:                   False

[model.dfl_h128]
lowmem:                   False

[trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4
```

**Comment by torzdf** [comment]
Ok, firstly, training on CPU is so slow as to not be worth it. You have been warned. I would not recommend it!

However, if you do wish to proceed, please install the "CPU" version of Faceswap, not the "AMD" version.

This may just fix your issue. If it does not, however, and you get the same error message, then run open a terminal emulator and run these commands:
```
conda activate faceswap
pip install chardet
```
