### ISSUE TITLE
OSError: exception: access violation writing 0x00007FFD6187A3E4

### ISSUE THREAD

**Issue by xieshanjie** [deepfakes/faceswap#1312]
ISSUE： OSError: exception: access violation writing 0x00007FFD6187A3E4
i meet this erorr suddenly when i want to start the faceswap gui

**Comment by xieshanjie** [comment]
the complete error reporting as follow：
``
Setting Faceswap backend to DIRECTML
Traceback (most recent call last):
  File "H:\profess_L\faceswap\faceswap.py", line 6, in <module>
    from lib.cli import args as cli_args
  File "H:\profess_L\faceswap\lib\cli\args.py", line 24, in <module>
    _GPUS = GPUStats().cli_devices
  File "H:\profess_L\faceswap\lib\gpu_stats\directml.py", line 489, in __init__
    super().__init__(log=log)
  File "H:\profess_L\faceswap\lib\gpu_stats\_base.py", line 96, in __init__
    self._initialize()
  File "H:\profess_L\faceswap\lib\gpu_stats\directml.py", line 545, in _initialize
    self._devices = self._get_devices()
  File "H:\profess_L\faceswap\lib\gpu_stats\directml.py", line 528, in _get_devices
    adapters = Adapters(log_func=self._log)
  File "H:\profess_L\faceswap\lib\gpu_stats\directml.py", line 315, in __init__
    self._devices = self._process_adapters()
  File "H:\profess_L\faceswap\lib\gpu_stats\directml.py", line 468, in _process_adapters
    is_d3d12 = self._test_d3d12(adapter)
  File "H:\profess_L\faceswap\lib\gpu_stats\directml.py", line 428, in _test_d3d12
    success = factory_func(adapter,
OSError: exception: access violation writing 0x00007FFD6187A3E4
``

**Comment by torzdf** [comment]
This looks like an issue with DirectML communicating with your GPU. Make sure your drivers are up to date.
