### ISSUE TITLE
Issues when installing using the windows installer

### ISSUE THREAD

**Issue by MaximeMnt** [deepfakes/faceswap#1320]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
When using the latest installer on windows 11 i get the following error 

```
(check) MiniConda installed: conda 23.3.1
(check) CPU Supports AVX Instructions
(check) CPU Supports SSE4 Instructions
(check) Completed check for installed applications
(check) Setting up for: nvidia

Miniconda3 installed.
Initializing Conda...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
All requested packages already installed.
Creating Conda Virtual Environment...
Removing existing Conda Virtual Environment...
Remove all packages in environment C:\Users\maxim\MiniConda3\envs\faceswap:
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
Package Plan
  environment location: C:\Users\maxim\MiniConda3\envs\faceswap
  added / updated specs:
    - python=3.9
The following NEW packages will be INSTALLED:
  ca-certificates    pkgs/main/win-64::ca-certificates-2023.01.10-haa95532_0 
  openssl            pkgs/main/win-64::openssl-1.1.1t-h2bbff1b_0 
  pip                pkgs/main/win-64::pip-23.0.1-py39haa95532_0 
  python             pkgs/main/win-64::python-3.9.16-h6244533_2 
  setuptools         pkgs/main/win-64::setuptools-66.0.0-py39haa95532_0 
  sqlite             pkgs/main/win-64::sqlite-3.41.2-h2bbff1b_0 
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1 
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2 
  wheel              pkgs/main/win-64::wheel-0.38.4-py39haa95532_0 
Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

 To activate this environment, use

     $ conda activate faceswap

 To deactivate an active environment, use

     $ conda deactivate
Installing Git...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
 Package Plan 
  environment location: C:\Users\maxim\MiniConda3\envs\faceswap
  added / updated specs:
    - git
The following NEW packages will be INSTALLED:
  git                pkgs/main/win-64::git-2.34.1-haa95532_0 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Downloading Faceswap...
Cloning into 'C:\Users\mxm\faceswap'...
fatal: invalid branch name: init.defaultBranch = 
Error Downloading Faceswap
Install Aborted

```

**To Reproduce**
1. Use the latest installer to install faceswap

**Expected behavior**
The installation would succeed

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version 3.9
 - Conda Version [e.g. 4.5.12]

**Comment by jpchow26** [comment]
Insalling latest on Windows now has an error in lib/logger.py:

```
...

# To activate this environment, use
#
#     $ conda activate faceswap
#
# To deactivate an active environment, use
#
#     $ conda deactivate
Installing Git...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Users\jpcho\MiniConda3\envs\faceswap
  added / updated specs:
    - git
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    git-2.40.1                 |       haa95532_1        69.2 MB
    ------------------------------------------------------------
                                           Total:        69.2 MB
The following NEW packages will be INSTALLED:
  git                pkgs/main/win-64::git-2.40.1-haa95532_1 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Downloading Faceswap...
Cloning into 'C:\Users\jpcho\faceswap'...
Setting up FaceSwap Environment... This may take a while
Traceback (most recent call last):
  File "C:\Users\jpcho\faceswap\setup.py", line 20, in <module>
    from lib.logger import log_setup
  File "C:\Users\jpcho\faceswap\lib\logger.py", line 425, in <module>
    def _stream_handler(loglevel: int, is_gui: bool) -> logging.StreamHandler | TqdmHandler:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
Error Setting up Faceswap
Install Aborted
```

**Comment by jpchow26** [comment]
Followed steps on forum to scrub system of all faceswap/conda/python and got latest installer. Fixed running faceswap.

However now get runtime issue: Could not locate zlibwapi.dll. Please make sure it is in your library path!

**Comment by torzdf** [comment]
zlibwapi is part of cuDNN as far as I'm aware.  Given the error you put in the first error message, and now this issue, I would say your system is most likely in a mess, which may not be easily fixable.

In the meantime, please provide the following:
https://forum.faceswap.dev/app.php/rules?sid=f366e01a18f86fa4adb034a10af65bd9#rule-4b

**Comment by jpchow26** [comment]
I installed the missing dll manually to my system32... not sure if it is the proper fix but now everything works with latest release.

**Comment by torzdf** [comment]
Yeah. This seems like an issue on some Windows systems. I did a clean Nvidia install on a clean WIndows 11 machine, and it ran fine, so can't recreate.

For others who hit the issue, you could try the following, and let me know if it resolves your issue? If it does, I will look to build this into the install process.

Start > Anaconda prompt (cmd)
```
conda activate faceswap
conda install -c conda-forge -y zlib-wapi
```
Close the window when it has finished installing and relaunch faceswap

**Comment by jpchow26** [comment]
yep, that worked. removed the dll from system32 and ran the conda install steps above and training kicked in nicely.

also since the upgrade i see a noticable speed increase. getting ~15% higher EG/s

**Comment by torzdf** [comment]
Fixed in installer
