### ISSUE TITLE
windows installer: wrong pillow version installed

### ISSUE THREAD

**Issue by josh3io** [deepfakes/faceswap#1375]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
Using the 2.10.0 windows installer, it appears that the wrong version of pillow is installed.

**To Reproduce**
1. Download and run the v2.10.0 windows installer
2. run faceswap_win_launcher.bat
3. See error (crash report below)

**Expected behavior**
GUI should launch.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11

**Additional context**
Manually installing pillow==9.4.0 resolves the issue.

**Crash Report**
02/29/2024 10:42:40 MainProcess     MainThread                     logger          log_setup                      INFO     Log level set to: INFO
02/29/2024 10:42:40 MainProcess     MainThread                     launcher        _set_environment_variables     DEBUG    Setting TF_RUN_EAGER_OP_AS_FUNCTION env var to False
02/29/2024 10:42:41 MainProcess     MainThread                     tpu_cluster_resolver <module>                       DEBUG    Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
02/29/2024 10:42:41 MainProcess     MainThread                     __init__        <module>                       DEBUG    Creating converter from 7 to 5
02/29/2024 10:42:41 MainProcess     MainThread                     __init__        <module>                       DEBUG    Creating converter from 5 to 7
02/29/2024 10:42:41 MainProcess     MainThread                     __init__        <module>                       DEBUG    Creating converter from 7 to 5
02/29/2024 10:42:41 MainProcess     MainThread                     __init__        <module>                       DEBUG    Creating converter from 5 to 7
02/29/2024 10:42:42 MainProcess     MainThread                     launcher        _test_for_tf_version           DEBUG    Installed Tensorflow Version: (2, 10)
Traceback (most recent call last):
  File "C:\Users\josh\faceswap\lib\cli\launcher.py", line 223, in execute_script
    script = self._import_script()
  File "C:\Users\josh\faceswap\lib\cli\launcher.py", line 53, in _import_script
    module = import_module(mod)
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\josh\faceswap\scripts\gui.py", line 9, in <module>
    from lib.gui import (TaskBar, CliOptions, CommandNotebook, ConsoleOut, DisplayNotebook,
  File "C:\Users\josh\faceswap\lib\gui\__init__.py", line 4, in <module>
    from lib.gui.command import CommandNotebook
  File "C:\Users\josh\faceswap\lib\gui\command.py", line 9, in <module>
    from .control_helper import ControlPanel
  File "C:\Users\josh\faceswap\lib\gui\control_helper.py", line 15, in <module>
    from .custom_widgets import ContextMenu, MultiOption, ToggledFrame, Tooltip
  File "C:\Users\josh\faceswap\lib\gui\custom_widgets.py", line 14, in <module>
    from .utils import get_config
  File "C:\Users\josh\faceswap\lib\gui\utils\__init__.py", line 4, in <module>
    from .config import get_config, initialize_config, PATHCACHE
  File "C:\Users\josh\faceswap\lib\gui\utils\config.py", line 12, in <module>
    from lib.gui._config import Config as UserConfig
  File "C:\Users\josh\faceswap\lib\gui\_config.py", line 8, in <module>
    from matplotlib import font_manager
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\site-packages\matplotlib\__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\site-packages\matplotlib\colors.py", line 52, in <module>
    from PIL import Image
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

============ System Information ============
backend:             nvidia
encoding:            cp1252
git_branch:          master
git_commits:         dea021c bugfix - setup.py   - Install xorg-libxft for Linux users   - Force tensorflow-cpu from pip
gpu_cuda:            12.3
gpu_cudnn:           8.9.6
gpu_devices:         GPU_0: NVIDIA RTX A2000 Laptop GPU
gpu_devices_active:  GPU_0
gpu_driver:          546.12
gpu_vram:            GPU_0: 4096MB (2398MB free)
os_machine:          AMD64
os_platform:         Windows-10-10.0.22631-SP0
os_release:          10
py_command:          C:\Users\josh\faceswap/faceswap.py gui
py_conda_version:    conda 23.9.0
py_implementation:   CPython
py_version:          3.10.5
py_virtual_env:      True
sys_cores:           12
sys_processor:       Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
sys_ram:             Total: 32471MB, Available: 6273MB, Used: 26197MB, Free: 6273MB

=============== Pip Packages ===============
absl-py==2.1.0
astunparse==1.6.3
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
colorama @ file:///C:/b/abs_a9ozq0l032/croot/colorama_1672387194846/work
contourpy @ file:///C:/b/abs_853rfy8zse/croot/contourpy_1700583617587/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
fastcluster @ file:///D:/bld/fastcluster_1649783460966/work
ffmpy @ file:///home/conda/feedstock_root/build_artifacts/ffmpy_1659474992694/work
flatbuffers==23.5.26
fonttools==4.25.0
gast==0.4.0
google-auth==2.28.1
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.62.0
h5py==3.10.0
idna==3.6
imageio @ file:///C:/b/abs_aeqerw_nps/croot/imageio_1707247365204/work
imageio-ffmpeg==0.4.9
joblib @ file:///C:/b/abs_1anqjntpan/croot/joblib_1685113317150/work
keras==2.10.0
Keras-Preprocessing==1.1.2
kiwisolver @ file:///C:/b/abs_88mdhvtahm/croot/kiwisolver_1672387921783/work
libclang==16.0.6
Markdown==3.5.2
MarkupSafe==2.1.5
matplotlib @ file:///C:/b/abs_e26vnvd5s1/croot/matplotlib-suite_1698692153288/work
mkl-fft @ file:///C:/b/abs_19i1y8ykas/croot/mkl_fft_1695058226480/work
mkl-random @ file:///C:/b/abs_edwkj1_o69/croot/mkl_random_1695059866750/work
mkl-service==2.4.0
munkres==1.1.4
numexpr @ file:///C:/b/abs_5fucrty5dc/croot/numexpr_1696515448831/work
numpy @ file:///C:/b/abs_c1ywpu18ar/croot/numpy_and_numpy_base_1708638681471/work/dist/numpy-1.26.4-cp310-cp310-win_amd64.whl#sha256=ebb5aa2b36d8afa5ec3231c19e5a1fc75b6d85e7db483f0fb9e77dad58469977
nvidia-ml-py @ file:///home/conda/feedstock_root/build_artifacts/nvidia-ml-py_1698947663801/work
oauthlib==3.2.2
opencv-python==4.9.0.80
opt-einsum==3.3.0
packaging @ file:///C:/b/abs_28t5mcoltc/croot/packaging_1693575224052/work
Pillow==9.3.0
ply==3.11
protobuf==3.19.6
psutil @ file:///C:/Windows/Temp/abs_b2c2fd7f-9fd5-4756-95ea-8aed74d0039flsd9qufz/croots/recipe/psutil_1656431277748/work
pyasn1==0.5.1
pyasn1-modules==0.3.0
pyparsing @ file:///C:/Users/BUILDE~1/AppData/Local/Temp/abs_7f_7lba6rl/croots/recipe/pyparsing_1661452540662/work
PyQt5==5.15.10
PyQt5-sip @ file:///C:/b/abs_c0pi2mimq3/croot/pyqt-split_1698769125270/work/pyqt_sip
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pywin32==305.1
pywinpty @ file:///C:/ci_310/pywinpty_1644230983541/work/target/wheels/pywinpty-2.0.2-cp310-none-win_amd64.whl
requests==2.31.0
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn @ file:///C:/b/abs_daon7wm2p4/croot/scikit-learn_1694788586973/work
scipy==1.11.4
sip @ file:///C:/b/abs_edevan3fce/croot/sip_1698675983372/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.10.1
tensorflow-estimator==2.10.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.4.0
threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1629802263681/work
tomli @ file:///C:/Windows/TEMP/abs_ac109f85-a7b3-4b4d-bcfd-52622eceddf0hy332ojo/croots/recipe/tomli_1657175513137/work
tornado @ file:///C:/b/abs_0cbrstidzg/croot/tornado_1696937003724/work
tqdm @ file:///C:/b/abs_f76j9hg7pv/croot/tqdm_1679561871187/work
typing_extensions==4.10.0
urllib3==2.2.1
Werkzeug==3.0.1
wrapt==1.16.0

============== Conda Packages ==============
# packages in environment at C:\Users\josh\miniconda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
blas                      1.0                         mkl  
brotli                    1.0.9                h2bbff1b_7  
brotli-bin                1.0.9                h2bbff1b_7  
bzip2                     1.0.8                h2bbff1b_5  
ca-certificates           2024.2.2             h56e8100_0    conda-forge
cachetools                5.3.3                    pypi_0    pypi
certifi                   2024.2.2                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
colorama                  0.4.6           py310haa95532_0  
contourpy                 1.2.0           py310h59b6b97_0  
cudatoolkit               11.2.2              h933977f_10    conda-forge
cudnn                     8.1.0.77             h3e0f4f4_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0  
fastcluster               1.2.6           py310hf5e1058_1    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
ffmpy                     0.3.0              pyhb6f538c_0    conda-forge
flatbuffers               23.5.26                  pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.10.4               hd328e21_0  
gast                      0.4.0                    pypi_0    pypi
git                       2.40.1               haa95532_1  
glib                      2.69.1               h5dc1a3c_1  
google-auth               2.28.1                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.62.0                   pypi_0    pypi
gst-plugins-base          1.18.5               h9e645db_0  
gstreamer                 1.18.5               hd78058f_0  
h5py                      3.10.0                   pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2  
icu                       58.2                 ha925a31_3  
idna                      3.6                      pypi_0    pypi
imageio                   2.33.1          py310haa95532_0  
imageio-ffmpeg            0.4.9                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320  
joblib                    1.2.0           py310haa95532_0  
jpeg                      9e                   h2bbff1b_1  
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4           py310hd77b12b_0  
lerc                      3.0                  hd77b12b_0  
libbrotlicommon           1.0.9                h2bbff1b_7  
libbrotlidec              1.0.9                h2bbff1b_7  
libbrotlienc              1.0.9                h2bbff1b_7  
libclang                  16.0.6                   pypi_0    pypi
libdeflate                1.17                 h2bbff1b_1  
libffi                    3.4.4                hd77b12b_0  
libiconv                  1.16                 h2bbff1b_2  
libogg                    1.3.5                h2bbff1b_1  
libpng                    1.6.37               h2a8f88b_0  
libtiff                   4.5.0                h8a3f274_0  
libvorbis                 1.3.7                he774522_0  
libwebp                   1.2.2                h2bbff1b_0  
libzlib                   1.2.12               h8ffe710_2    conda-forge
libzlib-wapi              1.2.12               h8ffe710_2    conda-forge
lz4-c                     1.9.4                h2bbff1b_0  
markdown                  3.5.2                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.8.0           py310haa95532_0  
matplotlib-base           3.8.0           py310h4ed8f06_0  
mkl                       2023.1.0         h6b88ed4_46358  
mkl-service               2.4.0           py310h2bbff1b_1  
mkl_fft                   1.3.8           py310h2bbff1b_0  
mkl_random                1.2.4           py310h59b6b97_0  
munkres                   1.1.4                      py_0  
numexpr                   2.8.7           py310h2cd9be0_0  
numpy                     1.26.4          py310h055cbcc_0  
numpy-base                1.26.4          py310h65a83cf_0  
nvidia-ml-py              12.535.133         pyhd8ed1ab_0    conda-forge
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
openssl                   3.0.5                h8ffe710_1    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.1            py310haa95532_0  
pcre                      8.45                 hd77b12b_0  
pillow                    9.5.0                    pypi_0    pypi
pip                       23.3.1          py310haa95532_0  
ply                       3.11            py310haa95532_0  
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.0           py310h2bbff1b_0  
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pyparsing                 3.0.9           py310haa95532_0  
pyqt                      5.15.10         py310hd77b12b_0  
pyqt5-sip                 12.13.0         py310h2bbff1b_0  
python                    3.10.5          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python_abi                3.10                    4_cp310    conda-forge
pywin32                   305             py310h2bbff1b_0  
pywinpty                  2.0.2           py310h5da7b33_0  
qt-main                   5.15.2               he8e5bd7_7  
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.3.0           py310h4ed8f06_1  
scipy                     1.11.4          py310h309d312_0  
setuptools                68.2.2          py310haa95532_0  
sip                       6.7.12          py310hd77b12b_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h2bbff1b_0  
tbb                       2021.8.0             h59b6b97_0  
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.1                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.12               h2bbff1b_0  
tomli                     2.0.1           py310haa95532_0  
tornado                   6.3.3           py310h2bbff1b_0  
tqdm                      4.65.0          py310h9909e9c_0  
typing-extensions         4.10.0                   pypi_0    pypi
tzdata                    2024a                h04d1e81_0  
urllib3                   2.2.1                    pypi_0    pypi
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2          py310haa95532_0  
winpty                    0.4.3                         4  
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.4.6                h8cc25b3_0  
zlib                      1.2.12               h8ffe710_2    conda-forge
zlib-wapi                 1.2.12               h8ffe710_2    conda-forge
zstd                      1.5.2                h19a0ad4_0  

================= Configs ==================
--------- .faceswap ---------
backend:                  nvidia

--------- convert.ini ---------

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

[color.match_hist]
threshold:                99.0

[mask.mask_blend]
type:                     normalized
kernel_size:              3
passes:                   4
threshold:                4
erosion:                  0.0
erosion_top:              0.0
erosion_bottom:           0.0
erosion_left:             0.0
erosion_right:            0.0

[scaling.sharpen]
method:                   none
amount:                   150
radius:                   0.3
threshold:                5.0

[writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     none
profile:                  auto
level:                    auto
skip_mux:                 False

[writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

[writer.opencv]
format:                   png
draw_transparent:         False
separate_mask:            False
jpg_quality:              75
png_compress_level:       3

[writer.patch]
start_index:              0
index_offset:             0
number_padding:           6
include_filename:         True
face_index_location:      before
origin:                   bottom-left
empty_frames:             blank
json_output:              False
separate_mask:            False
bit_depth:                16
format:                   png
png_compress_level:       3
tiff_compression_method:  lzw

[writer.pillow]
format:                   png
draw_transparent:         False
separate_mask:            False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

--------- extract.ini ---------

[global]
allow_growth:             False
aligner_min_scale:        0.07
aligner_max_scale:        2.0
aligner_distance:         22.5
aligner_roll:             45.0
aligner_features:         True
filter_refeed:            True
save_filtered:            False
realign_refeeds:          True
filter_realign:           True

[align.fan]
batch-size:               12

[detect.cv2_dnn]
confidence:               50

[detect.mtcnn]
minsize:                  20
scalefactor:              0.709
batch-size:               8
cpu:                      True
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7

[detect.s3fd]
confidence:               70
batch-size:               4

[mask.bisenet_fp]
batch-size:               8
cpu:                      False
weights:                  faceswap
include_ears:             False
include_hair:             False
include_glasses:          True

[mask.custom]
batch-size:               8
centering:                face
fill:                     False

[mask.unet_dfl]
batch-size:               8

[mask.vgg_clear]
batch-size:               6

[mask.vgg_obstructed]
batch-size:               2

[recognition.vgg_face2]
batch-size:               16
cpu:                      False

--------- train.ini ---------

[global]
centering:                face
coverage:                 87.5
icnr_init:                False
conv_aware_init:          False
optimizer:                adam
learning_rate:            5e-05
epsilon_exponent:         -7
save_optimizer:           exit
lr_finder_iterations:     1000
lr_finder_mode:           set
lr_finder_strength:       default
autoclip:                 False
reflect_padding:          False
allow_growth:             False
mixed_precision:          False
nan_protection:           True
convert_batchsize:        16

[global.loss]
loss_function:            ssim
loss_function_2:          mse
loss_weight_2:            100
loss_function_3:          none
loss_weight_3:            0
loss_function_4:          none
loss_weight_4:            0
mask_loss_function:       mse
eye_multiplier:           3
mouth_multiplier:         2
penalized_mask_loss:      True
mask_type:                extended
mask_blur_kernel:         3
mask_threshold:           4
learn_mask:               False

[model.dfaker]
output_size:              128

[model.dfl_h128]
lowmem:                   False

[model.dfl_sae]
input_size:               128
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[model.dlight]
features:                 best
details:                  good
output_size:              256

[model.original]
lowmem:                   False

[model.phaze_a]
output_size:              128
shared_fc:                none
enable_gblock:            True
split_fc:                 True
split_gblock:             False
split_decoders:           False
enc_architecture:         fs_original
enc_scaling:              7
enc_load_weights:         True
bottleneck_type:          dense
bottleneck_norm:          none
bottleneck_size:          1024
bottleneck_in_encoder:    True
fc_depth:                 1
fc_min_filters:           1024
fc_max_filters:           1024
fc_dimensions:            4
fc_filter_slope:          -0.5
fc_dropout:               0.0
fc_upsampler:             upsample2d
fc_upsamples:             1
fc_upsample_filters:      512
fc_gblock_depth:          3
fc_gblock_min_nodes:      512
fc_gblock_max_nodes:      512
fc_gblock_filter_slope:   -0.5
fc_gblock_dropout:        0.0
dec_upscale_method:       subpixel
dec_upscales_in_fc:       0
dec_norm:                 none
dec_min_filters:          64
dec_max_filters:          512
dec_slope_mode:           full
dec_filter_slope:         -0.45
dec_res_blocks:           1
dec_output_kernel:        5
dec_gaussian:             True
dec_skip_last_residual:   True
freeze_layers:            keras_encoder
load_layers:              encoder
fs_original_depth:        4
fs_original_min_filters:  128
fs_original_max_filters:  1024
fs_original_use_alt:      False
mobilenet_width:          1.0
mobilenet_depth:          1
mobilenet_dropout:        0.001
mobilenet_minimalistic:   False

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.unbalanced]
input_size:               128
lowmem:                   False
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.villain]
lowmem:                   False

[trainer.original]
preview_images:           14
mask_opacity:             30
mask_color:               #ff0000
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4

**Comment by torzdf** [comment]
No. it's the correct version of Pillow...

This is a system issue, in some way (a required file missing on your PC, or a conflict of some kind).

In the first instance, try this to see if it resolves it:
https://forum.faceswap.dev/app.php/faqpage#f1r1

**Comment by josh3io** [comment]
C:\Users\josh\faceswap>"C:\Users\josh\Miniconda3\scripts\activate.bat"   && conda activate "faceswap"   && python "C:\Users\josh\faceswap/faceswap.py" gui
Setting Faceswap backend to NVIDIA
02/29/2024 10:44:58 INFO     Log level set to: INFO
02/29/2024 10:45:04 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "C:\Users\josh\faceswap\lib\cli\launcher.py", line 223, in execute_script
    script = self._import_script()
  File "C:\Users\josh\faceswap\lib\cli\launcher.py", line 53, in _import_script
    module = import_module(mod)
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\josh\faceswap\scripts\gui.py", line 9, in <module>
    from lib.gui import (TaskBar, CliOptions, CommandNotebook, ConsoleOut, DisplayNotebook,
  File "C:\Users\josh\faceswap\lib\gui\__init__.py", line 4, in <module>
    from lib.gui.command import CommandNotebook
  File "C:\Users\josh\faceswap\lib\gui\command.py", line 9, in <module>
    from .control_helper import ControlPanel
  File "C:\Users\josh\faceswap\lib\gui\control_helper.py", line 15, in <module>
    from .custom_widgets import ContextMenu, MultiOption, ToggledFrame, Tooltip
  File "C:\Users\josh\faceswap\lib\gui\custom_widgets.py", line 14, in <module>
    from .utils import get_config
  File "C:\Users\josh\faceswap\lib\gui\utils\__init__.py", line 4, in <module>
    from .config import get_config, initialize_config, PATHCACHE
  File "C:\Users\josh\faceswap\lib\gui\utils\config.py", line 12, in <module>
    from lib.gui._config import Config as UserConfig
  File "C:\Users\josh\faceswap\lib\gui\_config.py", line 8, in <module>
    from matplotlib import font_manager
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\site-packages\matplotlib\__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\site-packages\matplotlib\colors.py", line 52, in <module>
    from PIL import Image
  File "C:\Users\josh\miniconda3\envs\faceswap\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
02/29/2024 10:45:04 CRITICAL An unexpected crash has occurred. Crash report written to 'C:\Users\josh\faceswap\crash_report.2024.02.29.104500909341.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting

(faceswap) C:\Users\josh\faceswap>ls
CODE_OF_CONDUCT.md  __pycache__                               docs                       locales       tools
Dockerfile.cpu      _config.yml                               faceswap.py                plugins       tools.py
Dockerfile.gpu      config                                    faceswap_gui.log           requirements  update_deps.py
INSTALL.md          crash_report.2024.02.29.104006270120.log  faceswap_gui.log.1         scripts
LICENSE             crash_report.2024.02.29.104030719334.log  faceswap_setup.log         setup.cfg
README.md           crash_report.2024.02.29.104242856258.log  faceswap_win_launcher.bat  setup.py
USAGE.md            crash_report.2024.02.29.104500909341.log  lib                        tests

(faceswap) C:\Users\josh\faceswap>ls requirements
_requirements_base.txt          requirements_cpu.txt       requirements_nvidia.txt
requirements_apple_silicon.txt  requirements_directml.txt  requirements_rocm.txt

(faceswap) C:\Users\josh\faceswap>cat requirements/requirements_nvidia.txt
-r _requirements_base.txt
# Exclude badly numbered Python2 version of nvidia-ml-py
nvidia-ml-py>=11.525,<300
pynvx==1.0.0 ; sys_platform == "darwin"
tensorflow>=2.10.0,<2.11.0

(faceswap) C:\Users\josh\faceswap>cat requirements/_requirements_base.txt
tqdm>=4.65
psutil>=5.9.0
numexpr>=2.8.4
numpy>=1.25.0
opencv-python>=4.7.0.0
pillow>=9.4.0,<10.0.0
scikit-learn>=1.2.2
fastcluster>=1.2.6
matplotlib>=3.7.1
imageio>=2.26.0
imageio-ffmpeg>=0.4.8
ffmpy>=0.3.0
pywin32>=228 ; sys_platform == "win32"

(faceswap) C:\Users\josh\faceswap>pip install pillow
Requirement already satisfied: pillow in c:\users\josh\miniconda3\envs\faceswap\lib\site-packages (9.3.0)

(faceswap) C:\Users\josh\faceswap>pip install pillow==9.4.0
Collecting pillow==9.4.0
  Downloading Pillow-9.4.0-cp310-cp310-win_amd64.whl.metadata (9.4 kB)
Downloading Pillow-9.4.0-cp310-cp310-win_amd64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 12.1 MB/s eta 0:00:00
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.3.0
    Uninstalling Pillow-9.3.0:
      Successfully uninstalled Pillow-9.3.0
Successfully installed pillow-9.4.0

**Comment by torzdf** [comment]
Closing as FS2 no longer supported
