### ISSUE TITLE
ModuleNotFoundError: No module named 'pyparsing'

### ISSUE THREAD

**Issue by darkside369** [deepfakes/faceswap#1389]
Setting Faceswap backend to CPU
05/17/2024 03:54:53 INFO     Log level set to: INFO
05/17/2024 03:54:57 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/home/grogu/faceswap/lib/cli/launcher.py", line 223, in execute_script
    script = self._import_script()
  File "/home/grogu/faceswap/lib/cli/launcher.py", line 53, in _import_script
    module = import_module(mod)
  File "/home/grogu/miniconda3/envs/faceswap/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/grogu/faceswap/scripts/gui.py", line 9, in <module>
    from lib.gui import (TaskBar, CliOptions, CommandNotebook, ConsoleOut, DisplayNotebook,
  File "/home/grogu/faceswap/lib/gui/__init__.py", line 4, in <module>
    from lib.gui.command import CommandNotebook
  File "/home/grogu/faceswap/lib/gui/command.py", line 9, in <module>
    from .control_helper import ControlPanel
  File "/home/grogu/faceswap/lib/gui/control_helper.py", line 15, in <module>
    from .custom_widgets import ContextMenu, MultiOption, ToggledFrame, Tooltip
  File "/home/grogu/faceswap/lib/gui/custom_widgets.py", line 14, in <module>
    from .utils import get_config
  File "/home/grogu/faceswap/lib/gui/utils/__init__.py", line 4, in <module>
    from .config import get_config, initialize_config, PATHCACHE
  File "/home/grogu/faceswap/lib/gui/utils/config.py", line 12, in <module>
    from lib.gui._config import Config as UserConfig
  File "/home/grogu/faceswap/lib/gui/_config.py", line 8, in <module>
    from matplotlib import font_manager
  File "/home/grogu/.local/lib/python3.10/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/home/grogu/.local/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 29, in <module>
    from matplotlib._fontconfig_pattern import parse_fontconfig_pattern
  File "/home/grogu/.local/lib/python3.10/site-packages/matplotlib/_fontconfig_pattern.py", line 15, in <module>
    from pyparsing import (
ModuleNotFoundError: No module named 'pyparsing'
05/17/2024 03:54:57 CRITICAL An unexpected crash has occurred. Crash report written to '/home/grogu/faceswap/crash_report.2024.05.17.035455342092.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting

**Comment by torzdf** [comment]
> 05/17/2024 03:54:57 CRITICAL An unexpected crash has occurred. Crash report written to '/home/grogu/faceswap/crash_report.2024.05.17.035455342092.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting

**Comment by torzdf** [comment]
Your environment is polluted with all kinds of non-faceswap related packages.

Do this:
https://forum.faceswap.dev/app.php/faqpage?sid=30bc5dea5b0fdace789b769543a90124#f1r1
