### ISSUE TITLE
Faceswap no longer works for me after latest commit

### ISSUE THREAD

**Issue by thorprin** [deepfakes/faceswap#149]
Here is the error message that prints when trying to get the help screen: 
```
$ python ./faceswap.py -h

Traceback (most recent call last):
  File "faceswap.py", line 10, in <module>
    from scripts.extract import ExtractTrainingData
  File "/home/username/faceswap/scripts/extract.py", line 6, in <module>
    from lib.cli import DirectoryProcessor
  File "/home/username/faceswap/lib/cli.py", line 6, in <module>
    from lib.FaceFilter import FaceFilter
  File "/home/username/faceswap/lib/FaceFilter.py", line 3, in <module>
    import face_recognition
  File "/home/username/.virtualenvs/fs2/lib/python3.6/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/username/.virtualenvs/fs2/lib/python3.6/site-packages/face_recognition/api.py", line 24, in <module>
    cnn_face_detector = dlib.cnn_face_detection_model_v1(cnn_face_detection_model)
RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-build-4mju0q0f/dlib/dlib/dnn/gpu_data.cpp:178. code: 30, reason: unknown error
```

- **Operating system and version:** Ubuntu 14.04 
- **Python version:** 3.5.4 (3.6.4 yielded the same results)
- **Faceswap version:** f3bb0bba072f0bfc4c11480cd6f0728aaf1e3db6
- **Faceswap method:** GPU

**Comment by Clorr** [comment]
Hmm, strange. What I had recently is that the GPU was no more taken in account by tensorflow after updating nvidia drivers. Is it possible that it happens for you? My fix was just to reinstall tensorflow.

Can you also tell if you use a CUDA compiled dlib?

**Comment by thorprin** [comment]
I'm not sure. I installed _dlib_ using **pip -r requirements-gpu.txt** in my virtual environment. I tried running _pip_ in a new virtualenv (reinstalling all the dependencies) but with no effect. Also, I'm not sure if this is related, but when I execute _nvidia-smi_ I get the following message: `NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.` 
I appreciate any insight you can give me. Thank you.
