### ISSUE TITLE
Requirements now needs a correct version of theano installed.

### ISSUE THREAD

**Issue by bryanlyon** [deepfakes/faceswap#261]
## Expected behavior

All functions work.

## Actual behavior

After update, system errors out with 

ImportError: No module named 'theano'

Installing the latest theano (python3 -m pip install theano) gives the error

ValueError: You are tring to use the old GPU back-end. It was removed from Theano. Use device=cuda* now. See https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29 for more information.

## Steps to reproduce

Run any version after 232d9313afabc075e28c1a42047b22e0568200e6 with the INSTALL directions

## Proposed solution

Requirements.txt files should include an appropriate version of theano that corresponds to the Keras==2.1.2 that was installed.

I am unsure which version is used or I would have included a patch and pull request.
 
## Other relevant information

Ubuntu Linux, python 3.5

**Comment by iperov** [comment]
faceswap requie tensorflow, not theano

**Comment by Clorr** [comment]
Not sure why you have something related to theano. If confirmed please open an issue in faceswap-playground as this is more related to install

**Comment by bryanlyon** [comment]
Traceback (most recent call last):
  File "faceswap.py", line 10, in <module>
    from scripts.extract import ExtractTrainingData
  File "/superm/data/Projects/faceswap/scripts/extract.py", line 7, in <module>
    from lib.cli import DirectoryProcessor
  File "/superm/data/Projects/faceswap/lib/cli.py", line 7, in <module>
    from lib.faces_detect import detect_faces, DetectedFace
  File "/superm/data/Projects/faceswap/lib/faces_detect.py", line 1, in <module>
    from lib import FaceLandmarksExtractor
  File "/superm/data/Projects/faceswap/lib/FaceLandmarksExtractor/__init__.py", line 1, in <module>
    from .FaceLandmarksExtractor import extract
  File "/superm/data/Projects/faceswap/lib/FaceLandmarksExtractor/FaceLandmarksExtractor.py", line 6, in <module>
    import keras
  File "/local/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/local/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/local/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/local/lib/python3.5/site-packages/keras/backend/__init__.py", line 80, in <module>
    from .theano_backend import *
  File "/home/nikkelitous/.local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 3, in <module>
    import theano

**Comment by Clorr** [comment]
see https://github.com/deepfakes/faceswap-playground/issues/91#issuecomment-371875770
