### ISSUE TITLE
Failed Building wheels for collected packages: dlib while installing face_recognition

### ISSUE THREAD

**Issue by Saini-96** [deepfakes/faceswap#359]
(base) C:\Users\hp 1>pip install --upgrade dlib
Collecting dlib
  Using cached https://files.pythonhosted.org/packages/54/ff/5781a11bdc0d1c90a813f3f66d460abf628e5114856a842d18d43f709a7a/dlib-19.10.0.tar.gz
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... error
  Complete output from command "c:\program files\anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\HP1~1\\AppData\\Local\\Temp\\pip-install-cuelvrr5\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\HP1~1\AppData\Local\Temp\pip-wheel-fj3lg4hd --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\HP1~1\AppData\Local\Temp\pip-install-cuelvrr5\dlib\setup.py", line 249, in <module>
      'Topic :: Software Development',
    File "c:\program files\anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "c:\program files\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\program files\anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\program files\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "c:\program files\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\program files\anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\program files\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\HP1~1\AppData\Local\Temp\pip-install-cuelvrr5\dlib\setup.py", line 125, in run
      if LooseVersion(self.get_cmake_version()) < '3.1.0':
    File "C:\Users\HP1~1\AppData\Local\Temp\pip-install-cuelvrr5\dlib\setup.py", line 117, in get_cmake_version
      out = subprocess.check_output(['cmake', '--version'])
    File "c:\program files\anaconda3\lib\subprocess.py", line 626, in check_output
      **kwargs).stdout
    File "c:\program files\anaconda3\lib\subprocess.py", line 708, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1

  ----------------------------------------
  Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib ... error
    Complete output from command "c:\program files\anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\HP1~1\\AppData\\Local\\Temp\\pip-install-cuelvrr5\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HP1~1\AppData\Local\Temp\pip-record-7y022vwy\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HP1~1\AppData\Local\Temp\pip-install-cuelvrr5\dlib\setup.py", line 249, in <module>
        'Topic :: Software Development',
      File "c:\program files\anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files\anaconda3\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "c:\program files\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files\anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\HP1~1\AppData\Local\Temp\pip-install-cuelvrr5\dlib\setup.py", line 125, in run
        if LooseVersion(self.get_cmake_version()) < '3.1.0':
      File "C:\Users\HP1~1\AppData\Local\Temp\pip-install-cuelvrr5\dlib\setup.py", line 117, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "c:\program files\anaconda3\lib\subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "c:\program files\anaconda3\lib\subprocess.py", line 708, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1

    ----------------------------------------
Command ""c:\program files\anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\HP1~1\\AppData\\Local\\Temp\\pip-install-cuelvrr5\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HP1~1\AppData\Local\Temp\pip-record-7y022vwy\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\HP1~1\AppData\Local\Temp\pip-install-cuelvrr5\dlib\

what should i do?

**Comment by torzdf** [comment]
If you have a gpu then you should build dlib yourself. See: https://github.com/davisking/dlib/issues/909

**Comment by torzdf** [comment]
If you just want to solve this issue though, and go with dlib, then

`pip3 install cmake`

should have you covered

**Comment by vamzii** [comment]
https://www.youtube.com/watch?v=XcRgA9DDB14
made it if this can help you?
