### ISSUE TITLE
GUI v3.0.0a released

### ISSUE THREAD

**Issue by torzdf** [deepfakes/faceswap#412]
Ok, this is alpha, with known bugs, but I'm releasing now, so that any other bugs can be found and squashed before pushing to master. Please feedback with any issues, whilst I finalise.

The latest GUI can be tested by checking out the gui-v3.0 branch of this repo:
https://github.com/deepfakes/faceswap/tree/gui-v3.0

Known bugs:
- macOS tooltips still not working.
- Locale issue not yet fixed.
- layout issue on Windows 10 (and potentially others)
- **Possibly fixed - currently untested** - ffmpeg doesn't work properly (merge conflict between my changes and @AbysmalBiscuit new filehandlers)
- ~sort not working~
- ~Progress bar not working for sort tool~
- ~sometimes graphs fail to generate when commencing training~

This is a major overhaul of the GUI, and probably the final release apart from bugfixes. I do still intend to add a job queue at some point in the future, but didn't want to delay the release any longer.

New features:
- tools.py and faceswap.py now both accessible from the same GUI
- tqdm/loss output to console removed and added to new progress bar/status bar in the gui
- Previews on extract/convert (preview updates every 5 seconds to reduce disk contention)
- Previews for GAN now all load
 - Ability to pop training previews into their own window (as per default faceswap behaviour). Previews for the GUI are now handled internally, and can be switched off. To enable the external previews, just check the preview option on training.
- Generate command line arguments
 - New 'Analysis' tab. Fairly basic stuff, but each training session now saves it's stats into the model folder. The analysis tab enables you to see total, or individual stats for all sessions on a given model, graph the progress and save the stats out to csv.
- DPI scaling fix for windows (untested)
- Save graphs and previews to disk

![analysis](https://user-images.githubusercontent.com/36920800/40886054-222c0b72-6729-11e8-966c-056ecda84814.png)
![analysis2](https://user-images.githubusercontent.com/36920800/40886055-2248de28-6729-11e8-9ef0-4f7ea66c4531.png)

**Comment by torzdf** [comment]
@andenixa I implemented your DPI fix pretty much exactly as you stated, but can't test. Could you let me know if it works. Thanks

**Comment by andenixa** [comment]
@torzdf sure I shall test it ASAP.
Thank you

**Comment by linkoid** [comment]
I got this error when I tried to use it at first:
```
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
ImportError: cannot import name 'NavigationToolbar2Tk'
```
I had to uninstall and reinstall matplotlib again and it worked.
Nothing seems to be an issue now, but I figured I should mention it so you could add a note about it or something.

**Comment by torzdf** [comment]
Thanks for the feedback.

I'll add a minimum requirement version for matplotlib, they changed the naming convention for NavigationToolbar2Tk

What OS are you using? It displays differently in different OSes, so I'll try to set the geometry for the OS that requires the most space.

**Comment by LordOEQJen** [comment]
System: Ubuntu 16.04

When starting the training with preview enabled, the preview window shows up twice: One preview windows is inside the GUI (as expected), the other preview window opens as a separate window. Both preview windows are showing the same output.
When I use GAN as a Trainer, beside the main faceswap.py-window there are 3 separate windows opening called masked, raw, mask (in titles of the window bar).

**Comment by LordOEQJen** [comment]
Sometimes when I start training, the graph won't show up. Error message:

/home/USER//faceswapNewGui/env/lib/python3.6/site-packages/numpy/lib/polynomial.py:584: RuntimeWarning: invalid value encountered in true_divide
  lhs /= scale
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/USER/faceswapNewGui/lib/gui/display_page.py", line 211, in <lambda>
    self.after(waittime, lambda t=waittime: self.update_page(t))
  File "/home/USER/faceswapNewGui/lib/gui/display_page.py", line 210, in update_page
    self.load_display()
  File "/home/USER/faceswapNewGui/lib/gui/display_page.py", line 221, in load_display
    self.display_item_process()
  File "/home/USER/faceswapNewGui/lib/gui/display_command.py", line 157, in display_item_process
    selections=["raw", "trend"])
  File "/home/USER/faceswapNewGui/lib/gui/stats.py", line 214, in __init__
    self.refresh()
  File "/home/USER/faceswapNewGui/lib/gui/stats.py", line 220, in refresh
    self.get_calculations()
  File "/home/USER/faceswapNewGui/lib/gui/stats.py", line 302, in get_calculations
    self.stats[key] = method(raw)
  File "/home/USER/faceswapNewGui/lib/gui/stats.py", line 334, in calc_trend
    fit = np.polyfit(x_range, data, 3)
  File "/home/USER/faceswapNewGui/env/lib/python3.6/site-packages/numpy/lib/polynomial.py", line 585, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "/home/USER/faceswapNewGui/env/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 2041, in lstsq
    0, work, lwork, iwork, 0)
ValueError: On entry to DLASCL parameter number 4 had an illegal value

Status remains:"Waiting for graph"

**Comment by torzdf** [comment]
Yeah, I've seen that too. Normally if I kill training and start again it goes away. I'd imagine it's to do with attempting to calculate the polynormal when there isn't enough data. I'll look to fix this

**Comment by torzdf** [comment]
FYI, I'm not going to be able to work on this until next week, but please keep reporting bugs. Thanks!

**Comment by LordOEQJen** [comment]
Happens here in the same situation, when attempting to restart the training.

**Comment by luiscosio** [comment]
@torzdf Effmpeg tab gets stuck (but I see that this is a known bug), but everything is working on Windows 2016

**Comment by andenixa** [comment]
@torzdf negate on the GUI DPI, its still upscaled at MS Windows, but probably for the best.
That way at least the layout is preserved.

**Comment by luiscosio** [comment]
```
Loading...
Please backup your data and/or test the tool you want to use with a smaller data set to make sure you understand how it works.
Traceback (most recent call last):
File "C:\Users\Administrator\faceswap\tools.py", line 40, in <module>
ARGUMENTS.func(ARGUMENTS)
File "C:\Users\Administrator\faceswap\lib\cli.py", line 79, in execute_script
script = self.import_script()
File "C:\Users\Administrator\faceswap\lib\cli.py", line 28, in import_script
Process exited.module = import_module(mod)

File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scripts.sort'

```

Sort doesn't work.

**Comment by ruah1984** [comment]
is this include 128??

**Comment by andenixa** [comment]
@torzdf not sure if its still a thing but I am fished with 128 model for now at least.
For one its pretty fast now. I don't recommend raising dense layer size. I'd try batch_size 16 and lower though.
It features two different modes: Original (HgihRes) and Shaonlu (not GAN). I personally think Shaonlu's has more generalization, but that's debatable.
PS: When I say 128 technically its not really limited to any size, you can put anything to IMAGE_SHAPE as long as its >=16, but converters are not tuned to "auto detect" model output size so you'd be on your ow if you change it. Also increasing input size tremendously increases memory demand. I wouldn't try to set 256x256 unless you have like 12+ GB of video memory.

**Comment by tjess78** [comment]
@andenixa nice to hear! 
Could you please explain what you mean with Shaonlu mode? I know Shaonlu only for his GAN-specific experiments.
Thanks!

**Comment by andenixa** [comment]
@tjess78 sure. Basically apart from GAN which ain't performing too well Shaoanlu uses a unique activation for hist Convolution layers which is different from LeakyRelu used by most is not all Autoencoder models. I did numerous experiments and in many cases this activation provides a better generalization at a increased memory and computational cost. So by default OriginalHighRes model uses Shaoanlu Encoder's and decoder (minus mask and GAN part, obviously). If you are getting Reouse exhausted exception or find the training to be too long you should switch to `ENCODER = EncoderType.ORIGINAL` in `Model.py` file which is less computationally extensive. It might even give you better result depending on the data-sets.

**Comment by andenixa** [comment]
@tjess78 
One thing when testing, regardless of common oppinion that both sets ough to be huge, its better to keep set B (your target face) rather small and clean. No more than 2000-3000 crisp shots that would include as much possible directions. Shots which are too similar don't help the learning but rather slow it down.

**Comment by LordOEQJen** [comment]
That's the point, when it comes to the sorting tool. Sorting by hist-dissim (histogram dissimilarity), deleting all pictures at the end of the directory.

Btw.: Why is in faceswap's sorting tool the option "group" existing ? Only know that one from Iperov's script

**Comment by scarecrow2415** [comment]
python faceswap.py gui

Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\cli.py", line 79, in execute_script
    script = self.import_script()
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\cli.py", line 28, in import_script
    module = import_module(mod)
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\scripts\gui.py", line 11, in <module>
    from lib.gui import CurrentSession, CommandNotebook, Config, ConsoleOut
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\gui\__init__.py", line 2, in <module>
    from lib.gui.display import DisplayNotebook
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\gui\display.py", line 10, in <module>
    from .display_analysis import Analysis
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\gui\display_analysis.py", line 8, in <module>
    from .display_graph import SessionGraph
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\gui\display_graph.py", line 14, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
ImportError: cannot import name 'NavigationToolbar2Tk'




why happen this?

**Comment by scarecrow2415** [comment]
python faceswap.py gui
Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\cli.py", line 79, in execute_script
    script = self.import_script()
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\cli.py", line 28, in import_script
    module = import_module(mod)
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\scripts\gui.py", line 11, in <module>
    from lib.gui import CurrentSession, CommandNotebook, Config, ConsoleOut
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\gui\__init__.py", line 2, in <module>
    from lib.gui.display import DisplayNotebook
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\gui\display.py", line 10, in <module>
    from .display_analysis import Analysis
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\gui\display_analysis.py", line 8, in <module>
    from .display_graph import SessionGraph
  File "C:\Users\kwg20\Desktop\test\pythondf\pythondf\python-3.6.3.amd64\faceswap-gui-v3.0\lib\gui\display_graph.py", line 14, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
ImportError: cannot import name 'NavigationToolbar2Tk'

why is this happening?

**Comment by torzdf** [comment]
@scarecrow2415 what version of matplotlib are you using? Try re-installing the latest version of matplotlib. I'll bump the version requirements.

**Comment by torzdf** [comment]
Updated with latest Original 128 mode from @andenixa 
tools.py bug fixed (should execute now)
ffmpeg potentially fixed (needs testing)

Some reworking of the code done, so please report any new bugs.

Thanks

**Comment by torzdf** [comment]
Please keep model 128 talk to issue #385, thanks

**Comment by torzdf** [comment]
Latest commit:
Fix issue with graphing when commencing training (@LordOEQJen )
Bump matplotlib version to hopefully fixes with the navigation toolbar
Fix Progress bar for sort/tools

**Comment by torzdf** [comment]
@linkoid What screen resolution are you running? Have you any strange DPI settings? I've just fired it up in windows 10 and it displays fine for me. Could you provide a screengrab?

Thanks

**Comment by koest** [comment]
So excited about the GUI V3.0.0.a. I tried it but the effmpeg didn't work when I clicked the output folder
https://s1.ax1x.com/2018/06/18/CxDO5n.png

I input manually and clicked the effmepg, the windows closed. 

I tried Extract, train, and convert, it works fine. 
I used Windows7

May I ask if I could translate the GUI language?

**Comment by torzdf** [comment]
@AbysmalBiscuit is working on the effmpeg code at the moment.

Please feel free to raise a PR for multilanguage support. If you need any pointers you can ask in discord

**Comment by koest** [comment]
@torzdf Thank you!

**Comment by torzdf** [comment]
beta now merged to master.
