### ISSUE TITLE
Cannot extract video to image use by GUI v3.0

### ISSUE THREAD

**Issue by g0147** [deepfakes/faceswap#445]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "E:\Faceswap\faceswap-master\lib\gui\wrapper.py", line 62, in action_command
    self.task.terminate()
  File "E:\Faceswap\faceswap-master\lib\gui\wrapper.py", line 275, in terminate
    pgid = os.getpgid(self.process.pid)
AttributeError: module 'os' has no attribute 'getpgid'

 Module missing or ?

**Comment by torzdf** [comment]
OS Version:
command generated:
pip-freeze:

**Comment by torzdf** [comment]
@AbysmalBiscuit

**Comment by torzdf** [comment]
This should *finally* be fixed.
