### ISSUE TITLE
originalhighres didn't work

### ISSUE THREAD

**Issue by eziohonor** [deepfakes/faceswap#450]
C:\Users\admin>cd /d c:\faceswap && python faceswap.py train -A D:\faceswap\DataA\model1\extracted -B D:\faceswap\DataB\idol1\extracted -m d:\faceswap\model  -p -pl -bs 128 -t OriginalHighRes
Using TensorFlow backend.
Model A Directory: D:\faceswap\DataA\model1\extracted
Model B Directory: D:\faceswap\DataB\idol1\extracted
Training data directory: d:\faceswap\model
Loading data, this may take a while...
Using live preview.
Press 'ENTER' on the preview window to save and quit.
Press 'S' on the preview window to save model weights immediately
Loading Model from Model_OriginalHighRes plugin...
Error loading training info: No such file or directory
Failed loading training data: None
Loading Trainer from Model_OriginalHighRes plugin...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\faceswap\scripts\train.py", line 97, in process_thread
    raise err
  File "c:\faceswap\scripts\train.py", line 89, in process_thread
    self.run_training_cycle(model, trainer)
  File "c:\faceswap\scripts\train.py", line 124, in run_training_cycle
    trainer.train_one_step(iteration, viewer)
  File "c:\faceswap\plugins\Model_OriginalHighRes\Trainer.py", line 38, in train_one_step
    loss_A = self.model.autoencoder_A.train_on_batch(warped_A, target_A)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py", line 1220, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\keras\backend\tensorflow_backend.py", line 2661, in __call__
    return self._call(inputs)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\keras\backend\tensorflow_backend.py", line 2631, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1454, in __call__
    self._session._session, self._handle, args, status, None)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[128,512,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: model_2/conv2d_6/convolution = Conv2D[T=DT_FLOAT, _class=["loc:@train...kpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_2/conv2d_6/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_6/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: loss/mul/_361 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1729_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: cd /d c:\faceswap && python faceswap.py train -A D:\faceswap\DataA\model1\extracted -B D:\faceswap\DataB\idol1\extracted -m d:\faceswap\model  –p -pl -bs 128 -t OriginalHighRes
- **Operating system and version:** Windows 10
- **Python version:3.6.4
- **Faceswap version:** the lastest one
- **Faceswap method:** GPU

**Comment by torzdf** [comment]
What gfx card are you using?

Either way, I think you'd need to significantly lower your batch size,

**Comment by eziohonor** [comment]
@torzdf  it's gtx 1080.Well,I think it's enough to run batch size128

**Comment by torzdf** [comment]
OriginalHiRes uses a lot of VRAM even on a 1080. It is highly unlikely it would run at batch size 128 (although @andenixa  could clarify). Reduce the batchsize down and you should be able to get it to run.

**Comment by oracle9i88** [comment]
1060 does not  work, 1070 is ok

**Comment by eziohonor** [comment]
@andenixa  it worked!! Appreciated!!
