### ISSUE TITLE
Issue with sort on GUI

### ISSUE THREAD

**Issue by luiscosio** [deepfakes/faceswap#459]
## Expected behavior

The sort tool  should sort images

## Actual behavior

The verbose parameter is missing in the sort tool GUI.

```
Loading...
Please backup your data and/or test the tool you want to use with a smaller data set to make sure you understand how it works.
Using TensorFlow backend.
Sorting by histogram similarity...

Loading:   0%|          | 0/9046 [00:00<?, ?it/s]

Sorting:   0%|          | 0/9045 [00:00<?, ?it/s]
Preparing to group...
Traceback (most recent call last):

Reloading:   0%|          | 0/9046 [00:00<?, ?it/s]File "D:\Projects\faceswap\faceswap\tools.py", line 40, in <module>

ARGUMENTS.func(ARGUMENTS)
File "D:\Projects\faceswap\faceswap\lib\cli.py", line 81, in execute_script
process.process()
File "D:\Projects\faceswap\faceswap\tools\sort.py", line 72, in process
self.sort_process()
File "D:\Projects\faceswap\faceswap\tools\sort.py", line 88, in sort_process
img_list = self.reload_images(group_method, img_list)
File "D:\Projects\faceswap\faceswap\tools\sort.py", line 639, in reload_images
input_is_predetected_face=True).landmarks
TypeError: __init__() missing 1 required positional argument: 'verbose'
Process exited.

```
## Steps to reproduce

![image](https://user-images.githubusercontent.com/1666/42341364-7418f858-8058-11e8-8b8b-010f02d8c685.png)

## Other relevant information
Latest master version

**Comment by torzdf** [comment]
Try latest commit.
