### ISSUE TITLE
bug on convert:  'Model' object has no attribute 'IMAGE_SHAPE'

### ISSUE THREAD

**Issue by hyybuaa** [deepfakes/faceswap#463]
Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "/home/hyy/swap/faceswap-master/lib/cli.py", line 81, in execute_script
    process.process()
  File "/home/hyy/swap/faceswap-master/scripts/convert.py", line 42, in process
    model = self.load_model()
  File "/home/hyy/swap/faceswap-master/scripts/convert.py", line 74, in load_model
    self._image_shape = model.IMAGE_SHAPE
AttributeError: 'Model' object has no attribute 'IMAGE_SHAPE'

**Comment by torzdf** [comment]
Fixed: f90cd92ec36a0860c58a75631f762069419149de
