### ISSUE TITLE
AttributeError: module 'keras.engine' has no attribute 'base_layer' on staging

### ISSUE THREAD

**Issue by Tvde1** [deepfakes/faceswap#476]
**Note: Please only report bugs in this repository. Just because you are getting an error message does not automatically mean you have discovered a bug. If you don't have a lot of experience with this type of project, or if you need for setup help and other issues in using the faceswap tool, please refer to the [faceswap-playground](https://github.com/deepfakes/faceswap-playground/issues) instead. The faceswap-playground is also an excellent place to ask questions and submit feedback.**

I'm extracting with this:

```
python faceswap/faceswap.py extract -i ~/Drive/{video_folder} -o ~/Drive/{extracted_folder} \
  --alignments ~/Drive/{extracted_folder}/alignments.json \
  --serializer 'json' -D 'mtcnn' -mtms 10 -mtth 0.5 0.6 0.6 -mtsc 0.5 -l 0.6 -r 45 -v
```

## Expected behavior

I expect the extraction to begin.

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

I get this output:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "faceswap/faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "/content/faceswap/lib/cli.py", line 79, in execute_script
    script = self.import_script()
  File "/content/faceswap/lib/cli.py", line 28, in import_script
    module = import_module(mod)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/faceswap/scripts/extract.py", line 12, in <module>
    from scripts.fsmedia import Alignments, Faces, Images, Utils
  File "/content/faceswap/scripts/fsmedia.py", line 16, in <module>
    from lib.faces_detect import detect_faces, DetectedFace
  File "/content/faceswap/lib/faces_detect.py", line 4, in <module>
    from lib import face_alignment
  File "/content/faceswap/lib/face_alignment/__init__.py", line 1, in <module>
    from .extractor import Extract
  File "/content/faceswap/lib/face_alignment/extractor.py", line 12, in <module>
    from .model import KerasModel
  File "/content/faceswap/lib/face_alignment/model.py", line 13, in <module>
    class TorchBatchNorm2D(keras.engine.base_layer.Layer):
AttributeError: module 'keras.engine' has no attribute 'base_layer'
```

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

Uh just try it on `staging`

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Linux 
- **Python version:** 3.something
- **Faceswap version:** f41f3e99c164863ca7b957b704c0e2cc40245272
- **Faceswap method:** GPU
- **Other related issues:**
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by torzdf** [comment]
Upgrade Keras to 2.2.0
