### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by daipiaoxiang** [deepfakes/faceswap#534]
Initializing Face Alignment Network...
2018-11-13 18:17:11.114608: E tensorflow/core/common_runtime/executor.cc:630] Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC on device type CPU
         [[{{node fa/avg_pool}} = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](fa/Add_1)]]
Process SpawnProcess-3:
Traceback (most recent call last):
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
    return fn(*args)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingOp only supports NHWC on device type CPU
         [[{{node fa/avg_pool}} = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](fa/Add_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 60, in align
    super().align(*args, **kwargs)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\_base.py", line 70, in align
    self.initialize(*args, **kwargs)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 53, in initialize
    verbose=self.verbose, ratio=tf_ratio)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 213, in __init__
    self.session = self.set_session(ratio)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 238, in set_session
    session.run(self.output, feed_dict={self.input: placeholder})
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingOp only supports NHWC on device type CPU
         [[{{node fa/avg_pool}} = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](fa/Add_1)]]

Caused by op 'fa/avg_pool', defined at:
  File "<string>", line 1, in <module>
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 60, in align
    super().align(*args, **kwargs)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\_base.py", line 70, in align
    self.initialize(*args, **kwargs)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 53, in initialize
    verbose=self.verbose, ratio=tf_ratio)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 210, in __init__
    self.graph = self.load_graph()
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 226, in load_graph
    tf.import_graph_def(graph_def, name="fa")
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3438, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3438, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3297, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Default AvgPoolingOp only supports NHWC on device type CPU
         [[{{node fa/avg_pool}} = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](fa/Add_1)]]

Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\lib\cli.py", line 81, in execute_script
    process.process()
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\scripts\extract.py", line 47, in process
    self.run_extraction(save_thread)
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\scripts\extract.py", line 113, in run_extraction
    self.plugins.launch_aligner()
  File "C:\Users\10580\Desktop\workspasce\faceswap-master\scripts\extract.py", line 303, in launch_aligner
    raise ValueError("Error inititalizing Aligner")
ValueError: Error inititalizing Aligner

**Comment by torzdf** [comment]
You either don't have a GPU or you are using the CPU version of tensorflow.

Either way FAN does not currently support CPU, so either use dlib aligner or install tensorflow-gpu.

**Comment by cwcwcw721** [comment]
> Initializing Face Alignment Network...
> 2018-11-13 18:17:11.114608: E tensorflow/core/common_runtime/executor.cc:630] Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC on device type CPU
> [[{{node fa/avg_pool}} = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](fa/Add_1)]]
> Process SpawnProcess-3:
> Traceback (most recent call last):
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
> return fn(*args)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
> options, feed_dict, fetch_list, target_list, run_metadata)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingOp only supports NHWC on device type CPU
> [[{{node fa/avg_pool}} = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](fa/Add_1)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
> self.run()
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
> self._target(*self._args, **self._kwargs)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 60, in align
> super().align(*args, **kwargs)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align_base.py", line 70, in align
> self.initialize(*args, **kwargs)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 53, in initialize
> verbose=self.verbose, ratio=tf_ratio)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 213, in **init**
> self.session = self.set_session(ratio)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 238, in set_session
> session.run(self.output, feed_dict={self.input: placeholder})
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
> run_metadata_ptr)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
> feed_dict_tensor, options, run_metadata)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
> run_metadata)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingOp only supports NHWC on device type CPU
> [[{{node fa/avg_pool}} = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](fa/Add_1)]]
> 
> Caused by op 'fa/avg_pool', defined at:
> File "", line 1, in 
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
> exitcode = _main(fd)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 118, in _main
> return self._bootstrap()
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
> self.run()
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
> self._target(*self._args, **self._kwargs)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 60, in align
> super().align(*args, **kwargs)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align_base.py", line 70, in align
> self.initialize(*args, **kwargs)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 53, in initialize
> verbose=self.verbose, ratio=tf_ratio)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 210, in **init**
> self.graph = self.load_graph()
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\plugins\extract\align\fan.py", line 226, in load_graph
> tf.import_graph_def(graph_def, name="fa")
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
> return func(*args, **kwargs)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\importer.py", line 442, in import_graph_def
> _ProcessNewOps(graph)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\importer.py", line 234, in _ProcessNewOps
> for new_op in graph._add_new_tf_operations(compute_devices=False): # pylint: disable=protected-access
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3438, in _add_new_tf_operations
> for c_op in c_api_util.new_tf_operations(self)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3438, in 
> for c_op in c_api_util.new_tf_operations(self)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3297, in _create_op_from_tf_operation
> ret = Operation(c_op, self)
> File "C:\Users\10580\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in **init**
> self._traceback = tf_stack.extract_stack()
> 
> InvalidArgumentError (see above for traceback): Default AvgPoolingOp only supports NHWC on device type CPU
> [[{{node fa/avg_pool}} = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](fa/Add_1)]]
> 
> Traceback (most recent call last):
> File "faceswap.py", line 36, in 
> ARGUMENTS.func(ARGUMENTS)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\lib\cli.py", line 81, in execute_script
> process.process()
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\scripts\extract.py", line 47, in process
> self.run_extraction(save_thread)
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\scripts\extract.py", line 113, in run_extraction
> self.plugins.launch_aligner()
> File "C:\Users\10580\Desktop\workspasce\faceswap-master\scripts\extract.py", line 303, in launch_aligner
> raise ValueError("Error inititalizing Aligner")
> ValueError: Error inititalizing Aligner

hello~I also encountered the same problem, how can I deal with this problem?
I try to work it on GTX 550Ti 
thanks

**Comment by cwcwcw721** [comment]
> You either don't have a GPU or you are using the CPU version of tensorflow.
> 
> Either way FAN does not currently support CPU, so either use dlib aligner or install tensorflow-gpu.

I installed tensorflow-gpu-1.12.0 already。there is the same problem

**Comment by torzdf** [comment]
Please checkout the staging branch, try again and if it fails post your crash report.

Thanks

**Comment by cwcwcw721** [comment]
> Please checkout the staging branch, try again and if it fails post your crash report.
> 
> Thanks
I checkout staging branch ,this is my crash report.
[crash_report.2018.12.10.110119210247.log](https://github.com/deepfakes/faceswap/files/2661434/crash_report.2018.12.10.110119210247.log)

**Comment by cwcwcw721** [comment]
Loading...
12/10/2018 10:52:49 INFO     Log level set to: INFO
12/10/2018 10:52:51 INFO     Output Directory: G:\AI\A\faceA
12/10/2018 10:52:51 INFO     Input Directory: G:\AI\A\OutA
12/10/2018 10:52:51 INFO     Loading Detect from Mtcnn plugin...
12/10/2018 10:52:51 INFO     Loading Align from Fan plugin...
12/10/2018 10:52:51 INFO     NB: Parallel processing disabled.You may get faster extraction speeds by enabling it with the -mp switch
12/10/2018 10:52:51 INFO     Starting, this may take a while...
12/10/2018 10:52:51 INFO     Initializing MTCNN Detector...
12/10/2018 10:52:53 WARNING  Using CPU


2018-12-10 10:52:52.618271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 550 Ti major: 2 minor: 1 memoryClockRate(GHz): 1.82
pciBusID: 0000:01:00.0
totalMemory: 1.00GiB freeMemory: 866.89MiB
2018-12-10 10:52:52.618271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1482] Ignoring visible gpu device (device: 0, name: GeForce GTX 550 Ti, pci bus id: 0000:01:00.0, compute capability: 2.1) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.7.
2018-12-10 10:52:52.618271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-10 10:52:52.618271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-12-10 10:52:52.618271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
12/10/2018 10:56:19 INFO     Initializing Face Alignment Network...
12/10/2018 10:56:26 ERROR    Caught exception in child process: 5160
2018-12-10 10:56:22.021249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 550 Ti major: 2 minor: 1 memoryClockRate(GHz): 1.82
pciBusID: 0000:01:00.0
totalMemory: 1.00GiB freeMemory: 866.89MiB
2018-12-10 10:56:22.021249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1482] Ignoring visible gpu device (device: 0, name: GeForce GTX 550 Ti, pci bus id: 0000:01:00.0, compute capability: 2.1) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.7.
2018-12-10 10:56:22.021249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-10 10:56:22.021249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-12-10 10:56:22.021249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-12-10 10:56:26.428501: E tensorflow/core/common_runtime/executor.cc:623] Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC on device type CPU
[[{{node fa/avg_pool}} = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](fa/Add_1)]]
12/10/2018 11:01:19 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "G:\AI\faceswap-staging\lib\cli.py", line 90, in execute_script
process.process()
File "G:\AI\faceswap-staging\scripts\extract.py", line 51, in process
self.run_extraction(save_thread)
File "G:\AI\faceswap-staging\scripts\extract.py", line 150, in run_extraction
self.plugins.launch_aligner()
File "G:\AI\faceswap-staging\scripts\extract.py", line 348, in launch_aligner
raise ValueError("Error initializing Aligner")
ValueError: Error initializing Aligner
12/10/2018 11:01:19 CRITICAL An unexpected crash has occurred. Crash report written to G:\AI\faceswap-staging\crash_report.2018.12.10.110119210247.log. Please verify you are running the latest version of faceswap before reporting
Process exited.

**Comment by torzdf** [comment]
This is not the crash report.

This is the crash report:

> 12/10/2018 11:01:19 CRITICAL An unexpected crash has occurred. Crash report written to G:\AI\faceswap-staging\crash_report.2018.12.10.110119210247.log

**Comment by cwcwcw721** [comment]
> This is not the crash report.
> 
> This is the crash report:
> 
> > 12/10/2018 11:01:19 CRITICAL An unexpected crash has occurred. Crash report written to G:\AI\faceswap-staging\crash_report.2018.12.10.110119210247.log

The log file is in the attachment above。
[crash_report.2018.12.10.110119210247.log](https://github.com/deepfakes/faceswap/files/2662776/crash_report.2018.12.10.110119210247.log)

**Comment by torzdf** [comment]
Sorry dude. Missed that. Will check

**Comment by cwcwcw721** [comment]
> Sorry dude. Missed that. Will check

thank you so much！

**Comment by torzdf** [comment]
Firstly, I'm afraid it's highly unlikely you will be able to run FS with your gfx card. You really need a minimum of 2GB VRAM for it to work. You can try, but I'm afraid it's unsupported.

As for the above issue, You have both the CPU and GPU versions of Tensorflow installed:
```
tensorflow==1.12.0
tensorflow-gpu==1.12.0
```
 Remove the CPU version:
```pip uninstall tensorflow```

or (as may be more relevant in your case) remove the GPU version and use a different extractor:
```pip uninstall tensorflow-gpu```

**Comment by cwcwcw721** [comment]
> Firstly, I'm afraid it's highly unlikely you will be able to run FS with your gfx card. You really need a minimum of 2GB VRAM for it to work. You can try, but I'm afraid it's unsupported.
> 
> As for the above issue, You have both the CPU and GPU versions of Tensorflow installed:
> 
> ```
> tensorflow==1.12.0
> tensorflow-gpu==1.12.0
> ```
> Remove the CPU version:
> `pip uninstall tensorflow`
> 
> or (as may be more relevant in your case) remove the GPU version and use a different detector/aligner:
> `pip uninstall tensorflow-gpu`

Thanks dude, I try to run FS with another PC, gfx 1050.， use detector with dlib-cnn, and
Aligner with dlib,  It works well,thanks.

**Comment by jlllweco** [comment]
`pip install tensorflow-gpu`
then try it.
