### ISSUE TITLE
Get error in extract (mtcnn) after upgrade display card.

### ISSUE THREAD

**Issue by g0147** [deepfakes/faceswap#535]
After upgrade to RTX 2070, I get following error in extract (mtcnn)
The Others (dlib) work.

2018-11-14 01:15:51.906117: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_blas.cc:636] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED0%|          | 0/1682 [00:00<?, ?it/s]

2018-11-14 01:15:52.020361: F C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_util.cc:343] CPU->GPU Memcpy failed
Process exited.

Command: python E:\Faceswap\faceswap-master\faceswap.py extract -i E:\InputA -o E:\alignA --serializer json -D mtcnn -mtms 20 -mtth 0.6 0.7 0.7 -mtsc 0.709 -l 0.6

**Comment by g0147** [comment]
> Looking at your cli it looks like you are running an older version of FS, so you can update and see if that fixes it.
> 
> Unfortunately I do not have a next gen Nvidia card to test on, so if there are still issues, most likely someone else will have to raise a PR to fix this.

what is FS?

**Comment by gessyoo** [comment]
g0147, FS = this repro.  Upgrade to the latest version, if you have not done so already, and try again.  PS = Pull Request: suggested code changes by a python coder who has an RTX card to troubleshoot the problem.

**Comment by g0147** [comment]
But this is work when use  GTX 1060 before , the error is flow when only after replace the display card. 

Howeven, after i update FS, it flow another error when extract:

**mtcnn**
2018-11-15 00:23:54.764227: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-11-15 00:23:55.344866: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.74
pciBusID: 0000:09:00.0
totalMemory: 8.00GiB freeMemory: 6.57GiB
2018-11-15 00:23:55.345506: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce RTX 2070, pci bus id: 0000:09:00.0, compute capability: 7.5)
Initializing MTCNN Detector...Process SpawnProcess-3:

Traceback (most recent call last):
File "C:\Users\Mark\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
self.run()
File "C:\Users\Mark\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "E:\Faceswap\faceswap-master(5)\plugins\extract\detect\mtcnn.py", line 100, in detect_faces
super().detect_faces(*args, **kwargs)
File "E:\Faceswap\faceswap-master(5)\plugins\extract\detect\_base.py", line 81, in detect_faces
self.initialize(*args, **kwargs)
File "E:\Faceswap\faceswap-master(5)\plugins\extract\detect\mtcnn.py", line 73, in initialize
alloc = int(sess.run(tf.contrib.memory_stats.BytesLimit()) /
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\contrib\memory_stats\python\ops\memory_stats_ops.py", line 36, in BytesLimit
return gen_memory_stats_ops.bytes_limit()
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\contrib\memory_stats\ops\gen_memory_stats_ops.py", line 64, in bytes_limit
"BytesLimit", name=name)
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
op_def=op_def)
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\python\framework\ops.py", line 3162, in create_op
compute_device=compute_device)
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\python\framework\ops.py", line 3208, in _create_op_helper
set_shapes_for_outputs(op)
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\python\framework\ops.py", line 2427, in set_shapes_for_outputs
return _set_shapes_for_outputs(op)
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\python\framework\ops.py", line 2400, in _set_shapes_for_outputs
shapes = shape_func(op)
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\python\framework\ops.py", line 2330, in call_with_requiring
return call_cpp_shape_fn(op, require_shape_fn=True)
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
require_shape_fn)
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
input_tensors_as_shapes, status)
File "E:\Faceswap\faceswap-master(5)\env\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'BytesLimit' in binary running on DESKTOP-HELDK0A. Make sure the Op and Kernel are registered in the binary running in this process.

Command : E:\Faceswap\faceswap-master(5)\env\Scripts\python.exe E:\Faceswap\faceswap-master(5)\faceswap.py extract -i E:\InputA -o E:\alignA -l 0.6 -v --serializer json -D mtcnn -A dlib -mtms 20 -mtth 0.6 0.7 0.7 -mtsc 0.709 -sz 256 -ae

**Comment by gessyoo** [comment]
This repro (and DeepFaceLab) were written for CUDA 9 and the GTX series 10 cards.  Nvidia apparently made some hardware changes in the RTX series that require changes in the current extract code.  But the error can't be fixed easily without a developer having an RTX series card to work with.

**Comment by torzdf** [comment]
Get the latest tensorflow and try again.

**Comment by torzdf** [comment]
This is a Windows/Anaconda bug I'm looking at soon. In the meantime you can still use mtcnn if you remove the `-mp` flag
