### ISSUE TITLE
Error loading training info: No such file or directory

### ISSUE THREAD

**Issue by jmike1211** [deepfakes/faceswap#538]
# Operating system and version:ubuntu 18.04

# command
"""
python3.6 faceswap.py train -A ~/faceswap/zi/ -B ~/faceswap/zi/ -m ~/faceswap/models/
"""
# error message
Using TensorFlow backend.
Model A Directory: /home/administrator/faceswap/zi
Model B Directory: /home/administrator/faceswap/zi
Training data directory: /home/administrator/faceswap/models
Loading data, this may take a while...
Starting. Press 'ENTER' to stop training and save model
Loading Model from Model_Original plugin...
Error loading training info: No such file or directory
Failed loading existing training data.
Unable to open file (unable to open file: name = '/home/administrator/faceswap/models/encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Loading Trainer from Model_Original plugin...
^CExit requested! The trainer will complete its current cycle, save the models and quit (it can take up a couple of seconds depending on your training speed). If you want to kill it now, press Ctrl + c
^CTraceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "/home/administrator/faceswap/lib/cli.py", line 81, in execute_script
    process.process()
  File "/home/administrator/faceswap/scripts/train.py", line 46, in process
    self.end_thread(thread)
  File "/home/administrator/faceswap/scripts/train.py", line 79, in end_thread
    thread.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
2018-11-30 08:41:32.336487: E tensorflow/core/common_runtime/direct_session.cc:154] Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: driver shutting down

**Comment by Tvde1** [comment]
Did you expect that it would find the file? Have you trained before? If not, then of course it cannot be found and it will create a blank model.

**Comment by jmike1211** [comment]
this is train process for two file thanks

**Comment by Tvde1** [comment]
Have you already trained? If not, you can ignore the error.

**Comment by jmike1211** [comment]
thanks ,i will try it again
