### ISSUE TITLE
EFFmpeg doesn't work

### ISSUE THREAD

**Issue by tomventa** [deepfakes/faceswap#560]
[faceswap.log](https://github.com/deepfakes/faceswap/files/2705199/faceswap.log)
[faceswap_gui.log](https://github.com/deepfakes/faceswap/files/2705200/faceswap_gui.log)

```
12/22/2018 13:50:26 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: VERBOSE
12/22/2018 13:50:26 MainProcess     MainThread      cli             execute_script            DEBUG    Executing: effmpeg. PID: 8364
Traceback (most recent call last):
  File "C:\Users\tomma\Miniconda3\lib\site-packages\ffmpy.py", line 95, in run
    stderr=stderr
  File "C:\Users\tomma\Miniconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\tomma\Miniconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\faceswap-master\lib\cli.py", line 90, in execute_script
    process.process()
  File "D:\faceswap-master\tools\effmpeg.py", line 161, in process
    self.input = DataItem(path=self.args.input)
  File "D:\faceswap-master\tools\effmpeg.py", line 54, in __init__
    self.set_fps()
  File "D:\faceswap-master\tools\effmpeg.py", line 108, in set_fps
    self.fps = Effmpeg.get_fps(self.path)
  File "D:\faceswap-master\tools\effmpeg.py", line 332, in get_fps
    _fps = ff.run(stdout=subprocess.PIPE)[0].decode("utf-8")
  File "C:\Users\tomma\Miniconda3\lib\site-packages\ffmpy.py", line 99, in run
    raise FFExecutableNotFoundError("Executable '{0}' not found".format(self.executable))
ffmpy.FFExecutableNotFoundError: Executable 'ffprobe' not found

============ System Information ============
git_branch:        Not Found
git_commits:       Not Found
gpu_cuda:          10.0 9.0
gpu_cudnn:         7.4.2
gpu_devices:       GPU_0: GeForce GTX 1070
gpu_driver:        417.35
gpu_vram:          GPU_0: 8192MB
os_machine:        AMD64
os_platform:       Windows-10-10.0.17134-SP0
os_release:        10
py_command:        D:\faceswap-master\tools.py effmpeg -L VERBOSE -a get-fps -i D:/faceswap-master/dataset/a.mp4 -o D:/faceswap-master/dataset/temp_a -r D:/faceswap-master/dataset/a.mp4 -fps 1 -ef .png -s 00:00:00 -e 00:00:00 -d 00:00:00 -tr (0, 90CounterClockwise&VerticalFlip) -sc 1920x1080 -v
py_conda_version:  conda 4.5.12
py_implementation: CPython
py_version:        3.6.4
py_virtual_env:    False
sys_cores:         6
sys_processor:     Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
sys_ram:           Total: 16322MB, Available: 8962MB, Used: 7359MB, Free: 8962MB

=============== Pip Packages ===============
asn1crypto==0.24.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
cloudpickle==0.6.1
cmake==3.13.2.post1
conda==4.5.12
cryptography==2.4.2
cycler==0.10.0
dask==1.0.0
decorator==4.3.0
dlib==19.8.1
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
ffprobe==0.5
h5py==2.8.0
idna==2.8
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
matplotlib==2.2.2
menuinst==1.4.14
mkl-fft==1.0.6
mkl-random==1.0.2
networkx==2.2
numpy==1.15.4
nvidia-ml-py3==7.352.0
opencv-python==3.4.4.19
pathlib==1.0.1
Pillow==5.3.0
psutil==5.4.8
pycosat==0.6.3
pycparser==2.19
pyOpenSSL==18.0.0
pyparsing==2.3.0
PySocks==1.6.8
python-dateutil==2.7.5
pytz==2018.7
PyWavelets==1.0.1
pywin32==223
PyYAML==3.13
requests==2.21.0
ruamel-yaml==0.15.46
scandir==1.7
scikit-image==0.14.1
scikit-learn==0.20.2
scipy==1.2.0
six==1.12.0
toolz==0.9.0
tqdm==4.28.1
urllib3==1.24.1
win-inet-pton==1.0.1
wincertstore==0.2

============== Conda Packages ==============
# packages in environment at C:\Users\tomma\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0  
blas                      1.0                         mkl  
ca-certificates           2018.03.07                    0  
certifi                   2018.11.29               py36_0  
cffi                      1.11.5           py36h74b6da3_1  
chardet                   3.0.4                    py36_1  
Click                     7.0                       <pip>
cloudpickle               0.6.1                     <pip>
cmake                     3.13.2.post1              <pip>
conda                     4.5.12                   py36_0  
conda-env                 2.6.0                         1  
console_shortcut          0.1.1                         3  
cryptography              2.4.2            py36h7a1dbc1_0  
cycler                    0.10.0                    <pip>
dask                      1.0.0                     <pip>
decorator                 4.3.0                     <pip>
dlib                      19.8.1                    <pip>
face-recognition          1.2.3                     <pip>
face-recognition-models   0.3.0                     <pip>
ffmpy                     0.2.2                     <pip>
ffprobe                   0.5                       <pip>
h5py                      2.8.0                     <pip>
hdf5                      1.8.20               hac2f561_1  
icc_rt                    2019.0.0             h0cc432a_1  
idna                      2.8                      py36_0  
intel-openmp              2019.1                      144  
jpeg                      9b                   hb83a4c4_2  
Keras                     2.2.4                     <pip>
Keras-Applications        1.0.6                     <pip>
Keras-Preprocessing       1.0.5                     <pip>
kiwisolver                1.0.1                     <pip>
libopencv                 3.4.2                h20b85fd_0  
libpng                    1.6.35               h2a8f88b_0  
libtiff                   4.0.9                h36446d0_2  
matplotlib                2.2.2                     <pip>
menuinst                  1.4.14           py36hfa6e2cd_0  
mkl                       2019.1                      144  
mkl_fft                   1.0.6            py36h6288b17_0  
mkl_random                1.0.2            py36h343c172_0  
networkx                  2.2                       <pip>
numpy                     1.15.4                    <pip>
numpy                     1.15.4           py36h19fb1c0_0  
numpy-base                1.15.4           py36hc3f5095_0  
nvidia-ml-py3             7.352.0                   <pip>
opencv                    3.4.2            py36h40b0b35_0  
opencv-python             3.4.4.19                  <pip>
openssl                   1.1.1a               he774522_0  
pathlib                   1.0.1                     <pip>
Pillow                    5.3.0                     <pip>
pip                       18.1                     py36_0  
pip                       18.1                      <pip>
psutil                    5.4.8                     <pip>
py-opencv                 3.4.2            py36hc319ecb_0  
pycosat                   0.6.3            py36hfa6e2cd_0  
pycparser                 2.19                     py36_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.3.0                     <pip>
pysocks                   1.6.8                    py36_0  
python                    3.6.4                h0c2934d_3  
python-dateutil           2.7.5                     <pip>
pytz                      2018.7                    <pip>
PyWavelets                1.0.1                     <pip>
pywin32                   223              py36hfa6e2cd_1  
PyYAML                    3.13                      <pip>
requests                  2.21.0                   py36_0  
ruamel_yaml               0.15.46          py36hfa6e2cd_0  
scandir                   1.7                       <pip>
scikit-image              0.14.1                    <pip>
scikit-learn              0.20.2                    <pip>
scipy                     1.2.0                     <pip>
setuptools                40.6.3                   py36_0  
six                       1.12.0                   py36_0  
toolz                     0.9.0                     <pip>
tqdm                      4.28.1                    <pip>
urllib3                   1.24.1                   py36_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_0  
wheel                     0.32.3                   py36_0  
win_inet_pton             1.0.1                    py36_1  
wincertstore              0.2              py36h7fe50ca_0  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3 
```
-------------------------------
OS: WIndows 10 Pro 64bit
CPU: i5 8600
RAM: 16gb ddr4 2666
GPU: gtx 1070 
-------------------------------

**Comment by tomventa** [comment]
How to fix:

**Comment by torzdf** [comment]
Alternatively (And easier)

From inside your environment enter:
```conda install -c conda-forge ffmpeg```

I have added automatic install to setup.py for future installs.
