### ISSUE TITLE
Extract doesn't work

### ISSUE THREAD

**Issue by tomventa** [deepfakes/faceswap#561]
```
12/22/2018 22:19:38 INFO     Log level set to: INFO
12/22/2018 22:19:40 INFO     Output Directory: D:\faceswap-master\dataset\a
12/22/2018 22:19:40 INFO     Input Directory: D:\faceswap-master\dataset\temp_a
12/22/2018 22:19:40 INFO     Loading Detect from Mtcnn plugin...
12/22/2018 22:19:40 INFO     Loading Align from Fan plugin...
12/22/2018 22:19:40 INFO     NB: Parallel processing disabled.You may get faster extraction speeds by enabling it with the -mp switch
12/22/2018 22:19:40 INFO     Starting, this may take a while...
12/22/2018 22:19:40 INFO     Initializing MTCNN Detector...
12/22/2018 22:19:40 ERROR    Caught exception in child process: 12560
Traceback (most recent call last):
  File "D:\faceswap-master\lib\cli.py", line 90, in execute_script
    process.process()
  File "D:\faceswap-master\scripts\extract.py", line 49, in process
    self.run_extraction()
  File "D:\faceswap-master\scripts\extract.py", line 143, in run_extraction
    self.run_detection(to_process)
  File "D:\faceswap-master\scripts\extract.py", line 194, in run_detection
    self.plugins.launch_detector()
  File "D:\faceswap-master\scripts\extract.py", line 375, in launch_detector
    event.wait(60)
  File "C:\Users\tomma\Miniconda3\lib\multiprocessing\synchronize.py", line 361, in wait
    self._cond.wait(timeout)
  File "C:\Users\tomma\Miniconda3\lib\multiprocessing\synchronize.py", line 262, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\faceswap-master\faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "D:\faceswap-master\lib\cli.py", line 103, in execute_script
    safe_shutdown()
  File "D:\faceswap-master\lib\utils.py", line 303, in safe_shutdown
    queue_manager.terminate_queues()
  File "D:\faceswap-master\lib\queue_manager.py", line 76, in terminate_queues
    queue.get(True, 1)
  File "<string>", line 2, in get
  File "C:\Users\tomma\Miniconda3\lib\multiprocessing\managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "C:\Users\tomma\Miniconda3\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\tomma\Miniconda3\lib\multiprocessing\connection.py", line 306, in _recv_bytes
    [ov.event], False, INFINITE)
KeyboardInterrupt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\tomma\Miniconda3\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Pipe terminata

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tomma\Miniconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\tomma\Miniconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tomma\Miniconda3\lib\logging\handlers.py", line 1476, in _monitor
    record = self.dequeue(True)
  File "C:\Users\tomma\Miniconda3\lib\logging\handlers.py", line 1425, in dequeue
    return self.queue.get(block)
  File "<string>", line 2, in get
  File "C:\Users\tomma\Miniconda3\lib\multiprocessing\managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "C:\Users\tomma\Miniconda3\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\tomma\Miniconda3\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
```

CPU: i5 8600
RAM: 16GB ddr4 2666
GPU: gtx 1070
HDD: 1tb + intel optane + ssd samsung evo 860 250gb

**Comment by torzdf** [comment]
Please provide the crash report file.

Also your output says:
"Keyboard interrupt" which suggests you terminated the process

**Comment by torzdf** [comment]
I think this was fixed in Discord. Re-open if not.

**Comment by Pluckypan** [comment]
same error:
12/23/2018 16:41:06 INFO     Loading Detect from Mtcnn plugin...
12/23/2018 16:41:06 INFO     Loading Align from Fan plugin...
12/23/2018 16:41:06 WARNING  No GPU detected. Switching to CPU mode
12/23/2018 16:41:06 INFO     Starting, this may take a while...
12/23/2018 16:41:06 INFO     Initializing Face Alignment Network...
12/23/2018 16:41:06 WARNING  No GPU detected. Switching to CPU mode
12/23/2018 16:41:06 ERROR    Caught exception in child process: 68177
12/23/2018 16:41:07 INFO     Initializing MTCNN Detector...
12/23/2018 16:41:07 ERROR    Caught exception in child process: 68181
12/23/2018 16:42:06 INFO     Waiting for Detector... Time out in 4 minutes
12/23/2018 16:43:06 INFO     Waiting for Detector... Time out in 3 minutes
12/23/2018 16:44:06 INFO     Waiting for Detector... Time out in 2 minutes
12/23/2018 16:45:06 INFO     Waiting for Detector... Time out in 1 minutes
