### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by Teckt** [deepfakes/faceswap#590]
In previous commits before the logging implementation, multiple GPUS were able to run different tasks simultaneously ( extract/train/convert ).

After the logging commit, only 1 task can be run due to the log file being in use by the first process.

Is there an option to disable logging or specify a log file instead?

**Comment by torzdf** [comment]
Unfortunately logging is not going anywhere, as it's integral to solving issues and development.
I can look at the possibility of specifying a logfile. What is the specific error that you receive?

**Comment by Teckt** [comment]
It would be great if a log file could be specified in the arguments. Here's the error output:

Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "C:\fs-new\lib\cli.py", line 85, in execute_script
    log_setup(arguments.loglevel, self.command)
  File "C:\fs-new\lib\logger.py", line 79, in log_setup
    f_handler = file_handler(numeric_loglevel, log_format, command)
  File "C:\fs-new\lib\logger.py", line 97, in file_handler
    log_file.doRollover()
  File "C:\Users\Cool\AppData\Local\Programs\Python\Python36\lib\logging\handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Users\Cool\AppData\Local\Programs\Python\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\fs-new\\faceswap.log' -> 'C:\\fs-new\\faceswap.log.1
`

**Comment by torzdf** [comment]
Ok logfile has been added to latest Staging Branch. Can you test it works ok for you and report back, and I'll merge it to master.

```-LF --logfile```

**Comment by Teckt** [comment]
Thanks for the quick fix! It only works for training. Are you planning to make the changes to extract and convert as well?

**Comment by torzdf** [comment]
Hmmm, I thought I'd put it in as a global option. Will double check

**Comment by torzdf** [comment]
I just tested this on extract and it worked fine for me. Are you sure?

**Comment by Teckt** [comment]
Sorry, I just tested it again and it worked perfectly for all 3 processes. I forgot to change batch file to direct to the staging commit. Thank you for the update.
