### ISSUE TITLE
[FIXED] Memory Leak Bug on Extract

### ISSUE THREAD

**Issue by torzdf** [deepfakes/faceswap#594]
This issue is fixed.

There is a bug in numpy version 1.16.0. Downgrade numpy to 1.15.2 and your problems will disappear.

requirements.txt being edited.

____________________________________________________________________________

This is a bug that I have not been able to replicate but have seen reported in multiple places, so this is a call for information for anyone who receives an error similar to:
```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\faceswap\lib\multiprocessing\managers.py", line 228, in serve_client
    request = recv()
  File "D:\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "D:\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 318, in _recv_bytes
    return self._get_more_data(ov, maxsize)
  File "D:\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 344, in _get_more_data
    f.write(ov.getbuffer())
MemoryError
```
**NB: This is a system RAM issue, NOT a GPU VRAM issue**
Ideally, please post your crash log to this issue.

If you're feeling particularly brave, please checkout the memtest branch and run extract (without the -mp flag) there, and post the resulting faceswap.log file. Note that this is a slightly hacky test branch that outputs memory useage every 100 frames. It most likely will hang every 100 frames, but should complete.

Also please provide:
- OS
- The amount of System RAM you have
- CPU
- GPU
- Python version
- Conda version (if used)
- Cuda verision
- cuDNN version
- Tensorflow version

What we know:
- It only impacts Extract, but it does not matter which extractor you use
- The memory useage growth is linear and rapid
- Seen cases:
    - Windows 10 (Intel64 Family 6 Model 158 Stepping 9, GenuineIntel),  GTX 1080 Ti (417.71), Python 3.5.6, conda 4.5.12, Cuda 9.0, cuDNN  7.4.2, TF 1.12.0
    - Windows 10 (Intel64 Family 6 Model 85 Stepping 4, GenuineIntel), GTX 1080 Ti (417.35), Python 3.5.6,  conda 4.5.12, Cuda 9.0, cuDNN 7.2.1, TF 1.9.0 
    - Windows 10 (Intel64 Family 6 Model 158 Stepping 10, GenuineIntel), RTX 2080 Ti (417.71), Python 3.6.8, conda 4.5.12, Cuda 10.0, cuDNN 7.4.2, TF 1.12.0
    - Ubuntu 14.04, GTX 980M, Python 3.6.7, Cuda 8.0, cuDNN 5.1, TF 1.12.0
- Possible issues:
   - ~Scaling? (These issues seem to have only occured since scaling bugfix was implemented)~

ref: https://github.com/deepfakes/faceswap-playground/issues/238

**Comment by torzdf** [comment]
Crash Report:
```01/16/2019 22:49:22 MainProcess     MainThread      multithreading  start                     DEBUG    Spawning Process: (name: 'Detector.run', args: (), kwargs: {'event': <multiprocessing.synchronize.Event object at 0x00000163BB308A90>, 'log_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x163a9c7c978>, 'log_init': <function set_root_logger at 0x00000163A9B9D1E0>, 'out_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x163bb2e3860>, 'in_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x163bb2e3be0>}, daemon: True)
01/16/2019 22:49:22 MainProcess     MainThread      multithreading  start                     DEBUG    Spawned Process: (name: 'Detector.run', PID: 11260)
01/16/2019 22:49:22 MainProcess     MainThread      extract         launch_detector           DEBUG    Launched Detector
01/16/2019 22:49:22 MainProcess     MainThread      extract         detect_faces              DEBUG    Running Detection. Pass: 'align'
01/16/2019 22:49:22 Detector.run    MainThread      dlib_cnn        initialize                INFO     Initialized Dlib-CNN Detector...
01/16/2019 22:49:22 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'align'
01/16/2019 22:49:22 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'align'
01/16/2019 22:49:25 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 1.png
01/16/2019 22:49:25 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10.png
01/16/2019 22:49:38 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10148.png
01/16/2019 22:49:38 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10149.png
01/16/2019 22:49:38 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10150.png
01/16/2019 22:49:38 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10151.png
01/16/2019 22:49:39 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10152.png
01/16/2019 22:49:39 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10153.png
01/16/2019 22:49:39 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10154.png
01/16/2019 22:49:39 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10155.png
01/16/2019 22:49:39 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10156.png
01/16/2019 22:49:39 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10157.png
01/16/2019 22:49:39 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10158.png
01/16/2019 22:49:39 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10159.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10160.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10161.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10162.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10163.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10164.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10165.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10166.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10167.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10168.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10169.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10170.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10171.png
01/16/2019 22:49:40 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10172.png
01/16/2019 22:49:41 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10173.png
01/16/2019 22:49:41 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10174.png
01/16/2019 22:49:41 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10175.png
01/16/2019 22:49:41 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10176.png
01/16/2019 22:49:41 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10177.png
01/16/2019 22:49:41 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10178.png
01/16/2019 22:49:41 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 10179.png
01/16/2019 22:49:41 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 1018.png
01/16/2019 22:49:42 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 1019.png
01/16/2019 22:49:43 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 1020.png
01/16/2019 22:49:43 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 1021.png
01/16/2019 22:49:44 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 1022.png
01/16/2019 22:49:45 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 1023.png
01/16/2019 22:49:46 MainProcess     MainThread      extract         run_extraction            VERBOSE  No faces were detected in image: 1024.png
01/16/2019 22:50:07 Detector.run    MainThread      _base           run                       ERROR    Caught exception in child process: 11260
01/16/2019 22:50:07 Aligner.run     MainThread      _base           run                       ERROR    Caught exception in child process: 9320
Traceback (most recent call last):
  File "F:\PythonProject\faceswap\lib\cli.py", line 90, in execute_script
    process.process()
  File "F:\PythonProject\faceswap\scripts\extract.py", line 49, in process
    self.run_extraction()
  File "F:\PythonProject\faceswap\scripts\extract.py", line 149, in run_extraction
    desc="Extracting faces"):
  File "C:\Users\jsy20\AppData\Roaming\Python\Python35\site-packages\tqdm\_tqdm.py", line 1002, in __iter__
    for obj in iterable:
  File "F:\PythonProject\faceswap\scripts\extract.py", line 409, in detect_faces
    raise Exception(err)
Exception: Error in child process 9320. Traceback (most recent call last):
  File "F:\PythonProject\faceswap\plugins\extract\align\_base.py", line 90, in run
    self.align(*args, **kwargs)
  File "F:\PythonProject\faceswap\plugins\extract\align\dlib.py", line 44, in align
    self.finalize(item)
  File "F:\PythonProject\faceswap\plugins\extract\align\_base.py", line 113, in finalize
    self.queues["out"].put((output))
  File "<string>", line 2, in put
  File "D:\Anaconda3\envs\faceswap\lib\multiprocessing\managers.py", line 732, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Anaconda3\envs\faceswap\lib\multiprocessing\managers.py", line 228, in serve_client
    request = recv()
  File "D:\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "D:\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 318, in _recv_bytes
    return self._get_more_data(ov, maxsize)
  File "D:\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 344, in _get_more_data
    f.write(ov.getbuffer())
MemoryError
---------------------------------------------------------------------------


============ System Information ============
git_branch:        Not Found
git_commits:       Not Found
gpu_cuda:          9.0
gpu_cudnn:         7.4.2
gpu_devices:       GPU_0: GeForce GTX 1080 Ti
gpu_driver:        417.71
gpu_vram:          GPU_0: 11264MB
os_machine:        AMD64
os_platform:       Windows-10-10.0.17763-SP0
os_release:        10
py_command:        F:\PythonProject\faceswap\faceswap.py extract -i F:/testvideo/data_a/frame -o F:/testvideo/data_a/frame/face -l 0.99 --serializer json -D dlib-cnn -A dlib -mtms 50 -mtth 0.6 0.7 0.7 -mtsc 0.709 -sz 256 -L INFO
py_conda_version:  conda 4.5.12
py_implementation: CPython
py_version:        3.5.6
py_virtual_env:    False
sys_cores:         8
sys_processor:     Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
sys_ram:           Total: 16343MB, Available: 5105MB, Used: 11238MB, Free: 5105MB

=============== Pip Packages ===============
absl-py==0.7.0
astor==0.7.1
certifi==2018.8.24
Click==7.0
cloudpickle==0.6.1
cmake==3.13.3
cycler==0.10.0
dask==1.0.0
decorator==4.3.0
dlib==19.16.0
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.2
grpcio==1.18.0
h5py==2.8.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==2.2.2
networkx==2.2
numpy==1.16.0
nvidia-ml-py3==7.352.0
opencv-python==4.0.0.21
pathlib==1.0.1
Pillow==5.4.1
protobuf==3.6.1
psutil==5.4.8
pyparsing==2.3.1
python-dateutil==2.7.5
pytz==2018.9
PyWavelets==1.0.1
PyYAML==3.13
scandir==1.7
scikit-image==0.14.1
scikit-learn==0.20.2
scipy==1.2.0
six==1.12.0
tensorboard==1.12.2
tensorflow-gpu==1.12.0
termcolor==1.1.0
toolz==0.9.0
tqdm==4.29.1
Werkzeug==0.14.1
wincertstore==0.2

============== Conda Packages ==============
# packages in environment at D:\Anaconda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
certifi                   2018.8.24             py35_1001    conda-forge
ffmpeg                    4.1               h86867b3_1000    conda-forge
pip                       10.0.1                   py35_0    defaults
python                    3.5.6                he025d50_0    defaults
setuptools                40.2.0                   py35_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.31.1                   py35_0    defaults
wincertstore              0.2              py35hfebbdb8_0    defaults```

**Comment by torzdf** [comment]
Crash report:
```01/22/2019 20:05:34 Detector.run detect_thread_5 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:34 Detector.run detect_thread_3 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:35 Detector.run detect_thread_1 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:35 Detector.run detect_thread_2 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:36 Detector.run detect_thread_4 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:36 Detector.run detect_thread_6 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:37 Detector.run detect_thread_0 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:37 Detector.run detect_thread_5 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:38 Detector.run detect_thread_3 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:39 Detector.run detect_thread_1 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:39 Detector.run detect_thread_2 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:40 Detector.run detect_thread_4 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:40 Detector.run detect_thread_6 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:41 Detector.run detect_thread_0 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:41 Detector.run detect_thread_5 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:42 Detector.run detect_thread_3 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:42 Detector.run detect_thread_1 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:42 Detector.run detect_thread_2 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:43 Detector.run detect_thread_4 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:44 Detector.run detect_thread_0 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:45 Detector.run detect_thread_5 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:45 Detector.run detect_thread_6 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:46 Detector.run detect_thread_3 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:46 Detector.run detect_thread_2 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:47 Detector.run detect_thread_1 _base set_detect_image VERBOSE Resizing image from 2731x4096 to 1175x1763.
01/22/2019 20:05:47 Detector.run detect_thread_4 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:48 Detector.run detect_thread_0 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:50 Detector.run detect_thread_5 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:50 Detector.run detect_thread_6 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:50 Detector.run detect_thread_3 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:50 Detector.run detect_thread_2 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:51 Detector.run detect_thread_1 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:59 Detector.run detect_thread_4 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:05:59 Detector.run detect_thread_6 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:03 Detector.run detect_thread_5 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:04 Detector.run detect_thread_0 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:04 Detector.run detect_thread_3 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:05 Detector.run detect_thread_2 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:05 Detector.run detect_thread_1 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:06 Detector.run detect_thread_4 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:06 Detector.run detect_thread_6 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:07 Detector.run detect_thread_5 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:07 Detector.run detect_thread_0 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:10 Detector.run detect_thread_3 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:11 Detector.run detect_thread_4 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:11 Detector.run detect_thread_2 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:12 Detector.run detect_thread_6 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:12 Detector.run detect_thread_1 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:14 Detector.run detect_thread_0 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
01/22/2019 20:06:14 Detector.run detect_thread_5 _base set_detect_image VERBOSE Resizing image from 4096x2731 to 1763x1175.
Traceback (most recent call last):
File "C:\Users\nope\df\faceswap\lib\cli.py", line 90, in execute_script
process.process()
File "C:\Users\nope\df\faceswap\scripts\extract.py", line 49, in process
self.run_extraction()
File "C:\Users\nope\df\faceswap\scripts\extract.py", line 146, in run_extraction
self.run_detection(to_process)
File "C:\Users\nope\df\faceswap\scripts\extract.py", line 202, in run_detection
desc="Detecting faces"):
File "C:\Users\nope\Anaconda3\envs\face\lib\site-packages\tqdm_tqdm.py", line 979, in iter
for obj in iterable:
File "C:\Users\nope\df\faceswap\scripts\extract.py", line 405, in detect_faces
faces = out_queue.get(True, 1)
File "", line 2, in get
File "C:\Users\nope\Anaconda3\envs\face\lib\multiprocessing\managers.py", line 732, in _callmethod
raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError:

Unserializable message: Traceback (most recent call last):
File "C:\Users\nope\Anaconda3\envs\face\lib\multiprocessing\managers.py", line 276, in serve_client
send(msg)
File "C:\Users\nope\Anaconda3\envs\face\lib\multiprocessing\connection.py", line 206, in send
self._send_bytes(ForkingPickler.dumps(obj))
File "C:\Users\nope\Anaconda3\envs\face\lib\multiprocessing\reduction.py", line 50, in dumps
cls(buf, protocol).dump(obj)
MemoryError

============ System Information ============
git_branch: master
git_commits: 4376bbf Alignments tool: Filename clash bugfix. 20cb538 Merge branch 'master' into staging. af3acaa Alignments tool: Allow empty folder/non existant folder for extract. 8f5bbef Merge branch 'master' into staging. f761a31 Extract - bugfix: Skip non-loaded image
gpu_cuda: 9.0
gpu_cudnn: 7.2.1
gpu_devices: GPU_0: GeForce GTX 1080 Ti
gpu_driver: 417.35
gpu_vram: GPU_0: 11264MB
os_machine: AMD64
os_platform: Windows-10-10.0.17763-SP0
os_release: 10
py_command: C:\Users\nope\df\faceswap\faceswap.py extract -i D:/deep_temp/kayden/kayden -o D:/deep_temp/kayden/face2 -l 0.7 --serializer yaml -D mtcnn -A fan -mtms 20 -mtth 0.7 0.7 0.8 -mtsc 0.709 -bt 15 -sz 256 -s -sf -si 500 -L VERBOSE -LF D:/deep_temp/kayden/log.txt
py_conda_version: conda 4.5.12
py_implementation: CPython
py_version: 3.5.6
py_virtual_env: False
sys_cores: 12
sys_processor: Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
sys_ram: Total: 32643MB, Available: 1161MB, Used: 31481MB, Free: 1161MB

=============== Pip Packages ===============
absl-py==0.7.0
astor==0.7.1
certifi==2018.8.24
Click==7.0
cloudpickle==0.6.1
cmake==3.13.2.post1
cycler==0.10.0
dask==1.0.0
decorator==4.3.0
dlib==19.16.0
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.2
grpcio==1.18.0
h5py==2.8.0
Keras==2.2.4
Keras-Applications==1.0.6
keras-contrib==2.0.8
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==2.2.2
mkl-fft==1.0.6
mkl-random==1.0.1
networkx==2.2
numpy==1.16.0
nvidia-ml-py3==7.352.0
opencv-python==3.4.4.19
pathlib==1.0.1
Pillow==5.3.0
protobuf==3.6.1
psutil==5.4.8
pyparsing==2.3.0
python-dateutil==2.7.5
pytz==2018.7
PyWavelets==1.0.1
PyYAML==3.13
scandir==1.7
scikit-image==0.14.1
scikit-learn==0.20.2
scipy==1.2.0
six==1.12.0
tensorboard==1.9.0
tensorflow-gpu==1.9.0
termcolor==1.1.0
toolz==0.9.0
tqdm==4.28.1
Werkzeug==0.14.1
wincertstore==0.2

============== Conda Packages ==============
packages in environment at C:\Users\nope\Anaconda3\envs\face:
Name Version Build Channel

absl-py 0.6.1
astor 0.7.1
blas 1.0 mkl
certifi 2018.8.24 py35_1001 conda-forge
Click 7.0
cloudpickle 0.6.1
cmake 3.13.2.post1
cudatoolkit 9.0 1 anaconda
cycler 0.10.0
dask 1.0.0
decorator 4.3.0
dlib 19.16.0
face-recognition 1.2.3
face-recognition-models 0.3.0
ffmpeg 4.1 h8fefcd1_0 conda-forge
ffmpy 0.2.2
gast 0.2.0
grpcio 1.17.1
h5py 2.8.0
hdf5 1.8.20 hac2f561_1
icc_rt 2019.0.0 h0cc432a_1
intel-openmp 2019.1 144
jpeg 9b hb83a4c4_2
Keras 2.2.4
Keras-Applications 1.0.6
keras-contrib 2.0.8
Keras-Preprocessing 1.0.5
kiwisolver 1.0.1
libopencv 3.4.2 h20b85fd_0
libpng 1.6.36 h2a8f88b_0
libtiff 4.0.9 h36446d0_2
Markdown 3.0.1
matplotlib 2.2.2
mkl 2018.0.3 1
mkl_fft 1.0.6 py35hdbbee80_0
mkl_random 1.0.1 py35h77b88f5_1
networkx 2.2
numpy 1.15.4
numpy 1.15.2 py35ha559c80_0
numpy-base 1.15.2 py35h8128ebf_0
nvidia-ml-py3 7.352.0
opencv 3.4.2 py35h40b0b35_0
opencv-python 3.4.4.19
pathlib 1.0.1
Pillow 5.3.0
pip 18.1
pip 18.0 py35_1001 conda-forge
protobuf 3.6.1
psutil 5.4.8
py-opencv 3.4.2 py35hc319ecb_0
pyparsing 2.3.0
python 3.5.6 he025d50_0
python-dateutil 2.7.5
pytz 2018.7
PyWavelets 1.0.1
PyYAML 3.13
scandir 1.7
scikit-image 0.14.1
scikit-learn 0.20.2
scipy 1.2.0
setuptools 40.2.0 py35_0
six 1.12.0
tensorboard 1.12.1
tensorflow-gpu 1.12.0
termcolor 1.1.0
tk 8.6.8 hfa6e2cd_0
toolz 0.9.0
tqdm 4.28.1
vc 14.1 h21ff451_3 anaconda
vs2015_runtime 15.5.2 3 anaconda
Werkzeug 0.14.1
wheel 0.31.1 py35_0
wincertstore 0.2 py35hfebbdb8_0
zlib 1.2.11 h62dcd97_3```

**Comment by cp0000** [comment]
hi, i got the same problem when i tried to extract images,how to fix it?
