### ISSUE TITLE
crashed at the beginning of train

### ISSUE THREAD

**Issue by TTTJJJWWW** [deepfakes/faceswap#629]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I get the error like that:
Loading...
02/27/2019 10:58:45 INFO     Log level set to: INFO
Using TensorFlow backend.
02/27/2019 10:58:46 INFO     Model A Directory: /home/tjw/Desktop/faceswap-master/data/cage
02/27/2019 10:58:46 INFO     Model B Directory: /home/tjw/Desktop/faceswap-master/data/trump
02/27/2019 10:58:46 INFO     Training data directory: /home/tjw/Desktop/faceswap-master/models
02/27/2019 10:58:46 INFO     ===============================================
02/27/2019 10:58:46 INFO     - Starting                                    -
02/27/2019 10:58:46 INFO     - Press 'ENTER' to save and quit              -
02/27/2019 10:58:46 INFO     - Press 'S' to save model weights immediately -
02/27/2019 10:58:46 INFO     ===============================================
02/27/2019 10:58:47 INFO     Loading data, this may take a while...
02/27/2019 10:58:47 INFO     Loading Model from Original plugin...
02/27/2019 10:58:50 INFO     Loading config: '/home/tjw/Desktop/faceswap-master/config/train.ini'
02/27/2019 10:58:50 WARNING  No existing state file found. Generating.
02/27/2019 10:58:51 INFO     Loaded model from disk: '/home/tjw/Desktop/faceswap-master/models'
02/27/2019 10:58:52 INFO     Loading Trainer from Original plugin...
02/27/2019 10:58:52 INFO     Enabled TensorBoard Logging
02/27/2019 10:58:56 CRITICAL Error caught! Exiting...
02/27/2019 10:58:56 ERROR    Caught exception in thread: 'training_0'
02/27/2019 10:58:57 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "/home/tjw/Desktop/faceswap-master/lib/cli.py", line 90, in execute_script
process.process()
File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 97, in process
self.end_thread(thread, err)
File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 122, in end_thread
thread.join()
File "/home/tjw/Desktop/faceswap-master/lib/multithreading.py", line 179, in join
raise thread.err[1].with_traceback(thread.err[2])
File "/home/tjw/Desktop/faceswap-master/lib/multithreading.py", line 117, in run
self._target(*self._args, **self._kwargs)
File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 148, in training
raise err
File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 138, in training
self.run_training_cycle(model, trainer)
File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 210, in run_training_cycle
trainer.train_one_step(viewer, timelapse)
File "/home/tjw/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 138, in train_one_step
loss[side] = batcher.train_one_batch(is_preview_iteration)
File "/home/tjw/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 212, in train_one_batch
loss = self.model.predictors[self.side].train_on_batch(*batch)
File "/home/tjw/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
outputs = self.train_function(ins)
File "/home/tjw/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
return self._call(inputs)
File "/home/tjw/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
fetched = self._callable_fn(*array_vals)
File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1454, in __call__
self._session._session, self._handle, args, status, None)
File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Adam/lr
[[Node: Adam/lr/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Adam/lr)]]
[[Node: loss/mul/_545 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2022_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
02/27/2019 10:58:57 CRITICAL An unexpected crash has occurred. Crash report written to /home/tjw/Desktop/faceswap-master/crash_report.2019.02.27.105856394302.log. Please verify you are running the latest version of faceswap before reporting
terminate called without an active exception
terminate called recursively
Process exited.

How to fix this? thanks!

**Comment by TTTJJJWWW** [comment]
python 3.5
tensorflow 1.8.0
CUDA 9
cuDNN 7

**Comment by torzdf** [comment]
Upgrade tensorflow to 1.12

**Comment by changyunke** [comment]
I also have this problem,did you fix it?

**Comment by TTTJJJWWW** [comment]
@changyunke Yes, i fix this by using tensorflow to 1.12+cuda9.0+cudnn7.1.3
