### ISSUE TITLE
QHull error using Dfl-H128 model during training

### ISSUE THREAD

**Issue by bronzelion** [deepfakes/faceswap#650]
Hi,
I am currently experiencing an issue during training(both with and without warp landmarks). The training randomly segfaults after a few iterations with this error.

### Error
```
Traceback (most recent call last):
  File "/code/deepfakes/lib/cli.py", line 90, in execute_script
    process.process()
  File "/code/deepfakes/scripts/train.py", line 97, in process
    self.end_thread(thread, err)
  File "/code/deepfakes/scripts/train.py", line 122, in end_thread
    thread.join()
  File "/code/deepfakes/lib/multithreading.py", line 179, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/code/deepfakes/lib/multithreading.py", line 117, in run
    self._target(*self._args, **self._kwargs)
  File "/code/deepfakes/scripts/train.py", line 148, in training
    raise err
  File "/code/deepfakes/scripts/train.py", line 138, in training
    self.run_training_cycle(model, trainer)
  File "/code/deepfakes/scripts/train.py", line 210, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "/code/deepfakes/plugins/train/trainer/_base.py", line 138, in train_one_step
    loss[side] = batcher.train_one_batch(is_preview_iteration)
  File "/code/deepfakes/plugins/train/trainer/_base.py", line 211, in train_one_batch
    batch = self.get_next(is_preview_iteration)
  File "/code/deepfakes/plugins/train/trainer/_base.py", line 219, in get_next
    batch = next(self.feed)
  File "/code/deepfakes/lib/training_data.py", line 118, in minibatch
    load_thread.join()
  File "/code/deepfakes/lib/multithreading.py", line 179, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/code/deepfakes/lib/multithreading.py", line 117, in run
    self._target(*self._args, **self._kwargs)
  File "/code/deepfakes/lib/training_data.py", line 83, in load_batches
    queue.put(self.process_face(img, side, is_timelapse))
  File "/code/deepfakes/lib/training_data.py", line 144, in process_face
    processed = self.processing.random_warp_landmarks(image, src_pts, dst_pts)
  File "/code/deepfakes/lib/training_data.py", line 342, in random_warp_landmarks
    grid_z = griddata(destination, source, (grid_x, grid_y), method="linear")
  File "/virtual/lib/python/scipy/interpolate/ndgriddata.py", line 208, in griddata
    rescale=rescale)
  File "scipy/interpolate/interpnd.pyx", line 239, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__ (scipy/interpolate/interpnd.c:49
45)
  File "scipy/spatial/qhull.pyx", line 1740, in scipy.spatial.qhull.Delaunay.__init__ (scipy/spatial/qhull.c:15132)
  File "scipy/spatial/qhull.pyx", line 331, in scipy.spatial.qhull._Qhull.__init__ (scipy/spatial/qhull.c:3682)
```

### Training Model : DFL-H128

Training	| Settings |Result
----------|---------|-------
Trial 1 | Warp landmarks On, coverage setting 87.5, subpixel upscaling = False|Failed|
Trial 2|Warp landmarks Off, coverage setting 62.5, subpixel upscaling = True|Failed|
Trial 3|Warp landmarks On, coverage setting 62.5, subpixel upscaling = False|completed 100,000+ iterations

I have seen this error twice now, with the same training dataset and model. Maybe worth mentioning that I have also seen the same model and dataset completing over a 100,000 iterations without errors. Could that be solely because the warping landmarks/face step is random and I perhaps was lucky to not to encounter the issue in my previous runs?

### Environment
```============ System Information ============
gpu_cuda:          9.
gpu_cudnn:         Not Found
gpu_devices:       GPU_0: Quadro P6000
gpu_driver:        384.98
gpu_vram:          GPU_0: 24443MB
os_machine:        x86_64
os_platform:       Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.4.1708-Core
os_release:        3.10.0-693.2.2.el7.x86_64
py_conda_version:  N/A
py_implementation: CPython
py_version:        3.6.6
py_virtual_env:    False
sys_cores:         32
sys_processor:     x86_64
sys_ram:           Total: 64190MB, Available: 55631MB, Used: 25279MB, Free: 38910MB
=============== Pip Packages ===============
absl-py==0.6.1
astor==0.7.1
backports.ssl-match-hostname==3.4.0.2
certifi==2015.4.28
cycler==0.10.0
Cython==0.29.2
decorator==3.3.2
dlib==19.16.0
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.1
google-apputils==0.4.2
grpcio==1.17.1
h5py==2.8.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==2.2.2
mpmath==1.0.0
networkx==1.10
numpy==1.15.4
nvidia-ml-py3==7.352.0
pathlib==1.0.1
Pillow==2.4.0
protobuf==3.6.1
psutil==2.1.1
pyparsing==2.0.3
python-dateutil==2.4.2
python-gflags==2.0
pytz==2016.10
PyYAML==3.11
scandir==1.7
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==0.16.0
six==1.11.0
sympy==1.1.1
tensorboard==1.12.2
tensorflow-gpu==1.12.0
termcolor==1.1.0
tornado==4.2.1
tqdm==4.28.1
Werkzeug==0.14.1
```
Thanks!

**Comment by bronzelion** [comment]
Hi,
Just wondering if anyone else is experiencing the same error?

Thanks!

**Comment by torzdf** [comment]
This issue has not been reported before and I've never seen it. There may be an issue/conflict in one of your packages, so I suggest wiping your environment clean, re-installing and see if the issue persists.

**Comment by torzdf** [comment]
Closing due to lack of activity
