### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by Nostalgia1990** [deepfakes/faceswap#667]
**Describe the bug**
System Dependencies are met and the log shows setup is ok

**success info**
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
INFO    Installing Required Conda Packages. This may take some time...
INFO    Installing ffmpeg
INFO    All python3 dependencies are met.
        You are good to go.

        Enter:  'python faceswap.py -h' to see the options
                'python faceswap.py gui' to launch the GUI

But when I enter "python faceswap.py gui" , An error happend:

**error info**
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jinyi\faceswap\faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "C:\Users\jinyi\faceswap\lib\cli.py", line 12, in <module>
    from lib.utils import safe_shutdown
  File "C:\Users\jinyi\faceswap\lib\utils.py", line 12, in <module>
    import cv2
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
**Desktop (please complete the following information):**
 - Device:  PC
 - OS: win 10

**Comment by kvrooman** [comment]
Likely wrong version of numpy installed

type
```conda list numpy```
it should be 1.15.4

**Comment by Nostalgia1990** [comment]
> Likely wrong version of numpy installed
> 
> type
> `conda list numpy`
> it should be 1.15.4

My numpy's version is 1.15.4.  Is there something wrong with opencv-python? My opencv-python's version is 4.0.0.21

**Comment by torzdf** [comment]
This is usually because of a version conflict somewhere, either multiple versions of numpy/cv2 installed in different environments. Google around for solutions.

**Comment by Nostalgia1990** [comment]
> Likely wrong version of numpy installed
> 
> type
> `conda list numpy`
> it should be 1.15.4

Thank you.I resolved the problem.
1.install numpy 1.15.4
2.python setup.py again

both steps are important.

**Comment by Nostalgia1990** [comment]
> This is usually because of a version conflict somewhere, either multiple versions of numpy/cv2 installed in different environments. Google around for solutions.


Thank you.I resolved the problem.
1.install numpy 1.15.4
2.python setup.py again

both steps are important.
