### ISSUE TITLE
train failed

### ISSUE THREAD

**Issue by Nostalgia1990** [deepfakes/faceswap#670]
03/15/2019 22:08:06 MainProcess     training_0      multithreading  run                       DEBUG    Error in thread (training_0): OOM when allocating tensor with shape[16384,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n	 [[{{node training_1/Adam/mul_43}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Adam/beta_2/read, training_1/Adam/Variable_30/read)]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n	 [[{{node loss_1/mul/_401}} = _Recv[[[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1638_loss_1/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n
03/15/2019 22:08:06 MainProcess     MainThread      train           monitor_console           DEBUG    Thread error detected
03/15/2019 22:08:06 MainProcess     MainThread      train           monitor_console           DEBUG    Closed Console Monitor
03/15/2019 22:08:06 MainProcess     MainThread      train           end_thread                DEBUG    Ending Training thread
03/15/2019 22:08:06 MainProcess     MainThread      train           end_thread                CRITICAL Error caught! Exiting...
03/15/2019 22:08:06 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'training'
03/15/2019 22:08:06 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'training_0'
03/15/2019 22:08:06 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: 'training_0'
Traceback (most recent call last):
  File "C:\Users\jinyi\faceswap\lib\cli.py", line 107, in execute_script
    process.process()
  File "C:\Users\jinyi\faceswap\scripts\train.py", line 101, in process
    self.end_thread(thread, err)
  File "C:\Users\jinyi\faceswap\scripts\train.py", line 126, in end_thread
    thread.join()
  File "C:\Users\jinyi\faceswap\lib\multithreading.py", line 443, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "C:\Users\jinyi\faceswap\lib\multithreading.py", line 381, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jinyi\faceswap\scripts\train.py", line 152, in training
    raise err
  File "C:\Users\jinyi\faceswap\scripts\train.py", line 142, in training
    self.run_training_cycle(model, trainer)
  File "C:\Users\jinyi\faceswap\scripts\train.py", line 214, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "C:\Users\jinyi\faceswap\plugins\train\trainer\_base.py", line 139, in train_one_step
    loss[side] = batcher.train_one_batch(do_preview)
  File "C:\Users\jinyi\faceswap\plugins\train\trainer\_base.py", line 214, in train_one_batch
    loss = self.model.predictors[self.side].train_on_batch(*batch)
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16384,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node training_1/Adam/mul_43}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Adam/beta_2/read, training_1/Adam/Variable_30/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [[{{node loss_1/mul/_401}} = _Recv[[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1638_loss_1/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by Nostalgia1990** [comment]
@torzdf @kvrooman

**Comment by gessyoo** [comment]
@Nostalgia1990, use the Windows installer: https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#windows-install-guide.

**Comment by Nostalgia1990** [comment]
> @Nostalgia1990, use the Windows installer: https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#windows-install-guide.

I always use the guide,it's helpless to this problem.

**Comment by Nostalgia1990** [comment]
I removed TF 1.13.1 and installed TF 1.12,but it also doesn't work.


**error log**

Loading...
03/15/2019 23:33:12 INFO     Log level set to: INFO
Using TensorFlow backend.
03/15/2019 23:33:13 INFO     Model A Directory: C:\Users\jinyi\faceswap\workspace\data_dst\aligned
03/15/2019 23:33:13 INFO     Model B Directory: C:\Users\jinyi\faceswap\workspace\data_src\aligned
03/15/2019 23:33:13 INFO     Training data directory: C:\Users\jinyi\faceswap\models
03/15/2019 23:33:13 INFO     ===============================================
03/15/2019 23:33:13 INFO     - Starting                                    -
03/15/2019 23:33:13 INFO     - Press 'ENTER' to save and quit              -
03/15/2019 23:33:13 INFO     - Press 'S' to save model weights immediately -
03/15/2019 23:33:13 INFO     ===============================================
03/15/2019 23:33:15 INFO     Loading data, this may take a while...
03/15/2019 23:33:15 INFO     Loading Model from Original plugin...
03/15/2019 23:36:18 INFO     Loading config: 'C:\Users\jinyi\faceswap\config\train.ini'
03/15/2019 23:36:18 WARNING  No existing state file found. Generating.
03/15/2019 23:36:44 INFO     Creating new 'original' model in folder: 'C:\Users\jinyi\faceswap\models'
03/15/2019 23:37:07 INFO     Loading Trainer from Original plugin...
03/15/2019 23:41:31 INFO     Enabled TensorBoard Logging
03/15/2019 23:48:04 CRITICAL Error caught! Exiting...
03/15/2019 23:48:04 ERROR    Caught exception in thread: 'training_0'
03/15/2019 23:48:08 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "C:\Users\jinyi\faceswap\lib\cli.py", line 107, in execute_script
process.process()
File "C:\Users\jinyi\faceswap\scripts\train.py", line 101, in process
self.end_thread(thread, err)
File "C:\Users\jinyi\faceswap\scripts\train.py", line 126, in end_thread
thread.join()
File "C:\Users\jinyi\faceswap\lib\multithreading.py", line 443, in join
raise thread.err[1].with_traceback(thread.err[2])
File "C:\Users\jinyi\faceswap\lib\multithreading.py", line 381, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\jinyi\faceswap\scripts\train.py", line 152, in training
raise err
File "C:\Users\jinyi\faceswap\scripts\train.py", line 142, in training
self.run_training_cycle(model, trainer)
File "C:\Users\jinyi\faceswap\scripts\train.py", line 214, in run_training_cycle
trainer.train_one_step(viewer, timelapse)
File "C:\Users\jinyi\faceswap\plugins\train\trainer\_base.py", line 139, in train_one_step
loss[side] = batcher.train_one_batch(do_preview)
File "C:\Users\jinyi\faceswap\plugins\train\trainer\_base.py", line 214, in train_one_batch
loss = self.model.predictors[self.side].train_on_batch(*batch)
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
outputs = self.train_function(ins)
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
return self._call(inputs)
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
fetched = self._callable_fn(*array_vals)
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
run_metadata_ptr)
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16384,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[{{node training_1/Adam/mul_43}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Adam/beta_2/read, training_1/Adam/Variable_30/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[[{{node loss_1/mul/_401}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1638_loss_1/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

03/15/2019 23:48:08 CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\jinyi\faceswap\crash_report.2019.03.15.234804885710.log. Please verify you are running the latest version of faceswap before reporting
Exception ignored in: <generator object TrainingDataGenerator.minibatch at 0x00000168780462B0>
Traceback (most recent call last):
File "C:\Users\jinyi\faceswap\lib\training_data.py", line 135, in minibatch
File "C:\Users\jinyi\faceswap\lib\multithreading.py", line 43, in __exit__
File "C:\Users\jinyi\faceswap\lib\multithreading.py", line 35, in free
File "C:\Users\jinyi\faceswap\lib\multithreading.py", line 173, in free
File "<string>", line 2, in put
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\multiprocessing\managers.py", line 753, in _callmethod
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\multiprocessing\managers.py", line 740, in _connect
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 485, in Client
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 686, in PipeClient
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x0000016878045400>>
Traceback (most recent call last):
File "D:\PC_apps\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable
Process exited.

**Comment by gessyoo** [comment]
@Nostalgia1990, have you to force version install: 
conda install tensorflow-gpu==1.12
conda install tensorboard==1.12
conda install tensorflow-estimator==1.12

**Comment by Nostalgia1990** [comment]
> @Nostalgia1990, have you tried to force version install:
> conda install tensorflow-gpu==1.12
> conda install tensorboard==1.12
> conda install tensorflow-estimator==1.12
my tensorflow-gpu==1.12.0
my  tensorflow-estimator==1.13.0
my conda install tensorboard==1.12.2

let me try your advice ,thank you. wait a moment.

**Comment by Nostalgia1990** [comment]
> @Nostalgia1990, have you tried to force version install:
> conda install tensorflow-gpu==1.12
> conda install tensorboard==1.12
> conda install tensorflow-estimator==1.12

 Could not find a version that satisfies the requirement tensorflow-estimator==1.12.0 (from versions: 1.10.6, 1.10.7, 1.10.8, 1.10.9, 1.10.10, 1.10.11, 1.10.12, 1.13.0rc0, 1.13.0)
No matching distribution found for tensorflow-estimator==1.12.0

Could not find a version that satisfies the requirement tensorboardrd==1.12.0 (from versions: )
No matching distribution found for tensorboardrd==1.12.0

**Comment by torzdf** [comment]
You're out of memory. Lower batch size or choose a different model. If you still have issues provide a crash report.

**Comment by Nostalgia1990** [comment]
> You're out of memory. Lower batch size or choose a different model. If you still have issues provide a crash report.



> You're out of memory. Lower batch size or choose a different model. If you still have issues provide a crash report.

It's not OK ,although I set batch size the minimum 2.   My laptop  has 8g RAM,and my graphic gard is GetForce 970m about 3g vram.

@torzdf 


[crash_report.2019.03.16.094702509958.log](https://github.com/deepfakes/faceswap/files/2973353/crash_report.2019.03.16.094702509958.log)

**Comment by Nostalgia1990** [comment]
@torzdf

**Comment by torzdf** [comment]
3GB of RAM is low. Original model will generally not work on less than 4GB.

However there are new VRAM saving features in the latest commit, so either try them, or use the lightweight model or lowmem version of the original model.
