### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by ArmsZhou** [deepfakes/faceswap#676]
macos(10.13.6) no gpu python(3.6.8) tensorflow(1.13.0)

(faceswap) ➜  faceswap git:(master) ✗ python faceswap.py train -A ./photo/A -B ./photo/B -m ./models
03/21/2019 13:50:48 INFO     Log level set to: INFO
Using TensorFlow backend.
03/21/2019 13:50:50 INFO     Model A Directory: /Users/three/Desktop/Python3.6.8/faceswap/photo/A
03/21/2019 13:50:50 INFO     Model B Directory: /Users/three/Desktop/Python3.6.8/faceswap/photo/B
03/21/2019 13:50:50 INFO     Training data directory: /Users/three/Desktop/Python3.6.8/faceswap/models
03/21/2019 13:50:50 INFO     ===============================================
03/21/2019 13:50:50 INFO     - Starting                                    -
03/21/2019 13:50:50 INFO     - Press 'ENTER' to save and quit              -
03/21/2019 13:50:50 INFO     - Press 'S' to save model weights immediately -
03/21/2019 13:50:50 INFO     ===============================================
03/21/2019 13:50:51 INFO     Loading data, this may take a while...
03/21/2019 13:50:51 INFO     Loading Model from Original plugin...
03/21/2019 13:50:55 INFO     Loading config: '/Users/three/Desktop/Python3.6.8/faceswap/config/train.ini'
03/21/2019 13:50:55 WARNING  No existing state file found. Generating.
03/21/2019 13:50:56 INFO     Creating new 'original' model in folder: '/Users/three/Desktop/Python3.6.8/faceswap/models'
03/21/2019 13:50:56 INFO     Loading Trainer from Original plugin...
03/21/2019 13:52:42 ERROR    
Traceback (most recent call last):
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/multithreading.py", line 261, in _runner
    target(*args, **kwargs)
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/training_data.py", line 105, in load_batches
    imgs = self.process_face(img_path, side, is_timelapse)
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/training_data.py", line 167, in process_face
    processed = self.processing.random_warp(image)
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/training_data.py", line 283, in random_warp
    assert height == width and height % 2 == 0
AssertionError
03/21/2019 14:10:11 INFO     Enabled TensorBoard Logging
03/21/2019 14:10:12 CRITICAL Error caught! Exiting...
03/21/2019 14:10:12 ERROR    Caught exception in thread: 'training_0'
03/21/2019 14:10:15 ERROR    
Traceback (most recent call last):
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/multithreading.py", line 261, in _runner
    target(*args, **kwargs)
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/training_data.py", line 105, in load_batches
    imgs = self.process_face(img_path, side, is_timelapse)
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/training_data.py", line 167, in process_face
    processed = self.processing.random_warp(image)
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/training_data.py", line 283, in random_warp
    assert height == width and height % 2 == 0
AssertionError
03/21/2019 14:10:16 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/cli.py", line 107, in execute_script
    process.process()
  File "/Users/three/Desktop/Python3.6.8/faceswap/scripts/train.py", line 101, in process
    self.end_thread(thread, err)
  File "/Users/three/Desktop/Python3.6.8/faceswap/scripts/train.py", line 126, in end_thread
    thread.join()
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/multithreading.py", line 443, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/Users/three/Desktop/Python3.6.8/faceswap/lib/multithreading.py", line 381, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/three/Desktop/Python3.6.8/faceswap/scripts/train.py", line 152, in training
    raise err
  File "/Users/three/Desktop/Python3.6.8/faceswap/scripts/train.py", line 142, in training
    self.run_training_cycle(model, trainer)
  File "/Users/three/Desktop/Python3.6.8/faceswap/scripts/train.py", line 217, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "/Users/three/Desktop/Python3.6.8/faceswap/plugins/train/trainer/_base.py", line 153, in train_one_step
    loss[side] = batcher.train_one_batch(do_preview)
  File "/Users/three/Desktop/Python3.6.8/faceswap/plugins/train/trainer/_base.py", line 234, in train_one_batch
    batch = self.get_next(do_preview)
  File "/Users/three/Desktop/Python3.6.8/faceswap/plugins/train/trainer/_base.py", line 242, in get_next
    batch = next(self.feed)
StopIteration
03/21/2019 14:10:16 CRITICAL An unexpected crash has occurred. Crash report written to /Users/three/Desktop/Python3.6.8/faceswap/crash_report.2019.03.21.141012380144.log. Please verify you are running the latest version of faceswap before reporting
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x160f7ac50>>
Traceback (most recent call last):
  File "/Users/three/.virtualenvs/faceswap/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable

**Comment by torzdf** [comment]
```assert height == width and height % 2 == 0```
Non training image in your input folder
