### ISSUE TITLE
When I try to convert images,i got following errors

### ISSUE THREAD

**Issue by zy1620454507** [deepfakes/faceswap#716]
**Describe the bug**
Traceback (most recent call last):
  File "E:\python\faceswap\lib\cli.py", line 109, in execute_script
    process = script(arguments)
  File "E:\python\faceswap\scripts\convert.py", line 43, in __init__
    self.disk_io = DiskIO(self.alignments, self.images, arguments)
  File "E:\python\faceswap\scripts\convert.py", line 175, in __init__
    self.load_extractor()
  File "E:\python\faceswap\scripts\convert.py", line 246, in load_extractor
    self.extractor = Extractor(None, extract_args)
  File "E:\python\faceswap\scripts\extract.py", line 274, in __init__
    self.add_queues()
  File "E:\python\faceswap\scripts\extract.py", line 313, in add_queues
    queue_manager.add_queue(task, maxsize=size)
  File "E:\python\faceswap\lib\queue_manager.py", line 49, in add_queue
    raise ValueError("Queue '{}' already exists.".format(name))
ValueError: Queue 'save' already exists.
**To Reproduce**
1.train,ok
2.convert,ok
3.add more images to trump folder
4.convert,error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5830375/56961126-7f2d2c00-6b85-11e9-94d5-42fd4abdf7bb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zy1620454507** [comment]
##all error msg
E:\python\faceswap>python faceswap.py convert -i ./photo/trump/ -o ./output -m ./models -M none
04/30/2019 20:12:23 INFO     Log level set to: INFO
04/30/2019 20:12:27 INFO     Input Directory: E:\python\faceswap\photo\trump
04/30/2019 20:12:27 INFO     Output Directory: E:\python\faceswap\output
QueueManager adding: (name: '%s', maxsize: %s) convert_in 8
QueueManager adding: (name: '%s', maxsize: %s) save 8
QueueManager adding: (name: '%s', maxsize: %s) patch 8
04/30/2019 20:12:27 INFO     Loading Writer from Opencv plugin...
04/30/2019 20:12:27 WARNING  No Alignments file found. Extracting on the fly.
04/30/2019 20:12:27 WARNING  NB: This will use the inferior dlib-hog for extraction and dlib pose predictor for landmarks. It is recommended to perfom Extract first for superior results
04/30/2019 20:12:27 INFO     Loading Detect from Dlib_Hog plugin...
04/30/2019 20:12:27 INFO     Loading Align from Dlib plugin...
QueueManager adding: (name: '%s', maxsize: %s) load 100
QueueManager adding: (name: '%s', maxsize: %s) detect 0
QueueManager adding: (name: '%s', maxsize: %s) align 0
QueueManager adding: (name: '%s', maxsize: %s) save 0
04/30/2019 20:12:36 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "E:\python\faceswap\lib\cli.py", line 109, in execute_script
    process = script(arguments)
  File "E:\python\faceswap\scripts\convert.py", line 43, in __init__
    self.disk_io = DiskIO(self.alignments, self.images, arguments)
  File "E:\python\faceswap\scripts\convert.py", line 175, in __init__
    self.load_extractor()
  File "E:\python\faceswap\scripts\convert.py", line 246, in load_extractor
    self.extractor = Extractor(None, extract_args)
  File "E:\python\faceswap\scripts\extract.py", line 274, in __init__
    self.add_queues()
  File "E:\python\faceswap\scripts\extract.py", line 313, in add_queues
    queue_manager.add_queue(task, maxsize=size)
  File "E:\python\faceswap\lib\queue_manager.py", line 49, in add_queue
    raise ValueError("Queue '{}' already exists.".format(name))
ValueError: Queue 'save' already exists.
04/30/2019 20:12:36 CRITICAL An unexpected crash has occurred. Crash report written to E:\python\faceswap\crash_report.2019.04.30.201227768930.log. Please verify you are running the latest version of faceswap before reporting

**Comment by zy1620454507** [comment]
I have solve this problem.

**Comment by liangshuang1993** [comment]
Hi @zy1620454507 ， Can you tell me how to solve this problem? Thanks!

**Comment by torzdf** [comment]
This is a bug which was fixed a few days ago. Get latest code.

**Comment by liangshuang1993** [comment]
OK, thanks a lot!
