### ISSUE TITLE
I got some error in dfk-h128 training

### ISSUE THREAD

**Issue by ho6009** [deepfakes/faceswap#717]
At first, it trains well. But after few seconds ago, my gpu fans(gtx1080) accelerate and program got some error.

[11:13:56] [#2046049] total_loss_A: 0.05094, loss_A: 0.02987, mask_loss_A: 0.02107, total_loss_B: 0.04346, loss_B: 0.02605/03/2019 11:14:07 CRITICAL Error caught! Exiting...
05/03/2019 11:14:07 ERROR    Caught exception in thread: 'training_0'
05/03/2019 11:14:09 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "c:\faceswap\lib\cli.py", line 107, in execute_script
    process.process()
  File "c:\faceswap\scripts\train.py", line 101, in process
    self.end_thread(thread, err)
  File "c:\faceswap\scripts\train.py", line 126, in end_thread
    thread.join()
  File "c:\faceswap\lib\multithreading.py", line 443, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "c:\faceswap\lib\multithreading.py", line 381, in run
    self._target(*self._args, **self._kwargs)
  File "c:\faceswap\scripts\train.py", line 152, in training
    raise err
  File "c:\faceswap\scripts\train.py", line 142, in training
    self.run_training_cycle(model, trainer)
  File "c:\faceswap\scripts\train.py", line 217, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "c:\faceswap\plugins\train\trainer\_base.py", line 153, in train_one_step
    loss[side] = batcher.train_one_batch(do_preview)
  File "c:\faceswap\plugins\train\trainer\_base.py", line 235, in train_one_batch
    loss = self.model.predictors[self.side].train_on_batch(*batch)
  File "C:\Users\jho60\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\jho60\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\jho60\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\jho60\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\jho60\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,128,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training_1/Adam/gradients/decoder_1/conv2d_9/convolution_grad/Conv2DBackpropInput}} = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@decoder_1/conv2d_9/convolution"], data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training_1/Adam/gradients/decoder_1/conv2d_9/convolution_grad/ShapeN, conv2d_9/kernel/read, training_1/Adam/gradients/decoder_1/conv2d_9/Sigmoid_grad/SigmoidGrad)]]

[crash_report.2019.05.03.110653291981.log](https://github.com/deepfakes/faceswap/files/3140471/crash_report.2019.05.03.110653291981.log)

**Comment by torzdf** [comment]
OOM = Out of Memory. Lower your batch size
