### ISSUE TITLE
ImportError: Module use of python37.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by WSADKeysGaming** [deepfakes/faceswap#728]
**Describe the bug**
Some python dll import error something something

**To Reproduce**
1. Run setup.exe
2. Error

**Expected behavior**
Install w/o error

**Installer Details**
```
(check) Git installed: git version 2.20.1.windows.1
(check) MiniConda installed: conda 4.5.12
(check) CPU Supports AVX Instructions
(check) CPU Supports SSE4 Instructions
(check) Completed check for installed applications

All Prerequisites installed.
Downloading Faceswap...
Cloning into 'C:\Users\Cole\faceswap'...
Creating Conda Virtual Environment...
Remove all packages in environment C:\Users\Cole\MiniConda3\envs\faceswap:
## Package Plan ##
  environment location: C:\Users\Cole\MiniConda3\envs\faceswap
The following packages will be REMOVED:
    certifi:        2019.3.9-py36_0       
    pip:            19.1.1-py36_0         
    python:         3.6.8-h9f7ef89_7      
    setuptools:     41.0.1-py36_0         
    sqlite:         3.28.0-he774522_0     
    vc:             14.1-h0510ff6_4       
    vs2015_runtime: 14.15.26706-h3a45250_4
    wheel:          0.33.2-py36_0         
    wincertstore:   0.2-py36h7fe50ca_0    
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Users\Cole\MiniConda3\envs\faceswap
  added / updated specs: 
    - python=3.6
The following NEW packages will be INSTALLED:
    certifi:        2019.3.9-py36_0       
    pip:            19.1.1-py36_0         
    python:         3.6.8-h9f7ef89_7      
    setuptools:     41.0.1-py36_0         
    sqlite:         3.28.0-he774522_0     
    vc:             14.1-h0510ff6_4       
    vs2015_runtime: 14.15.26706-h3a45250_4
    wheel:          0.33.2-py36_0         
    wincertstore:   0.2-py36h7fe50ca_0    
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.14
Please update conda by running
    $ conda update -n base -c defaults conda
#
# To activate this environment, use
#
#     $ conda activate faceswap
#
# To deactivate an active environment, use
#
#     $ conda deactivate
Setting up FaceSwap Environment... This may take a while
Traceback (most recent call last):
  File "C:\Users\Cole\faceswap\setup.py", line 5, in <module>
    import ctypes
  File "C:\Users\Cole\MiniConda3\envs\faceswap\lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: Module use of python37.dll conflicts with this version of Python.
Error Setting up Faceswap
Install Aborted


```
**Desktop**
 - OS: W10Pro B1803
- All latest cudnn cuda nvidia anything installed
-gtx 1080

**Additional context**
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by torzdf** [comment]
This is a python issue, not a faceswap issue. 

Completely remove all versions of python from your system (Conda/Python). Delete any python/conda files in `C:\users\<username>` and  `C:\users\<username>\roaming` and try to install again.
