### ISSUE TITLE
fix setup.py for 19.04

### ISSUE THREAD

**Issue by omen23** [deepfakes/faceswap#729]
**Describe the bug**
faceswap install script won't install with Python 3.7+ except you patch it - even on Linux TensorFlow works with Python 3.7
tensorflow-gpu 1.13.1 works with python 3.7.3
**To Reproduce**
follow isntallation steps...

**Expected behavior**
works with python 3.7.3
**Screenshots**
![Screenshot_20190518_124123](https://user-images.githubusercontent.com/1809702/57968409-7ea8d980-796a-11e9-8d0a-0f4ab76d9fa1.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser: Chromium
 - Version: 19.04

**Additional context**

quick n dirty fix
```
    def check_python(self):
        """ Check python and virtual environment status """
        self.output.info("Installed Python: {0} {1}".format(self.py_version[0],
                                                            self.py_version[1]))
        
        if self.os_version[0] == "Linux":
            if not (self.py_version[0].split(".")[0] == "3"
                    and self.py_version[0].split(".")[1] in ("3", "4", "5", "6", "7")
                    and self.py_version[1] == "64bit"):
                self.output.error("Please run this script with Python version 3.3, 3.4, 3.5, 3.6 or 3.7 "
                              "64bit and try again.")
                exit(1)
                
        else:
            if not (self.py_version[0].split(".")[0] == "3"
                    and self.py_version[0].split(".")[1] in ("3", "4", "5", "6")
                    and self.py_version[1] == "64bit"):
                self.output.error("Please run this script with Python version 3.3, 3.4, 3.5 or 3.6 "
                              "64bit and try again.")
                exit(1)    

```
in setup.py

**Comment by torzdf** [comment]
We don't currently officially support TF 1.13 because there is a Tensorboard/Keras callback issue with logging.

**Comment by procule** [comment]
> We don't currently officially support TF 1.13 because there is a Tensorboard/Keras callback issue with logging.

@torzdf 
Is that the reason for that error ?
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/opt/faceswap/lib/gui/display_page.py", line 245, in <lambda>
    self.after(waittime, lambda t=waittime: self.update_page(t))
  File "/opt/faceswap/lib/gui/display_page.py", line 244, in update_page
    self.load_display()
  File "/opt/faceswap/lib/gui/display_page.py", line 256, in load_display
    self.display_item_process()
  File "/opt/faceswap/lib/gui/display_command.py", line 217, in display_item_process
    selections=["raw", "trend"])
  File "/opt/faceswap/lib/gui/stats.py", line 343, in __init__
    self.refresh()
  File "/opt/faceswap/lib/gui/stats.py", line 352, in refresh
    self.stats = self.get_raw()
  File "/opt/faceswap/lib/gui/stats.py", line 364, in get_raw
    loss_dict = self.session.total_loss if self.is_totals else self.session.loss
  File "/opt/faceswap/lib/gui/stats.py", line 139, in loss
    loss_dict = self.tb_logs.get_loss(session=self.session_id)[self.session_id]
  File "/opt/faceswap/lib/gui/stats.py", line 61, in get_loss
    for event in tf.train.summary_iterator(logfile):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/summary/summary_iterator.py", line 68, in summary_iterator
    for r in tf_record.tf_record_iterator(path):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py", line 181, in tf_record_iterator
    reader.GetNext()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 489, in GetNext
    return _pywrap_tensorflow_internal.PyRecordReader_GetNext(self)
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 234295
```

**Comment by omen23** [comment]
lol it works for me - with GUI or command line.

**Comment by omen23** [comment]
Hey,
try it with python 3.7 also maybe in a virtualenv.

Kind Regards

Am Fr., 24. Mai 2019 um 00:27 Uhr schrieb Olivier Gagnon <
notifications@github.com>:

**Comment by deepfakes** [comment]
Not that logging. Loss value logging. IE the graph and tensorboard don't work with tf 1.13

**Comment by omen23** [comment]
works for me tho .. hmm ...
![g](https://user-images.githubusercontent.com/1809702/58368649-1325b580-7ef0-11e9-9625-9eabdf2b7237.png)

**Comment by torzdf** [comment]
You're still missing the point. Not the output. Storing the history doesn't work.

**Comment by omen23** [comment]
why does the quality imrpove over time then?

**Comment by omen23** [comment]
OH I see your point - sorry it is about the graphical part - when will the versions be updated so everything works again?
Regards

**Comment by torzdf** [comment]
Python 3.7 and TF 1.13.1 support has been added.
