### ISSUE TITLE
error with extract

### ISSUE THREAD

**Issue by Tettel** [deepfakes/faceswap#742]
I installed the program on Windows. I launch GUI interface and try to make an "extract" command. There is an error when trying to download the detector model. Tried with all the detectors but the same error is coming out.

I read the forums, I didn't find such an error anywhere. Apparently something with my pc, but I installed using the installer for Windows.
http://prntscr.com/nw9zn7

06/01/2019 17:32:03 MainProcess     MainThread      utils           download_model            INFO     Downloading model: 'mtcnn_det' from: https://github.com/deepfakes-models/faceswap-models/releases/download/v1.2.1/mtcnn_det_v1.zip
06/01/2019 17:32:07 MainProcess     MainThread      utils           download_model            DEBUG    header info: {x-amz-id-2: wsJrz9DnQZFW48l71fOast19lfZy6a6IB1V45NfbQFhfbucTjzef5aT+jvMhMSUuuDosUjZoaKo=\nx-amz-request-id: B3E655FCDDFFE3D7\nDate: Sat, 01 Jun 2019 12:32:10 GMT\nLast-Modified: Mon, 06 May 2019 17:49:23 GMT\nETag: "37c1f441c72e18f6bf2e698f406b8cc5"\nContent-Disposition: attachment; filename=mtcnn_det_v1.zip\nAccept-Ranges: bytes\nContent-Type: application/octet-stream\nContent-Length: 1853013\nServer: AmazonS3\nConnection: close\n\n}
06/01/2019 17:32:07 MainProcess     MainThread      utils           download_model            DEBUG    Return Code: 200
Traceback (most recent call last):
  File "C:\Users\User\faceswap\lib\cli.py", line 109, in execute_script
    process = script(arguments)
  File "C:\Users\User\faceswap\scripts\extract.py", line 38, in __init__
    self.args.min_size)
  File "C:\Users\User\faceswap\plugins\extract\pipeline.py", line 31, in __init__
    self.detector = self.load_detector(detector, loglevel, rotate_images, min_size)
  File "C:\Users\User\faceswap\plugins\extract\pipeline.py", line 78, in load_detector
    min_size=min_size)
  File "C:\Users\User\faceswap\plugins\extract\detect\mtcnn.py", line 34, in __init__
    super().__init__(git_model_id=git_model_id, model_filename=model_filename, **kwargs)
  File "C:\Users\User\faceswap\plugins\extract\detect\_base.py", line 54, in __init__
    self.model_path = self.get_model(git_model_id, model_filename)
  File "C:\Users\User\faceswap\plugins\extract\detect\_base.py", line 107, in get_model
    model = GetModel(model_filename, cache_path, git_model_id)
  File "C:\Users\User\faceswap\lib\utils.py", line 253, in __init__
    self.get()
  File "C:\Users\User\faceswap\lib\utils.py", line 341, in get
    self.download_model()
  File "C:\Users\User\faceswap\lib\utils.py", line 357, in download_model
    self.write_zipfile(response, downloaded_size)
  File "C:\Users\User\faceswap\lib\utils.py", line 384, in write_zipfile
    unit_divisor=1024)
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tqdm\_tqdm.py", line 662, in __init__
    TqdmKeyError("Unknown argument(s): " + str(kwargs)))
tqdm._tqdm.TqdmKeyError: "Unknown argument(s): {'unit_divisor': 1024}"

**Comment by Tettel** [comment]
Solved the problem by updating tqdm
