### ISSUE TITLE
ModuleNotFoundError: No module named 'pynvx'

### ISSUE THREAD

**Issue by obiwankenoobi** [deepfakes/faceswap#743]
**Describe the bug**
trying to run the program by using `python3.6 faceswap.py -h` and can't move forward because it crash right a way with the error 

```
$python3.6 faceswap.py -h
pyenv-implicit: found multiple python3.6 in pyenv. Use version 3.6.2.
Traceback (most recent call last):
  File "faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "/faceswap/lib/cli.py", line 13, in <module>
    from lib.logger import crash_log, log_setup
  File "/faceswap/lib/logger.py", line 16, in <module>
    from lib.sysinfo import sysinfo
  File "/faceswap/lib/sysinfo.py", line 13, in <module>
    from lib.gpu_stats import GPUStats
  File "/faceswap/lib/gpu_stats.py", line 9, in <module>
    import pynvx  # pylint: disable=import-error
ModuleNotFoundError: No module named 'pynvx'
```

**To Reproduce**
```
python3.6 setup.py      
python3.6 faceswap.py -h
```

**Expected behavior**
program to run
.
**Desktop (please complete the following information):**
 - OS: [macOS 10.14.5]

**Comment by torzdf** [comment]
`pip install pynvx`

**Comment by obiwankenoobi** [comment]
Thanks for quick reply! I tried the suggestions and got this error: 
```
Cleaning up...
Command /Users/user/.pyenv/versions/3.4.0/bin/python3.4 -c "import setuptools, tokenize;__file__='/private/var/folders/yw/y2_zx6wd0hq286ccjddngy0m0000gn/T/pip_build_artiumsirchenko/pynvx/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/yw/y2_zx6wd0hq286ccjddngy0m0000gn/T/pip-owx06yd6-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/yw/y2_zx6wd0hq286ccjddngy0m0000gn/T/pip_build_artiumsirchenko/pynvx
Storing debug log for failure in /Users/user/.pip/pip.log
```

I suspect its something related to the python version? Have any clue what what it?

**Comment by torzdf** [comment]
This is now either an issue with pyvnx or your setup. I recommend using MiniConda, or contacting the author of pynvx on his github page.

Either way, it's out of scope.
