### ISSUE TITLE
crash while training

### ISSUE THREAD

**Issue by obiwankenoobi** [deepfakes/faceswap#746]
**Describe the bug**
running `python3.6 faceswap.py train` crash  

**To Reproduce**
`python3.6 faceswap.py train -A face_1 -B face_2 -m ./models  -t lightweight -bs 8`

**Expected behavior**
keep trainning

**Additional context**
```
Traceback (most recent call last):
  File "/Users/user_path/faceswap/lib/multithreading.py", line 266, in _runner
    target(*args, **kwargs)
  File "/Users/user_path/faceswap/lib/training_data.py", line 90, in load_batches
    self.validate_samples(images)
  File "/Users/user_path/faceswap/lib/training_data.py", line 125, in validate_samples
    assert length >= self.batchsize, msg
AssertionError: Number of images is lower than batch-size (Note that too few images may lead to bad training). # images: 7, batch-size: 8
06/02/2019 00:44:30 SpawnProcess-2  MainThread      multithreading  _runner                   DEBUG    FixedProducerDispatcher worker for <bound method TrainingDataGenerator.load_batches of <lib.training_data.TrainingDataGenerator object at 0x1220df400>> shutdown
06/02/2019 00:44:30 MainProcess     training_0      multithreading  __init__                  DEBUG    Initialized FixedProducerDispatcher
06/02/2019 00:44:30 MainProcess     training_0      training_data   minibatch_ab              DEBUG    Batching to queue: (side: 'b', is_timelapse: False)
06/02/2019 00:44:30 MainProcess     training_0      _base           set_tensorboard           DEBUG    Enabling TensorBoard Logging
06/02/2019 00:44:30 MainProcess     training_0      _base           set_tensorboard           DEBUG    Setting up TensorBoard Logging. Side: a
06/02/2019 00:44:30 MainProcess     training_0      _base           name                      DEBUG    model name: 'lightweight'
06/02/2019 00:44:30 MainProcess     training_0      _base           set_tensorboard           DEBUG    Setting up TensorBoard Logging. Side: b
06/02/2019 00:44:30 MainProcess     training_0      _base           name                      DEBUG    model name: 'lightweight'
06/02/2019 00:44:30 MainProcess     training_0      _base           set_tensorboard           INFO     Enabled TensorBoard Logging
06/02/2019 00:44:30 MainProcess     training_0      _base           use_mask                  DEBUG    False
06/02/2019 00:44:30 MainProcess     training_0      _base           __init__                  DEBUG    Initializing Samples: model: '<plugins.train.model.lightweight.Model object at 0x13f2bd438>', use_mask: False, coverage_ratio: 0.6241947029348605)
06/02/2019 00:44:30 MainProcess     training_0      _base           __init__                  DEBUG    Initialized Samples
06/02/2019 00:44:30 MainProcess     training_0      _base           use_mask                  DEBUG    False
06/02/2019 00:44:30 MainProcess     training_0      _base           __init__                  DEBUG    Initializing Timelapse: model: <plugins.train.model.lightweight.Model object at 0x13f2bd438>, use_mask: False, coverage_ratio: 0.6241947029348605, batchers: '{'a': <plugins.train.trainer._base.Batcher object at 0x157ad6898>, 'b': <plugins.train.trainer._base.Batcher object at 0x158370f28>}')
06/02/2019 00:44:30 MainProcess     training_0      _base           __init__                  DEBUG    Initializing Samples: model: '<plugins.train.model.lightweight.Model object at 0x13f2bd438>', use_mask: False, coverage_ratio: 0.6241947029348605)
06/02/2019 00:44:30 MainProcess     training_0      _base           __init__                  DEBUG    Initialized Samples
06/02/2019 00:44:30 MainProcess     training_0      _base           __init__                  DEBUG    Initialized Timelapse
06/02/2019 00:44:30 MainProcess     training_0      _base           __init__                  DEBUG    Initialized TrainerBase
06/02/2019 00:44:30 MainProcess     training_0      train           load_trainer              DEBUG    Loaded Trainer
06/02/2019 00:44:30 MainProcess     training_0      train           run_training_cycle        DEBUG    Running Training Cycle
06/02/2019 00:44:30 MainProcess     training_0      training_data   minibatch                 DEBUG    Launching minibatch generator for queue (side: 'a', is_timelapse: False)
06/02/2019 00:44:30 MainProcess     training_0      training_data   minibatch                 DEBUG    Finished minibatch generator for queue: (side: 'a', is_timelapse: False)
06/02/2019 00:44:30 MainProcess     training_0      multithreading  run                       DEBUG    Error in thread (training_0):
06/02/2019 00:44:30 SpawnProcess-3  MainThread      multithreading  _runner                   DEBUG    FixedProducerDispatcher worker for <bound method TrainingDataGenerator.load_batches of <lib.training_data.TrainingDataGenerator object at 0x11b7b6438>> started
06/02/2019 00:44:30 SpawnProcess-3  MainThread      training_data   load_batches              DEBUG    Loading batch: (image_count: 7, side: 'b', is_timelapse: False, do_shuffle: True)
06/02/2019 00:44:30 SpawnProcess-3  MainThread      multithreading  _runner                   ERROR    Number of images is lower than batch-size (Note that too few images may lead to bad training). # images: 7, batch-size: 8
Traceback (most recent call last):
  File "/Users/user_path/faceswap/lib/multithreading.py", line 266, in _runner
    target(*args, **kwargs)
  File "/Users/user_path/faceswap/lib/training_data.py", line 90, in load_batches
    self.validate_samples(images)
  File "/Users/user_path/faceswap/lib/training_data.py", line 125, in validate_samples
    assert length >= self.batchsize, msg
AssertionError: Number of images is lower than batch-size (Note that too few images may lead to bad training). # images: 7, batch-size: 8
06/02/2019 00:44:30 SpawnProcess-3  MainThread      multithreading  _runner                   DEBUG    FixedProducerDispatcher worker for <bound method TrainingDataGenerator.load_batches of <lib.training_data.TrainingDataGenerator object at 0x11b7b6438>> shutdown
06/02/2019 00:44:31 MainProcess     MainThread      train           monitor                   DEBUG    Thread error detected
06/02/2019 00:44:31 MainProcess     MainThread      train           monitor                   DEBUG    Closed Monitor
06/02/2019 00:44:31 MainProcess     MainThread      train           end_thread                DEBUG    Ending Training thread
06/02/2019 00:44:31 MainProcess     MainThread      train           end_thread                CRITICAL Error caught! Exiting...
06/02/2019 00:44:31 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'training'
06/02/2019 00:44:31 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'training_0'
06/02/2019 00:44:31 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: 'training_0'
Traceback (most recent call last):
  File "/Users/user_path/faceswap/lib/cli.py", line 110, in execute_script
    process.process()
  File "/Users/user_path/faceswap/scripts/train.py", line 98, in process
    self.end_thread(thread, err)
  File "/Users/user_path/faceswap/scripts/train.py", line 123, in end_thread
    thread.join()
  File "/Users/user_path/faceswap/lib/multithreading.py", line 460, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/Users/user_path/faceswap/lib/multithreading.py", line 390, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user_path/faceswap/scripts/train.py", line 149, in training
    raise err
  File "/Users/user_path/faceswap/scripts/train.py", line 139, in training
    self.run_training_cycle(model, trainer)
  File "/Users/user_path/faceswap/scripts/train.py", line 214, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "/Users/user_path/faceswap/plugins/train/trainer/_base.py", line 153, in train_one_step
    loss[side] = batcher.train_one_batch(do_preview)
  File "/Users/user_path/faceswap/plugins/train/trainer/_base.py", line 234, in train_one_batch
    batch = self.get_next(do_preview)
  File "/Users/user_path/faceswap/plugins/train/trainer/_base.py", line 242, in get_next
    batch = next(self.feed)
StopIteration

============ System Information ============
encoding:            UTF-8
git_branch:          master
git_commits:         26836a4 Bugfixes. 6b7efa4 Convert: Add manual balance color adjustment plugin. 236c35f Convert settings tool (#737). 919b672 Bugfix: save interval on extract (#740). 66cee3e Pin imageio to version 2.5.0
gpu_cuda:            Unsupported OS
gpu_cudnn:           Unsupported OS
gpu_devices:         
gpu_devices_active:  
gpu_driver:          0
gpu_vram:            
os_machine:          x86_64
os_platform:         Darwin-18.6.0-x86_64-i386-64bit
os_release:          18.6.0
py_command:          faceswap.py train -A face_1 -B face_2 -m ./models -t lightweight -bs 8
py_conda_version:    N/A
py_implementation:   CPython
py_version:          3.6.0
py_virtual_env:      True
sys_cores:           12
sys_processor:       i386
sys_ram:             Total: 16384MB, Available: 7787MB, Used: 6293MB, Free: 2940MB

=============== Pip Packages ===============
absl-py==0.7.1
astor==0.8.0
cycler==0.10.0
Django==2.2.1
estimator==0.0.10
fastcluster==1.1.25
gast==0.2.2
grpcio==1.21.1
h5py==2.9.0
image==1.5.27
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==3.1.0
mock==3.0.5
numpy==1.16.4
opencv-python==4.1.0.25
Pillow==6.0.0
protobuf==3.8.0
psutil==5.6.2
pynvx==1.0.0
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2019.1
PyYAML==5.1
scipy==1.3.0
six==1.12.0
sqlparse==0.3.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
tqdm==4.32.1
train==0.0.3
Werkzeug==0.15.4
```

**Comment by torzdf** [comment]
Too few images in training set.
