### ISSUE TITLE
The problem with training and GPU

### ISSUE THREAD

**Issue by Tettel** [deepfakes/faceswap#750]
*Hey. I ask for help. Already the second day I can not train images using the GPU.*
I have already reinstalled faceswap several times.
Used installer for windows.
Installed, reinstalled "CUDA & CUDDN" using different versions.

When installing using the installer for windows, I see that it installs tensorflow version 1.12.0 for my computer, but because I have CUDA 10.0, I see errors when I use tesorflow and trying to extract. I reinstall after this on the tensorflow version 1.13.1.

Further, if I use the CPU, there is no problem, but when I try to use the GPU, problems flow. I don’t know what to do, because I tried to reinstall the front end of the installation several times by experimenting with different versions of CUda, tensorflow, etc.

i think, the problem is somewhere I have, but because I was already tired of trying, I do not know what to do.

```Loading...
06/05/2019 00:02:27 INFO     Log level set to: INFO
Using TensorFlow backend.
06/05/2019 00:02:28 INFO     Model A Directory: H:\faceswap-examples\1\amalfaces
06/05/2019 00:02:28 INFO     Model B Directory: H:\faceswap-examples\1\ruslanfaces
06/05/2019 00:02:28 INFO     Training data directory: H:\faceswap-examples\1\amal_compare_with_ruslan\original_logs
06/05/2019 00:02:28 INFO     ===============================================
06/05/2019 00:02:28 INFO     - Starting                                    -
06/05/2019 00:02:28 INFO     - Press 'ENTER' to save and quit              -
06/05/2019 00:02:28 INFO     - Press 'S' to save model weights immediately -
06/05/2019 00:02:28 INFO     ===============================================
06/05/2019 00:02:29 INFO     Loading data, this may take a while...
06/05/2019 00:02:29 INFO     Loading Model from Realface plugin...
06/05/2019 00:02:30 WARNING  No existing state file found. Generating.
06/05/2019 00:02:30 WARNING  From C:\ProgramData\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nColocations handled automatically by placer.
06/05/2019 00:02:33 INFO     Creating new 'realface' model in folder: 'H:\faceswap-examples\1\amal_compare_with_ruslan\original_logs'
06/05/2019 00:02:33 INFO     Loading Trainer from Original plugin...
06/05/2019 00:02:33 INFO     Reading alignments from: 'H:\faceswap-examples\1\amal_alignments.json'
06/05/2019 00:02:34 INFO     Reading alignments from: 'H:\faceswap-examples\1\ruslan_cutted_alignments.json'
06/05/2019 00:02:41 INFO     Enabled TensorBoard Logging
06/05/2019 00:02:41 WARNING  From C:\ProgramData\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.
06/05/2019 00:03:00 CRITICAL Error caught! Exiting...
06/05/2019 00:03:00 ERROR    Caught exception in thread: 'training_0'
06/05/2019 00:03:03 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "D:\face\faceswap\lib\cli.py", line 110, in execute_script
process.process()
File "D:\face\faceswap\scripts\train.py", line 98, in process
self.end_thread(thread, err)
File "D:\face\faceswap\scripts\train.py", line 123, in end_thread
thread.join()
File "D:\face\faceswap\lib\multithreading.py", line 460, in join
raise thread.err[1].with_traceback(thread.err[2])
File "D:\face\faceswap\lib\multithreading.py", line 390, in run
self._target(*self._args, **self._kwargs)
File "D:\face\faceswap\scripts\train.py", line 149, in training
raise err
File "D:\face\faceswap\scripts\train.py", line 139, in training
self.run_training_cycle(model, trainer)
File "D:\face\faceswap\scripts\train.py", line 217, in run_training_cycle
trainer.train_one_step(viewer, timelapse)
File "D:\face\faceswap\plugins\train\trainer\_base.py", line 153, in train_one_step
loss[side] = batcher.train_one_batch(do_preview)
File "D:\face\faceswap\plugins\train\trainer\_base.py", line 235, in train_one_batch
loss = self.model.predictors[self.side].train_on_batch(*batch)
File "C:\ProgramData\Anaconda3\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
outputs = self.train_function(ins)
File "C:\ProgramData\Anaconda3\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
return self._call(inputs)
File "C:\ProgramData\Anaconda3\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
fetched = self._callable_fn(*array_vals)
File "C:\ProgramData\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
run_metadata_ptr)
File "C:\ProgramData\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16384,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[{{node training/Adam/mul_161}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[[{{node loss/add}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

06/05/2019 00:03:03 CRITICAL An unexpected crash has occurred. Crash report written to D:\face\faceswap\crash_report.2019.06.05.000300415383.log. Please verify you are running the latest version of faceswap before reporting
Process exited.

```

**Comment by Tettel** [comment]
```
============ System Information ============
encoding:            cp1251
git_branch:          master
git_commits:         081da3c Merge branch 'master' into staging
gpu_cuda:            10.0
gpu_cudnn:           7.4.1
gpu_devices:         GPU_0: GeForce GTX 1050 Ti
gpu_devices_active:  GPU_0
gpu_driver:          417.01
gpu_vram:            GPU_0: 4096MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.15063-SP0
os_release:          10
py_command:          D:\face\faceswap/faceswap.py gui
py_conda_version:    conda 4.6.11
py_implementation:   CPython
py_version:          3.6.8
py_virtual_env:      True
sys_cores:           4
sys_processor:       Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
sys_ram:             Total: 8147MB, Available: 4903MB, Used: 3243MB, Free: 4903MB

=============== Pip Packages ===============
absl-py==0.7.1
aioChatbase==1.0.0
aiodownload==0.2.5
aiogram==1.4
aiohttp==3.4.4
aiohttp-requests==0.1.2
aiourllib==0.1.3
aliexpress-api-client==1.2
args==0.1.0
aspy.yaml==1.1.1
astor==0.7.1
async-timeout==3.0.0
Automat==0.7.0
cached-property==1.5.1
cchardet==2.1.1
certifi==2018.10.15
cfgv==1.1.0
click==6.7
clint==0.5.1
cloudpickle==1.0.0
constantly==15.1.0
contextvars==2.3
cycler==0.10.0
cytoolz==0.9.0.1
dask==1.2.2
decorator==4.4.0
fastcluster==1.1.25
ffmpy==0.2.2
filelock==3.0.9
gast==0.2.2
google==2.0.1
google-search==1.0.2
googletrans==2.3.0
grpcio==1.16.1
h5py==2.9.0
hyperlink==18.0.0
identify==1.1.7
imageio==2.5.0
imageio-ffmpeg==0.3.0
immutables==0.6
incremental==17.5.0
InstagramAPI==1.0.1
joblib==0.13.2
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.1.0
Markdown==3.1
matplotlib==2.2.2
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mock==3.0.5
moviepy==0.2.3.2
networkx==2.3
nodeenv==1.3.2
numpy==1.16.2
nvidia-ml-py3==7.352.0
olefile==0.46
opencv-python==4.1.0.25
outcome==1.0.0
parse==1.8.4
pathlib==1.0.1
Pillow==6.0.0
pluggy==0.8.0
pre-commit==1.11.2
protobuf==3.7.1
psutil==5.4.8
psycopg2==2.7.5
py==1.7.0
PyHamcrest==1.9.0
pymediawiki==0.4.1
pyocclient==0.4
pyparsing==2.4.0
pyreadline==2.1
python-dateutil==2.8.0
python3-weather-api==0.0.3rc0
pytube==9.2.2
pytz==2019.1
PyWavelets==1.0.3
PyYAML==3.13
qiwipy==2.1.4
qrcode==6.1
requests==2.11.1
requests-toolbelt==0.7.0
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.2.1
six==1.12.0
sniffio==1.0.0
sortedcontainers==2.0.5
SQLAlchemy==1.2.12
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1
termcolor==1.1.0
toml==0.10.0
toolz==0.9.0
toposort==1.5
tornado==6.0.2
tox==3.5.2
tqdm==4.31.1
translate==3.5.0
trio==0.8.0
unittest-data-provider==1.0.1
urllib3-mock==0.3.3
urllib5==5.0.0
weather-api==1.0.6
Werkzeug==0.15.2
Wikipedia-API==0.3.7
wincertstore==0.2
zope.interface==4.5.0

============== Conda Packages ==============
Could not get package list

```

**Comment by torzdf** [comment]
OOM = Out of Memory.
You will not be able to train RealFace on a 4GB card.

**Comment by Tettel** [comment]
i tryed on Original and another :/

**Comment by torzdf** [comment]
https://github.com/deepfakes/faceswap/issues/660#issuecomment-472808285
