### ISSUE TITLE
faceswap.py gices errors

### ISSUE THREAD

**Issue by marvic2409** [deepfakes/faceswap#753]
**Describe the bug**

I am running on windows 10, I am using a amd gpu but am using it through plaidml-keras. When I run the command python faceswap.py extract -i Subject_A/frames -o Subject_A/faces I get the errors:

Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "C:\Users\marti\faceswap\lib\cli.py", line 81, in execute_script
    process.process()
  File "C:\Users\marti\faceswap\scripts\extract.py", line 49, in process
    self.extract_single_process()
  File "C:\Users\marti\faceswap\scripts\extract.py", line 66, in extract_single_process
    filename, faces = self.process_single_image(filename)
  File "C:\Users\marti\faceswap\scripts\extract.py", line 103, in process_single_image
    process_faces = [[idx, face] for idx, face in faces]
  File "C:\Users\marti\faceswap\scripts\extract.py", line 103, in <listcomp>
    process_faces = [[idx, face] for idx, face in faces]
  File "C:\Users\marti\faceswap\scripts\fsmedia.py", line 215, in get_faces
    for face in faces:
  File "C:\Users\marti\faceswap\lib\faces_detect.py", line 14, in detect_faces
    verbose)
  File "C:\Users\marti\faceswap\lib\face_alignment\extractor.py", line 257, in __init__
    self.initialize(mtcnn_kwargs, dlib_buffer)
  File "C:\Users\marti\faceswap\lib\face_alignment\extractor.py", line 280, in initialize
    self.initialize_detector(mtcnn_kwargs)
  File "C:\Users\marti\faceswap\lib\face_alignment\extractor.py", line 320, in initialize_detector
    self.detector.create_detector(**kwargs)
  File "C:\Users\marti\faceswap\lib\face_alignment\detectors.py", line 172, in create_detector
    pnet, rnet, onet = create_mtcnn(mtcnn_session, self.data_path)
  File "C:\Users\marti\faceswap\lib\face_alignment\mtcnn.py", line 288, in create_mtcnn
    pnet.load(os.path.join(model_path, 'det1.npy'), sess)
  File "C:\Users\marti\faceswap\lib\face_alignment\mtcnn.py", line 90, in load
    data_dict = np.load(data_path, encoding='latin1').item() #pylint: disable=no-member
  File "C:\Users\marti\faceswap\faceswap_env\lib\site-packages\numpy\lib\npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "C:\Users\marti\faceswap\faceswap_env\lib\site-packages\numpy\lib\format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by torzdf** [comment]
None of the extractors are written in Keras. They are written in source Tensorflow, so PlaidML is unlikely to pick them up.

We do not directly support PlaidML at this time, unfortunately.

**Comment by marvic2409** [comment]
I fixed it somehow anyways

**Comment by siddas27** [comment]
@marvic2409 how did you fix this?
