### ISSUE TITLE
06/22/2019 21:03:45 CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\PC\faceswap\crash_report.2019.06.22.210339802226.log.

### ISSUE THREAD

**Issue by z-Nathan-z** [deepfakes/faceswap#770]
2019-06-22 21:03:45.875703: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
2019-06-22 21:03:45.876067: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
2019-06-22 21:03:45.876277: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
2019-06-22 21:03:45.876503: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
2019-06-22 21:03:45.876708: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
2019-06-22 21:03:45.876905: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
2019-06-22 21:03:45.877084: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
2019-06-22 21:03:45.877263: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
2019-06-22 21:03:45.877458: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
2019-06-22 21:03:45.877688: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001F8F1934770: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
Exception ignored in: <generator object TrainingDataGenerator.minibatch at 0x000001F8E85EB888>
Traceback (most recent call last):
File "C:\Users\PC\faceswap\lib\training_data.py", line 148, in minibatch
File "C:\Users\PC\faceswap\lib\multithreading.py", line 48, in __exit__
File "C:\Users\PC\faceswap\lib\multithreading.py", line 40, in free
File "C:\Users\PC\faceswap\lib\multithreading.py", line 178, in free
File "<string>", line 2, in put
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\multiprocessing\managers.py", line 753, in _callmethod
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\multiprocessing\managers.py", line 740, in _connect
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\multiprocessing\connection.py", line 485, in Client
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\multiprocessing\connection.py", line 686, in PipeClient
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <generator object TrainingDataGenerator.minibatch at 0x000001F8E85EB6D0>
Traceback (most recent call last):
File "C:\Users\PC\faceswap\lib\training_data.py", line 148, in minibatch
File "C:\Users\PC\faceswap\lib\multithreading.py", line 48, in __exit__
File "C:\Users\PC\faceswap\lib\multithreading.py", line 40, in free
File "C:\Users\PC\faceswap\lib\multithreading.py", line 178, in free
File "<string>", line 2, in put
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\multiprocessing\managers.py", line 753, in _callmethod
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\multiprocessing\managers.py", line 740, in _connect
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\multiprocessing\connection.py", line 485, in Client
File "C:\Users\PC\MiniConda3\envs\faceswap\lib\multiprocessing\connection.py", line 686, in PipeClient
FileNotFoundError: [WinError 2] The system cannot find the file specified
Process exited.

THIS HAPPEN WHEN RUNNING THE PROGRAM AFTER 5 MINUTES

**Comment by torzdf** [comment]
1) We would need the crash report.
2) This is a CUDA error. Not a Faceswap error

**Comment by z-Nathan-z** [comment]
How  would I go about fixing the error so it will work properly in the
future?

Many thanks
Nathan L

**Comment by torzdf** [comment]
We would need the crash report.

**Comment by z-Nathan-z** [comment]
here you are
