### ISSUE TITLE
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found

### ISSUE THREAD

**Issue by zhuiyi1997** [deepfakes/faceswap#778]
Traceback (most recent call last):
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pynvml.py", line 644, in _LoadNvmlLibrary
nvmlLib = CDLL("libnvidia-ml.so.1")
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/ctypes/__init__.py", line 356, in __init__
self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/data/github/faceswap-master/lib/cli.py", line 123, in execute_script
process = script(arguments)
File "/data/github/faceswap-master/scripts/extract.py", line 42, in __init__
normalize_method=normalization)
File "/data/github/faceswap-master/plugins/extract/pipeline.py", line 36, in __init__
self.is_parallel = self.set_parallel_processing(multiprocess)
File "/data/github/faceswap-master/plugins/extract/pipeline.py", line 109, in set_parallel_processing
gpu_stats = GPUStats()
File "/data/github/faceswap-master/lib/gpu_stats.py", line 45, in __init__
self.initialize(log)
File "/data/github/faceswap-master/lib/gpu_stats.py", line 92, in initialize
raise err
File "/data/github/faceswap-master/lib/gpu_stats.py", line 85, in initialize
pynvml.nvmlInit()
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pynvml.py", line 608, in nvmlInit
_LoadNvmlLibrary()
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pynvml.py", line 646, in _LoadNvmlLibrary
_nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pynvml.py", line 310, in _nvmlCheckReturn
raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pynvml.py", line 644, in _LoadNvmlLibrary
nvmlLib = CDLL("libnvidia-ml.so.1")
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/ctypes/__init__.py", line 356, in __init__
self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/data/github/faceswap-master/faceswap.py", line 36, in <module>
ARGUMENTS.func(ARGUMENTS)
File "/data/github/faceswap-master/lib/cli.py", line 130, in execute_script
crash_file = crash_log()
File "/data/github/faceswap-master/lib/logger.py", line 158, in crash_log
from lib.sysinfo import sysinfo
File "/data/github/faceswap-master/lib/sysinfo.py", line 355, in <module>
sysinfo = SysInfo()  # pylint: disable=invalid-name
File "/data/github/faceswap-master/lib/sysinfo.py", line 21, in __init__
gpu_stats = GPUStats(log=False)
File "/data/github/faceswap-master/lib/gpu_stats.py", line 45, in __init__
self.initialize(log)
File "/data/github/faceswap-master/lib/gpu_stats.py", line 92, in initialize
raise err
File "/data/github/faceswap-master/lib/gpu_stats.py", line 85, in initialize
pynvml.nvmlInit()
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pynvml.py", line 608, in nvmlInit
_LoadNvmlLibrary()
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pynvml.py", line 646, in _LoadNvmlLibrary
_nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
File "/home/ytc/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pynvml.py", line 310, in _nvmlCheckReturn
raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found

**Comment by torzdf** [comment]
There was an error reading from the Nvidia Machine Learning Library. The most likely cause is incorrectly installed drivers. Please remove and reinstall your Nvidia drivers.

**Comment by HyperSimon** [comment]
问题解决了吗？
