### ISSUE TITLE
cv2 Error

### ISSUE THREAD

**Issue by aaronmartin1651** [deepfakes/faceswap#819]
**Describe the bug**
I have been playing around with faceswap and made a few successful gif files from images.  I have started receiving this error any time I try to patch the images back together, and can no longer build a video.  It stops at around 33%.  I have confirmed that there are no 0 byte files and that the images are all named in sequence.  Any idea what I am missing?

**To Reproduce**
python faceswap.py convert -i D:\FS2\video\P\A\5 -o D:\FS2\video\P\A\5\swap -m D:\FS2\video\FS_Models\K-A\models

**Error**
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

I am running via GPU not CPU.
I have reinstalled faceswap
I have tried with both command line and gui

**CRASHLOG**

```
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     save_0          convert         save                      DEBUG    Writing GUI Preview image: 'D:\FS2\video\P\A\5\swap\.gui_preview.jpg'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:11 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:11 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 MainProcess     predict_faces_0 _base           largest_face_index        DEBUG    0
07/30/2019 19:14:12 MainProcess     load_0          pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
07/30/2019 19:14:12 Aligner.run     MainThread      _base           run                       ERROR    Caught exception in child process: 3104
07/30/2019 19:14:12 MainProcess     load_0          multithreading  run                       DEBUG    Error in thread (load_0): Error in child process 3104. Traceback (most recent call last):\n File "C:\Users\username\faceswap\plugins\extract\align\_base.py", line 112, in run\n self.align(*args, **kwargs)\n File "C:\Users\username\faceswap\plugins\extract\align\_base.py", line 138, in align\n item["landmarks"] = self.process_landmarks(image, item["detected_faces"])\n File "C:\Users\username\faceswap\plugins\extract\align\_base.py", line 168, in process_landmarks\n feed_dict = self.align_image(detected_face, image)\n File "C:\Users\username\faceswap\plugins\extract\align\cv2_dnn.py", line 90, in align_image\n interpolation=interpolation)\ncv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n\n
07/30/2019 19:14:13 MainProcess     MainThread      multithreading  check_and_raise_error     DEBUG    Thread error caught: [(<class 'Exception'>, Exception('Error in child process 3104. Traceback (most recent call last):\n File "C:\\Users\\username\\faceswap\\plugins\\extract\\align\\_base.py", line 112, in run\n self.align(*args, **kwargs)\n File "C:\\Users\\username\\faceswap\\plugins\\extract\\align\\_base.py", line 138, in align\n item["landmarks"] = self.process_landmarks(image, item["detected_faces"])\n File "C:\\Users\\username\\faceswap\\plugins\\extract\\align\\_base.py", line 168, in process_landmarks\n feed_dict = self.align_image(detected_face, image)\n File "C:\\Users\\username\\faceswap\\plugins\\extract\\align\\cv2_dnn.py", line 90, in align_image\n interpolation=interpolation)\ncv2.error: OpenCV(4.1.0) C:\\projects\\opencv-python\\opencv\\modules\\imgproc\\src\\resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function \'cv::resize\'\n\n',), <traceback object at 0x00000233D33E5D08>)]
Traceback (most recent call last):
  File "C:\Users\username\faceswap\lib\cli.py", line 122, in execute_script
    process.process()
  File "C:\Users\username\faceswap\scripts\convert.py", line 103, in process
    self.convert_images()
  File "C:\Users\username\faceswap\scripts\convert.py", line 131, in convert_images
    self.check_thread_error()
  File "C:\Users\username\faceswap\scripts\convert.py", line 153, in check_thread_error
    thread.check_and_raise_error()
  File "C:\Users\username\faceswap\lib\multithreading.py", line 433, in check_and_raise_error
    raise error[1].with_traceback(error[2])
  File "C:\Users\username\faceswap\lib\multithreading.py", line 391, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\username\faceswap\scripts\convert.py", line 328, in load
    detected_faces = self.get_detected_faces(filename, image)
  File "C:\Users\username\faceswap\scripts\convert.py", line 357, in get_detected_faces
    detected_faces = self.detect_faces(filename, image)
  File "C:\Users\username\faceswap\scripts\convert.py", line 388, in detect_faces
    faces = next(self.extractor.detected_faces())
  File "C:\Users\username\faceswap\plugins\extract\pipeline.py", line 258, in detected_faces
    raise Exception(err)
Exception: Error in child process 3104. Traceback (most recent call last):
  File "C:\Users\username\faceswap\plugins\extract\align\_base.py", line 112, in run
    self.align(*args, **kwargs)
  File "C:\Users\username\faceswap\plugins\extract\align\_base.py", line 138, in align
    item["landmarks"] = self.process_landmarks(image, item["detected_faces"])
  File "C:\Users\username\faceswap\plugins\extract\align\_base.py", line 168, in process_landmarks
    feed_dict = self.align_image(detected_face, image)
  File "C:\Users\username\faceswap\plugins\extract\align\cv2_dnn.py", line 90, in align_image
    interpolation=interpolation)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'



============ System Information ============
encoding:            cp1252
git_branch:          master
git_commits:         c094128 bugfix: GUI: Display system info - show error message on failure. cbdef0b gpu_stats: log unhandled errors and continue. 1d0d721 bugfix: Frame ranges for ffmpeg/gif writers. 0132d32 Bugfix: Preview Tool - empty tk_var string. c6319ca Model output size assertions fix (#816)
gpu_cuda:            9.0
gpu_cudnn:           7.6.2
gpu_devices:         GPU_0: GeForce GTX 1080
gpu_devices_active:  GPU_0
gpu_driver:          431.60
gpu_vram:            GPU_0: 8192MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.18362-SP0
os_release:          10
py_command:          C:\Users\username\faceswap\faceswap.py convert -i D:/FS2/video/P/A/5 -o D:/FS2/video/P/A/5/swap -l 0.4 -m D:/FS2/video/FS_Models/K-A/models -ref D:/FS2/video/P/A/4.mp4 -c avg-color -sc sharpen -M predicted -w ffmpeg -osc 100 -j 0 -g 1 -L INFO -gui
py_conda_version:    conda 4.7.10
py_implementation:   CPython
py_version:          3.6.8
py_virtual_env:      True
sys_cores:           8
sys_processor:       Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
sys_ram:             Total: 32705MB, Available: 18723MB, Used: 13981MB, Free: 18723MB

=============== Pip Packages ===============
absl-py==0.7.1
astor==0.7.1
certifi==2019.6.16
cloudpickle==1.2.1
cycler==0.10.0
cytoolz==0.10.0
dask==2.1.0
decorator==4.4.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.2.2
grpcio==1.16.1
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.13.2
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mock==3.0.5
networkx==2.3
numpy==1.16.2
nvidia-ml-py3==7.352.1
olefile==0.46
opencv-python==4.1.0.25
pathlib==1.0.1
Pillow==6.1.0
protobuf==3.8.0
psutil==5.6.3
pyparsing==2.4.0
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
pywin32==223
PyYAML==5.1.1
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.3.0
six==1.12.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
toolz==0.10.0
toposort==1.5
tornado==6.0.3
tqdm==4.32.1
Werkzeug==0.15.4
wincertstore==0.2

============== Conda Packages ==============
# packages in environment at F:\anaconda\envs\faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.1                    py36_0  
astor                     0.7.1                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py36_1  
cloudpickle               1.2.1                      py_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.0                cuda10.0_0  
cycler                    0.10.0           py36h009560c_0  
cytoolz                   0.10.0           py36he774522_0  
dask-core                 2.1.0                      py_0  
decorator                 4.4.0                    py36_1  
fastcluster               1.1.25          py36h830ac7b_1000    conda-forge
ffmpeg                    4.1.3                h6538335_0    conda-forge
ffmpy                     0.2.2                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1  
gast                      0.2.2                    py36_0  
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0            py36h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
imageio                   2.5.0                    py36_0  
imageio-ffmpeg            0.3.0                      py_0    conda-forge
intel-openmp              2019.4                      245  
joblib                    0.13.2                   py36_0  
jpeg                      9b                   hb83a4c4_2  
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py36ha925a31_0  
libmklml                  2019.0.3                      0  
libpng                    1.6.37               h2a8f88b_0  
libprotobuf               3.8.0                h7bd577a_0  
libtiff                   4.0.10               hb898794_2  
markdown                  3.1.1                    py36_0  
matplotlib                2.2.2            py36had4c4a9_2  
mkl                       2019.4                      245  
mkl-service               2.0.2            py36he774522_0  
mkl_fft                   1.0.12           py36h14836fe_0  
mkl_random                1.0.2            py36h343c172_0  
mock                      3.0.5                    py36_0  
networkx                  2.3                        py_0  
numpy                     1.16.2           py36h19fb1c0_0  
numpy-base                1.16.2           py36hc3f5095_0  
nvidia-ml-py3             7.352.1                  pypi_0    pypi
olefile                   0.46                     py36_0  
opencv-python             4.1.0.25                 pypi_0    pypi
openssl                   1.1.1c               he774522_1  
pathlib                   1.0.1                    py36_1  
pillow                    6.1.0            py36hdc69c19_0  
pip                       19.1.1                   py36_0  
protobuf                  3.8.0            py36h33f27b4_0  
psutil                    5.6.3            py36he774522_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py36h6538335_2  
pyreadline                2.1                      py36_1  
python                    3.6.8                h9f7ef89_7  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py36h8c2d366_1  
pywin32                   223              py36hfa6e2cd_1  
pyyaml                    5.1.1            py36he774522_0  
qt                        5.9.7            vc14h73c81de_0  
scikit-image              0.15.0           py36ha925a31_0  
scikit-learn              0.21.2           py36h6288b17_0  
scipy                     1.3.0            py36h29ff71c_0  
setuptools                41.0.1                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.12.0                   py36_0  
sqlite                    3.29.0               he774522_0  
tensorboard               1.13.1           py36h33f27b4_0  
tensorflow                1.13.1          gpu_py36h9006a92_0  
tensorflow-base           1.13.1          gpu_py36h871c8ca_0  
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.13.1               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.10.0                     py_0  
toposort                  1.5                        py_3    conda-forge
tornado                   6.0.3            py36he774522_0  
tqdm                      4.32.1                     py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  
```

**Comment by torzdf** [comment]
You'd need to post the crash log.

**Comment by aaronmartin1651** [comment]
> 
> 
> You'd need to post the crash log.

Just updated the main post with the crash log.  I did a smaller video successfully (2 minutes) this one is about 9 minutes in length.

**Comment by torzdf** [comment]
That suggests that there's a problem with one of your images, or there is a bug in the cv2 DNN detector. If it's the latter, it's unlikely to be addressed any time soon, because it is really the last choice detector.

Either way, in the first instance I would recommend not using on the fly conversion, and generating an alignments file. You will get better results.

See here:
https://faceswap.dev/forum/viewtopic.php?f=5&t=27

**Comment by aaronmartin1651** [comment]
> 
> 
> That suggests that there's a problem with one of your images, or there is a bug in the cv2 DNN detector. If it's the latter, it's unlikely to be addressed any time soon, because it is really the last choice detector.
> 
> Either way, in the first instance I would recommend not using on the fly conversion, and generating an alignments file. You will get better results (and will bypass this potential issue)
> 
> See here:
> https://faceswap.dev/forum/viewtopic.php?f=5&t=27

I created the alignments file and will train with them.  Once complete and ready to perform a conversion, I see that the Convert tab has an Alignments field.  Where should this alignments file come from?  Source Video?  Face A faces?  Face B faces?  I looked around the FAQ and couldn't find that specific answer.

**Comment by torzdf** [comment]
The article linked in the above post explains what alignments are used for, how to create it and how to clean it, If you have generated an alignments file for the source video, then you should be able to leave the alignments field blank.

Usage questions should be directed to our forum or the Discord server
