### ISSUE TITLE
Windows GUI error

### ISSUE THREAD

**Issue by VadVergasov** [deepfakes/faceswap#822]
After training stop, this error occurs:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\faceswap\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\ProgramData\Anaconda3\envs\faceswap\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\Vadim\faceswap\lib\gui\display_analysis.py", line 141, in <lambda>
    self.after(1000, lambda msg=message: self.set_session_summary(msg))
  File "C:\Users\Vadim\faceswap\lib\gui\display_analysis.py", line 144, in set_session_summary
    self.summary = self.thread.get_result()
  File "C:\Users\Vadim\faceswap\lib\gui\utils.py", line 1111, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "C:\Users\Vadim\faceswap\lib\gui\utils.py", line 1090, in run
    retval = self._target(*self._args, **self._kwargs)
  File "C:\Users\Vadim\faceswap\lib\gui\display_analysis.py", line 153, in summarise_data
    return session.full_summary
  File "C:\Users\Vadim\faceswap\lib\gui\stats.py", line 131, in full_summary
    return self.summary.compile_stats()
  File "C:\Users\Vadim\faceswap\lib\gui\stats.py", line 290, in compile_stats
    compiled_stats = self.sessions_stats
  File "C:\Users\Vadim\faceswap\lib\gui\stats.py", line 274, in sessions_stats
    iterations = self.session.get_iterations_for_session(sess_idx)
  File "C:\Users\Vadim\faceswap\lib\gui\stats.py", line 244, in get_iterations_for_session
    session = self.state["sessions"].get(str(session_id), None)
TypeError: 'NoneType' object is not subscriptable
```
It seems all working good, but something not so good.

**Comment by torzdf** [comment]
Are you on the latest code? This bug *should* have been squashed.

**Comment by VadVergasov** [comment]
Yes, I tried to update, but also found a strange thing: I clicked "Check for updates...", then I restarted FaceSwap and ran it again. And every time I'm trying to update I get the following log:
```
08/05/2019 08:32:15 INFO     Checking for updates...
08/05/2019 08:32:15 INFO     Faceswap is up to date.
08/05/2019 08:32:15 INFO     Updating dependencies...
08/05/2019 08:32:15 INFO     Setup in Windows 10
08/05/2019 08:32:15 INFO     Installed Python: 3.6.9 64bit
08/05/2019 08:32:15 INFO     Running in Conda
08/05/2019 08:32:15 INFO     Running in a Virtual Environment
08/05/2019 08:32:15 INFO     Encoding: cp1251
08/05/2019 08:32:15 INFO     Installed pip: 19.1.1
08/05/2019 08:32:17 INFO     Installing Required Python Packages. This may take some time...
08/05/2019 08:32:17 INFO     Installing Pillow>=6.0.0
08/05/2019 08:32:22 INFO     Installing git+https://github.com/deepfakes/nvidia-ml-py3.git
08/05/2019 08:32:25 INFO     git+https://github.com/deepfakes/nvidia-ml-py3.git not available in Conda. Installing with pip
08/05/2019 08:32:25 INFO     Installing git+https://github.com/deepfakes/nvidia-ml-py3.git
08/05/2019 08:32:28 INFO     Dependencies updated
```
Also, I can do it all the time after I ran the program.

**Comment by torzdf** [comment]
That's standard. I'll probably look to pin Pillow, but nvidia-ml-py3 will always check as we had to hold a fork in our github repo.

There is a problem with stock nvidia-ml-py3 that does not work with Windows Update installed Nvidia drivers. Our version fixes this, but unfortunately pip cannot check the version number until it has downloaded the latest git version, so it will attempt to re-install it every time you check for updates.

**Comment by VadVergasov** [comment]
Problem is still here:
```
08/05/2019 15:28:04 INFO     Exit requested! The trainer will complete its current cycle, save the models and quit (This can take a couple of minutes depending on your training speed).
08/05/2019 15:28:09 INFO     [Saved models] - Average since last save: face_loss_A: 0.03513, face_loss_B: 0.04683
Process exited.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\faceswap\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\ProgramData\Anaconda3\envs\faceswap\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\Vadim\faceswap\lib\gui\display_analysis.py", line 141, in <lambda>
    self.after(1000, lambda msg=message: self.set_session_summary(msg))
  File "C:\Users\Vadim\faceswap\lib\gui\display_analysis.py", line 144, in set_session_summary
    self.summary = self.thread.get_result()
  File "C:\Users\Vadim\faceswap\lib\gui\utils.py", line 1111, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "C:\Users\Vadim\faceswap\lib\gui\utils.py", line 1090, in run
    retval = self._target(*self._args, **self._kwargs)
  File "C:\Users\Vadim\faceswap\lib\gui\display_analysis.py", line 153, in summarise_data
    return session.full_summary
  File "C:\Users\Vadim\faceswap\lib\gui\stats.py", line 131, in full_summary
    return self.summary.compile_stats()
  File "C:\Users\Vadim\faceswap\lib\gui\stats.py", line 290, in compile_stats
    compiled_stats = self.sessions_stats
  File "C:\Users\Vadim\faceswap\lib\gui\stats.py", line 274, in sessions_stats
    iterations = self.session.get_iterations_for_session(sess_idx)
  File "C:\Users\Vadim\faceswap\lib\gui\stats.py", line 244, in get_iterations_for_session
    session = self.state["sessions"].get(str(session_id), None)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Zishuo** [comment]
I have the same issue.
Added some print before that line, and it turns out to be "self.state is None"

**Comment by warraich7885** [comment]
I have the same issue. but do not know too much

**Comment by torzdf** [comment]
This is a GUI bug which I thought I had squashed. Make sure you are running with the latest code.

Either way, it won't impact training, just the analysis/graph display.

**Comment by torzdf** [comment]
I'm closing this, as this section has been rewritten. Any new bugs pertaining to this area should open a new issue.
