### ISSUE TITLE
Can't run on  Tesla V100 16GB

### ISSUE THREAD

**Issue by shadowzoom** [deepfakes/faceswap#833]
Loading...
08/12/2019 03:14:02 INFO     Log level set to: DEBUG
08/12/2019 03:14:04 INFO     Output Directory: C:\Users\Administrator\Desktop\out
08/12/2019 03:14:04 INFO     Input Video: C:\Users\Administrator\Desktop\1.mp4
08/12/2019 03:14:04 VERBOSE  Using 'json' serializer for alignments
08/12/2019 03:14:04 VERBOSE  Alignments filepath: 'C:\Users\Administrator\Desktop\1_alignments.json'
08/12/2019 03:14:04 INFO     Loading Detect from Mtcnn plugin...
08/12/2019 03:14:04 VERBOSE  Loading config: 'C:\Users\Administrator\faceswap\config\extract.ini'
08/12/2019 03:14:04 INFO     Loading Align from Fan plugin...
08/12/2019 03:14:04 VERBOSE  Tesla V100-PCIE-16GB - 16288MB free of 16288MB
08/12/2019 03:14:05 INFO     Starting, this may take a while...
08/12/2019 03:14:20 WARNING  FFMPEG hung while attempting to obtain the frame count. Retrying 2 of 3
08/12/2019 03:14:22 INFO     Initializing Face Alignment Network...
08/12/2019 03:14:22 VERBOSE  Using device Tesla V100-PCIE-16GB with 16288MB free of 16288MB
08/12/2019 03:14:22 VERBOSE  Reserving 2240MB for face alignments
08/12/2019 03:14:22 VERBOSE  Initializing Face Alignment Network model...
2019-08-12 03:14:27.485169: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-08-12 03:14:28.054730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: Tesla V100-PCIE-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:05:00.0
totalMemory: 15.91GiB freeMemory: 15.46GiB
2019-08-12 03:14:28.055514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
08/12/2019 03:14:28 ERROR    Caught exception in child process: 4500
08/12/2019 03:14:28 ERROR    Traceback:
Traceback (most recent call last):
File "C:\Users\Administrator\faceswap\plugins\extract\align\_base.py", line 112, in run
self.align(*args, **kwargs)
File "C:\Users\Administrator\faceswap\plugins\extract\align\_base.py", line 127, in align
self.initialize(*args, **kwargs)
File "C:\Users\Administrator\faceswap\plugins\extract\align\fan.py", line 47, in initialize
raise err
File "C:\Users\Administrator\faceswap\plugins\extract\align\fan.py", line 41, in initialize
self.model = FAN(self.model_path, ratio=tf_ratio)
File "C:\Users\Administrator\faceswap\plugins\extract\align\fan.py", line 199, in __init__
self.session = self.set_session(ratio)
File "C:\Users\Administrator\faceswap\plugins\extract\align\fan.py", line 221, in set_session
session = self.tf.Session(config=config)
File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1551, in __init__
super(Session, self).__init__(target, graph, config=config)
File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 676, in __init__
self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
08/12/2019 03:14:34 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "C:\Users\Administrator\faceswap\lib\cli.py", line 125, in execute_script
process.process()
File "C:\Users\Administrator\faceswap\scripts\extract.py", line 62, in process
self.run_extraction()
File "C:\Users\Administrator\faceswap\scripts\extract.py", line 183, in run_extraction
self.extractor.launch()
File "C:\Users\Administrator\faceswap\plugins\extract\pipeline.py", line 171, in launch
self.launch_aligner()
File "C:\Users\Administrator\faceswap\plugins\extract\pipeline.py", line 206, in launch_aligner
raise ValueError("Error initializing Aligner")
ValueError: Error initializing Aligner
08/12/2019 03:14:34 CRITICAL An unexpected crash has occurred. Crash report written to 'C:\Users\Administrator\faceswap\crash_report.2019.08.12.031434375303.log'. Please verify you are running the latest version of faceswap before reporting
Process exited.

**Comment by bryanlyon** [comment]
Please read the error messages.  It tells you the problem right here: Status: CUDA driver version is insufficient for CUDA runtime version

Update your driver.
