### ISSUE TITLE
win10  gui run error

### ISSUE THREAD

**Issue by foxundermoon** [deepfakes/faceswap#852]
extract meet error after installed .

 - OS:  win10 
 - Version  latest

```log
Loading...
Setting Faceswap backend to NVIDIA
08/31/2019 16:07:27 INFO     Log level set to: INFO
08/31/2019 16:07:30 INFO     Output Directory: T:\faceswap\out
08/31/2019 16:07:30 INFO     Input Video: T:\faceswap\nv_short.mkv
08/31/2019 16:07:31 INFO     Loading Detect from S3Fd plugin...
08/31/2019 16:07:31 INFO     Loading Align from Fan plugin...
08/31/2019 16:07:31 INFO     Starting, this may take a while...
WARNING: Logging before flag parsing goes to stderr.
I0831 16:07:35.449158  8512 _base.py:75] _base initialize Align: (PID: 9452, args: (), kwargs: {'event': <multiprocessing.synchronize.Event object at 0x00000254BB943DD8>, 'error': <multiprocessing.synchronize.Event object at 0x00000254BD31EC50>, 'log_init': <function set_root_logger at 0x00000254BBBF8730>, 'log_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x254c42067f0>, 'log_level': 10, 'in_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x254c4206908>, 'out_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x254c4206978>})
I0831 16:07:35.449158  8512 fan.py:30] Initializing Face Alignment Network...
I0831 16:07:35.449158  8512 fan.py:31] fan initialize: (args: () kwargs: {'event': <multiprocessing.synchronize.Event object at 0x00000254BB943DD8>, 'error': <multiprocessing.synchronize.Event object at 0x00000254BD31EC50>, 'log_init': <function set_root_logger at 0x00000254BBBF8730>, 'log_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x254c42067f0>, 'log_level': 10, 'in_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x254c4206908>, 'out_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x254c4206978>})
I0831 16:07:35.449158  8512 gpu_stats.py:34] Initializing GPUStats
I0831 16:07:35.449158  8512 gpu_stats.py:84] OS is not macOS. Using pynvml
I0831 16:07:35.464778  8512 gpu_stats.py:136] GPU Device count: 1
I0831 16:07:35.464778  8512 gpu_stats.py:151] Active GPU Devices: [0]
I0831 16:07:35.496067  8512 gpu_stats.py:163] GPU Handles found: 1
I0831 16:07:35.496067  8512 gpu_stats.py:177] GPU Driver: 388.31
I0831 16:07:35.496067  8512 gpu_stats.py:194] GPU Devices: ['GeForce GTX 1070 Ti']
I0831 16:07:35.496067  8512 gpu_stats.py:212] GPU VRAM: [8192.0]
I0831 16:07:35.511652  8512 gpu_stats.py:57] Initialized GPUStats
I0831 16:07:35.511652  8512 gpu_stats.py:84] OS is not macOS. Using pynvml
I0831 16:07:35.511652  8512 gpu_stats.py:136] GPU Device count: 1
I0831 16:07:35.511652  8512 gpu_stats.py:151] Active GPU Devices: [0]
I0831 16:07:35.527282  8512 gpu_stats.py:163] GPU Handles found: 1
I0831 16:07:35.527282  8512 gpu_stats.py:252] GPU VRAM free: [7703.8125]
I0831 16:07:35.527282  8512 gpu_stats.py:271] Active GPU Card with most free VRAM: {'card_id': 0, 'device': 'GeForce GTX 1070 Ti', 'free': 7703.8125, 'total': 8192.0}
I0831 16:07:35.527282  8512 _base.py:232] Using device GeForce GTX 1070 Ti with 7703MB free of 8192MB
I0831 16:07:35.527282  8512 fan.py:39] Reserving 2240MB for face alignments
I0831 16:07:35.527282  8512 fan.py:204] Initializing Face Alignment Network model...
W0831 16:07:35.527282  8512 deprecation_wrapper.py:119] From C:\Users\foxundermoon\faceswap\plugins\extract\align\fan.py:206: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0831 16:07:35.527282  8512 deprecation_wrapper.py:119] From C:\Users\foxundermoon\faceswap\plugins\extract\align\fan.py:207: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

W0831 16:07:43.289920  8512 deprecation_wrapper.py:119] From C:\Users\foxundermoon\faceswap\plugins\extract\align\fan.py:219: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.08/31/2019 16:07:43 WARNING  From C:\Users\foxundermoon\faceswap\plugins\extract\align\fan.py:219: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.\n
08/31/2019 16:07:43 WARNING  From C:\Users\foxundermoon\faceswap\plugins\extract\align\fan.py:221: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.\n


E0831 16:07:43.696161  8512 _base.py:114] Caught exception in child process: 945208/31/2019 16:07:43 ERROR    Caught exception in child process: 9452
08/31/2019 16:07:43 ERROR    Traceback:
Traceback (most recent call last):
File "C:\Users\foxundermoon\faceswap\plugins\extract\align\_base.py", line 112, in run
self.align(*args, **kwargs)
File "C:\Users\foxundermoon\faceswap\plugins\extract\align\_base.py", line 127, in align
self.initialize(*args, **kwargs)
File "C:\Users\foxundermoon\faceswap\plugins\extract\align\fan.py", line 47, in initialize
raise err
File "C:\Users\foxundermoon\faceswap\plugins\extract\align\fan.py", line 41, in initialize
self.model = FAN(self.model_path, ratio=tf_ratio)
File "C:\Users\foxundermoon\faceswap\plugins\extract\align\fan.py", line 199, in __init__
self.session = self.set_session(ratio)
File "C:\Users\foxundermoon\faceswap\plugins\extract\align\fan.py", line 221, in set_session
session = self.tf.Session(config=config)
File "C:\ProgramData\Miniconda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1570, in __init__
super(Session, self).__init__(target, graph, config=config)
File "C:\ProgramData\Miniconda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 693, in __init__
self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
08/31/2019 16:07:51 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "C:\Users\foxundermoon\faceswap\lib\cli.py", line 125, in execute_script
process.process()
File "C:\Users\foxundermoon\faceswap\scripts\extract.py", line 62, in process
self.run_extraction()
File "C:\Users\foxundermoon\faceswap\scripts\extract.py", line 189, in run_extraction
self.extractor.launch()
File "C:\Users\foxundermoon\faceswap\plugins\extract\pipeline.py", line 171, in launch
self.launch_aligner()
File "C:\Users\foxundermoon\faceswap\plugins\extract\pipeline.py", line 206, in launch_aligner
raise ValueError("Error initializing Aligner")
ValueError: Error initializing Aligner
08/31/2019 16:07:51 CRITICAL An unexpected crash has occurred. Crash report written to 'C:\Users\foxundermoon\faceswap\crash_report.2019.08.31.160751703656.log'. Please verify you are running the latest version of faceswap before reporting
Process exited.

```

**Comment by torzdf** [comment]
https://faceswap.dev/forum/viewtopic.php?f=5&t=13
