### ISSUE TITLE
Caught exception in thread: 'training_0'

### ISSUE THREAD

**Issue by Joburgess** [deepfakes/faceswap#855]
09/02/2019 21:02:53 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: 'training_0'
Traceback (most recent call last):
  File "C:\Users\qnc99\Desktop\faceswap-master\lib\cli.py", line 125, in execute_script
    process.process()
  File "C:\Users\qnc99\Desktop\faceswap-master\scripts\train.py", line 98, in process
    self.end_thread(thread, err)
  File "C:\Users\qnc99\Desktop\faceswap-master\scripts\train.py", line 124, in end_thread
    thread.join()
  File "C:\Users\qnc99\Desktop\faceswap-master\lib\multithreading.py", line 461, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "C:\Users\qnc99\Desktop\faceswap-master\lib\multithreading.py", line 392, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\qnc99\Desktop\faceswap-master\scripts\train.py", line 149, in training
    raise err
  File "C:\Users\qnc99\Desktop\faceswap-master\scripts\train.py", line 139, in training
    self.run_training_cycle(model, trainer)
  File "C:\Users\qnc99\Desktop\faceswap-master\scripts\train.py", line 221, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "C:\Users\qnc99\Desktop\faceswap-master\plugins\train\trainer\_base.py", line 213, in train_one_step
    raise err
  File "C:\Users\qnc99\Desktop\faceswap-master\plugins\train\trainer\_base.py", line 178, in train_one_step
    loss[side] = batcher.train_one_batch(do_preview)
  File "C:\Users\qnc99\Desktop\faceswap-master\plugins\train\trainer\_base.py", line 276, in train_one_batch
    batch = self.get_next(do_preview)
  File "C:\Users\qnc99\Desktop\faceswap-master\plugins\train\trainer\_base.py", line 297, in get_next
    batch = next(self.feed)
StopIteration

**Comment by torzdf** [comment]
crash report

**Comment by torzdf** [comment]
1) This is a cuDNN initialization error.
2) 

> An unexpected crash has occurred. Crash report written to '/home/andy/Projects/FaceSwap/faceswap/crash_report.2019.09.12.144903345346.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting

**Comment by gildo** [comment]
Hello, this seems a Tensorflow/cuDNN issue related with RTX cards, I've fixed it with
`TF_FORCE_GPU_ALLOW_GROWTH=true` enviroment variable.

Hope this helps fellow googlenauts.

**Comment by torzdf** [comment]
@gildo Thanks for the tip. I will look to add this as an option for extract

**Comment by torzdf** [comment]
@gildo Thanks for the feedback. There is actually an "Allow Growth" option for TF in the cli for training

**Comment by gildo** [comment]
@torzdf, yes, but only on the training scripts.
This method fixes extraction and conversion scripts too.

**Comment by torzdf** [comment]
It's been added to extract too (in config options)
