### ISSUE TITLE
cannot extract images.

### ISSUE THREAD

**Issue by siwahashi** [deepfakes/faceswap#865]
**Describe the bug**
I cannot extract images.

**To Reproduce**
I executed below command...
```
$ python ../../faceswap/faceswap.py extract -i personB -o personB_face
```
then, unknown error occured.
```
09/07/2019 01:38:09 INFO     Log level set to: INFO
09/07/2019 01:38:11 INFO     Output Directory: /home/ec2-user/faceswap/projects/test/personB_face
09/07/2019 01:38:11 INFO     Input Directory: /home/ec2-user/faceswap/projects/test/personB
09/07/2019 01:38:11 INFO     Loading Detect from Cv2_Dnn plugin...
09/07/2019 01:38:11 INFO     Updating config at: '/home/ec2-user/faceswap/faceswap/config/extract.ini'
09/07/2019 01:38:11 INFO     Downloading model: 'resnet_ssd' from: https://github.com/deepfakes-models/faceswap-models/releases/download/v1.4.1/resnet_ssd_v1.zip
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.83M/4.83M [00:00<00:00, 6.52MB/s]
09/07/2019 01:38:12 INFO     Extracting: 'resnet_ssd'
Decompressing: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.13M/5.13M [00:00<00:00, 70.9MB/s]
09/07/2019 01:38:12 INFO     Loading Align from Cv2_Dnn plugin...
09/07/2019 01:38:12 INFO     Downloading model: 'cnn-facial-landmark' from: https://github.com/deepfakes-models/faceswap-models/releases/download/v1.1.1/cnn-facial-landmark_v1.zip
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.9M/25.9M [00:02<00:00, 10.4MB/s]
09/07/2019 01:38:15 INFO     Extracting: 'cnn-facial-landmark'
Decompressing: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28.0M/28.0M [00:00<00:00, 73.5MB/s]
09/07/2019 01:38:16 INFO     Starting, this may take a while...
09/07/2019 01:38:18 INFO     Initializing cv2 DNN Aligner...

flatten/strided_slice:StridedSlice(flatten/Shape)(flatten/strided_slice/stack)(flatten/strided_slice/stack_1)(flatten/strided_slice/stack_2)
Index:[ ]
T:0
shrink_axis_mask:[ ]
ellipsis_mask:[ ]
begin_mask:[ ]
new_axis_mask:[ ]
end_mask:[ ]
_output_shapes:[ ]
OpenCV(3.4.1) Error: Unspecified error (Unknown layer type StridedSlice in op flatten/strided_slice) in populateNet, file /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 1582
09/07/2019 01:38:18 ERROR    Caught exception in child process: 3902
09/07/2019 01:38:18 ERROR    Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/faceswap/faceswap/plugins/extract/align/_base.py", line 112, in run
    self.align(*args, **kwargs)
  File "/home/ec2-user/faceswap/faceswap/plugins/extract/align/_base.py", line 127, in align
    self.initialize(*args, **kwargs)
  File "/home/ec2-user/faceswap/faceswap/plugins/extract/align/cv2_dnn.py", line 61, in initialize
    raise err
  File "/home/ec2-user/faceswap/faceswap/plugins/extract/align/cv2_dnn.py", line 55, in initialize
    self.model_path)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:1582: error: (-2) Unknown layer type StridedSlice in op flatten/strided_slice in function populateNet

09/07/2019 01:38:20 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/home/ec2-user/faceswap/faceswap/lib/cli.py", line 128, in execute_script
    process.process()
  File "/home/ec2-user/faceswap/faceswap/scripts/extract.py", line 62, in process
    self.run_extraction()
  File "/home/ec2-user/faceswap/faceswap/scripts/extract.py", line 189, in run_extraction
    self.extractor.launch()
  File "/home/ec2-user/faceswap/faceswap/plugins/extract/pipeline.py", line 171, in launch
    self.launch_aligner()
  File "/home/ec2-user/faceswap/faceswap/plugins/extract/pipeline.py", line 206, in launch_aligner
    raise ValueError("Error initializing Aligner")
ValueError: Error initializing Aligner
09/07/2019 01:38:20 CRITICAL An unexpected crash has occurred. Crash report written to '/home/ec2-user/faceswap/projects/test/crash_report.2019.09.07.013820775396.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting
[crash_report.2019.09.07.013820775396.log](https://github.com/deepfakes/faceswap/files/3586138/crash_report.2019.09.07.013820775396.log)
```

**Expected behavior**
Face images are extracted precisely by thus command.

**Desktop (please complete the following information):**
 ```
Amazon Linux AMI release 2018.03
Kernel \r on an \m
```

I attached crash_report on this repot.

**Comment by siwahashi** [comment]
I found this why that opencv version is 3.4.1. So I upgrade opencv version, from 3.4.1 to 3.4.5. Then I resolved this isuue.
