### ISSUE TITLE
imageio_ffmpeg missing after install python3.7 and requirements

### ISSUE THREAD

**Issue by algorithmz** [deepfakes/faceswap#879]
**Screenshots**
![image](https://user-images.githubusercontent.com/17625859/65421784-32e5cf80-de37-11e9-93ba-bf8bbbad31eb.png)

I installed on Windows 10 x64 and i installed python latest with requirements. But still missing imageio_ffmpeg. Please fix this :) Thank you

C:\Users\BD\faceswap>"C:\Users\BD\Miniconda3\scripts\activate.bat"   && conda activate "faceswap"   && python "C:\Users\BD\faceswap/faceswap.py" gui
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\BD\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\BD\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\BD\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\BD\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\BD\MiniConda3\envs\faceswap\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\BD\MiniConda3\envs\faceswap\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\BD\MiniConda3\envs\faceswap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\BD\faceswap\faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "C:\Users\BD\faceswap\lib\cli.py", line 17, in <module>
    from lib.utils import FaceswapError, get_backend, safe_shutdown
  File "C:\Users\BD\faceswap\lib\utils.py", line 18, in <module>
    import imageio_ffmpeg as im_ffm
ModuleNotFoundError: No module named 'imageio_ffmpeg'

**Comment by torzdf** [comment]
For some reason `setup.py` sometimes misses items.

To fix this do:
Start > Anaconda Prompt
```conda activate faceswap
cd faceswap
python updates_deps.py
```
Then try running again

**Comment by algorithmz** [comment]
Thanks a lot. You should add this tip to readme :)

**Comment by DomeenoH** [comment]
really helps.
