### ISSUE TITLE
Train Failed,unable to run OpenCL kernel

### ISSUE THREAD

**Issue by os-tll** [deepfakes/faceswap#884]
Hi all ☺:
 I'm new here ,and this phenomenon occur every time when I run command like 
`python faceswap.py train -A D:\AA -B D:\DD -m D:\model\  --batch-size 1 -t lightweight`. but install and extract is fine.
Below is the log ,thanks very much for everything you provide!
```
(face) E:\faceswap>python faceswap.py train -A D:\AA -B D:\DD -m D:\model\  --batch-size 1 -t lightweight
Setting Faceswap backend to AMD
09/25/2019 16:14:34 INFO     Log level set to: INFO
09/25/2019 16:14:34 INFO     Setting up for PlaidML
09/25/2019 16:14:34 INFO     Setting GPU to largest available supported device. If you want to override this selection, run `plaidml-setup` from the command line.
09/25/2019 16:14:34 INFO     Using GPU: ['opencl_nvidia_geforce_940mx.0', 'opencl_nvidia_geforce_940mx.0']
09/25/2019 16:14:34 INFO     Successfully set up for PlaidML
Using plaidml.keras.backend backend.
09/25/2019 16:14:38 INFO     Model A Directory: D:\AA
09/25/2019 16:14:38 INFO     Model B Directory: D:\DD
09/25/2019 16:14:38 INFO     Training data directory: D:\model
09/25/2019 16:14:38 INFO     ===================================================
09/25/2019 16:14:38 INFO       Starting
09/25/2019 16:14:38 INFO       Press 'ENTER' to save and quit
09/25/2019 16:14:38 INFO       Press 'S' to save model weights immediately
09/25/2019 16:14:38 INFO     ===================================================
09/25/2019 16:14:39 INFO     Loading data, this may take a while...
09/25/2019 16:14:39 INFO     Loading Model from Lightweight plugin...
09/25/2019 16:14:39 INFO     Using configuration saved in state file
09/25/2019 16:14:39 INFO     Opening device "opencl_nvidia_geforce_940mx.0"
09/25/2019 16:14:40 INFO     Opening device "opencl_nvidia_geforce_940mx.0"
09/25/2019 16:14:40 INFO     Loaded model from disk: 'D:\model'
09/25/2019 16:14:40 INFO     Loading Trainer from Original plugin...
09/25/2019 16:14:41 INFO     Enabled TensorBoard Logging
09/25/2019 16:14:44 INFO     Analyzing Ops: 150 of 478 operations complete
09/25/2019 16:14:58 INFO     Analyzing Ops: 150 of 478 operations complete
unable to run OpenCL kernel kernel_c18_sdk_11: CL_MEM_OBJECT_ALLOCATION_FAILURE
09/25/2019 16:15:09 ERROR    unable to run OpenCL kernel kernel_c18_sdk_11: CL_MEM_OBJECT_ALLOCATION_FAILURE
Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE
09/25/2019 16:15:09 ERROR    Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE
Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE
09/25/2019 16:15:09 ERROR    Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE
09/25/2019 16:15:09 ERROR    Caught exception in thread: 'save_decoder_a_0'
Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE
09/25/2019 16:15:10 ERROR    Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE
09/25/2019 16:15:10 CRITICAL Error caught! Exiting...
09/25/2019 16:15:10 ERROR    Caught exception in thread: 'training_0'
09/25/2019 16:15:13 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "E:\faceswap\lib\cli.py", line 128, in execute_script
    process.process()
  File "E:\faceswap\scripts\train.py", line 98, in process
    self.end_thread(thread, err)
  File "E:\faceswap\scripts\train.py", line 124, in end_thread
    thread.join()
  File "E:\faceswap\lib\multithreading.py", line 111, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "E:\faceswap\lib\multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "E:\faceswap\scripts\train.py", line 149, in training
    raise err
  File "E:\faceswap\scripts\train.py", line 139, in training
    self.run_training_cycle(model, trainer)
  File "E:\faceswap\scripts\train.py", line 231, in run_training_cycle
    model.save_models()
  File "E:\faceswap\plugins\train\model\_base.py", line 483, in save_models
    thread.join()
  File "E:\faceswap\lib\multithreading.py", line 111, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "E:\faceswap\lib\multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "E:\faceswap\plugins\train\model\_base.py", line 860, in save
    self.weights = self.network.get_weights()
  File "D:\soft\Anaconda\envs\face\lib\site-packages\keras\engine\network.py", line 492, in get_weights
    return K.batch_get_value(weights)
  File "D:\soft\Anaconda\envs\face\lib\site-packages\plaidml\keras\backend.py", line 351, in batch_get_value
    return [get_value(x) for x in xs]
  File "D:\soft\Anaconda\envs\face\lib\site-packages\plaidml\keras\backend.py", line 351, in <listcomp>
    return [get_value(x) for x in xs]
  File "D:\soft\Anaconda\envs\face\lib\site-packages\plaidml\keras\backend.py", line 768, in get_value
    with tensor.mmap_current() as view:
  File "D:\soft\Anaconda\envs\face\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "D:\soft\Anaconda\envs\face\lib\site-packages\plaidml\__init__.py", line 1245, in mmap_current
    ctypes.cast(None, _MAP_BUFFER_FUNCTYPE), None)
  File "D:\soft\Anaconda\envs\face\lib\site-packages\plaidml\__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "D:\soft\Anaconda\envs\face\lib\site-packages\plaidml\library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE`
```
Thanks very much for everything you provide!

**Comment by os-tll** [comment]
@torzdf  thanks for your sign

**Comment by kilroythethird** [comment]
I am not sure why you are running into this error, but it looks like you selected the AMD option while you in fact have an nvidia. card.
Please delete `D:\soft\Anaconda\envs\face` and `E:\faceswap` and rerun the installer.
Make sure you select the nvidia option when prompted.

**Comment by os-tll** [comment]
Thanks for your time, it's worked after installed again,What a foolish question ,I'm so careless.
Appreciate again @kilroythethird  @torzdf
