### ISSUE TITLE
 cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by w4cky** [deepfakes/faceswap#887]
09/28/2019 10:10:02 MainProcess     MainThread      utils           write_model               DEBUG    Extracting from: 'E:\faceswap\plugins\extract\align\.cache\face-alignment-network_2d4_keras_v1.zip' to 'E:\faceswap\plugins\extract\align\.cache\face-alignment-network_2d4_keras_v1.h5'
09/28/2019 10:10:04 MainProcess     MainThread      _base           __init__                  DEBUG    Initialized _base Align
09/28/2019 10:10:04 MainProcess     MainThread      _base           __init__                  DEBUG    Initialized Align
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initializing GPUStats
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 1
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0]
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 1
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_driver                DEBUG    GPU Driver: 399.24
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_devices               DEBUG    GPU Devices: ['GeForce GTX 1070']
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_vram                  DEBUG    GPU VRAM: [8192.0]
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initialized GPUStats
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 1
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0]
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 1
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_free                  DEBUG    GPU VRAM free: [7105.43359375]
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_card_most_free        DEBUG    Active GPU Card with most free VRAM: {'card_id': 0, 'device': 'GeForce GTX 1070', 'free': 7105.43359375, 'total': 8192.0}
09/28/2019 10:10:04 MainProcess     MainThread      pipeline        _set_parallel_processing  VERBOSE  GeForce GTX 1070 - 7105MB free of 8192MB
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initializing GPUStats
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 1
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0]
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 1
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_driver                DEBUG    GPU Driver: 399.24
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_devices               DEBUG    GPU Devices: ['GeForce GTX 1070']
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_vram                  DEBUG    GPU VRAM: [8192.0]
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initialized GPUStats
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 1
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0]
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 1
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_free                  DEBUG    GPU VRAM free: [7105.43359375]
09/28/2019 10:10:04 MainProcess     MainThread      gpu_stats       get_card_most_free        DEBUG    Active GPU Card with most free VRAM: {'card_id': 0, 'device': 'GeForce GTX 1070', 'free': 7105.43359375, 'total': 8192.0}
09/28/2019 10:10:04 MainProcess     MainThread      pipeline        _set_plugin_batchsize     VERBOSE  Reset batchsize for FAN to 3
09/28/2019 10:10:04 MainProcess     MainThread      pipeline        _set_plugin_batchsize     VERBOSE  Reset batchsize for S3FD to 1
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_detect_in', maxsize: 64)
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_detect_in')
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_detect_in'
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_detect_in'
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_align_in', maxsize: 32)
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_align_in')
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_align_in'
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_align_in'
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_align_out', maxsize: 32)
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_align_out')
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_align_out'
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_align_out'
09/28/2019 10:10:04 MainProcess     MainThread      pipeline        _add_queues               DEBUG    Queues: {'extract_detect_in': <queue.Queue object at 0x0000026C4CF40128>, 'extract_align_in': <queue.Queue object at 0x0000026C4D149F28>, 'extract_align_out': <queue.Queue object at 0x0000026C4D1334A8>}
09/28/2019 10:10:04 MainProcess     MainThread      pipeline        __init__                  DEBUG    Initialized Extractor
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_save'
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_save', maxsize: 0)
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_save')
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_save'
09/28/2019 10:10:04 MainProcess     MainThread      extract         __init__                  DEBUG    Initialized Extract
09/28/2019 10:10:04 MainProcess     MainThread      extract         process                   INFO     Starting, this may take a while...
09/28/2019 10:10:04 MainProcess     MainThread      extract         threaded_io               DEBUG    Threading task: (Task: 'load')
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'load_images', thread_count: 1)
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'load_images'
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'load_images'
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'load_images_0'
09/28/2019 10:10:04 MainProcess     load_images_0   extract         load_images               DEBUG    Load Images: Start
09/28/2019 10:10:04 MainProcess     load_images_0   fsmedia         load_video_frames         DEBUG    Input is video. Capturing frames
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'load_images': 1
09/28/2019 10:10:04 MainProcess     MainThread      extract         threaded_io               DEBUG    Threading task: (Task: 'save')
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'save_faces', thread_count: 1)
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'save_faces'
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'save_faces'
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'save_faces_0'
09/28/2019 10:10:04 MainProcess     save_faces_0    extract         save_faces                DEBUG    Save Faces: Start
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'save_faces': 1
09/28/2019 10:10:04 MainProcess     MainThread      extract         process_item_count        DEBUG    Items already processed: 0
09/28/2019 10:10:04 MainProcess     MainThread      extract         process_item_count        DEBUG    Items to be Processed: 19240
09/28/2019 10:10:04 MainProcess     MainThread      pipeline        _launch_aligner           DEBUG    Launching Aligner
09/28/2019 10:10:04 MainProcess     MainThread      _base           initialize                DEBUG    initialize Align: (args: (), kwargs: {'in_queue': <queue.Queue object at 0x0000026C4D149F28>, 'out_queue': <queue.Queue object at 0x0000026C4D1334A8>})
09/28/2019 10:10:04 MainProcess     MainThread      _base           initialize                INFO     Initializing FAN Aligner...
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'align_predict'
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'align_predict', maxsize: 1)
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'align_predict')
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'align_predict'
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'align_post'
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'align_post', maxsize: 1)
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'align_post')
09/28/2019 10:10:04 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'align_post'
09/28/2019 10:10:04 MainProcess     MainThread      _base           _compile_threads          DEBUG    Compiling align threads
09/28/2019 10:10:04 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: align_input, function: <bound method Align.process_input of <plugins.extract.align.fan.Align object at 0x0000026C4D1078D0>>, in_queue: <queue.Queue object at 0x0000026C4D149F28>, out_queue: <queue.Queue object at 0x0000026C4D15BF28>)
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'align_input', thread_count: 1)
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'align_input'
09/28/2019 10:10:04 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: align_input
09/28/2019 10:10:04 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: align_predict, function: <bound method Aligner._predict of <plugins.extract.align.fan.Align object at 0x0000026C4D1078D0>>, in_queue: <queue.Queue object at 0x0000026C4D15BF28>, out_queue: <queue.Queue object at 0x0000026C4D15B898>)
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'align_predict', thread_count: 1)
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'align_predict'
09/28/2019 10:10:04 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: align_predict
09/28/2019 10:10:04 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: align_output, function: <bound method Align.process_output of <plugins.extract.align.fan.Align object at 0x0000026C4D1078D0>>, in_queue: <queue.Queue object at 0x0000026C4D15B898>, out_queue: <queue.Queue object at 0x0000026C4D1334A8>)
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'align_output', thread_count: 1)
09/28/2019 10:10:04 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'align_output'
09/28/2019 10:10:04 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: align_output
09/28/2019 10:10:04 MainProcess     MainThread      _base           _compile_threads          DEBUG    Compiled align threads: [<lib.multithreading.MultiThread object at 0x0000026C4D15B8D0>, <lib.multithreading.MultiThread object at 0x0000026C4D15BE80>, <lib.multithreading.MultiThread object at 0x0000026C4D15B828>]
09/28/2019 10:10:04 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From E:\faceswap\lib\model\session.py:105: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.\n
09/28/2019 10:10:04 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From E:\faceswap\lib\model\session.py:106: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.\n
Traceback (most recent call last):
  File "E:\faceswap\lib\cli.py", line 128, in execute_script
    process.process()
  File "E:\faceswap\scripts\extract.py", line 61, in process
    self.run_extraction()
  File "E:\faceswap\scripts\extract.py", line 187, in run_extraction
    self.extractor.launch()
  File "E:\faceswap\plugins\extract\pipeline.py", line 180, in launch
    self._launch_aligner()
  File "E:\faceswap\plugins\extract\pipeline.py", line 326, in _launch_aligner
    self._aligner.initialize(**kwargs)
  File "E:\faceswap\plugins\extract\_base.py", line 328, in initialize
    self.init_model()
  File "E:\faceswap\plugins\extract\align\fan.py", line 33, in init_model
    self.model = KSession(self.name, self.model_path, model_kwargs=model_kwargs)
  File "E:\faceswap\lib\model\session.py", line 37, in __init__
    self._session = self._set_session()
  File "E:\faceswap\lib\model\session.py", line 106, in _set_session
    session = tf.Session(graph=tf.Graph(), config=config)
  File "C:\Users\Michal\Miniconda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1570, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "C:\Users\Michal\Miniconda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 693, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

============ System Information ============
encoding:            cp1250
git_branch:          master
git_commits:         84932c0 Bugfix: Don't overide kernel_initializer if it is explicitly set in model definition
gpu_cuda:            No global version found. Check Conda packages for Conda Cuda
gpu_cudnn:           No global version found. Check Conda packages for Conda cuDNN
gpu_devices:         GPU_0: GeForce GTX 1070
gpu_devices_active:  GPU_0
gpu_driver:          399.24
gpu_vram:            GPU_0: 8192MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.18362-SP0
os_release:          10
py_command:          E:\faceswap\faceswap.py extract -i E:/faceswap/ZABAWA/Jarosaw Kaczyski - Wystpienie Prezesa PiS w odzi.avi -o E:/faceswap/ZABAWA/KACZKYNSKI_OUT --serializer json -D s3fd -A fan -nm none -min 0 -l 0.4 -bt 0.0 -een 1 -sz 256 -si 0 -L INFO -gui
py_conda_version:    conda 4.7.12
py_implementation:   CPython
py_version:          3.6.9
py_virtual_env:      True
sys_cores:           4
sys_processor:       Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
sys_ram:             Total: 16335MB, Available: 5819MB, Used: 10516MB, Free: 5819MB

=============== Pip Packages ===============
absl-py==0.8.0
astor==0.8.0
certifi==2019.9.11
cloudpickle==1.2.2
cycler==0.10.0
cytoolz==0.10.0
dask==2.4.0
decorator==4.4.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.3.2
grpcio==1.16.1
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.13.2
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
networkx==2.3
numpy==1.16.2
nvidia-ml-py3==7.352.1
olefile==0.46
opencv-python==4.1.1.26
pathlib==1.0.1
Pillow==6.1.0
protobuf==3.9.2
psutil==5.6.3
pyparsing==2.4.2
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.2
PyWavelets==1.0.3
pywin32==223
PyYAML==5.1.2
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
six==1.12.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
toolz==0.10.0
toposort==1.5
tornado==6.0.3
tqdm==4.36.1
Werkzeug==0.16.0
wincertstore==0.2
wrapt==1.11.2

============== Conda Packages ==============
# packages in environment at C:\Users\Michal\Miniconda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.8.0                    py36_0  
astor                     0.8.0                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.8.28                     0  
certifi                   2019.9.11                py36_0  
cloudpickle               1.2.2                      py_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.0                cuda10.0_0  
cycler                    0.10.0           py36h009560c_0  
cytoolz                   0.10.0           py36he774522_0  
dask-core                 2.4.0                      py_0  
decorator                 4.4.0                    py36_1  
fastcluster               1.1.25          py36h830ac7b_1000    conda-forge
ffmpeg                    4.2                  h6538335_0    conda-forge
ffmpy                     0.2.2                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1  
gast                      0.3.2                      py_0  
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0            py36h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
imageio                   2.5.0                    py36_0  
imageio-ffmpeg            0.3.0                      py_0    conda-forge
intel-openmp              2019.4                      245  
joblib                    0.13.2                   py36_0  
jpeg                      9b                   hb83a4c4_2  
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py36ha925a31_0  
libmklml                  2019.0.5                      0  
libpng                    1.6.37               h2a8f88b_0  
libprotobuf               3.9.2                h7bd577a_0  
libtiff                   4.0.10               hb898794_2  
markdown                  3.1.1                    py36_0  
matplotlib                2.2.2            py36had4c4a9_2  
mkl                       2019.4                      245  
mkl-service               2.3.0            py36hb782905_0  
mkl_fft                   1.0.14           py36h14836fe_0  
mkl_random                1.1.0            py36h675688f_0  
networkx                  2.3                        py_0  
numpy                     1.16.2           py36h19fb1c0_0  
numpy-base                1.16.2           py36hc3f5095_0  
nvidia-ml-py3             7.352.1                  pypi_0    pypi
olefile                   0.46                     py36_0  
opencv-python             4.1.1.26                 pypi_0    pypi
openssl                   1.1.1d               he774522_0  
pathlib                   1.0.1                    py36_1  
pillow                    6.1.0            py36hdc69c19_0  
pip                       19.2.3                   py36_0  
protobuf                  3.9.2            py36h33f27b4_0  
psutil                    5.6.3            py36he774522_0  
pyparsing                 2.4.2                      py_0  
pyqt                      5.9.2            py36h6538335_2  
pyreadline                2.1                      py36_1  
python                    3.6.9                h5500b2f_0  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.2                     py_0  
pywavelets                1.0.3            py36h8c2d366_1  
pywin32                   223              py36hfa6e2cd_1  
pyyaml                    5.1.2            py36he774522_0  
qt                        5.9.7            vc14h73c81de_0  
scikit-image              0.15.0           py36ha925a31_0  
scikit-learn              0.21.3           py36h6288b17_0  
scipy                     1.3.1            py36h29ff71c_0  
setuptools                41.2.0                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.12.0                   py36_0  
sqlite                    3.29.0               he774522_0  
tensorboard               1.14.0           py36he3c9ec2_0  
tensorflow                1.14.0          gpu_py36h305fd99_0  
tensorflow-base           1.14.0          gpu_py36h55fc52a_0  
tensorflow-estimator      1.14.0                     py_0  
tensorflow-gpu            1.14.0               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.10.0                     py_0  
toposort                  1.5                        py_3    conda-forge
tornado                   6.0.3            py36he774522_0  
tqdm                      4.36.1                     py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_0  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
wrapt                     1.11.2           py36he774522_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  

================= Configs ==================
--------- .faceswap ---------
backend:                  nvidia

--------- convert.ini ---------

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

[color.match_hist]
threshold:                99.0

[mask.box_blend]
type:                     gaussian
distance:                 11.0
radius:                   5.0
passes:                   1

[mask.mask_blend]
type:                     normalized
radius:                   3.0
passes:                   4
erosion:                  0.0

[scaling.sharpen]
method:                   unsharp_mask
amount:                   150
radius:                   0.3
threshold:                5.0

[writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     none
profile:                  auto
level:                    auto

[writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

[writer.opencv]
format:                   png
draw_transparent:         False
jpg_quality:              75
png_compress_level:       3

[writer.pillow]
format:                   png
draw_transparent:         False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

--------- extract.ini ---------

[align.fan]
batch-size:               8

[detect.cv2_dnn]
confidence:               50

[detect.mtcnn]
minsize:                  20
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7
scalefactor:              0.709
batch-size:               8

[detect.s3fd]
confidence:               50
batch-size:               8

--------- gui.ini ---------

[global]
fullscreen:               False
tab:                      extract
options_panel_width:      30
console_panel_height:     20
font:                     default
font_size:                9

--------- train.ini ---------

[global]
coverage:                 68.75
mask_type:                none
mask_blur:                False
icnr_init:                False
conv_aware_init:          False
subpixel_upscaling:       False
reflect_padding:          False
penalized_mask_loss:      True
loss_function:            mae
learning_rate:            5e-05

[model.dfl_h128]
lowmem:                   False

[model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[model.original]
lowmem:                   False

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.villain]
lowmem:                   False

[trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4

**Comment by w4cky** [comment]
Installed newest driver.
