### ISSUE TITLE
Can't exctract from webm.

### ISSUE THREAD

**Issue by p-funk** [deepfakes/faceswap#889]
Unable to extract from webm

```
09/28/2019 19:05:28 MainProcess     load_images_0   fsmedia         load_video_frames         DEBUG    Input is video. Capturing frames
09/28/2019 19:05:28 MainProcess     MainThread      extract         threaded_io               DEBUG    Threading task: (Task: 'save')
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'save_faces', thread_count: 1)
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'save_faces'
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'save_faces'
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'save_faces_0'
09/28/2019 19:05:28 MainProcess     save_faces_0    extract         save_faces                DEBUG    Save Faces: Start
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'save_faces': 1
09/28/2019 19:05:28 MainProcess     MainThread      extract         process_item_count        DEBUG    Items already processed: 0
09/28/2019 19:05:28 MainProcess     MainThread      extract         process_item_count        DEBUG    Items to be Processed: 4324
09/28/2019 19:05:28 MainProcess     MainThread      pipeline        _launch_detector          DEBUG    Launching Detector
09/28/2019 19:05:28 MainProcess     MainThread      _base           initialize                DEBUG    initialize Detect: (args: (), kwargs: {'in_queue': <queue.Queue object at 0x000002394D801B38>, 'out_queue': <queue.Queue object at 0x000002394DA4E978>})
09/28/2019 19:05:28 MainProcess     MainThread      _base           initialize                INFO     Initializing S3FD Detector...
09/28/2019 19:05:28 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'detect_predict'
09/28/2019 19:05:28 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'detect_predict', maxsize: 1)
09/28/2019 19:05:28 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'detect_predict')
09/28/2019 19:05:28 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'detect_predict'
09/28/2019 19:05:28 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'detect_post'
09/28/2019 19:05:28 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'detect_post', maxsize: 1)
09/28/2019 19:05:28 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'detect_post')
09/28/2019 19:05:28 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'detect_post'
09/28/2019 19:05:28 MainProcess     MainThread      _base           _compile_threads          DEBUG    Compiling detect threads
09/28/2019 19:05:28 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: detect_input, function: <bound method Detect.process_input of <plugins.extract.detect.s3fd.Detect object at 0x000002394D978940>>, in_queue: <queue.Queue object at 0x000002394D801B38>, out_queue: <queue.Queue object at 0x000002394DA4EF60>)
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'detect_input', thread_count: 1)
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'detect_input'
09/28/2019 19:05:28 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: detect_input
09/28/2019 19:05:28 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: detect_predict, function: <bound method Detector._predict of <plugins.extract.detect.s3fd.Detect object at 0x000002394D978940>>, in_queue: <queue.Queue object at 0x000002394DA4EF60>, out_queue: <queue.Queue object at 0x000002394DA635F8>)
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'detect_predict', thread_count: 1)
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'detect_predict'
09/28/2019 19:05:28 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: detect_predict
09/28/2019 19:05:28 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: detect_output, function: <bound method Detect.process_output of <plugins.extract.detect.s3fd.Detect object at 0x000002394D978940>>, in_queue: <queue.Queue object at 0x000002394DA635F8>, out_queue: <queue.Queue object at 0x000002394DA4E978>)
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'detect_output', thread_count: 1)
09/28/2019 19:05:28 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'detect_output'
09/28/2019 19:05:28 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: detect_output
09/28/2019 19:05:28 MainProcess     MainThread      _base           _compile_threads          DEBUG    Compiled detect threads: [<lib.multithreading.MultiThread object at 0x000002394D9F9B00>, <lib.multithreading.MultiThread object at 0x000002394DA636D8>, <lib.multithreading.MultiThread object at 0x000002394DA63780>]
09/28/2019 19:05:28 MainProcess     MainThread      s3fd            __init__                  DEBUG    Initializing: S3fd: (model_path: 'C:\Users\Perry\faceswap\plugins\extract\detect\.cache\s3fd_keras_v1.h5')
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing BlpImagePlugin
09/28/2019 19:05:28 MainProcess     MainThread      session         _set_session              DEBUG    Creating tf.session: (graph: <tensorflow.python.framework.ops.Graph object at 0x000002394EAB7198>, session: <tensorflow.python.client.session.Session object at 0x000002394EAA9CC0>, config: )
09/28/2019 19:05:28 MainProcess     MainThread      session         load_model                VERBOSE  Initializing plugin model: S3FD
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing BmpImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing BufrStubImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing CurImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing DcxImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing DdsImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing EpsImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing FitsStubImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing FliImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing FpxImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing FtexImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing GbrImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing GifImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing GribStubImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing Hdf5StubImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing IcnsImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing IcoImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing ImImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing ImtImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing IptcImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing JpegImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing Jpeg2KImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing McIdasImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing MicImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing MpegImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing MpoImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing MspImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing PalmImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing PcdImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing PcxImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing PdfImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing PixarImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing PngImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing PpmImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing PsdImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing SgiImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing SpiderImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing SunImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing TgaImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing TiffImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing WebPImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing WmfImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing XbmImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing XpmImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   Image           init                      DEBUG    Importing XVThumbImagePlugin
09/28/2019 19:05:28 MainProcess     load_images_0   multithreading  run                       DEBUG    Error in thread (load_images_0): Could not find a format to read the specified file in mode '?'
09/28/2019 19:05:29 MainProcess     MainThread      s3fd            __init__                  DEBUG    Initialized: S3fd
09/28/2019 19:05:29 MainProcess     MainThread      _base           initialize                INFO     Initialized S3FD Detector with batchsize of 8
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'detect_input'
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'detect_input_0'
09/28/2019 19:05:29 MainProcess     detect_input_0  _base           _thread_process           DEBUG    threading: (function: 'process_input')
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'detect_input': 1
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'detect_predict'
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'detect_predict_0'
09/28/2019 19:05:29 MainProcess     detect_predict_0 _base           _thread_process           DEBUG    threading: (function: '_predict')
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'detect_predict': 1
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'detect_output'
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'detect_output_0'
09/28/2019 19:05:29 MainProcess     detect_output_0 _base           _thread_process           DEBUG    threading: (function: 'process_output')
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'detect_output': 1
09/28/2019 19:05:29 MainProcess     MainThread      pipeline        _launch_detector          DEBUG    Launched Detector
09/28/2019 19:05:29 MainProcess     MainThread      multithreading  check_and_raise_error     DEBUG    Thread error caught: [(<class 'ValueError'>, ValueError("Could not find a format to read the specified file in mode '?'",), <traceback object at 0x000002394ED81508>)]
Traceback (most recent call last):
  File "C:\Users\Perry\faceswap\lib\cli.py", line 128, in execute_script
    process.process()
  File "C:\Users\Perry\faceswap\scripts\extract.py", line 61, in process
    self.run_extraction()
  File "C:\Users\Perry\faceswap\scripts\extract.py", line 188, in run_extraction
    self.check_thread_error()
  File "C:\Users\Perry\faceswap\scripts\extract.py", line 223, in check_thread_error
    thread.check_and_raise_error()
  File "C:\Users\Perry\faceswap\lib\multithreading.py", line 84, in check_and_raise_error
    raise error[1].with_traceback(error[2])
  File "C:\Users\Perry\faceswap\lib\multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Perry\faceswap\scripts\extract.py", line 88, in load_images
    for filename, image in self.images.load():
  File "C:\Users\Perry\faceswap\scripts\fsmedia.py", line 180, in load
    for filename, image in iterator():
  File "C:\Users\Perry\faceswap\scripts\fsmedia.py", line 196, in load_video_frames
    reader = imageio.get_reader(self.args.input_dir)
  File "C:\Users\Perry\MiniConda3\envs\faceswap\lib\site-packages\imageio\core\functions.py", line 139, in get_reader
    "Could not find a format to read the specified file " "in mode %r" % mode
ValueError: Could not find a format to read the specified file in mode '?'

============ System Information ============
encoding:            cp1252
git_branch:          master
git_commits:         84932c0 Bugfix: Don't overide kernel_initializer if it is explicitly set in model definition
gpu_cuda:            No global version found. Check Conda packages for Conda Cuda
gpu_cudnn:           No global version found. Check Conda packages for Conda cuDNN
gpu_devices:         GPU_0: GeForce GTX 1050 Ti, GPU_1: GeForce RTX 2060
gpu_devices_active:  GPU_0, GPU_1
gpu_driver:          436.30
gpu_vram:            GPU_0: 4096MB, GPU_1: 6144MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.18362-SP0
os_release:          10
py_command:          C:\Users\Perry\faceswap\faceswap.py extract -i C:/Temp/Faceswap/flat_neil/input_c/$num WIRED - Bill Nye Answers Science Questions From Twitter - Part 3 _ Tech Support _ WIRED (2019-09-17).webm -o C:/Temp/Faceswap/flat_neil/output_c -al C:/Temp/Faceswap/flat_neil/alignments/c/alignments_c.json --serializer json -D s3fd -A fan -nm none -min 256 -l 0.4 -bt 0.0 -een 4 -sz 256 -si 0 -L DEBUG -gui
py_conda_version:    conda 4.7.12
py_implementation:   CPython
py_version:          3.6.9
py_virtual_env:      True
sys_cores:           6
sys_processor:       Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
sys_ram:             Total: 32716MB, Available: 28267MB, Used: 4448MB, Free: 28267MB

=============== Pip Packages ===============
absl-py==0.8.0
astor==0.8.0
certifi==2019.9.11
cloudpickle==1.2.2
cycler==0.10.0
cytoolz==0.10.0
dask==2.4.0
decorator==4.4.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.3.2
grpcio==1.16.1
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.13.2
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
networkx==2.3
numpy==1.16.2
nvidia-ml-py3==7.352.1
olefile==0.46
opencv-python==4.1.1.26
pathlib==1.0.1
Pillow==6.1.0
protobuf==3.9.2
psutil==5.6.3
pyparsing==2.4.2
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.2
PyWavelets==1.0.3
pywin32==223
PyYAML==5.1.2
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
six==1.12.0
tensorboard==1.12.2
tensorflow==1.12.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
toolz==0.10.0
toposort==1.5
tornado==6.0.3
tqdm==4.36.1
Werkzeug==0.16.0
wincertstore==0.2
wrapt==1.11.2

============== Conda Packages ==============
# packages in environment at C:\Users\Perry\MiniConda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.8.0                    py36_0  
astor                     0.8.0                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.8.28                     0  
certifi                   2019.9.11                py36_0  
cloudpickle               1.2.2                      py_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.0                cuda10.0_0  
cycler                    0.10.0           py36h009560c_0  
cytoolz                   0.10.0           py36he774522_0  
dask-core                 2.4.0                      py_0  
decorator                 4.4.0                    py36_1  
fastcluster               1.1.25          py36h830ac7b_1000    conda-forge
ffmpeg                    4.2                  h6538335_0    conda-forge
ffmpy                     0.2.2                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1  
gast                      0.3.2                      py_0  
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0            py36h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
imageio                   2.5.0                    py36_0  
imageio-ffmpeg            0.3.0                      py_0    conda-forge
intel-openmp              2019.4                      245  
joblib                    0.13.2                   py36_0  
jpeg                      9b                   hb83a4c4_2  
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py36ha925a31_0  
libmklml                  2019.0.5                      0  
libpng                    1.6.37               h2a8f88b_0  
libprotobuf               3.9.2                h7bd577a_0  
libtiff                   4.0.10               hb898794_2  
markdown                  3.1.1                    py36_0  
matplotlib                2.2.2            py36had4c4a9_2  
mkl                       2019.4                      245  
mkl-service               2.3.0            py36hb782905_0  
mkl_fft                   1.0.14           py36h14836fe_0  
mkl_random                1.1.0            py36h675688f_0  
networkx                  2.3                        py_0  
numpy                     1.16.2           py36h19fb1c0_0  
numpy-base                1.16.2           py36hc3f5095_0  
nvidia-ml-py3             7.352.1                  pypi_0    pypi
olefile                   0.46                     py36_0  
opencv-python             4.1.1.26                 pypi_0    pypi
openssl                   1.1.1d               he774522_0  
pathlib                   1.0.1                    py36_1  
pillow                    6.1.0            py36hdc69c19_0  
pip                       19.2.3                   py36_0  
protobuf                  3.9.2            py36h33f27b4_0  
psutil                    5.6.3            py36he774522_0  
pyparsing                 2.4.2                      py_0  
pyqt                      5.9.2            py36h6538335_2  
pyreadline                2.1                      py36_1  
python                    3.6.9                h5500b2f_0  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.2                     py_0  
pywavelets                1.0.3            py36h8c2d366_1  
pywin32                   223              py36hfa6e2cd_1  
pyyaml                    5.1.2            py36he774522_0  
qt                        5.9.7            vc14h73c81de_0  
scikit-image              0.15.0           py36ha925a31_0  
scikit-learn              0.21.3           py36h6288b17_0  
scipy                     1.3.1            py36h29ff71c_0  
setuptools                41.2.0                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.12.0                   py36_0  
sqlite                    3.29.0               he774522_0  
tensorboard               1.12.2                   pypi_0    pypi
tensorflow                1.12.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                     py_0  
tensorflow-gpu            1.14.0               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.10.0                     py_0  
toposort                  1.5                        py_3    conda-forge
tornado                   6.0.3            py36he774522_0  
tqdm                      4.36.1                     py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_0  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
wrapt                     1.11.2           py36he774522_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  

================= Configs ==================
--------- .faceswap ---------
backend:                  nvidia

--------- convert.ini ---------

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

[color.match_hist]
threshold:                99.0

[mask.box_blend]
type:                     gaussian
distance:                 11.0
radius:                   5.0
passes:                   1

[mask.mask_blend]
type:                     normalized
radius:                   3.0
passes:                   4
erosion:                  0.0

[scaling.sharpen]
method:                   unsharp_mask
amount:                   150
radius:                   0.3
threshold:                5.0

[writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     none
profile:                  auto
level:                    auto

[writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

[writer.opencv]
format:                   png
draw_transparent:         False
jpg_quality:              75
png_compress_level:       3

[writer.pillow]
format:                   png
draw_transparent:         False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

--------- extract.ini ---------

[align.fan]
batch-size:               8

[detect.cv2_dnn]
confidence:               50

[detect.mtcnn]
minsize:                  20
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7
scalefactor:              0.709
batch-size:               8

[detect.s3fd]
confidence:               50
batch-size:               8

--------- gui.ini ---------

[global]
fullscreen:               False
tab:                      extract
options_panel_width:      30
console_panel_height:     20
font:                     default
font_size:                9

--------- train.ini ---------

[global]
coverage:                 68.75
mask_type:                none
mask_blur:                False
icnr_init:                False
conv_aware_init:          False
subpixel_upscaling:       False
reflect_padding:          False
penalized_mask_loss:      True
loss_function:            mae
learning_rate:            5e-05

[model.dfl_h128]
lowmem:                   False

[model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[model.original]
lowmem:                   False

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.villain]
lowmem:                   False

[trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4
```

**Comment by torzdf** [comment]
Try latest commit. I've forced it to use ffmpeg for all video files,
