### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR when Extracting

### ISSUE THREAD

**Issue by Futtttz** [deepfakes/faceswap#904]
Error on extrace:
```
2019-10-14 00:35:36.958535: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-10-14 00:35:36.964129: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

10/14/2019 00:35:39 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "/home/tianze/face/lib/cli.py", line 128, in execute_script
process.process()
File "/home/tianze/face/scripts/extract.py", line 61, in process
self.run_extraction()
File "/home/tianze/face/scripts/extract.py", line 187, in run_extraction
self.extractor.launch()
File "/home/tianze/face/plugins/extract/pipeline.py", line 180, in launch
self._launch_aligner()
File "/home/tianze/face/plugins/extract/pipeline.py", line 326, in _launch_aligner
self._aligner.initialize(**kwargs)
File "/home/tianze/face/plugins/extract/_base.py", line 330, in initialize
self.init_model()
File "/home/tianze/face/plugins/extract/align/fan.py", line 41, in init_model
self.model.predict(placeholder)
File "/home/tianze/face/lib/model/session.py", line 66, in predict
return self._model.predict(feed, batch_size=batch_size)
File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/engine/training.py", line 1169, in predict
steps=steps)
File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
batch_outs = f(ins_batch)
File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
return self._call(inputs)
File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
fetched = self._callable_fn(*array_vals)
File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
(0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[{{node conv2d_1/convolution}}]]
[[conv2d_56/BiasAdd/_6051]]
(1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.


To Reproduce
Extract from mp4

Expected behavior
Extraction



Log:



10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_card_most_free        DEBUG    Active GPU Card with most free VRAM: {'device': 'Tesla V100-PCIE-32GB', 'free': 32061.625, 'total': 32480.5, 'card_id': 1}
10/14/2019 00:35:18 MainProcess     MainThread      pipeline        _set_parallel_processing  VERBOSE  Tesla V100-PCIE-32GB - 32061MB free of 32480MB
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initializing GPUStats
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 3
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1, 2]
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 3
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_driver                DEBUG    GPU Driver: 410.104
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_devices               DEBUG    GPU Devices: ['Tesla V100-PCIE-32GB', 'Tesla V100-PCIE-32GB', 'Tesla V100-PCIE-32GB']
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_vram                  DEBUG    GPU VRAM: [32480.5, 32480.5, 32480.5]
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initialized GPUStats
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 3
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1, 2]
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 3
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_free                  DEBUG    GPU VRAM free: [1143.625, 32061.625, 32061.625]
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 3
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1, 2]
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 3
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_free                  DEBUG    GPU VRAM free: [1143.625, 32061.625, 32061.625]
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 3
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1, 2]
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 3
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_free                  DEBUG    GPU VRAM free: [1143.625, 32061.625, 32061.625]
10/14/2019 00:35:18 MainProcess     MainThread      gpu_stats       get_card_most_free        DEBUG    Active GPU Card with most free VRAM: {'device': 'Tesla V100-PCIE-32GB', 'free': 32061.625, 'total': 32480.5, 'card_id': 1}
10/14/2019 00:35:18 MainProcess     MainThread      pipeline        _set_extractor_batchsize  DEBUG    Plugin requirements within threshold: (plugin_required: 8192MB, vram_free: 32061MB)
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_detect_in', maxsize: 64)
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_detect_in')
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_detect_in'
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_detect_in'
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_align_in', maxsize: 32)
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_align_in')
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_align_in'
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_align_in'
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_align_out', maxsize: 32)
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_align_out')
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_align_out'
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_align_out'
10/14/2019 00:35:18 MainProcess     MainThread      pipeline        _add_queues               DEBUG    Queues: {'extract_align_out': <queue.Queue object at 0x7f9b05530048>, 'extract_align_in': <queue.Queue object at 0x7f9b05525f28>, 'extract_detect_in': <queue.Queue object at 0x7f9b05525e10>}
10/14/2019 00:35:18 MainProcess     MainThread      pipeline        __init__                  DEBUG    Initialized Extractor
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_save'
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_save', maxsize: 0)
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_save')
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_save'
10/14/2019 00:35:18 MainProcess     MainThread      extract         __init__                  DEBUG    Initialized Extract
10/14/2019 00:35:18 MainProcess     MainThread      extract         process                   INFO     Starting, this may take a while...
10/14/2019 00:35:18 MainProcess     MainThread      extract         threaded_io               DEBUG    Threading task: (Task: 'load')
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'load_images', thread_count: 1)
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'load_images'
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'load_images'
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'load_images_0'
10/14/2019 00:35:18 MainProcess     load_images_0   extract         load_images               DEBUG    Load Images: Start
10/14/2019 00:35:18 MainProcess     load_images_0   fsmedia         load_video_frames         DEBUG    Input is video. Capturing frames
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'load_images': 1
10/14/2019 00:35:18 MainProcess     MainThread      extract         threaded_io               DEBUG    Threading task: (Task: 'save')
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'save_faces', thread_count: 1)
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'save_faces'
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'save_faces'
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'save_faces_0'
10/14/2019 00:35:18 MainProcess     save_faces_0    extract         save_faces                DEBUG    Save Faces: Start
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'save_faces': 1
10/14/2019 00:35:18 MainProcess     MainThread      extract         process_item_count        DEBUG    Items already processed: 0
10/14/2019 00:35:18 MainProcess     MainThread      extract         process_item_count        DEBUG    Items to be Processed: 335
10/14/2019 00:35:18 MainProcess     MainThread      pipeline        _launch_aligner           DEBUG    Launching Aligner
10/14/2019 00:35:18 MainProcess     MainThread      _base           initialize                DEBUG    initialize Align: (args: (), kwargs: {'out_queue': <queue.Queue object at 0x7f9b05530048>, 'in_queue': <queue.Queue object at 0x7f9b05525f28>})
10/14/2019 00:35:18 MainProcess     MainThread      _base           initialize                INFO     Initializing FAN Aligner...
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'align_predict'
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'align_predict', maxsize: 1)
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'align_predict')
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'align_predict'
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'align_post'
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'align_post', maxsize: 1)
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'align_post')
10/14/2019 00:35:18 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'align_post'
10/14/2019 00:35:18 MainProcess     MainThread      _base           _compile_threads          DEBUG    Compiling align threads
10/14/2019 00:35:18 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: align_input, function: <bound method Align.process_input of <plugins.extract.align.fan.Align object at 0x7f9b055136a0>>, in_queue: <queue.Queue object at 0x7f9b05525f28>, out_queue: <queue.Queue object at 0x7f9b05525d68>)
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'align_input', thread_count: 1)
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'align_input'
10/14/2019 00:35:18 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: align_input
10/14/2019 00:35:18 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: align_predict, function: <bound method Aligner._predict of <plugins.extract.align.fan.Align object at 0x7f9b055136a0>>, in_queue: <queue.Queue object at 0x7f9b05525d68>, out_queue: <queue.Queue object at 0x7f9b05525b38>)
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'align_predict', thread_count: 1)
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'align_predict'
10/14/2019 00:35:18 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: align_predict
10/14/2019 00:35:18 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: align_output, function: <bound method Align.process_output of <plugins.extract.align.fan.Align object at 0x7f9b055136a0>>, in_queue: <queue.Queue object at 0x7f9b05525b38>, out_queue: <queue.Queue object at 0x7f9b05530048>)
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'align_output', thread_count: 1)
10/14/2019 00:35:18 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'align_output'
10/14/2019 00:35:18 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: align_output
10/14/2019 00:35:18 MainProcess     MainThread      _base           _compile_threads          DEBUG    Compiled align threads: [<lib.multithreading.MultiThread object at 0x7f9b05525978>, <lib.multithreading.MultiThread object at 0x7f9b05530240>, <lib.multithreading.MultiThread object at 0x7f9b05530278>]
10/14/2019 00:35:18 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From /home/tianze/face/lib/model/session.py:110: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.\n
10/14/2019 00:35:18 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From /home/tianze/face/lib/model/session.py:113: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.\n
10/14/2019 00:35:20 MainProcess     MainThread      session         _set_session              DEBUG    Creating tf.session: (graph: <tensorflow.python.framework.ops.Graph object at 0x7f9b05530588>, session: <tensorflow.python.client.session.Session object at 0x7f9b05530748>, config: )
10/14/2019 00:35:20 MainProcess     MainThread      session         load_model                VERBOSE  Initializing plugin model: FAN
10/14/2019 00:35:20 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From /home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.\n
10/14/2019 00:35:20 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From /home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.\n
10/14/2019 00:35:20 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From /home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:245: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.\n
10/14/2019 00:35:21 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From /home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:3980: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.\n
10/14/2019 00:35:21 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From /home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:2018: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.\n
10/14/2019 00:35:33 MainProcess     MainThread      deprecation_wrapper __getattr__               WARNING  From /home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.\n
Traceback (most recent call last):
  File "/home/tianze/face/lib/cli.py", line 128, in execute_script
    process.process()
  File "/home/tianze/face/scripts/extract.py", line 61, in process
    self.run_extraction()
  File "/home/tianze/face/scripts/extract.py", line 187, in run_extraction
    self.extractor.launch()
  File "/home/tianze/face/plugins/extract/pipeline.py", line 180, in launch
    self._launch_aligner()
  File "/home/tianze/face/plugins/extract/pipeline.py", line 326, in _launch_aligner
    self._aligner.initialize(**kwargs)
  File "/home/tianze/face/plugins/extract/_base.py", line 330, in initialize
    self.init_model()
  File "/home/tianze/face/plugins/extract/align/fan.py", line 41, in init_model
    self.model.predict(placeholder)
  File "/home/tianze/face/lib/model/session.py", line 66, in predict
    return self._model.predict(feed, batch_size=batch_size)
  File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/tianze/anaconda3/envs/ftz/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}}]]
	 [[conv2d_56/BiasAdd/_6051]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}}]]
0 successful operations.
0 derived errors ignored.

============ System Information ============
encoding:            UTF-8
git_branch:          Not Found
git_commits:         Not Found
gpu_cuda:            9.1
gpu_cudnn:           7.6.3
gpu_devices:         GPU_0: Tesla V100-PCIE-32GB, GPU_1: Tesla V100-PCIE-32GB, GPU_2: Tesla V100-PCIE-32GB
gpu_devices_active:  GPU_0, GPU_1, GPU_2
gpu_driver:          410.104
gpu_vram:            GPU_0: 32480MB, GPU_1: 32480MB, GPU_2: 32480MB
os_machine:          x86_64
os_platform:         Linux-4.15.0-64-generic-x86_64-with-debian-buster-sid
os_release:          4.15.0-64-generic
py_command:          /home/tianze/face/faceswap.py extract -i /home/tianze/face/src/nomask.mp4 -o /home/tianze/face/faces/nomask --serializer json -D s3fd -A fan -nm none -min 0 -l 0.4 -bt 0.0 -een 1 -sz 256 -si 0 -L INFO -gui
py_conda_version:    conda 4.7.12
py_implementation:   CPython
py_version:          3.5.6
py_virtual_env:      True
sys_cores:           48
sys_processor:       x86_64
sys_ram:             Total: 514627MB, Available: 469354MB, Used: 40669MB, Free: 314539MB

=============== Pip Packages ===============
absl-py==0.8.1
astor==0.8.0
certifi==2016.9.26
cloudpickle==1.2.2
cycler==0.10.0
dask==2.5.2
decorator==4.4.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.3.2
google-pasta==0.1.7
grpcio==1.24.1
h5py==2.9.0
imageio==2.4.1
imageio-ffmpeg==0.3.0
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.0.1
Markdown==3.1.1
matplotlib==2.2.2
networkx==2.3
numpy==1.16.2
nvidia-ml-py3==7.352.1
olefile==0.46
opencv-python==4.1.1.26
pathlib==1.0.1
Pillow==6.1.0
protobuf==3.10.0
psutil==5.4.7
pyparsing==2.4.2
python-dateutil==2.7.3
pytz==2019.3
PyWavelets==1.0.0
PyYAML==5.1.2
scikit-image==0.14.0
scikit-learn==0.20.0
scipy==1.1.0
six==1.11.0
tensorboard==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
termcolor==1.1.0
toolz==0.10.0
toposort==1.5
tornado==5.1.1
tqdm==4.36.1
Werkzeug==0.16.0
wrapt==1.11.2

============== Conda Packages ==============
# packages in environment at /home/tianze/anaconda3/envs/ftz:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.8.1                    pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
blas                      1.0                         mkl  
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2016.9.26                py35_0    conda-forge
cloudpickle               1.2.2                      py_0  
cycler                    0.10.0           py35hc4d5149_0  
dask-core                 2.5.2                      py_0  
dbus                      1.13.6               h746ee38_0  
decorator                 4.4.0                      py_0  
expat                     2.2.6                he6710b0_0  
fastcluster               1.1.25           py35hf8a1672_0    conda-forge
ffmpeg                    4.0                  h04d0a96_0  
ffmpy                     0.2.2                    pypi_0    pypi
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8                  hab7d2ae_1  
gast                      0.3.2                    pypi_0    pypi
glib                      2.56.2               hd408876_0  
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.24.1                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.9.0                    pypi_0    pypi
icu                       58.2                 h9c2bf20_1  
imageio                   2.4.1                    py35_0  
imageio-ffmpeg            0.3.0                      py_0    conda-forge
intel-openmp              2019.4                      243  
jpeg                      9b                   h024ee3a_2  
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
kiwisolver                1.0.1            py35hf484d3e_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libopus                   1.3                  h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
markdown                  3.1.1                    pypi_0    pypi
matplotlib                2.2.2            py35h0e671d2_1  
mkl                       2018.0.3                      1  
ncurses                   6.1                  he6710b0_1  
networkx                  2.3                        py_0  
numpy                     1.16.2                   pypi_0    pypi
nvidia-ml-py3             7.352.1                  pypi_0    pypi
olefile                   0.46                     py35_0  
opencv-python             4.1.1.26                 pypi_0    pypi
openssl                   1.0.2r               h14c3975_0    conda-forge
pathlib                   1.0.1                    pypi_0    pypi
pcre                      8.43                 he6710b0_0  
pillow                    6.1.0                    pypi_0    pypi
pip                       10.0.1                   py35_0  
protobuf                  3.10.0                   pypi_0    pypi
psutil                    5.4.7            py35h14c3975_0  
pyparsing                 2.4.2                      py_0  
pyqt                      5.9.2            py35h751905a_0  
python                    3.5.6                hc3d631a_0  
python-dateutil           2.7.3                    py35_0  
pytz                      2019.3                     py_0  
pywavelets                1.0.0            py35hdd07704_0  
pyyaml                    5.1.2                    pypi_0    pypi
qt                        5.9.5                h7e424d6_0  
readline                  7.0                  h7b6447c_5  
scikit-image              0.14.0           py35hf484d3e_1  
scikit-learn              0.20.0           py35h4989274_1  
scipy                     1.1.0            py35hd20e5f9_0  
setuptools                41.4.0                   pypi_0    pypi
sip                       4.19.8           py35hf484d3e_0  
six                       1.11.0                   py35_1  
sqlite                    3.30.0               h7b6447c_0  
tensorboard               1.14.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
tensorflow-gpu            1.14.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
toolz                     0.10.0                     py_0  
toposort                  1.5                        py_3    conda-forge
tornado                   5.1.1            py35h7b6447c_0  
tqdm                      4.36.1                     py_0  
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.31.1                   py35_0  
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  

================= Configs ==================
--------- gui.ini ---------

[global]
fullscreen:               False
tab:                      extract
options_panel_width:      30
console_panel_height:     20
font:                     default
font_size:                9

--------- train.ini ---------

[global]
coverage:                 68.75
mask_type:                none
mask_blur:                False
icnr_init:                False
conv_aware_init:          False
subpixel_upscaling:       False
reflect_padding:          False
penalized_mask_loss:      True
loss_function:            mae
learning_rate:            5e-05

[model.dfl_sae]
input_size:               128
autoencoder_dims:         0
architecture:             df
clipnorm:                 True
multiscale_decoder:       False
decoder_dims:             21
encoder_dims:             42

[model.realface]
complexity_decoder:       512
input_size:               64
dense_nodes:              1536
output_size:              128
complexity_encoder:       128

[model.original]
lowmem:                   False

[model.dfl_h128]
lowmem:                   False

[model.villain]
lowmem:                   False

[model.unbalanced]
input_size:               128
complexity_decoder_b:     512
complexity_encoder:       128
lowmem:                   False
complexity_decoder_a:     384
clipnorm:                 True
nodes:                    1024

[trainer.original]
rotation_range:           10
color_clahe_max_size:     4
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
preview_images:           14
zoom_amount:              5
shift_range:              5

--------- convert.ini ---------

[mask.box_blend]
radius:                   5.0
distance:                 11.0
type:                     gaussian
passes:                   1

[mask.mask_blend]
erosion:                  0.0
radius:                   3.0
type:                     normalized
passes:                   4

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.manual_balance]
balance_3:                0.0
balance_1:                0.0
contrast:                 0.0
colorspace:               HSV
brightness:               0.0
balance_2:                0.0

[color.match_hist]
threshold:                99.0

[scaling.sharpen]
threshold:                5.0
radius:                   0.3
method:                   unsharp_mask
amount:                   150

[writer.ffmpeg]
profile:                  auto
container:                mp4
level:                    auto
tune:                     none
preset:                   medium
crf:                      23
codec:                    libx264

[writer.pillow]
optimize:                 False
png_compress_level:       3
tif_compression:          tiff_deflate
jpg_quality:              75
format:                   png
draw_transparent:         False
gif_interlace:            True

[writer.gif]
subrectangles:            False
loop:                     0
fps:                      25
palettesize:              256

[writer.opencv]
png_compress_level:       3
draw_transparent:         False
jpg_quality:              75
format:                   png

--------- .faceswap ---------
backend:                  nvidia

--------- extract.ini ---------

[global]
allow_growth:             False

[align.fan]
batch-size:               8

[detect.cv2_dnn]
confidence:               50

[detect.mtcnn]
batch-size:               8
threshold_1:              0.6
threshold_2:              0.7
minsize:                  20
scalefactor:              0.709
threshold_3:              0.7

[detect.s3fd]
batch-size:               8
confidence:               50
```

**Comment by torzdf** [comment]
Tensorflow raised an unknown error. This is most likely caused by a failure to launch cuDNN which can occur for some GPU/Tensorflow combinations.

You should enable `allow_growth` to attempt to resolve this issue:
- **GUI:** Go to Settings > Extract Plugins > Global and enable the `allow_growth` option.
- **CLI:** Go to `faceswap/config/extract.ini` and change the `allow_growth option to `True`.
