### ISSUE TITLE
Attribute Error when doing alignment manual, extract, merge, anything with alignment. object has no attribute 'copy'. Sometimes 'batchsize.

### ISSUE THREAD

**Issue by colorsdiary** [deepfakes/faceswap#911]
Every time I try to sort or merge or do something with alignments, it fails,
I looked up online, and it seems that I have to change or downgrade my keras version,
I'm pretty familiar with codes. I don't code at all, but I can copy and paste a command line. For the life of me, I spent a few hours to figure out that "python" is a different terminal than windows' own CMD. I tried many codes, nothing worked. I installed FaceSwap through the installer, and it seems something didn't install right .. but I don't even know how would I try to fix it.

My hardware is AMD ryzen CPU, and AMD Vega 56 GPU

```
> Traceback (most recent call last):
> File "C:\Users\ColorsDiary\faceswap\lib\cli.py", line 128, in execute_script
> process.process()
> File "C:\Users\ColorsDiary\faceswap\tools\alignments.py", line 52, in process
> job.process()
> File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs_manual.py", line 461, in process
> self.mouse_handler = MouseHandler(self.interface, self.arguments.loglevel)
> File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs_manual.py", line 768, in init
> self.extractor = self.init_extractor()
> File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs_manual.py", line 788, in init_extractor
> extractor.set_batchsize(plugin_type, 1)
> File "C:\Users\ColorsDiary\faceswap\plugins\extract\pipeline.py", line 166, in set_batchsize
> plugin.batchsize = batchsize
> AttributeError: 'NoneType' object has no attribute 'batchsize'
```
Here is another log with the entire log file info:
```
> 10/26/2019 05:03:53 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO
> 10/26/2019 05:03:53 MainProcess     MainThread      cli             execute_script            DEBUG    Executing: alignments. PID: 13740
> 10/26/2019 05:03:53 MainProcess     MainThread      cli             setup_amd                 DEBUG    Setting up for AMD
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   setup_plaidml             INFO     Setting up for PlaidML
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   setup_plaidml             VERBOSE  Setting Keras Backend to PlaidML
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   __init__                  DEBUG    Initializing: PlaidMLStats: (loglevel: INFO, log: True)
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   initialize                DEBUG    Initializing PlaidML
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   set_plaidml_logger        DEBUG    Setting PlaidML Default Logger
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   set_plaidml_logger        DEBUG    Set PlaidML Default Logger
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   set_verbosity             DEBUG    Setting PlaidML Loglevel: INFO
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   initialize                DEBUG    Initialized PlaidML
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   get_supported_devices     DEBUG    [<plaidml._DeviceConfig object at 0x000001B2C4AF2AC8>]
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   get_all_devices           DEBUG    Experimental Devices: [<plaidml._DeviceConfig object at 0x000001B2C4AF2F98>]
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   get_all_devices           DEBUG    [<plaidml._DeviceConfig object at 0x000001B2C4AF2F98>, <plaidml._DeviceConfig object at 0x000001B2C4AF2AC8>]
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   __init__                  DEBUG    Initialized: PlaidMLStats
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   load_active_devices       DEBUG    Setting largest PlaidML device
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   set_largest_gpu           DEBUG    Obtaining largest supported device
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   supported_indices         DEBUG    [1]
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   set_largest_gpu           DEBUG    Max VRAM: 8176.0
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   set_largest_gpu           DEBUG    GPU IDX: 1
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   set_largest_gpu           INFO     Setting GPU to largest available supported device. If you want to override this selection, run `plaidml-setup` from the command line.
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   setup_plaidml             INFO     Using GPU: ['opencl_amd_gfx900.0', 'opencl_amd_gfx900.0']
> 10/26/2019 05:03:53 MainProcess     MainThread      plaidml_tools   setup_plaidml             INFO     Successfully set up for PlaidML
> 10/26/2019 05:03:53 MainProcess     MainThread      cli             setup_amd                 DEBUG    setup up for PlaidML
> 10/26/2019 05:03:55 MainProcess     MainThread      cli             test_for_tf_version       DEBUG    Installed Tensorflow Version: 1.14
> 10/26/2019 05:03:55 MainProcess     MainThread      queue_manager   __init__                  DEBUG    Initializing QueueManager
> 10/26/2019 05:03:55 MainProcess     MainThread      queue_manager   __init__                  DEBUG    Initialized QueueManager
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      __init__                  DEBUG    Initializing Alignments: (arguments: 'Namespace(align_eyes=False, alignments_file=['C:\\FaceSwap\\Monica_alignments.fsa'], configfile=None, disable_monitor=False, extract_every_n=10, faces_dir='C:\\FaceSwap\\Monica alignment thingy', frames_dir='C:\\FaceSwap\\Monica.mp4', func=<bound method ScriptExecutor.execute_script of <lib.cli.ScriptExecutor object at 0x000001B2C4A16F60>>, job='extract', large=False, logfile=None, loglevel='INFO', output='console', redirect_gui=True, size=256)'
> 10/26/2019 05:03:55 MainProcess     MainThread      utils           set_system_verbosity      DEBUG    System Verbosity level: 2
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      load_alignments           DEBUG    Loading alignments
> 10/26/2019 05:03:55 MainProcess     MainThread      media           __init__                  DEBUG    Initializing AlignmentData: (alignments file: 'C:\FaceSwap\Monica_alignments.fsa')
> 10/26/2019 05:03:55 MainProcess     MainThread      media           __init__                  INFO     [ALIGNMENT DATA]
> 10/26/2019 05:03:55 MainProcess     MainThread      media           check_file_exists         VERBOSE  Alignments file exists at 'C:\FaceSwap\Monica_alignments.fsa'
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      __init__                  DEBUG    Initializing AlignmentData: (folder: 'C:\FaceSwap', filename: 'Monica_alignments.fsa')
> 10/26/2019 05:03:55 MainProcess     MainThread      serializer      get_serializer            DEBUG    <lib.serializer._PickleSerializer object at 0x000001B2DABFF2E8>
> 10/26/2019 05:03:55 MainProcess     MainThread      serializer      get_serializer            DEBUG    <lib.serializer._CompressedSerializer object at 0x000001B2DABFF320>
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      get_location              DEBUG    Getting location: (folder: 'C:\FaceSwap', filename: 'Monica_alignments.fsa')
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      get_location              VERBOSE  Alignments filepath: 'C:\FaceSwap\Monica_alignments.fsa'
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      load                      DEBUG    Loading alignments
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      load                      INFO     Reading alignments from: 'C:\FaceSwap\Monica_alignments.fsa'
> 10/26/2019 05:03:55 MainProcess     MainThread      serializer      load                      DEBUG    filename: C:\FaceSwap\Monica_alignments.fsa
> 10/26/2019 05:03:55 MainProcess     MainThread      serializer      load                      DEBUG    stored data type: <class 'bytes'>
> 10/26/2019 05:03:55 MainProcess     MainThread      serializer      unmarshal                 DEBUG    data type: <class 'bytes'>
> 10/26/2019 05:03:55 MainProcess     MainThread      serializer      unmarshal                 DEBUG    returned data type: <class 'dict'>
> 10/26/2019 05:03:55 MainProcess     MainThread      serializer      load                      DEBUG    data type: <class 'dict'>
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      load                      DEBUG    Loaded alignments
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      has_legacy_landmarksxy    DEBUG    checking legacy landmarksXY
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      has_legacy_landmarksxy    DEBUG    legacy landmarksXY: False
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      __init__                  DEBUG    Initialized AlignmentData
> 10/26/2019 05:03:55 MainProcess     MainThread      media           __init__                  VERBOSE  3425 items loaded
> 10/26/2019 05:03:55 MainProcess     MainThread      media           __init__                  DEBUG    Initialized AlignmentData
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      load_alignments           DEBUG    Alignments: <tools.lib_alignments.media.AlignmentData object at 0x000001B2C4AF2EF0>
> 10/26/2019 05:03:55 MainProcess     MainThread      alignments      __init__                  DEBUG    Initialized Alignments
> 10/26/2019 05:03:55 MainProcess     MainThread      jobs            __init__                  DEBUG    Initializing Extract: (arguments: Namespace(align_eyes=False, alignments_file=['C:\\FaceSwap\\Monica_alignments.fsa'], configfile=None, disable_monitor=False, extract_every_n=10, faces_dir='C:\\FaceSwap\\Monica alignment thingy', frames_dir='C:\\FaceSwap\\Monica.mp4', func=<bound method ScriptExecutor.execute_script of <lib.cli.ScriptExecutor object at 0x000001B2C4A16F60>>, job='extract', large=False, logfile=None, loglevel='INFO', output='console', redirect_gui=True, size=256))
> 10/26/2019 05:03:55 MainProcess     MainThread      media           __init__                  DEBUG    Initializing Frames: (folder: 'C:\FaceSwap\Monica.mp4')
> 10/26/2019 05:03:55 MainProcess     MainThread      media           __init__                  INFO     [FRAMES DATA]
> 10/26/2019 05:03:55 MainProcess     MainThread      media           check_input_folder        VERBOSE  Video exists at: 'C:\FaceSwap\Monica.mp4'
> 10/26/2019 05:03:56 MainProcess     MainThread      media           process_video             INFO     Loading video frames from C:\FaceSwap\Monica.mp4
> 10/26/2019 05:03:56 MainProcess     MainThread      image           count_frames_and_secs     DEBUG    iswin: 'True'
> 10/26/2019 05:03:56 MainProcess     MainThread      image           count_frames_and_secs     DEBUG    FFMPEG Command: 'C:\Users\ColorsDiary\MiniConda3\envs\faceswap\Library\bin\ffmpeg.exe -i C:\FaceSwap\Monica.mp4 -map 0:v:0 -c copy -f null -'
> 10/26/2019 05:03:56 MainProcess     MainThread      image           count_frames_and_secs     DEBUG    attempt: 1 of 3
> 10/26/2019 05:03:56 MainProcess     MainThread      image           count_frames_and_secs     DEBUG    Succesfully communicated with FFMPEG
> 10/26/2019 05:03:56 MainProcess     MainThread      image           count_frames_and_secs     DEBUG    frame line: 'frame= 3424 fps=0.0 q=-1.0 Lsize=N/A time=00:02:22.62 bitrate=N/A speed=1.74e+03x    '
> 10/26/2019 05:03:56 MainProcess     MainThread      utils           convert_to_secs           DEBUG    from time: ('00', '02', '22.62')
> 10/26/2019 05:03:56 MainProcess     MainThread      utils           convert_to_secs           DEBUG    to secs: 142.62
> 10/26/2019 05:03:56 MainProcess     MainThread      image           count_frames_and_secs     DEBUG    nframes: 3424, nsecs: 142.62
> 10/26/2019 05:03:56 MainProcess     MainThread      media           __init__                  VERBOSE  3424 items loaded
> 10/26/2019 05:03:56 MainProcess     MainThread      media           __init__                  DEBUG    Initialized Frames
> 10/26/2019 05:03:56 MainProcess     MainThread      jobs            __init__                  DEBUG    Initialized Extract
> 10/26/2019 05:03:56 MainProcess     MainThread      alignments      process                   DEBUG    <tools.lib_alignments.jobs.Extract object at 0x000001B2C3A1CB38>
> 10/26/2019 05:03:56 MainProcess     MainThread      jobs            process                   INFO     [EXTRACT FACES]
> 10/26/2019 05:03:56 MainProcess     MainThread      jobs            check_folder              VERBOSE  Creating output folder at 'C:\FaceSwap\Monica alignment thingy'
> 10/26/2019 05:03:56 MainProcess     MainThread      jobs            export_faces              INFO     Skipping every 10 frames
> 10/26/2019 05:04:23 MainProcess     MainThread      plaidml_tools   initialize                DEBUG    PlaidML already initialized
> 10/26/2019 05:04:23 MainProcess     MainThread      plaidml_tools   get_supported_devices     DEBUG    [<plaidml._DeviceConfig object at 0x000001B2DDA30240>]
> 10/26/2019 05:04:23 MainProcess     MainThread      plaidml_tools   get_all_devices           DEBUG    Experimental Devices: [<plaidml._DeviceConfig object at 0x000001B2DDA30898>]
> 10/26/2019 05:04:23 MainProcess     MainThread      plaidml_tools   get_all_devices           DEBUG    [<plaidml._DeviceConfig object at 0x000001B2DDA30898>, <plaidml._DeviceConfig object at 0x000001B2DDA30240>]
> 10/26/2019 05:04:23 MainProcess     MainThread      plaidml_tools   __init__                  DEBUG    Initialized: PlaidMLStats
> 10/26/2019 05:04:23 MainProcess     MainThread      plaidml_tools   supported_indices         DEBUG    [1]
> 10/26/2019 05:04:23 MainProcess     MainThread      plaidml_tools   supported_indices         DEBUG    [1]
> Traceback (most recent call last):
>   File "C:\Users\ColorsDiary\faceswap\lib\cli.py", line 128, in execute_script
>     process.process()
>   File "C:\Users\ColorsDiary\faceswap\tools\alignments.py", line 52, in process
>     job.process()
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs.py", line 422, in process
>     self.export_faces()
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs.py", line 457, in export_faces
>     extracted_faces += self.output_faces(frame)
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs.py", line 470, in output_faces
>     faces = self.select_valid_faces(frame_fullname)
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\jobs.py", line 487, in select_valid_faces
>     faces = self.extracted_faces.get_faces_in_frame(frame)
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\media.py", line 305, in get_faces_in_frame
>     self.get_faces(frame)
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\media.py", line 288, in get_faces
>     self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
>   File "C:\Users\ColorsDiary\faceswap\tools\lib_alignments\media.py", line 288, in <listcomp>
>     self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
> AttributeError: 'NoneType' object has no attribute 'copy'
> 
> ============ System Information ============
> encoding:            cp1252
> git_branch:          master
> git_commits:         bb26afd BUGFIX: Nn_blocks upscale (#909)
> gpu_cuda:            No global version found. Check Conda packages for Conda Cuda
> gpu_cudnn:           No global version found. Check Conda packages for Conda cuDNN
> gpu_devices:         GPU_0: Advanced Micro Devices, Inc. - gfx900 (experimental), GPU_1: Advanced Micro Devices, Inc. - gfx900 (supported)
> gpu_devices_active:  GPU_0, GPU_1
> gpu_driver:          ['2906.10 (PAL,HSAIL)', '2906.10 (PAL,HSAIL)']
> gpu_vram:            GPU_0: 8176MB, GPU_1: 8176MB
> os_machine:          AMD64
> os_platform:         Windows-10-10.0.17763-SP0
> os_release:          10
> py_command:          C:\Users\ColorsDiary\faceswap\tools.py alignments -j extract -a C:/FaceSwap/Monica_alignments.fsa -fc C:/FaceSwap/Monica alignment thingy -fr C:/FaceSwap/Monica.mp4 -o console -een 10 -sz 256 -L INFO -gui
> py_conda_version:    conda 4.7.12
> py_implementation:   CPython
> py_version:          3.6.9
> py_virtual_env:      True
> sys_cores:           12
> sys_processor:       AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
> sys_ram:             Total: 16315MB, Available: 11711MB, Used: 4604MB, Free: 11711MB
> 
> =============== Pip Packages ===============
> absl-py==0.8.0
> astor==0.8.0
> certifi==2019.9.11
> cffi==1.13.1
> cloudpickle==1.2.2
> cycler==0.10.0
> cytoolz==0.10.0
> dask==2.6.0
> decorator==4.4.0
> enum34==1.1.6
> fastcluster==1.1.25
> ffmpy==0.2.2
> gast==0.3.2
> grpcio==1.16.1
> h5py==2.9.0
> imageio==2.5.0
> imageio-ffmpeg==0.3.0
> joblib==0.13.2
> Keras==2.2.4
> Keras-Applications==1.0.8
> Keras-Preprocessing==1.1.0
> kiwisolver==1.1.0
> Markdown==3.1.1
> matplotlib==2.2.2
> mkl-fft==1.0.14
> mkl-random==1.1.0
> mkl-service==2.3.0
> networkx==2.4
> numpy==1.16.2
> nvidia-ml-py3==7.352.1
> olefile==0.46
> opencv-python==4.1.1.26
> pathlib==1.0.1
> Pillow==6.1.0
> plaidml==0.6.4
> plaidml-keras==0.6.4
> protobuf==3.9.2
> psutil==5.6.3
> pycparser==2.19
> pyparsing==2.4.2
> pyreadline==2.1
> python-dateutil==2.8.0
> pytz==2019.3
> PyWavelets==1.1.1
> pywin32==223
> PyYAML==5.1.2
> scikit-image==0.15.0
> scikit-learn==0.21.3
> scipy==1.3.1
> six==1.12.0
> tensorboard==1.14.0
> tensorflow==1.14.0
> tensorflow-estimator==1.14.0
> termcolor==1.1.0
> toolz==0.10.0
> toposort==1.5
> tornado==6.0.3
> tqdm==4.36.1
> Werkzeug==0.16.0
> wincertstore==0.2
> wrapt==1.11.2
> 
> ============== Conda Packages ==============
> # packages in environment at C:\Users\ColorsDiary\MiniConda3\envs\faceswap:
> #
> # Name                    Version                   Build  Channel
> _tflow_select             2.3.0                       mkl  
> absl-py                   0.8.0                    py36_0  
> astor                     0.8.0                    py36_0  
> blas                      1.0                         mkl  
> ca-certificates           2019.10.16                    0  
> certifi                   2019.9.11                py36_0  
> cffi                      1.13.1                   pypi_0    pypi
> cloudpickle               1.2.2                      py_0  
> cycler                    0.10.0           py36h009560c_0  
> cytoolz                   0.10.0           py36he774522_0  
> dask-core                 2.6.0                      py_0  
> decorator                 4.4.0                    py36_1  
> enum34                    1.1.6                    pypi_0    pypi
> fastcluster               1.1.25          py36h830ac7b_1000    conda-forge
> ffmpeg                    4.2                  h6538335_0    conda-forge
> ffmpy                     0.2.2                    pypi_0    pypi
> freetype                  2.9.1                ha9979f8_1  
> gast                      0.3.2                      py_0  
> grpcio                    1.16.1           py36h351948d_1  
> h5py                      2.9.0            py36h5e291fa_0  
> hdf5                      1.10.4               h7ebc959_0  
> icc_rt                    2019.0.0             h0cc432a_1  
> icu                       58.2                 ha66f8fd_1  
> imageio                   2.5.0                    py36_0  
> imageio-ffmpeg            0.3.0                      py_0    conda-forge
> intel-openmp              2019.4                      245  
> joblib                    0.13.2                   py36_0  
> jpeg                      9b                   hb83a4c4_2  
> keras                     2.2.4                         0  
> keras-applications        1.0.8                      py_0  
> keras-base                2.2.4                    py36_0  
> keras-preprocessing       1.1.0                      py_1  
> kiwisolver                1.1.0            py36ha925a31_0  
> libmklml                  2019.0.5                      0  
> libpng                    1.6.37               h2a8f88b_0  
> libprotobuf               3.9.2                h7bd577a_0  
> libtiff                   4.0.10               hb898794_2  
> markdown                  3.1.1                    py36_0  
> matplotlib                2.2.2            py36had4c4a9_2  
> mkl                       2019.4                      245  
> mkl-service               2.3.0            py36hb782905_0  
> mkl_fft                   1.0.14           py36h14836fe_0  
> mkl_random                1.1.0            py36h675688f_0  
> networkx                  2.4                        py_0  
> numpy                     1.16.2           py36h19fb1c0_0  
> numpy-base                1.16.2           py36hc3f5095_0  
> nvidia-ml-py3             7.352.1                  pypi_0    pypi
> olefile                   0.46                     py36_0  
> opencv-python             4.1.1.26                 pypi_0    pypi
> openssl                   1.1.1d               he774522_3  
> pathlib                   1.0.1                    py36_1  
> pillow                    6.1.0            py36hdc69c19_0  
> pip                       19.3.1                   py36_0  
> plaidml                   0.6.4                    pypi_0    pypi
> plaidml-keras             0.6.4                    pypi_0    pypi
> protobuf                  3.9.2            py36h33f27b4_0  
> psutil                    5.6.3            py36he774522_0  
> pycparser                 2.19                     pypi_0    pypi
> pyparsing                 2.4.2                      py_0  
> pyqt                      5.9.2            py36h6538335_2  
> pyreadline                2.1                      py36_1  
> python                    3.6.9                h5500b2f_0  
> python-dateutil           2.8.0                    py36_0  
> pytz                      2019.3                     py_0  
> pywavelets                1.1.1            py36he774522_0  
> pywin32                   223              py36hfa6e2cd_1  
> pyyaml                    5.1.2            py36he774522_0  
> qt                        5.9.7            vc14h73c81de_0  
> scikit-image              0.15.0           py36ha925a31_0  
> scikit-learn              0.21.3           py36h6288b17_0  
> scipy                     1.3.1            py36h29ff71c_0  
> setuptools                41.4.0                   py36_0  
> sip                       4.19.8           py36h6538335_0  
> six                       1.12.0                   py36_0  
> sqlite                    3.30.1               he774522_0  
> tensorboard               1.14.0           py36he3c9ec2_0  
> tensorflow                1.14.0          mkl_py36hb88db5b_0  
> tensorflow-base           1.14.0          mkl_py36ha978198_0  
> tensorflow-estimator      1.14.0                     py_0  
> termcolor                 1.1.0                    py36_1  
> tk                        8.6.8                hfa6e2cd_0  
> toolz                     0.10.0                     py_0  
> toposort                  1.5                        py_3    conda-forge
> tornado                   6.0.3            py36he774522_0  
> tqdm                      4.36.1                     py_0  
> vc                        14.1                 h0510ff6_4  
> vs2015_runtime            14.16.27012          hf0eaf9b_0  
> werkzeug                  0.16.0                     py_0  
> wheel                     0.33.6                   py36_0  
> wincertstore              0.2              py36h7fe50ca_0  
> wrapt                     1.11.2           py36he774522_0  
> xz                        5.2.4                h2fa13f4_4  
> yaml                      0.1.7                hc54c509_2  
> zlib                      1.2.11               h62dcd97_3  
> zstd                      1.3.7                h508b16e_0  
> 
> ================= Configs ==================
> --------- .faceswap ---------
> backend:                  amd
> 
> --------- convert.ini ---------
> 
> [color.color_transfer]
> clip:                     True
> preserve_paper:           True
> 
> [color.manual_balance]
> colorspace:               HSV
> balance_1:                0.0
> balance_2:                0.0
> balance_3:                0.0
> contrast:                 0.0
> brightness:               0.0
> 
> [color.match_hist]
> threshold:                99.0
> 
> [mask.box_blend]
> type:                     gaussian
> distance:                 11.0
> radius:                   5.0
> passes:                   1
> 
> [mask.mask_blend]
> type:                     normalized
> radius:                   3.0
> passes:                   4
> erosion:                  0.0
> 
> [scaling.sharpen]
> method:                   unsharp_mask
> amount:                   150
> radius:                   0.3
> threshold:                5.0
> 
> [writer.ffmpeg]
> container:                mp4
> codec:                    libx264
> crf:                      23
> preset:                   medium
> tune:                     none
> profile:                  auto
> level:                    auto
> 
> [writer.gif]
> fps:                      25
> loop:                     0
> palettesize:              256
> subrectangles:            False
> 
> [writer.opencv]
> format:                   png
> draw_transparent:         False
> jpg_quality:              75
> png_compress_level:       3
> 
> [writer.pillow]
> format:                   png
> draw_transparent:         False
> optimize:                 False
> gif_interlace:            True
> jpg_quality:              75
> png_compress_level:       3
> tif_compression:          tiff_deflate
> 
> --------- extract.ini ---------
> 
> [global]
> allow_growth:             False
> 
> [align.fan]
> batch-size:               12
> 
> [detect.cv2_dnn]
> confidence:               50
> 
> [detect.mtcnn]
> minsize:                  20
> threshold_1:              0.6
> threshold_2:              0.7
> threshold_3:              0.7
> scalefactor:              0.709
> batch-size:               8
> 
> [detect.s3fd]
> confidence:               50
> batch-size:               4
> 
> [mask.unet_dfl]
> batch-size:               8
> 
> [mask.vgg_clear]
> batch-size:               6
> 
> [mask.vgg_obstructed]
> batch-size:               2
> 
> --------- gui.ini ---------
> 
> [global]
> fullscreen:               False
> tab:                      extract
> options_panel_width:      30
> console_panel_height:     20
> font:                     default
> font_size:                9
> 
> --------- train.ini ---------
> 
> [global]
> coverage:                 68.75
> mask_type:                none
> mask_blur:                False
> icnr_init:                False
> conv_aware_init:          False
> subpixel_upscaling:       False
> reflect_padding:          False
> penalized_mask_loss:      True
> loss_function:            mae
> learning_rate:            5e-05
> 
> [model.dfl_h128]
> lowmem:                   False
> 
> [model.dfl_sae]
> input_size:               128
> clipnorm:                 True
> architecture:             df
> autoencoder_dims:         0
> encoder_dims:             42
> decoder_dims:             21
> multiscale_decoder:       False
> 
> [model.original]
> lowmem:                   False
> 
> [model.realface]
> input_size:               64
> output_size:              128
> dense_nodes:              1536
> complexity_encoder:       128
> complexity_decoder:       512
> 
> [model.unbalanced]
> input_size:               128
> lowmem:                   False
> clipnorm:                 True
> nodes:                    1024
> complexity_encoder:       128
> complexity_decoder_a:     384
> complexity_decoder_b:     512
> 
> [model.villain]
> lowmem:                   False
> 
> [trainer.original]
> preview_images:           14
> zoom_amount:              5
> rotation_range:           10
> shift_range:              5
> flip_chance:              50
> color_lightness:          30
> color_ab:                 8
> color_clahe_chance:       50
> color_clahe_max_size:     4
> 

```

**Comment by torzdf** [comment]
Frustratingly (for you) you pulled the code during a brief period when untested code was pushed to the faceswap Master branch :/

Could you delete your faceswap folder and get the code again to see if your problem persists.

Thanks

**Comment by colorsdiary** [comment]
> Frustratingly (for you) you pulled the code during a brief period when untested code was pushed to the faceswap Master branch :/
> 
> Could you delete your faceswap folder and get the code again to see if your problem persists.
> 
> Thanks

Thank you,
I will try that now, I had the code training for a 100,000 iterations to kinda get a feel for it :)

**Comment by colorsdiary** [comment]
> Frustratingly (for you) you pulled the code during a brief period when untested code was pushed to the faceswap Master branch :/
> 
> Could you delete your faceswap folder and get the code again to see if your problem persists.
> 
> Thanks

I reinstalled the code and it worked,

Thanks !
