### ISSUE TITLE
Manual broken after update

### ISSUE THREAD

**Issue by TobiTrom** [deepfakes/faceswap#915]
**Crash Report**
```
10/28/2019 17:36:22 MainProcess     MainThread      config          add_item                  DEBUG    Add item: (section: 'detect.mtcnn', title: 'batch-size', datatype: '<class 'int'>', default: '8', info: 'The batch size to use. To a point, higher batch sizes equal better performance, but setting it too high can harm performance.\n\n	Nvidia users: If the batchsize is set higher than the your GPU can accomodate then this will automatically be lowered.', rounding: '1', min_max: (1, 64), choices: [], gui_radio: False, fixed: True, group: None)
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Added defaults: detect.mtcnn
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Adding defaults: (filename: s3fd_defaults.py, module_path: plugins.extract.detect, plugin_type: detect
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Importing defaults module: plugins.extract.detect.s3fd_defaults
10/28/2019 17:36:22 MainProcess     MainThread      config          add_section               DEBUG    Add section: (title: 'detect.s3fd', info: 'S3FD Detector options.Fast on GPU, slow on CPU. Can detect more faces and fewer false positives than other GPU detectors, but is a lot more resource intensive.')
10/28/2019 17:36:22 MainProcess     MainThread      config          add_item                  DEBUG    Add item: (section: 'detect.s3fd', title: 'confidence', datatype: '<class 'int'>', default: '50', info: 'The confidence level at which the detector has succesfully found a face.\nHigher levels will be more discriminating, lower levels will have more false positives.', rounding: '5', min_max: (25, 100), choices: [], gui_radio: False, fixed: True, group: None)
10/28/2019 17:36:22 MainProcess     MainThread      config          add_item                  DEBUG    Add item: (section: 'detect.s3fd', title: 'batch-size', datatype: '<class 'int'>', default: '4', info: 'The batch size to use. To a point, higher batch sizes equal better performance, but setting it too high can harm performance.\n\n	Nvidia users: If the batchsize is set higher than the your GPU can accomodate then this will automatically be lowered.\n	AMD users: A batchsize of 8 requires about 2 GB vram.', rounding: '1', min_max: (1, 64), choices: [], gui_radio: False, fixed: True, group: None)
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Added defaults: detect.s3fd
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Adding defaults: (filename: unet_dfl_defaults.py, module_path: plugins.extract.mask, plugin_type: mask
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Importing defaults module: plugins.extract.mask.unet_dfl_defaults
10/28/2019 17:36:22 MainProcess     MainThread      config          add_section               DEBUG    Add section: (title: 'mask.unet_dfl', info: 'UNET_DFL options. Mask designed to provide smart segmentation of mostly frontal faces.\nThe mask model has been trained by community members. Insert more commentary on testing here. Profile faces may result in sub-par performance.')
10/28/2019 17:36:22 MainProcess     MainThread      config          add_item                  DEBUG    Add item: (section: 'mask.unet_dfl', title: 'batch-size', datatype: '<class 'int'>', default: '8', info: 'The batch size to use. To a point, higher batch sizes equal better performance, but setting it too high can harm performance.\n\n	Nvidia users: If the batchsize is set higher than the your GPU can accomodate then this will automatically be lowered.', rounding: '1', min_max: (1, 64), choices: [], gui_radio: False, fixed: True, group: None)
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Added defaults: mask.unet_dfl
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Adding defaults: (filename: vgg_clear_defaults.py, module_path: plugins.extract.mask, plugin_type: mask
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Importing defaults module: plugins.extract.mask.vgg_clear_defaults
10/28/2019 17:36:22 MainProcess     MainThread      config          add_section               DEBUG    Add section: (title: 'mask.vgg_clear', info: 'VGG_Clear options. Mask designed to provide smart segmentation of mostly frontal faces clear of obstructions.\nProfile faces and obstructions may result in sub-par performance.')
10/28/2019 17:36:22 MainProcess     MainThread      config          add_item                  DEBUG    Add item: (section: 'mask.vgg_clear', title: 'batch-size', datatype: '<class 'int'>', default: '6', info: 'The batch size to use. To a point, higher batch sizes equal better performance, but setting it too high can harm performance.\n\n	Nvidia users: If the batchsize is set higher than the your GPU can accomodate then this will automatically be lowered.', rounding: '1', min_max: (1, 64), choices: [], gui_radio: False, fixed: True, group: None)
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Added defaults: mask.vgg_clear
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Adding defaults: (filename: vgg_obstructed_defaults.py, module_path: plugins.extract.mask, plugin_type: mask
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Importing defaults module: plugins.extract.mask.vgg_obstructed_defaults
10/28/2019 17:36:22 MainProcess     MainThread      config          add_section               DEBUG    Add section: (title: 'mask.vgg_obstructed', info: 'VGG_Obstructed options. Mask designed to provide smart segmentation of mostly frontal faces.\nThe mask model has been specifically trained to recognize some facial obstructions (hands and eyeglasses). Profile faces may result in sub-par performance.')
10/28/2019 17:36:22 MainProcess     MainThread      config          add_item                  DEBUG    Add item: (section: 'mask.vgg_obstructed', title: 'batch-size', datatype: '<class 'int'>', default: '2', info: 'The batch size to use. To a point, higher batch sizes equal better performance, but setting it too high can harm performance.\n\n	Nvidia users: If the batchsize is set higher than the your GPU can accomodate then this will automatically be lowered.', rounding: '1', min_max: (1, 64), choices: [], gui_radio: False, fixed: True, group: None)
10/28/2019 17:36:22 MainProcess     MainThread      _config         load_module               DEBUG    Added defaults: mask.vgg_obstructed
10/28/2019 17:36:22 MainProcess     MainThread      config          handle_config             DEBUG    Handling config
10/28/2019 17:36:22 MainProcess     MainThread      config          check_exists              DEBUG    Config file exists: 'C:\Users\Joshua\faceswap\config\extract.ini'
10/28/2019 17:36:22 MainProcess     MainThread      config          load_config               VERBOSE  Loading config: 'C:\Users\Joshua\faceswap\config\extract.ini'
10/28/2019 17:36:22 MainProcess     MainThread      config          validate_config           DEBUG    Validating config
10/28/2019 17:36:22 MainProcess     MainThread      config          check_config_change       DEBUG    Default config has not changed
10/28/2019 17:36:22 MainProcess     MainThread      config          check_config_choices      DEBUG    Checking config choices
10/28/2019 17:36:22 MainProcess     MainThread      config          check_config_choices      DEBUG    Checked config choices
10/28/2019 17:36:22 MainProcess     MainThread      config          validate_config           DEBUG    Validated config
10/28/2019 17:36:22 MainProcess     MainThread      config          handle_config             DEBUG    Handled config
10/28/2019 17:36:22 MainProcess     MainThread      config          __init__                  DEBUG    Initialized: Config
10/28/2019 17:36:22 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'allow_growth')
10/28/2019 17:36:22 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: False)
10/28/2019 17:36:22 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'align.fan', option: 'batch-size')
10/28/2019 17:36:22 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 1)
10/28/2019 17:36:22 MainProcess     MainThread      utils           get                       DEBUG    Model exists: C:\Users\Joshua\faceswap\plugins\extract\align\.cache\face-alignment-network_2d4_keras_v1.h5
10/28/2019 17:36:22 MainProcess     MainThread      _base           __init__                  DEBUG    Initialized _base Align
10/28/2019 17:36:22 MainProcess     MainThread      _base           __init__                  DEBUG    Initialized Align
10/28/2019 17:36:22 MainProcess     MainThread      pipeline        _load_mask                DEBUG    No masker selected. Returning None
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initializing GPUStats
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_driver                DEBUG    GPU Driver: 431.86
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_devices               DEBUG    GPU Devices: ['GeForce GTX 1050 Ti', 'GeForce GTX 1050 Ti']
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_vram                  DEBUG    GPU VRAM: [4096.0, 4096.0]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initialized GPUStats
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_free                  DEBUG    GPU VRAM free: [3620.46484375, 4015.3125]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_free                  DEBUG    GPU VRAM free: [3620.46484375, 4015.3125]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_card_most_free        DEBUG    Active GPU Card with most free VRAM: {'card_id': 1, 'device': 'GeForce GTX 1050 Ti', 'free': 4015.3125, 'total': 4096.0}
10/28/2019 17:36:22 MainProcess     MainThread      pipeline        _set_parallel_processing  VERBOSE  GeForce GTX 1050 Ti - 4015MB free of 4096MB
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initializing GPUStats
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_driver                DEBUG    GPU Driver: 431.86
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_devices               DEBUG    GPU Devices: ['GeForce GTX 1050 Ti', 'GeForce GTX 1050 Ti']
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_vram                  DEBUG    GPU VRAM: [4096.0, 4096.0]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       __init__                  DEBUG    Initialized GPUStats
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_free                  DEBUG    GPU VRAM free: [3620.46484375, 4015.3125]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       initialize                DEBUG    OS is not macOS. Using pynvml
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_device_count          DEBUG    GPU Device count: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_active_devices        DEBUG    Active GPU Devices: [0, 1]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_handles               DEBUG    GPU Handles found: 2
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_free                  DEBUG    GPU VRAM free: [3620.46484375, 4015.3125]
10/28/2019 17:36:22 MainProcess     MainThread      gpu_stats       get_card_most_free        DEBUG    Active GPU Card with most free VRAM: {'card_id': 1, 'device': 'GeForce GTX 1050 Ti', 'free': 4015.3125, 'total': 4096.0}
10/28/2019 17:36:22 MainProcess     MainThread      pipeline        _set_extractor_batchsize  DEBUG    Plugin requirements within threshold: (plugin_required: 2561.0MB, vram_free: 4015MB)
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_detect_in', maxsize: 64)
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_detect_in')
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_detect_in'
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_detect_in'
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_align_in', maxsize: 32)
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_align_in')
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_align_in'
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_align_in'
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'extract_align_out', maxsize: 32)
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'extract_align_out')
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'extract_align_out'
10/28/2019 17:36:22 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'extract_align_out'
10/28/2019 17:36:22 MainProcess     MainThread      pipeline        _add_queues               DEBUG    Queues: {'extract_detect_in': <queue.Queue object at 0x00000260AC773CC0>, 'extract_align_in': <queue.Queue object at 0x00000260ACE95160>, 'extract_align_out': <queue.Queue object at 0x00000260ACE952E8>}
10/28/2019 17:36:22 MainProcess     MainThread      pipeline        __init__                  DEBUG    Initialized Extractor
10/28/2019 17:36:22 MainProcess     MainThread      pipeline        set_batchsize             DEBUG    Overriding batchsize for plugin_type: detect to: 1
10/28/2019 17:36:22 MainProcess     MainThread      pipeline        set_batchsize             DEBUG    Overriding batchsize for plugin_type: align to: 1
10/28/2019 17:36:22 MainProcess     MainThread      pipeline        set_batchsize             DEBUG    Overriding batchsize for plugin_type: mask to: 1
Traceback (most recent call last):
  File "C:\Users\Joshua\faceswap\lib\cli.py", line 128, in execute_script
    process.process()
  File "C:\Users\Joshua\faceswap\tools\alignments.py", line 52, in process
    job.process()
  File "C:\Users\Joshua\faceswap\tools\lib_alignments\jobs_manual.py", line 461, in process
    self.mouse_handler = MouseHandler(self.interface, self.arguments.loglevel)
  File "C:\Users\Joshua\faceswap\tools\lib_alignments\jobs_manual.py", line 768, in __init__
    self.extractor = self.init_extractor()
  File "C:\Users\Joshua\faceswap\tools\lib_alignments\jobs_manual.py", line 788, in init_extractor
    extractor.set_batchsize(plugin_type, 1)
  File "C:\Users\Joshua\faceswap\plugins\extract\pipeline.py", line 166, in set_batchsize
    plugin.batchsize = batchsize
AttributeError: 'NoneType' object has no attribute 'batchsize'

============ System Information ============
encoding:            cp1252
git_branch:          master
git_commits:         ef49d12 Add masker to Travis Tests Bugfix: Parallel VRAM calculation for non-gpu extractors. 3b2eaa5 Remove debug code. 9af7726 Always set batchsize as int (#913). 6efafab Merge branch 'master' into staging. 3d06ce9 lib.nn_blocks bugfix for upscaler
gpu_cuda:            10.1
gpu_cudnn:           7.6.2
gpu_devices:         GPU_0: GeForce GTX 1050 Ti, GPU_1: GeForce GTX 1050 Ti
gpu_devices_active:  GPU_0, GPU_1
gpu_driver:          431.86
gpu_vram:            GPU_0: 4096MB, GPU_1: 4096MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.18362-SP0
os_release:          10
py_command:          C:\Users\Joshua\faceswap\tools.py alignments -j manual -a E:/Videos/Friends/Rachel/Rachel.fsa -fc E:/Videos/Friends/Rachel/faces -fr E:/Videos/Friends/Rachel/Rachel.mp4 -o console -een 1 -sz 256 -ae -L INFO -gui
py_conda_version:    conda 4.7.12
py_implementation:   CPython
py_version:          3.6.9
py_virtual_env:      True
sys_cores:           6
sys_processor:       Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
sys_ram:             Total: 16242MB, Available: 12482MB, Used: 3759MB, Free: 12482MB

=============== Pip Packages ===============
absl-py==0.8.0
astor==0.7.1
certifi==2019.9.11
click==6.7
cloudpickle==0.5.6
cmake==3.13.3
cycler==0.10.0
dask==1.1.0
decorator==4.3.0
dlib==19.16.99
face-recognition==1.2.3
face-recognition-models==0.3.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.2.0
google-pasta==0.1.7
grpcio==1.15.0
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==2.2.2
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
networkx==2.2
numpy==1.16.2
nvidia-ml-py3==7.352.1
olefile==0.46
opencv-python==4.1.1.26
pathlib==1.0.1
Pillow==6.1.0
protobuf==3.6.1
psutil==5.6.3
pyparsing==2.4.2
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.2
PyWavelets==1.0.0
pywin32==223
PyYAML==5.1.2
scandir==1.7
scikit-image==0.14.2
scikit-learn==0.20.2
scipy==1.3.1
six==1.12.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
termcolor==1.1.0
toolz==0.9.0
toposort==1.5
tqdm==4.29.1
Werkzeug==0.14.1
wincertstore==0.2
wrapt==1.11.2

============== Conda Packages ==============
# packages in environment at C:\Users\Joshua\Anaconda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.8.0                    py36_0  
astor                     0.8.0                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.8.28                     0  
certifi                   2019.9.11                py36_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.0                cuda10.0_0  
cycler                    0.10.0                   pypi_0    pypi
fastcluster               1.1.25          py36h830ac7b_1000    conda-forge
ffmpeg                    4.2                  h6538335_0    conda-forge
freetype                  2.9.1                ha9979f8_1  
gast                      0.3.2                      py_0  
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0            py36h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
imageio                   2.5.0                    py36_0  
imageio-ffmpeg            0.3.0                      py_0    conda-forge
intel-openmp              2019.4                      245  
jpeg                      9b                   hb83a4c4_2  
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.1.0                      py_1  
libmklml                  2019.0.5                      0  
libpng                    1.6.37               h2a8f88b_0  
libprotobuf               3.9.2                h7bd577a_0  
libtiff                   4.0.10               hb898794_2  
markdown                  3.1.1                    py36_0  
mkl                       2019.4                      245  
mkl-service               2.3.0            py36hb782905_0  
mkl_fft                   1.0.14           py36h14836fe_0  
mkl_random                1.1.0            py36h675688f_0  
numpy                     1.16.2           py36h19fb1c0_0  
numpy-base                1.16.2           py36hc3f5095_0  
nvidia-ml-py3             7.352.1                  pypi_0    pypi
olefile                   0.46                     py36_0  
opencv-python             4.1.1.26                 pypi_0    pypi
openssl                   1.1.1d               he774522_0  
pillow                    6.1.0            py36hdc69c19_0  
pip                       19.2.3                   py36_0  
protobuf                  3.9.2            py36h33f27b4_0  
psutil                    5.6.3            py36he774522_0  
pyparsing                 2.4.2                    pypi_0    pypi
pyreadline                2.1                      py36_1  
python                    3.6.9                h5500b2f_0  
python-dateutil           2.8.0                    pypi_0    pypi
pytz                      2019.2                   pypi_0    pypi
pywin32                   223              py36hfa6e2cd_1  
pyyaml                    5.1.2            py36he774522_0  
scipy                     1.3.1            py36h29ff71c_0  
setuptools                41.2.0                   py36_0  
six                       1.12.0                   py36_0  
sqlite                    3.29.0               he774522_0  
tensorboard               1.14.0           py36he3c9ec2_0  
tensorflow                1.14.0          gpu_py36h305fd99_0  
tensorflow-base           1.14.0          gpu_py36h55fc52a_0  
tensorflow-estimator      1.14.0                     py_0  
tensorflow-gpu            1.14.0                   pypi_0    pypi
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hfa6e2cd_0  
toposort                  1.5                        py_3    conda-forge
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_0  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
wrapt                     1.11.2           py36he774522_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  

================= Configs ==================
--------- .faceswap ---------
backend:                  nvidia

--------- convert.ini ---------

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.manual_balance]
balance_1:                0.0
balance_3:                0.0
balance_2:                0.0
colorspace:               HSV
brightness:               0.0
contrast:                 0.0

[color.match_hist]
threshold:                99.0

[mask.box_blend]
passes:                   1
distance:                 11.0
radius:                   5.0
type:                     gaussian

[mask.mask_blend]
passes:                   4
radius:                   3.0
type:                     normalized
erosion:                  0.0

[scaling.sharpen]
method:                   unsharp_mask
threshold:                5.0
radius:                   0.3
amount:                   150

[writer.ffmpeg]
level:                    auto
profile:                  auto
crf:                      23
container:                mp4
tune:                     none
preset:                   medium
codec:                    libx264

[writer.gif]
fps:                      25
subrectangles:            False
loop:                     0
palettesize:              256

[writer.opencv]
draw_transparent:         False
png_compress_level:       3
format:                   png
jpg_quality:              75

[writer.pillow]
png_compress_level:       3
tif_compression:          tiff_deflate
optimize:                 False
jpg_quality:              75
draw_transparent:         False
gif_interlace:            True
format:                   png

--------- extract.ini ---------

[global]
allow_growth:             False

[align.fan]
batch-size:               1

[detect.cv2_dnn]
confidence:               50

[detect.mtcnn]
minsize:                  20
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7
scalefactor:              0.709
batch-size:               1

[detect.s3fd]
confidence:               50
batch-size:               1

[mask.unet_dfl]
batch-size:               1

[mask.vgg_clear]
batch-size:               6

[mask.vgg_obstructed]
batch-size:               2

--------- gui.ini ---------

[global]
fullscreen:               True
tab:                      extract
options_panel_width:      25
console_panel_height:     10
font:                     default
font_size:                9

--------- train.ini ---------

[global]
coverage:                 100.0
mask_type:                none
mask_blur:                True
icnr_init:                True
conv_aware_init:          True
subpixel_upscaling:       True
reflect_padding:          True
penalized_mask_loss:      True
loss_function:            mae
learning_rate:            5e-05

[model.dfl_h128]
lowmem:                   True

[model.dfl_sae]
encoder_dims:             21
multiscale_decoder:       True
input_size:               64
architecture:             df
autoencoder_dims:         256
clipnorm:                 False
decoder_dims:             14

[model.original]
lowmem:                   False

[model.realface]
complexity_encoder:       128
output_size:              64
input_size:               64
dense_nodes:              1536
complexity_decoder:       512

[model.unbalanced]
input_size:               128
clipnorm:                 True
complexity_encoder:       128
complexity_decoder_a:     384
nodes:                    1024
lowmem:                   False
complexity_decoder_b:     512

[model.villain]
lowmem:                   True

[trainer.original]
color_clahe_chance:       50
zoom_amount:              10
rotation_range:           10
flip_chance:              50
color_clahe_max_size:     4
preview_images:           14
color_ab:                 8
color_lightness:          30
shift_range:              10
```

**Comment by torzdf** [comment]
Should be fixed in latest commit.
