### ISSUE TITLE
Manual near to work ...

### ISSUE THREAD

**Issue by TobiTrom** [deepfakes/faceswap#916]
Hi torzdf,
sorry, manual start! thx
but if i search for nofaces and click in the selection-window, or try to move a aligment then

```
10/28/2019 19:04:36 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "C:\Users\Joshua\faceswap\lib\cli.py", line 128, in execute_script
process.process()
File "C:\Users\Joshua\faceswap\tools\alignments.py", line 52, in process
job.process()
File "C:\Users\Joshua\faceswap\tools\lib_alignments\jobs_manual.py", line 466, in process
self.display_frames()
File "C:\Users\Joshua\faceswap\tools\lib_alignments\jobs_manual.py", line 510, in display_frames
frame, faces = self.get_frame()
File "C:\Users\Joshua\faceswap\tools\lib_alignments\jobs_manual.py", line 565, in get_frame
self.extracted_faces.get_faces(frame_name)
File "C:\Users\Joshua\faceswap\tools\lib_alignments\media.py", line 288, in get_faces
self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
File "C:\Users\Joshua\faceswap\tools\lib_alignments\media.py", line 288, in <listcomp>
self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
File "C:\Users\Joshua\faceswap\tools\lib_alignments\media.py", line 296, in extract_one_face
face.from_alignment(alignment, image=image)
File "C:\Users\Joshua\faceswap\lib\faces_detect.py", line 196, in from_alignment
landmarks = np.array(landmarks, dtype="int32")
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
10/28/2019 19:04:36 CRITICAL An unexpected crash has occurred. Crash report written to 'C:\Users\Joshua\faceswap\crash_report.2019.10.28.190436511183.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting
Process exited.


```

**Comment by jpchow26** [comment]
Can confirm with last Oct 29th build I was seeing the same error messages when trying to move an alignment.

**Comment by torzdf** [comment]
I cannot recreate this issue :/

I will take another look.

**Comment by jpchow26** [comment]
I'm on latest 30th now.... I can't seem to make the exception stack to pop up now. /shrug

**Comment by TobiTrom** [comment]
sorry, but after systemfreez->reboot => no problem, work fine for me !?
