### ISSUE TITLE
Crash when manually fixing alignments

### ISSUE THREAD

**Issue by Tylersuard** [deepfakes/faceswap#920]
```
10/30/2019 13:34:52 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "C:\Users\tyler\faceswap\lib\cli.py", line 128, in execute_script
process.process()
File "C:\Users\tyler\faceswap\tools\alignments.py", line 52, in process
job.process()
File "C:\Users\tyler\faceswap\tools\lib_alignments\jobs_manual.py", line 466, in process
self.display_frames()
File "C:\Users\tyler\faceswap\tools\lib_alignments\jobs_manual.py", line 510, in display_frames
frame, faces = self.get_frame()
File "C:\Users\tyler\faceswap\tools\lib_alignments\jobs_manual.py", line 565, in get_frame
self.extracted_faces.get_faces(frame_name)
File "C:\Users\tyler\faceswap\tools\lib_alignments\media.py", line 288, in get_faces
self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
File "C:\Users\tyler\faceswap\tools\lib_alignments\media.py", line 288, in <listcomp>
self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
File "C:\Users\tyler\faceswap\tools\lib_alignments\media.py", line 296, in extract_one_face
face.from_alignment(alignment, image=image)
File "C:\Users\tyler\faceswap\lib\faces_detect.py", line 196, in from_alignment
landmarks = np.array(landmarks, dtype="int32")
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
10/30/2019 13:34:52 CRITICAL An unexpected crash has occurred. Crash report written to 'C:\Users\tyler\faceswap\crash_report.2019.10.30.133452643929.log'. 


Crash log:      


 [625, 341],
       [613, 341],
       [597, 345],
       [621, 325],
       [625, 321],
       [629, 317],
       [633, 305],
       [633, 317],
       [629, 321],
       [621, 325]]), 'hash': '2038740477d3eca6cc9b80a9c4bfb3f3cea519e8', 'mask': {'extended': {'mask': b'x\x9c\xed\xdaQr\xc20\x0c\x04P\xdf\xccG\xf3\xd1r\xb4\xb4\xa4\xc0\xd0\x96D+i\xd7\x9ea\xb4\x9f\xfdy\xc8\xd0\xd8\xb1\xd4Z\xa5R\xa9T*\x95O\xcd\xe8\xcb\xe8>\xc6\xbe\xefk\xfc\x83\xbee\x9bo\xf7\x87\xbd/(\x7fl\xfbk\xa6\x96\xdf\xff\xe0S\xcb\xff\xb5\xea\xb3\xcb\xff_\xf8O\xc6\x04\xfb\xcd\xaa?3\x01?\xb5\xf5\xe5\x8fK\\\\\xfe\xc5\xaa\xcb\xcb\xbf^uq\xf9\xe6\xaa+\xcb\x07V\xfd\x19\xf6\xb3\x07\\\xf5G\xfc\xcf\x9e\xf1\x12G\x9d\xa1\xf2\xefLZ9\x8dQ\xbe\x0e\xbe\xc7\xf8\xf6\xd5\xbc\xf5\xed\xab}\xeb\x9fO\xed\x1b\xbc\xda7\x9f=b\xdf\xe2\xc5\xbe\xfd\xe8\xd5\xfa&\xaf\xf5\x81\x9dG\xea\x03;\x8f\x92Gv\x1e\xa5\x8fl\xbcB\x1e\xdax\x85>t\xee\xd0\xf1\xd8\xb9C\xe7c\xc7>\x9d\x0f\xf1:\x1f<\xf5\xca|\x8c\x97\xf9\xe8\xa1_\xe5\x83\xbc\xca\x87\xdfyD>\xca\x8b|\xfc\x95O\xe3\xc3\xbc\xc6w\xbc\xf1J|\x9c\x97\xf8\x9e\x17~\x85\xef\xe0\x15\xbe\xeb\xbeC\xe0{x\x81\xef\xbb\xee\xe1\xfb.\x9e\xef;o\xbb\xe8\xbe\x8f\xa7\xfb\xde\xcb>\xb6\xef\xe4\xd9\xbe\xfb\xae\x93\xec{y\xb2\xef\xbf\xea\xe5\xfan\x9e\xeb\x07\xdaLT?p\xd3\xcd\xe4#]6\xa6\x1f\xb9\xe8\'\xf2\xa1&#\xd1\x0f\xf59x|\xac\xc7\xca\xf3cm\x1e\x1a\x1fl1\xd3\xfc`\x97\x8b\xc5G;\xec,?\xda\xe4#\xf1\xe1\x01\x03\x92\x1f\xeeqr\xf8\xf8|\x05\xc7\x8f\xb7x)|b\xbc\x84\xe2\':\xdc\x0c>3]\xc3\xf03\r~\x02\x9f\x1a."\xf8\xa9\xf9\x86<\x9f\x9b\xadZ\\~\xdb\xd6\x96\xdfZO~\x82\xfctK_Y\xfe\x91\xb1\xb2\xfc#\xdb\xca\xf2o\t\xfe\x0c\x88\xb3M}-\xdf\x02?\x03\xfaT\xa9k\xdeJ7T\n\r~\xcd\x98i\xed\'\xb3a\xdf\x7f\x9d\xa0\xbf\xfb \xd3\xe5J\xa5R\xa9T*\x95\x0f\xcb\x17Ei#k', 'affine_matrix': array([[   0.40573079,   -0.23137773, -118.48918859],
       [   0.23137773,    0.40573079, -187.39548991]]), 'interpolator': 2, 'stored_size': 128}}}], original_roi: [array([[[419, 223]],

       [[554, 460]],

       [[791, 325]],

       [[656,  88]]], dtype=int32)])
10/30/2019 13:34:44 MainProcess     MainThread      annotate        __init__                  DEBUG    Initialized Annotate
10/30/2019 13:34:44 MainProcess     MainThread      annotate        __init__                  DEBUG    Initializing Annotate: (alignments: [{'landmarks_xy': array([[-40,  66],
       [-36,  98],
       [-38, 123],
       [-34, 146],
       [-27, 172],
       [ -2, 195],
       [ 28, 212],
       [ 64, 215],
       [ 92, 219],
       [116, 215],
       [125, 207],
       [129, 192],
       [139, 167],
       [155, 147],
       [167, 119],
       [180,  96],
       [174,  67],
       [ 49,  69],
       [ 74,  70],
       [ 96,  70],
       [109,  69],
       [117,  69],
       [158,  58],
       [170,  52],
       [182,  46],
       [192,  43],
       [198,  42],
       [133,  87],
       [139, 107],
       [148, 129],
       [143, 144],
       [108, 146],
       [117, 146],
       [128, 148],
       [135, 144],
       [137, 141],
       [ 70,  85],
       [ 86,  86],
       [ 97,  83],
       [102,  82],
       [ 93,  90],
       [ 83,  92],
       [146,  72],
       [158,  66],
       [171,  65],
       [173,  62],
       [167,  72],
       [155,  78],
       [ 88, 181],
       [105, 174],
       [122, 167],
       [130, 167],
       [132, 164],
       [139, 167],
       [136, 166],
       [136, 179],
       [131, 189],
       [121, 192],
       [112, 191],
       [103, 186],
       [ 88, 181],
       [117, 176],
       [122, 175],
       [127, 174],
       [136, 166],
       [130, 175],
       [125, 177],
       [117, 176]], dtype=int32)}], original_roi: [array([[[  0,   0],
        [  0, 255],
        [255, 255],
        [255,   0]]])])
10/30/2019 13:34:44 MainProcess     MainThread      annotate        __init__                  DEBUG    Initialized Annotate
10/30/2019 13:34:49 MainProcess     MainThread      jobs_manual     initialize                DEBUG    Initialize frame: 'GolfOrigTrimmed_000164.png'
10/30/2019 13:34:49 MainProcess     MainThread      jobs_manual     set_state_value           DEBUG    Setting state value: (item: edit, category: selected, value: 0)
10/30/2019 13:34:49 MainProcess     MainThread      jobs_manual     set_state_value           DEBUG    Setting state value: (item: edit, category: selected, value: 0)
10/30/2019 13:34:49 MainProcess     MainThread      pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
10/30/2019 13:34:49 MainProcess     MainThread      alignments      update_face               DEBUG    Updating face 0 for frame 'GolfOrigTrimmed_000164.png'
10/30/2019 13:34:49 MainProcess     MainThread      pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
10/30/2019 13:34:49 MainProcess     MainThread      alignments      update_face               DEBUG    Updating face 0 for frame 'GolfOrigTrimmed_000164.png'
10/30/2019 13:34:49 MainProcess     MainThread      jobs_manual     frame_selector            DEBUG    navigation: {'skip-mode': 4, 'frame-size': 1, 'frame_idx': 163, 'max_frame': 1507, 'last_request': 0, 'frame_name': 'GolfOrigTrimmed_000164.png'}, frame: 'GolfOrigTrimmed_000164.png', skip_mode: 'has faces'
10/30/2019 13:34:49 MainProcess     MainThread      jobs_manual     get_frame                 DEBUG    Frame Name: 'GolfOrigTrimmed_000164.png'
10/30/2019 13:34:49 MainProcess     MainThread      jobs_manual     get_frame                 DEBUG    Faces Updated: True
Traceback (most recent call last):
  File "C:\Users\tyler\faceswap\lib\cli.py", line 128, in execute_script
    process.process()
  File "C:\Users\tyler\faceswap\tools\alignments.py", line 52, in process
    job.process()
  File "C:\Users\tyler\faceswap\tools\lib_alignments\jobs_manual.py", line 466, in process
    self.display_frames()
  File "C:\Users\tyler\faceswap\tools\lib_alignments\jobs_manual.py", line 510, in display_frames
    frame, faces = self.get_frame()
  File "C:\Users\tyler\faceswap\tools\lib_alignments\jobs_manual.py", line 565, in get_frame
    self.extracted_faces.get_faces(frame_name)
  File "C:\Users\tyler\faceswap\tools\lib_alignments\media.py", line 288, in get_faces
    self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
  File "C:\Users\tyler\faceswap\tools\lib_alignments\media.py", line 288, in <listcomp>
    self.faces = [self.extract_one_face(alignment, image.copy()) for alignment in alignments]
  File "C:\Users\tyler\faceswap\tools\lib_alignments\media.py", line 296, in extract_one_face
    face.from_alignment(alignment, image=image)
  File "C:\Users\tyler\faceswap\lib\faces_detect.py", line 196, in from_alignment
    landmarks = np.array(landmarks, dtype="int32")
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

============ System Information ============
encoding:            cp1252
git_branch:          master
git_commits:         f0a0bba Bugfix: lib.alignments. Check for .fsa file extension. 68109fc bugfix: plugins.extract.pipeline - Exclude CPU plugins from vram calculations
gpu_cuda:            9.0
gpu_cudnn:           No global version found. Check Conda packages for Conda cuDNN
gpu_devices:         GPU_0: GeForce GTX 770, GPU_1: GeForce GTX 770
gpu_devices_active:  GPU_0, GPU_1
gpu_driver:          441.08
gpu_vram:            GPU_0: 2048MB, GPU_1: 2048MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.17763-SP0
os_release:          10
py_command:          C:\Users\tyler\faceswap\tools.py alignments -j manual -a C:/Users/tyler/Desktop/KenGolfSwap/kenvids/GolfOrigTrimmed_alignments_20191030_131823.fsa -fr C:/Users/tyler/Desktop/KenGolfSwap/kenvids/GolfOrigTrimmed.mp4 -o console -een 1 -sz 256 -L INFO -gui
py_conda_version:    conda 4.7.12
py_implementation:   CPython
py_version:          3.6.9
py_virtual_env:      True
sys_cores:           8
sys_processor:       Intel64 Family 6 Model 26 Stepping 4, GenuineIntel
sys_ram:             Total: 16375MB, Available: 10550MB, Used: 5824MB, Free: 10550MB

=============== Pip Packages ===============
absl-py==0.8.0
astor==0.8.0
certifi==2019.9.11
cloudpickle==1.2.2
cycler==0.10.0
cytoolz==0.10.0
dask==2.6.0
decorator==4.4.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.3.2
grpcio==1.16.1
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.13.2
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
networkx==2.4
numpy==1.16.2
nvidia-ml-py3==7.352.1
olefile==0.46
opencv-python==4.1.1.26
pathlib==1.0.1
Pillow==6.1.0
protobuf==3.9.2
psutil==5.6.3
pyparsing==2.4.2
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.3
PyWavelets==1.1.1
pywin32==223
PyYAML==5.1.2
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
six==1.12.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
toolz==0.10.0
toposort==1.5
tornado==6.0.3
tqdm==4.36.1
Werkzeug==0.16.0
wincertstore==0.2
wrapt==1.11.2

============== Conda Packages ==============
# packages in environment at C:\ProgramData\Anaconda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.8.0                    py36_0  
astor                     0.8.0                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.10.16                    0  
certifi                   2019.9.11                py36_0  
cloudpickle               1.2.2                      py_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.0                cuda10.0_0  
cycler                    0.10.0           py36h009560c_0  
cytoolz                   0.10.0           py36he774522_0  
dask-core                 2.6.0                      py_0  
decorator                 4.4.0                    py36_1  
fastcluster               1.1.25          py36h830ac7b_1000    conda-forge
ffmpeg                    4.2                  h6538335_0    conda-forge
ffmpy                     0.2.2                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1  
gast                      0.3.2                      py_0  
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0            py36h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
imageio                   2.5.0                    py36_0  
imageio-ffmpeg            0.3.0                      py_0    conda-forge
intel-openmp              2019.4                      245  
joblib                    0.13.2                   py36_0  
jpeg                      9b                   hb83a4c4_2  
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py36ha925a31_0  
libmklml                  2019.0.5                      0  
libpng                    1.6.37               h2a8f88b_0  
libprotobuf               3.9.2                h7bd577a_0  
libtiff                   4.0.10               hb898794_2  
markdown                  3.1.1                    py36_0  
matplotlib                2.2.2            py36had4c4a9_2  
mkl                       2019.4                      245  
mkl-service               2.3.0            py36hb782905_0  
mkl_fft                   1.0.14           py36h14836fe_0  
mkl_random                1.1.0            py36h675688f_0  
networkx                  2.4                        py_0  
numpy                     1.16.2           py36h19fb1c0_0  
numpy-base                1.16.2           py36hc3f5095_0  
nvidia-ml-py3             7.352.1                  pypi_0    pypi
olefile                   0.46                     py36_0  
opencv-python             4.1.1.26                 pypi_0    pypi
openssl                   1.1.1d               he774522_3  
pathlib                   1.0.1                    py36_1  
pillow                    6.1.0            py36hdc69c19_0  
pip                       19.3.1                   py36_0  
protobuf                  3.9.2            py36h33f27b4_0  
psutil                    5.6.3            py36he774522_0  
pyparsing                 2.4.2                      py_0  
pyqt                      5.9.2            py36h6538335_2  
pyreadline                2.1                      py36_1  
python                    3.6.9                h5500b2f_0  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.3                     py_0  
pywavelets                1.1.1            py36he774522_0  
pywin32                   223              py36hfa6e2cd_1  
pyyaml                    5.1.2            py36he774522_0  
qt                        5.9.7            vc14h73c81de_0  
scikit-image              0.15.0           py36ha925a31_0  
scikit-learn              0.21.3           py36h6288b17_0  
scipy                     1.3.1            py36h29ff71c_0  
setuptools                41.4.0                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.12.0                   py36_0  
sqlite                    3.30.1               he774522_0  
tensorboard               1.14.0           py36he3c9ec2_0  
tensorflow                1.14.0          gpu_py36h305fd99_0  
tensorflow-base           1.14.0          gpu_py36h55fc52a_0  
tensorflow-estimator      1.14.0                     py_0  
tensorflow-gpu            1.14.0               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.10.0                     py_0  
toposort                  1.5                        py_3    conda-forge
tornado                   6.0.3            py36he774522_0  
tqdm                      4.36.1                     py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_0  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
wrapt                     1.11.2           py36he774522_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  

================= Configs ==================
--------- .faceswap ---------
backend:                  nvidia

--------- convert.ini ---------

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

[color.match_hist]
threshold:                99.0

[mask.box_blend]
type:                     gaussian
distance:                 11.0
radius:                   5.0
passes:                   1

[mask.mask_blend]
type:                     normalized
radius:                   3.0
passes:                   4
erosion:                  0.0

[scaling.sharpen]
method:                   unsharp_mask
amount:                   150
radius:                   0.3
threshold:                5.0

[writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     none
profile:                  auto
level:                    auto

[writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

[writer.opencv]
format:                   png
draw_transparent:         False
jpg_quality:              75
png_compress_level:       3

[writer.pillow]
format:                   png
draw_transparent:         False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

--------- extract.ini ---------

[global]
allow_growth:             False

[align.fan]
batch-size:               12

[detect.cv2_dnn]
confidence:               50

[detect.mtcnn]
minsize:                  20
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7
scalefactor:              0.709
batch-size:               8

[detect.s3fd]
confidence:               50
batch-size:               4

[mask.unet_dfl]
batch-size:               8

[mask.vgg_clear]
batch-size:               6

[mask.vgg_obstructed]
batch-size:               2

--------- gui.ini ---------

[global]
fullscreen:               False
tab:                      extract
options_panel_width:      30
console_panel_height:     20
font:                     default
font_size:                9

--------- train.ini ---------

[global]
coverage:                 68.75
mask_type:                none
mask_blur:                False
icnr_init:                False
conv_aware_init:          False
subpixel_upscaling:       False
reflect_padding:          False
penalized_mask_loss:      True
loss_function:            mae
learning_rate:            5e-05

[model.dfl_h128]
lowmem:                   False

[model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[model.original]
lowmem:                   False

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.villain]
lowmem:                   False

[trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4
```

**Comment by kilroythethird** [comment]
@Tylersuard Could you check if that error still occurs with the current version ?
