### ISSUE TITLE
program expected double 'fsa' suffix

### ISSUE THREAD

**Issue by 50mkw** [deepfakes/faceswap#921]
**Describe the bug**
When I do training, the alignment file was renamed to ***.fsa but program expected double 'fsa' suffix file.

**git log**

```
commit 33598d52f4aa88a584d935bbf9808854f234cb52 (HEAD -> master, origin/master, origin/HEAD)
Merge: b1dd0db 11ab910
Author: Patrick Yang <patrick.yang@50mkw.com>
Date:   Fri Nov 1 13:04:04 2019 +0800

    Merge pull request #1 from deepfakes/master
    
    Pull from deepfakes

commit 11ab910c5e830dacc4030ac3b70e4bb49a5879b0
Author: torzdf <36920800+torzdf@users.noreply.github.com>
Date:   Thu Oct 31 11:55:51 2019 +0000

    Reinstate fast frame count for convert and extract. Exit early if count is wrong.

commit 8085b4a80bc406f32d4d960a77de4c643a716946
Author: torzdf <36920800+torzdf@users.noreply.github.com>
Date:   Thu Oct 31 11:19:29 2019 +0000

    lib.logger - Remove newlines from log messages
```

**To Reproduce**
1. train by `python faceswap.py train -A /home/patrick/work/faceswap/data/Train_A -ala /home/patrick/work/faceswap/data/Alignments/A_alignments.json -B /home/patrick/work/faceswap/data/Train_B -alb /home/patrick/work/faceswap/data/Alignments/B_alignments.json -m /home/patrick/work/faceswap/data/Models/villain -t villain -bs 4 -it 1000000 -g 1 -s 100 -ss 25000 -tia /home/patrick/work/faceswap/data/TimelapseA -tib /home/patrick/work/faceswap/data/TimelapseB -to /home/patrick/work/faceswap/data/TimelapseOut -wl -L INFO`
2. got error `11/01/2019 13:07:14 ERROR    Error: Alignments file not found at /home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.fsa`

**Crash Report**

```
11/01/2019 13:07:13 MainProcess     training_0      _config         load_module               DEBUG    Importing defaults module: plugins.train.trainer.original_defaults
11/01/2019 13:07:13 MainProcess     training_0      config          add_section               DEBUG    Add section: (title: 'trainer.original', info: 'Original Trainer Options.\nWARNING: The defaults for augmentation will be fine for 99.9% of use cases. Only change them if you absolutely know what you are doing!')
11/01/2019 13:07:13 MainProcess     training_0      config          add_item                  DEBUG    Add item: (section: 'trainer.original', title: 'preview_images', datatype: '<class 'int'>', default: '14', info: 'Number of sample faces to display for each side in the preview when training.', rounding: '2', min_max: (2, 16), choices: None, gui_radio: False, fixed: True, group: evaluation)
11/01/2019 13:07:13 MainProcess     training_0      config          add_item                  DEBUG    Add item: (section: 'trainer.original', title: 'zoom_amount', datatype: '<class 'int'>', default: '5', info: 'Percentage amount to randomly zoom each training image in and out.', rounding: '1', min_max: (0, 25), choices: None, gui_radio: False, fixed: True, group: image augmentation)
11/01/2019 13:07:13 MainProcess     training_0      config          add_item                  DEBUG    Add item: (section: 'trainer.original', title: 'rotation_range', datatype: '<class 'int'>', default: '10', info: 'Percentage amount to randomly rotate each training image.', rounding: '1', min_max: (0, 25), choices: None, gui_radio: False, fixed: True, group: image augmentation)
11/01/2019 13:07:13 MainProcess     training_0      config          add_item                  DEBUG    Add item: (section: 'trainer.original', title: 'shift_range', datatype: '<class 'int'>', default: '5', info: 'Percentage amount to randomly shift each training image horizontally and vertically.', rounding: '1', min_max: (0, 25), choices: None, gui_radio: False, fixed: True, group: image augmentation)
11/01/2019 13:07:13 MainProcess     training_0      config          add_item                  DEBUG    Add item: (section: 'trainer.original', title: 'flip_chance', datatype: '<class 'int'>', default: '50', info: 'Percentage chance to randomly flip each training image horizontally.\nNB: This is ignored if the 'no-flip' option is enabled', rounding: '1', min_max: (0, 75), choices: None, gui_radio: False, fixed: True, group: image augmentation)
11/01/2019 13:07:13 MainProcess     training_0      config          add_item                  DEBUG    Add item: (section: 'trainer.original', title: 'color_lightness', datatype: '<class 'int'>', default: '30', info: 'Percentage amount to randomly alter the lightness of each training image.\nNB: This is ignored if the 'no-augment-color' option is enabled', rounding: '1', min_max: (0, 75), choices: None, gui_radio: False, fixed: True, group: color augmentation)
11/01/2019 13:07:13 MainProcess     training_0      config          add_item                  DEBUG    Add item: (section: 'trainer.original', title: 'color_ab', datatype: '<class 'int'>', default: '8', info: 'Percentage amount to randomly alter the 'a' and 'b' colors of the L*a*b* color space of each training image.\nNB: This is ignored if the 'no-augment-color' option is enabled', rounding: '1', min_max: (0, 50), choices: None, gui_radio: False, fixed: True, group: color augmentation)
11/01/2019 13:07:13 MainProcess     training_0      config          add_item                  DEBUG    Add item: (section: 'trainer.original', title: 'color_clahe_chance', datatype: '<class 'int'>', default: '50', info: 'Percentage chance to perform Contrast Limited Adaptive Histogram Equalization on each training image.\nNB: This is ignored if the 'no-augment-color' option is enabled', rounding: '1', min_max: (0, 75), choices: None, gui_radio: False, fixed: False, group: color augmentation)
11/01/2019 13:07:13 MainProcess     training_0      config          add_item                  DEBUG    Add item: (section: 'trainer.original', title: 'color_clahe_max_size', datatype: '<class 'int'>', default: '4', info: 'The grid size dictates how much Contrast Limited Adaptive Histogram Equalization is performed on any training image selected for clahe. Contrast will be applied randomly with a gridsize of 0 up to the maximum. This value is a multiplier calculated from the training image size.\nNB: This is ignored if the 'no-augment-color' option is enabled', rounding: '1', min_max: (1, 8), choices: None, gui_radio: False, fixed: True, group: color augmentation)
11/01/2019 13:07:13 MainProcess     training_0      _config         load_module               DEBUG    Added defaults: trainer.original
11/01/2019 13:07:13 MainProcess     training_0      config          handle_config             DEBUG    Handling config
11/01/2019 13:07:13 MainProcess     training_0      config          check_exists              DEBUG    Config file exists: '/home/patrick/work/faceswap/config/train.ini'
11/01/2019 13:07:13 MainProcess     training_0      config          load_config               VERBOSE  Loading config: '/home/patrick/work/faceswap/config/train.ini'
11/01/2019 13:07:13 MainProcess     training_0      config          validate_config           DEBUG    Validating config
11/01/2019 13:07:13 MainProcess     training_0      config          check_config_change       DEBUG    Default config has not changed
11/01/2019 13:07:13 MainProcess     training_0      config          check_config_choices      DEBUG    Checking config choices
11/01/2019 13:07:13 MainProcess     training_0      config          check_config_choices      DEBUG    Checked config choices
11/01/2019 13:07:13 MainProcess     training_0      config          validate_config           DEBUG    Validated config
11/01/2019 13:07:13 MainProcess     training_0      config          handle_config             DEBUG    Handled config
11/01/2019 13:07:13 MainProcess     training_0      config          __init__                  DEBUG    Initialized: Config
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'coverage')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'float'>, value: 68.75)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'mask_type')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: None)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'mask_blur')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: False)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'icnr_init')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: False)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'conv_aware_init')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: False)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'subpixel_upscaling')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: False)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'reflect_padding')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: False)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'penalized_mask_loss')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: True)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'loss_function')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: mae)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'global', option: 'learning_rate')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'float'>, value: 5e-05)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'trainer.original', option: 'preview_images')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 14)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'trainer.original', option: 'zoom_amount')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 5)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'trainer.original', option: 'rotation_range')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 10)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'trainer.original', option: 'shift_range')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 5)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'trainer.original', option: 'flip_chance')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 50)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'trainer.original', option: 'color_lightness')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 30)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'trainer.original', option: 'color_ab')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 8)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'trainer.original', option: 'color_clahe_chance')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 50)
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Getting config item: (section: 'trainer.original', option: 'color_clahe_max_size')
11/01/2019 13:07:13 MainProcess     training_0      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 4)
11/01/2019 13:07:13 MainProcess     training_0      _base           add_session_batchsize     DEBUG    Adding session batchsize: 4
11/01/2019 13:07:13 MainProcess     training_0      _base           process_training_opts     DEBUG    {'alignments': {'a': '/home/patrick/work/faceswap/data/Alignments/A_alignments.json', 'b': '/home/patrick/work/faceswap/data/Alignments/B_alignments.json'}, 'preview_scaling': 0.5, 'warp_to_landmarks': True, 'augment_color': True, 'no_flip': False, 'pingpong': False, 'snapshot_interval': 25000, 'training_size': 256, 'no_logs': False, 'mask_type': 'facehull', 'coverage_ratio': 0.6875}
11/01/2019 13:07:13 MainProcess     training_0      _base           landmarks_required        DEBUG    True
11/01/2019 13:07:13 MainProcess     training_0      _base           __init__                  DEBUG    Initializing Landmarks: (training_opts: '{'alignments': {'a': '/home/patrick/work/faceswap/data/Alignments/A_alignments.json', 'b': '/home/patrick/work/faceswap/data/Alignments/B_alignments.json'}, 'preview_scaling': 0.5, 'warp_to_landmarks': True, 'augment_color': True, 'no_flip': False, 'pingpong': False, 'snapshot_interval': 25000, 'training_size': 256, 'no_logs': False, 'mask_type': 'facehull', 'coverage_ratio': 0.6875}')
11/01/2019 13:07:13 MainProcess     training_0      alignments      __init__                  DEBUG    Initializing Alignments: (folder: '/home/patrick/work/faceswap/data/Alignments', filename: 'A_alignments.json')
11/01/2019 13:07:13 MainProcess     training_0      serializer      get_serializer            DEBUG    <lib.serializer._PickleSerializer object at 0x7f623c6f1080>
11/01/2019 13:07:13 MainProcess     training_0      serializer      get_serializer            DEBUG    <lib.serializer._CompressedSerializer object at 0x7f623c6f1320>
11/01/2019 13:07:13 MainProcess     training_0      alignments      get_location              DEBUG    Getting location: (folder: '/home/patrick/work/faceswap/data/Alignments', filename: 'A_alignments.json')
11/01/2019 13:07:13 MainProcess     training_0      alignments      update_file_format        INFO     Reformatting legacy alignments file...
11/01/2019 13:07:13 MainProcess     training_0      alignments      update_file_format        INFO     Old location: '/home/patrick/work/faceswap/data/Alignments/A_alignments.json', New location: '/home/patrick/work/faceswap/data/Alignments/A_alignments.fsa'
11/01/2019 13:07:13 MainProcess     training_0      serializer      get_serializer_from_filename DEBUG    filename: '/home/patrick/work/faceswap/data/Alignments/A_alignments.json'
11/01/2019 13:07:13 MainProcess     training_0      serializer      get_serializer_from_filename DEBUG    extension: '.json'
11/01/2019 13:07:13 MainProcess     training_0      serializer      get_serializer_from_filename DEBUG    <lib.serializer._JSONSerializer object at 0x7f623c6f1240>
11/01/2019 13:07:13 MainProcess     training_0      serializer      load                      DEBUG    filename: /home/patrick/work/faceswap/data/Alignments/A_alignments.json
11/01/2019 13:07:13 MainProcess     training_0      serializer      load                      DEBUG    stored data type: <class 'bytes'>
11/01/2019 13:07:13 MainProcess     training_0      serializer      unmarshal                 DEBUG    data type: <class 'bytes'>
11/01/2019 13:07:13 MainProcess     training_0      serializer      unmarshal                 DEBUG    returned data type: <class 'dict'>
11/01/2019 13:07:13 MainProcess     training_0      serializer      load                      DEBUG    data type: <class 'dict'>
11/01/2019 13:07:13 MainProcess     training_0      serializer      save                      DEBUG    filename: /home/patrick/work/faceswap/data/Alignments/A_alignments.fsa, data type: <class 'dict'>
11/01/2019 13:07:13 MainProcess     training_0      serializer      _check_extension          DEBUG    Original filename: '/home/patrick/work/faceswap/data/Alignments/A_alignments.fsa', final filename: '/home/patrick/work/faceswap/data/Alignments/A_alignments.fsa'
11/01/2019 13:07:13 MainProcess     training_0      serializer      marshal                   DEBUG    data type: <class 'dict'>
11/01/2019 13:07:13 MainProcess     training_0      serializer      marshal                   DEBUG    returned data type: <class 'bytes'>
11/01/2019 13:07:13 MainProcess     training_0      alignments      get_location              DEBUG    Updated legacy alignments. New filename: 'A_alignments.fsa'
11/01/2019 13:07:13 MainProcess     training_0      alignments      get_location              DEBUG    File extension set from serializer: 'fsa'
11/01/2019 13:07:13 MainProcess     training_0      alignments      test_for_legacy           DEBUG    Checking for legacy alignments file formats: '/home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.fsa'
11/01/2019 13:07:13 MainProcess     training_0      alignments      test_for_legacy           DEBUG    Legacy alignments file does not exist: '/home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.json'
11/01/2019 13:07:13 MainProcess     training_0      alignments      test_for_legacy           DEBUG    Legacy alignments file does not exist: '/home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.p'
11/01/2019 13:07:13 MainProcess     training_0      alignments      test_for_legacy           DEBUG    Legacy alignments file does not exist: '/home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.pickle'
11/01/2019 13:07:13 MainProcess     training_0      alignments      test_for_legacy           DEBUG    Legacy alignments file does not exist: '/home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.yaml'
11/01/2019 13:07:13 MainProcess     training_0      alignments      get_location              VERBOSE  Alignments filepath: '/home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.fsa'
11/01/2019 13:07:13 MainProcess     training_0      alignments      load                      DEBUG    Loading alignments
11/01/2019 13:07:13 MainProcess     training_0      multithreading  run                       DEBUG    Error in thread (training_0): Error: Alignments file not found at /home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.fsa
11/01/2019 13:07:14 MainProcess     MainThread      train           monitor                   DEBUG    Thread error detected
11/01/2019 13:07:14 MainProcess     MainThread      train           monitor                   DEBUG    Closed Monitor
11/01/2019 13:07:14 MainProcess     MainThread      train           end_thread                DEBUG    Ending Training thread
11/01/2019 13:07:14 MainProcess     MainThread      train           end_thread                CRITICAL Error caught! Exiting...
11/01/2019 13:07:14 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'training'
11/01/2019 13:07:14 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'training_0'
11/01/2019 13:07:14 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: 'training_0'
11/01/2019 13:07:14 MainProcess     MainThread      cli             execute_script            ERROR    Error: Alignments file not found at /home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.fsa
Traceback (most recent call last):
  File "/home/patrick/work/faceswap/lib/cli.py", line 128, in execute_script
    process.process()
  File "/home/patrick/work/faceswap/scripts/train.py", line 109, in process
    self.end_thread(thread, err)
  File "/home/patrick/work/faceswap/scripts/train.py", line 135, in end_thread
    thread.join()
  File "/home/patrick/work/faceswap/lib/multithreading.py", line 117, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/home/patrick/work/faceswap/lib/multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "/home/patrick/work/faceswap/scripts/train.py", line 160, in training
    raise err
  File "/home/patrick/work/faceswap/scripts/train.py", line 149, in training
    trainer = self.load_trainer(model)
  File "/home/patrick/work/faceswap/scripts/train.py", line 215, in load_trainer
    self.args.configfile)
  File "/home/patrick/work/faceswap/plugins/train/trainer/original.py", line 10, in __init__
    super().__init__(*args, **kwargs)
  File "/home/patrick/work/faceswap/plugins/train/trainer/_base.py", line 61, in __init__
    self.process_training_opts()
  File "/home/patrick/work/faceswap/plugins/train/trainer/_base.py", line 108, in process_training_opts
    landmarks = Landmarks(self.model.training_opts).landmarks
  File "/home/patrick/work/faceswap/plugins/train/trainer/_base.py", line 671, in __init__
    self.landmarks = self.get_alignments()
  File "/home/patrick/work/faceswap/plugins/train/trainer/_base.py", line 679, in get_alignments
    alignments = Alignments(path, filename=filename)
  File "/home/patrick/work/faceswap/lib/alignments.py", line 30, in __init__
    self.data = self.load()
  File "/home/patrick/work/faceswap/lib/alignments.py", line 104, in load
    "{}".format(self.file))
lib.utils.FaceswapError: Error: Alignments file not found at /home/patrick/work/faceswap/data/Alignments/A_alignments.fsa.fsa

============ System Information ============
encoding:            UTF-8
git_branch:          位于分支 master
git_commits:         33598d5 Merge pull request #1 from deepfakes/master. 11ab910 Reinstate fast frame count for convert and extract. Exit early if count is wrong.. 8085b4a lib.logger - Remove newlines from log messages. b1dd0db bugfix: lib.image - Ensure video frame count is always read correctly. f0a0bba Bugfix: lib.alignments. Check for .fsa file extension
gpu_cuda:            10.0
gpu_cudnn:           7.6.2
gpu_devices:         GPU_0: GeForce RTX 2080 Ti
gpu_devices_active:  GPU_0
gpu_driver:          418.87.01
gpu_vram:            GPU_0: 10986MB
os_machine:          x86_64
os_platform:         Linux-5.0.0-32-generic-x86_64-with-Ubuntu-18.04-bionic
os_release:          5.0.0-32-generic
py_command:          faceswap.py train -A /home/patrick/work/faceswap/data/Train_A -ala /home/patrick/work/faceswap/data/Alignments/A_alignments.json -B /home/patrick/work/faceswap/data/Train_B -alb /home/patrick/work/faceswap/data/Alignments/B_alignments.json -m /home/patrick/work/faceswap/data/Models/villain -t villain -bs 4 -it 1000000 -g 1 -s 100 -ss 25000 -tia /home/patrick/work/faceswap/data/TimelapseA -tib /home/patrick/work/faceswap/data/TimelapseB -to /home/patrick/work/faceswap/data/TimelapseOut -wl -L INFO
py_conda_version:    N/A
py_implementation:   CPython
py_version:          3.6.8
py_virtual_env:      True
sys_cores:           16
sys_processor:       x86_64
sys_ram:             Total: 15949MB, Available: 10758MB, Used: 2799MB, Free: 736MB

=============== Pip Packages ===============
absl-py==0.8.1
astor==0.8.0
cycler==0.10.0
decorator==4.4.1
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.3.2
google-pasta==0.1.7
grpcio==1.24.3
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.14.0
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
networkx==2.4
numpy==1.16.2
nvidia-ml-py3==7.352.1
opencv-python==4.1.1.26
pathlib==1.0.1
Pillow==6.1.0
pkg-resources==0.0.0
protobuf==3.10.0
psutil==5.6.3
pyparsing==2.4.2
python-dateutil==2.8.0
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.1.2
scikit-image==0.16.2
scikit-learn==0.21.3
scipy==1.3.1
six==1.12.0
tensorboard==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
termcolor==1.1.0
toposort==1.5
tqdm==4.36.1
Werkzeug==0.16.0
wrapt==1.11.2

=============== State File =================
{
  "name": "villain",
  "sessions": {
    "1": {
      "timestamp": 1572270197.4377177,
      "no_logs": false,
      "pingpong": false,
      "loss_names": {
        "a": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ],
        "b": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ]
      },
      "batchsize": 4,
      "iterations": 64501,
      "config": {
        "learning_rate": 5e-05
      }
    },
    "2": {
      "timestamp": 1572298597.5491555,
      "no_logs": false,
      "pingpong": false,
      "loss_names": {
        "a": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ],
        "b": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ]
      },
      "batchsize": 4,
      "iterations": 68501,
      "config": {
        "learning_rate": 5e-05
      }
    },
    "3": {
      "timestamp": 1572330588.0051217,
      "no_logs": false,
      "pingpong": false,
      "loss_names": {
        "a": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ],
        "b": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ]
      },
      "batchsize": 4,
      "iterations": 30301,
      "config": {
        "learning_rate": 5e-05
      }
    },
    "4": {
      "timestamp": 1572340497.074306,
      "no_logs": false,
      "pingpong": false,
      "loss_names": {
        "a": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ],
        "b": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ]
      },
      "batchsize": 4,
      "iterations": 101,
      "config": {
        "learning_rate": 5e-05
      }
    },
    "5": {
      "timestamp": 1572340767.8174438,
      "no_logs": false,
      "pingpong": false,
      "loss_names": {
        "a": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ],
        "b": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ]
      },
      "batchsize": 4,
      "iterations": 1,
      "config": {
        "learning_rate": 5e-05
      }
    },
    "6": {
      "timestamp": 1572340949.2396297,
      "no_logs": false,
      "pingpong": false,
      "loss_names": {
        "a": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ],
        "b": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ]
      },
      "batchsize": 4,
      "iterations": 13901,
      "config": {
        "learning_rate": 5e-05
      }
    },
    "7": {
      "timestamp": 1572346546.5246103,
      "no_logs": false,
      "pingpong": false,
      "loss_names": {
        "a": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ],
        "b": [
          "total_loss",
          "face_loss",
          "mask_loss"
        ]
      },
      "batchsize": 4,
      "iterations": 1701,
      "config": {
        "learning_rate": 5e-05
      }
    }
  },
  "lowest_avg_loss": {
    "a": 0.005715244449675083,
    "b": 0.0142811369150877
  },
  "iterations": 179007,
  "inputs": {
    "face_in:0": [
      128,
      128,
      3
    ],
    "mask_in:0": [
      128,
      128,
      1
    ]
  },
  "training_size": 256,
  "config": {
    "coverage": 68.75,
    "mask_type": "facehull",
    "mask_blur": true,
    "icnr_init": true,
    "conv_aware_init": false,
    "subpixel_upscaling": false,
    "reflect_padding": false,
    "penalized_mask_loss": true,
    "loss_function": "ssim",
    "learning_rate": 5e-05,
    "lowmem": true
  }
}

================= Configs ==================
--------- .faceswap ---------
backend:                  nvidia

--------- train.ini ---------

[global]
coverage:                 68.75
mask_type:                none
mask_blur:                False
icnr_init:                False
conv_aware_init:          False
subpixel_upscaling:       False
reflect_padding:          False
penalized_mask_loss:      True
loss_function:            mae
learning_rate:            5e-05

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.dfl_h128]
lowmem:                   False

[model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[model.original]
lowmem:                   False

[model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.villain]
lowmem:                   False

[trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4
```

**Comment by TobiTrom** [comment]
@50mkw 
I think you already have one or both as .fsa file, change the A + B_alignments.json to ".fsa", worked for me.

**Comment by kilroythethird** [comment]
Fixed in current master branch
