### ISSUE TITLE
preview stoped

### ISSUE THREAD

**Issue by karvn** [deepfakes/faceswap#942]
**Describe the bug**
just convert a video from the tab "convert", after several frames converted, the preview stoped, and some call stack print to console.

**To Reproduce**
1. Open faceswap
2. Switch to "convert" tab
3. Fill the params that needed to convert
4. Convert the video.
5. Preview stoped after some frames convert, and some call stack print to the console.

**Expected behavior**
The preview could be ok.

**Desktop (please complete the following information):**
 - OS: Ubuntu18.04.3
 - Python Version: 3.6.9
 - Conda Version: conda 4.7.12
 - Commit ID: 18660da
 - 

**Crash Report**
No creash report found in the Faceswap folder, but some call stack print to the console:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/bd/miniconda3/envs/faceswap/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/bd/miniconda3/envs/faceswap/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/bd/faceswap/lib/gui/display_page.py", line 248, in <lambda>
    self.after(waittime, lambda t=waittime: self.update_page(t))
  File "/home/bd/faceswap/lib/gui/display_page.py", line 246, in update_page
    self.display_item_set()
  File "/home/bd/faceswap/lib/gui/display_command.py", line 29, in display_item_set
    frame_dims=(self.winfo_width(), self.winfo_height()))
  File "/home/bd/faceswap/lib/gui/utils.py", line 493, in load_latest_preview
    self._load_images_to_cache(image_files, frame_dims, thumbnail_size)
  File "/home/bd/faceswap/lib/gui/utils.py", line 560, in _load_images_to_cache
    img = img.resize((int(width * scaling), int(height * scaling)))
  File "/home/bd/miniconda3/envs/faceswap/lib/python3.6/site-packages/PIL/Image.py", line 1890, in resize
    self.load()
  File "/home/bd/miniconda3/envs/faceswap/lib/python3.6/site-packages/PIL/ImageFile.py", line 249, in load
    "(%d bytes not processed)" % len(b)
OSError: image file is truncated (53 bytes not processed)

**Comment by torzdf** [comment]
Preview for convert is just a GUI extra, it's non-breaking. I haven't seen this before, so I assume it was a freak circumstance.

**Comment by karvn** [comment]
ok, i got that.
