### ISSUE TITLE
'Could not find PlaidML configuration file: "{}".'.format(filename)) plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".

### ISSUE THREAD

**Issue by PuneethReddyHC** [deepfakes/faceswap#951]
C:\Users\xyz\Documents\Python\faceswap>python faceswap.py gui
Setting Faceswap backend to AMD
12/08/2019 22:20:44 INFO     Log level set to: INFO
Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "C:\Users\xyz\Documents\Python\faceswap\lib\cli.py", line 121, in execute_script
    plaidml_found = self.setup_amd(arguments.loglevel)
  File "C:\Users\xyz\Documents\Python\faceswap\lib\cli.py", line 156, in setup_amd
    import plaidml  # noqa pylint:disable=unused-import
  File "C:\Users\xyz\AppData\Roaming\Python\Python37\site-packages\plaidml\__init__.py", line 50, in <module>
    import plaidml.settings
  File "C:\Users\xyz\AppData\Roaming\Python\Python37\site-packages\plaidml\settings.py", line 33, in <module>
    _setup_config('PLAIDML_EXPERIMENTAL_CONFIG', 'experimental.json')
  File "C:\Users\xyz\AppData\Roaming\Python\Python37\site-packages\plaidml\settings.py", line 30, in _setup_config
    'Could not find PlaidML configuration file: "{}".'.format(filename))
plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".

**Comment by blabtonic** [comment]
any information on this I've receive this same message when I try to run python3.7 faceswap.py gui after I installed plaidml-setup

**Comment by torzdf** [comment]
Ultimately this is a local/plaidML issue. You may be able to solve it here:
https://github.com/plaidml/plaidml/issues/370
